liquibase/liquibase

liquibase-core/src/main/java/liquibase/database/core/MSSQLDatabase.java, liquibase-core/src/test/java/liquibase/database/core/MSSQLDatabaseTest.java
Fixes CORE-2178: https://liquibase.jira.com/browse/CORE-2178
MSSQLDatabase.isCaseSensitive() uses the system collation rather than the database collation to determine whether or not the database is case-sensitive. That is fixed by checking DATABASEPROPERTYEX(<catalog>, 'collation').
Also, MSSQLDatabase.getdbcSchemaName() always converts to lower case. That causes a false negative on a case-sensitive database when checking to see if the lock table exists.
I am not nearly familiar enough to understand the full impact of this change, but it does seem to fix the problem we are having on SQL Server 2012.
=> Fix CORE-2178 Use correct database collation

liquibase-core/src/main/java/liquibase/changelog/visitor/UpdateVisitor.java
reset should be set to previous strategy, not LEGACY.
A better place to reset should be in changeSet.execute(...), in case of exception...
this.database.setObjectQuotingStrategy(ObjectQuotingStrategy.LEGACY);
=> reset of quoting strategy is wrong

liquibase-core/src/main/java/liquibase/integration/servlet/LiquibaseServletListener.java
There is a bug that a dot remains as parameter name prefix
=> Fixed bug that Servlet listener wrongly handle LiquibaseServletListener.LIQUIBASE_PARAMETER

liquibase-core/src/main/java/liquibase/integration/ant/AbstractChangeLogBasedTask.java, liquibase-core/src/main/java/liquibase/integration/ant/BaseLiquibaseTask.java, liquibase-core/src/main/java/liquibase/integration/ant/DBDocTask.java
When the Ant tasks were refactored the change log parameter because an Ant ```FileResource``` object. This means change logs can only be located on the file system. This negates the usefulness of the ```ResourceAccessor``` interface in Liquibase.
I have converted the change log parameter back to a ```String``` and am letting the ```ResourceAccessor``` handle the locating and reading of the file.
This fixes CORE-2274.
=> CORE-2274 Changing change log parameter from FileResource to String

liquibase-core/src/main/java/liquibase/snapshot/jvm/IndexSnapshotGenerator.java
CORE-2263 Index Snapshot - doesn't include upper cased name indexes when db is NOT case sensitive - Make key to foundIndexes map 'corrected' to match 'corrected' exampleName.
=> CORE-2263 Index Snapshot - doesn't include upper cased name indexes when db is NOT case sensitive

liquibase-core/src/main/java/liquibase/integration/ant/AbstractDatabaseDiffTask.java, liquibase-core/src/main/java/liquibase/integration/ant/BaseLiquibaseTask.java, liquibase-core/src/main/java/liquibase/integration/ant/ChangeLogSyncTask.java, liquibase-core/src/main/java/liquibase/integration/ant/DBDocTask.java, liquibase-core/src/main/java/liquibase/integration/ant/DatabaseRollbackFutureTask.java, liquibase-core/src/main/java/liquibase/integration/ant/DatabaseRollbackTask.java, liquibase-core/src/main/java/liquibase/integration/ant/DatabaseUpdateTask.java, liquibase-core/src/main/java/liquibase/integration/ant/DatabaseUpdateTestingRollbackTask.java, liquibase-core/src/main/java/liquibase/integration/ant/DiffDatabaseTask.java, liquibase-core/src/main/java/liquibase/integration/ant/DiffDatabaseToChangeLogTask.java, liquibase-core/src/main/java/liquibase/integration/ant/DropAllTask.java, liquibase-core/src/main/java/liquibase/integration/ant/GenerateChangeLogTask.java, liquibase-core/src/main/java/liquibase/integration/ant/MarkNextChangeSetRanTask.java, liquibase-core/src/main/java/liquibase/integration/ant/TagDatabaseTask.java, liquibase-core/src/main/java/liquibase/integration/ant/type/DatabaseType.java
I am adding the output of the root cause exception to the corresponding Ant BuildException to give more context about the error. Before the Ant task refactoring, there were no custom messages when BuildException was through which resulted in the root cause message being the only message. Once more messages were added, the root cause message was lost.
This should fix CORE-2196.
=> CORE-2196 Adding root cause message to the build exception

liquibase-core/src/main/java/liquibase/datatype/core/DateTimeType.java, liquibase-core/src/main/java/liquibase/datatype/core/TimestampType.java
The current handling for TIMESTAMP precision handling really doesn't do a good job.
In the case of MySQL, the code simply ignores any precision specified and the version check is simply wrong (would fail for 6.x.x or 5.7.x).
In case of PostgreSQL, also the precision is simply ignored.
Related at least to the following issues:
* https://liquibase.jira.com/browse/CORE-1424
=> Handle timestamp precision

liquibase-core/src/main/java/liquibase/util/NetUtil.java
CORE-1943 - Handle Error: InetAddress.getLocalHost().getHostName() UnknownHostException results in NoClassDefFoundError - Use 'Smarter' way to get localhost for local host name as well as local host address.  (Basically same approach as 2.0.2 functionality, which worked)
=> CORE-1943 - Handle Error: InetAddress.getLocalHost().getHostName() UnknownHostException

liquibase-core/src/main/resources/liquibase/parser/core/xml/dbchangelog-3.0.xsd, liquibase-core/src/main/resources/liquibase/parser/core/xml/dbchangelog-3.1.xsd, liquibase-core/src/main/resources/liquibase/parser/core/xml/dbchangelog-3.2.xsd, liquibase-core/src/main/resources/liquibase/parser/core/xml/dbchangelog-3.3.xsd
CORE-1866 - Filtering changelog list by includeAll tag is not working - fix bad "filter" entry in xsd's to be "resourceFilter" to match Java code.
=> CORE-1866 - Filtering changelog list by includeAll tag is not working

liquibase-core/src/main/java/liquibase/precondition/core/ColumnExistsPrecondition.java
Speed up columnExists precondition by delegating work to SQL parser of the
database. Instead of inspecting database metadata (which can be slow when
many tables/columns exist in the db), check that the column can be selected
from the table.
=> CORE-2234: columnExists precondition speedup by relying on SQL parser in DB

liquibase-core/src/main/java/liquibase/datatype/LiquibaseDataType.java, liquibase-core/src/main/java/liquibase/datatype/core/UUIDType.java, liquibase-core/src/test/groovy/liquibase/datatype/core/UUIDTypeTest.groovy
[CORE-2325](https://liquibase.jira.com/browse/CORE-2325) Liquibase - New versions break DB create
Fixed UUIDType.objectToSql(), added a test case for UUIDType, added infrastructure for piecewise override of LiquibaseDataType.objectToSql(), added support for converting java.util.UUID
=> CORE-2325 Liquibase - New versions break DB create

liquibase-core/src/main/resources/dist/liquibase
MinGW should use semicolon for classpath separation.
=> CORE-2320 MinGW (Git Bash) support for shell

liquibase-core/src/main/java/liquibase/datatype/LiquibaseDataType.java, liquibase-core/src/main/java/liquibase/datatype/core/DecimalType.java, liquibase-core/src/test/groovy/liquibase/datatype/DataTypeFactoryTest.groovy
[CORE-2318](https://liquibase.jira.com/browse/CORE-2318) Add support for converting BigDecimal objects to a SQL string via DataTypeFactory
=> CORE-2318 Add support for converting BigDecimal objects to a SQL string via DataTypeFactory

liquibase-core/src/main/java/liquibase/integration/spring/SpringLiquibase.java, liquibase-core/src/main/java/liquibase/resource/ClassLoaderResourceAccessor.java, liquibase-core/src/main/java/liquibase/util/LiquibaseUtil.java
URL's cache results in FileNotFoundException for the case when jar was changed and liquibase tried to reread any file from this jar.
For example it happens when web application in Jetty 9 is stopped, jar file from WEB-INF/lib is replaced with new one and application is started back again. I got this problem with jetty-maven-plugin when it tried to apply changes I made in IDE to running web application (liquibase was configured as Spring bean).
=> URLs connection caching is turned off.

liquibase-core/src/main/java/liquibase/datatype/LiquibaseDataType.java, liquibase-core/src/main/java/liquibase/datatype/core/UUIDType.java
I had a slightly different idea of how to handle the merge conflict between CORE-2325 and CORE-2318. This should make behavior more predictable if someone later overrides LiquibaseDataType#numberToSql(Number, Database). The code in UUIDType#otherToSql(Object, Database) was also able to be simplified due to the inheriting the necessary code to handle a DatabaseFunction from LiquibaseDataType#objectToSql(Object, Database).
=> CORE-2325 Improve the merge conflict resolution between CORE-2325 and CORE-2318

liquibase-core/src/main/java/liquibase/datatype/DataTypeFactory.java, liquibase-core/src/main/java/liquibase/datatype/core/CharType.java, liquibase-core/src/main/java/liquibase/datatype/core/ClobType.java, liquibase-core/src/main/java/liquibase/datatype/core/NCharType.java, liquibase-core/src/main/java/liquibase/datatype/core/NVarcharType.java, liquibase-core/src/main/java/liquibase/datatype/core/VarcharType.java, liquibase-core/src/test/groovy/liquibase/datatype/DataTypeFactoryTest.groovy
[CORE-2331](https://liquibase.jira.com/browse/CORE-2331) Support for MSSQL collation in data type description broken
=> CORE-2331 Support for MSSQL collation in data type description broken

liquibase-core/src/main/java/liquibase/database/core/OracleDatabase.java
This is a very minor change that fixes dropAll when using Oracle Spatial. JIRA issue here https://liquibase.jira.com/browse/CORE-1768.
=> CORE-1768 Fixed dropAll issue when using Oracle spatial.

liquibase-core/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGenerator.java
[CORE-2301](https://liquibase.jira.com/browse/CORE-2301) Fix regression fetching remarks for column snapshot on SQL 2000 by using a SQL 2000-specific query. Improve robustness by narrowing the result set, using two-part object names, qualifying object names, quoting identifiers, escaping strings.
=> CORE-2301 Fix regression, improve robustness fetching remarks for column snapshot

liquibase-core/src/main/java/liquibase/integration/spring/SpringLiquibase.java
CORE-2023 - Problem using includeAll with SpringLiquibase - fix so that base folder is found using the 'relativeTo', and then the resources within that folder are NOT listed using the 'relativeTo' (i.e. invert the handling).
=> CORE-2023 - Problem using includeAll with SpringLiquibase

liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java
[CORE-2360](https://liquibase.jira.com/browse/CORE-2360) Skip is active by default
Liquibase should probably continue to run by default when run using Maven. The default behavior changed in 3.3.3 to not run by default.
=> CORE-2360 Skip is active by default

liquibase-core/src/test/java/liquibase/util/StreamUtilTest.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java
I found out that system does not work with Derby Client Driver in my project.  3.3.3 seems to work but it was false positive, because maven plugin gave me shouldRun=false and warning ....
I think shouldRun should be true by default.
=> CORE-2366   shouldRun defaulted false

liquibase-core/src/main/java/liquibase/change/core/AlterSequenceChange.java, liquibase-core/src/test/java/liquibase/serializer/core/xml/XMLChangeLogSerializerTest.java, liquibase-core/src/test/java/liquibase/sqlgenerator/core/AlterSequenceGeneratorTest.java
Added annotation on cacheSize property getter in AlterSequenceChange class and include it in checkStatus checks.
Updated alter sequence unit test in XMLChangeLogSerializerTest and added AlterSequenceGeneratorTest.
=> CORE-2357 alterSequence does not work as expected when you need to change the cache size

liquibase-core/src/main/java/liquibase/resource/FileSystemResourceAccessor.java
I created this pull request because the source input file that I am dealing with is over a gigabyte in size and it would be very good for us not to be storing it in an uncompressed form. This is the initial snapshot of the database and we would like it to be the first changset.
=> Added reading of content of gzipped source files

liquibase-core/src/main/resources/liquibase/parser/core/xml/dbchangelog-3.4.xsd
Standardizes on 4 space indent levels. Standardizes on no space before /> of empty tag. Fixes missing/excess space characters. Unwraps unnecessary wrapping that harms readability. (Essentially IntelliJ defaults)
=> Standardize whitespace used for formatting in 3.4 XSD

liquibase-core/src/main/java/liquibase/changelog/ChangeLogChild.java, liquibase-core/src/main/java/liquibase/changelog/ChangeLogInclude.java, liquibase-core/src/main/java/liquibase/changelog/ChangeLogIncludeAll.java, liquibase-core/src/main/java/liquibase/changelog/ChangeLogProperty.java, liquibase-core/src/main/java/liquibase/changelog/ChangeSet.java, liquibase-core/src/main/java/liquibase/changelog/RollbackContainer.java, liquibase-core/src/main/java/liquibase/precondition/AbstractPrecondition.java, liquibase-core/src/main/java/liquibase/precondition/PreconditionLogic.java, liquibase-core/src/main/java/liquibase/precondition/core/PreconditionContainer.java, liquibase-core/src/main/java/liquibase/serializer/ChangeLogSerializer.java, liquibase-core/src/main/java/liquibase/serializer/core/formattedsql/FormattedSqlChangeLogSerializer.java, liquibase-core/src/main/java/liquibase/serializer/core/json/JsonChangeLogSerializer.java, liquibase-core/src/main/java/liquibase/serializer/core/string/StringChangeLogSerializer.java, liquibase-core/src/main/java/liquibase/serializer/core/xml/XMLChangeLogSerializer.java, liquibase-core/src/main/java/liquibase/serializer/core/yaml/YamlChangeLogSerializer.java, liquibase-core/src/test/groovy/liquibase/changelog/ChangeSetTest.groovy, liquibase-core/src/test/groovy/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParserTest.groovy, liquibase-core/src/test/groovy/liquibase/parser/core/xml/XMLChangeLogSAXParser_RealFile_Test.groovy, liquibase-core/src/test/groovy/liquibase/parser/core/yaml/YamlChangeLogParser_RealFile_Test.groovy, liquibase-core/src/test/java/liquibase/serializer/MockChangeLogSerializer.java
[CORE-2361](https://liquibase.jira.com/browse/CORE-2361) preConditions, rollback, property, include, includeAll cannot be serialized
Makes it possible to serialize the `preConditions`, `rollback` children of a `changeSet` and the `property`, `preConditions`, `include` and `includeAll` children of a `databaseChangeLog`.
Note that the changes to `ChangeLogSerializer` interface are backwards compatible to callers, but not implementors. I think that is acceptable for 3.4.x. It's not possible to keep or deprecate the former `write` method due to duplicate method signatures caused by type erasure.
=> CORE-2361 preConditions, rollback, property, include, includeAll cannot be serialized

liquibase-core/src/main/java/liquibase/integration/commandline/Main.java, liquibase-core/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java
A small change to check for diffTypes=data in the diffChangeLog command. Users keep trying to use this, so a message indicating that it doesn't work is better than going forward and producing unexpected results.
=> Check diffchangelog params

liquibase-core/src/main/java/liquibase/datatype/core/XMLType.java, liquibase-core/src/test/groovy/liquibase/datatype/DataTypeFactoryTest.groovy, liquibase-core/src/test/groovy/liquibase/datatype/core/XMLTypeTest.groovy
[CORE-2345] (https://liquibase.jira.com/browse/CORE-2345) Add XML Type
With a number of databases supporting XML data types, it makes sense to have a dedicated Liquibase XMLType, rather than having the XML database types resolve to UnknownType, or requiring the plugin for each respective database to have their own XMLType.
=> CORE-2345 Add XMLType

liquibase-core/src/main/java/liquibase/serializer/core/yaml/YamlChangeLogSerializer.java
...by representing changeSets as a list instead of an associative array
=> Fixed invalid YAML serialized changelog output

liquibase-core/src/main/java/liquibase/change/ColumnConfig.java, liquibase-core/src/main/java/liquibase/change/core/AddPrimaryKeyChange.java, liquibase-core/src/main/java/liquibase/change/core/AddUniqueConstraintChange.java, liquibase-core/src/main/java/liquibase/change/core/CreateIndexChange.java, liquibase-core/src/main/java/liquibase/database/AbstractJdbcDatabase.java, liquibase-core/src/main/java/liquibase/diff/output/changelog/core/MissingIndexChangeGenerator.java, liquibase-core/src/main/java/liquibase/diff/output/changelog/core/MissingUniqueConstraintChangeGenerator.java, liquibase-core/src/main/java/liquibase/snapshot/DatabaseSnapshot.java, liquibase-core/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java, liquibase-core/src/main/java/liquibase/snapshot/jvm/IndexSnapshotGenerator.java, liquibase-core/src/main/java/liquibase/snapshot/jvm/PrimaryKeySnapshotGenerator.java, liquibase-core/src/main/java/liquibase/snapshot/jvm/UniqueConstraintSnapshotGenerator.java, liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateIndexGenerator.java, liquibase-core/src/main/java/liquibase/statement/core/AddUniqueConstraintStatement.java, liquibase-core/src/main/java/liquibase/structure/core/Column.java, liquibase-core/src/main/resources/liquibase/parser/core/xml/dbchangelog-3.4.xsd, liquibase-core/src/test/groovy/liquibase/change/ColumnConfigTest.groovy, liquibase-core/src/test/java/liquibase/serializer/core/xml/XMLChangeLogSerializerTest.java
Adds support for descending key columns on indexes, unique constraints and primary keys
For example:
```
<createIndex tableName="my_table" indexName="my_index">
<column name="col1"/>
<column name="col2" descending="true"/>
</createIndex>
<addPrimaryKey tableName="my_table" columnNames="col1, col2 DESC"/>
<addUniqueConstraint tableName="my_table" columnNames="col1, col2 DESC"/>
```
~~Snapshots aren't addressed, but~~ This should resolve all the following issues:
Liquibase JIRA:
[CORE-419](https://liquibase.jira.com/browse/CORE-419) Allowing ASC and DESC in index definitions
[CORE-1232](https://liquibase.jira.com/browse/CORE-1232) Ordered index creation
Liquibase Forum:
http://forum.liquibase.org/topic/create-index-and-order
Stack Overflow: …
=> CORE-419 Add support for descending key columns on indexes, unique constraints and primary keys

liquibase-core/src/test/java/liquibase/serializer/ChangeLogSerializerFactoryTest.java
[CORE-2236](https://liquibase.jira.com/browse/CORE-2236) 
There are now 6 supported file extensions including "yml", so the test case needs to be updated
=> CORE-2236 Update test case to be aware of support for the yml extension

liquibase-core/src/main/java/liquibase/sqlgenerator/core/CopyRowsGenerator.java
If the copy rows function is called with no copy columns, you'll end up with an invalid SQL statement.
This occurs when you try to add a single column to a table in an SQLITE database. This occurs because to alter table with an SQLite database you create a temporary table and copy over the rows.
Note: In the future, you might want to update the alter table implementation for SQLite since SQLIte now supports the "ALTER TABLE Query"
This patch fixes the `liquibase: [SQLITE_ERROR] SQL error or missing database (near ")": syntax error)` bug
=> Patch copy rows for edge case with no copy columns

liquibase-core/src/main/java/liquibase/servicelocator/ServiceLocator.java, liquibase-core/src/main/resources/META-INF/MANIFEST.MF
[CORE-2024](https://liquibase.jira.com/browse/CORE-2024) Replace liquibase.sdk with liquibase.sdk.database for packages to scan
Until the Liquibase SDK can be split off into it's own module, this is an effective workaround for class loaders that log class loading errors (e.g. in an application server environment) to avoid loading Jetty and JUnit classes that may not be on the classpath.
This also relates to [CORE-2145](https://liquibase.jira.com/browse/CORE-2145).
=> CORE-2024 Replace liquibase.sdk with liquibase.sdk.database for packages to scan

liquibase-core/src/main/java/liquibase/dbdoc/HTMLListWriter.java, liquibase-core/src/main/java/liquibase/dbdoc/TableWriter.java
Hi,
my teammates were not quite satisfied with the current status of generated dbDoc.
So I made following additions to these:
- Display current nullable status of each column in Column list in table view [6a61f69]
- Display current table indexes in table view, containing some details [16e3808]
- Primary Key or Unique/Non-Unique, Clustered/Non-Clustered
- Index name
- Columns in index
- Display current foreign keys in table view containing following details [13ecab6]
- Foreign Key Name
- Affected Column(s)
- Referenced Table
- Referenced Column(s) [f4f0ee9]
- Change logs containing uppercase characters produced dead links in "Change Logs" list on non-Windows Systems [404c0c5]
Thanks for your effort.
Best regards,
Juan
=> dbDoc enhancements (more information, bug fixed)

liquibase-core/src/main/java/liquibase/sqlgenerator/core/GetViewDefinitionGeneratorMSSQL.java
[CORE-2397](https://liquibase.jira.com/browse/CORE-2397) MSSQL View Snapshot should not use sp_helptext
Improves robustness of SQL generation for obtaining a view definition on SQL Server. Supports SQL Server 2000 and later without using sp_helptext.
=> CORE-2397 Improve robustness of SQL generation for obtaining a view definition on MSSQL

liquibase-core/src/main/java/liquibase/logging/LogFactory.java
This PR reverts the small change to the LogFactory that uses the `DefaultLogger` when the `ServiceLocator` throws and exception. This should fix [CORE-2443](https://liquibase.jira.com/browse/CORE-2443).
I am open to other solutions to the problem but as I am getting messages about my logger no longer working and I rather get this patched quickly.
=> CORE-2443 - Liquibase 3.4.0 ignores third party loggers in certain situations

liquibase-core/src/main/java/liquibase/sqlgenerator/core/UpdateGenerator.java, liquibase-core/src/test/java/liquibase/sqlgenerator/core/UpdateGeneratorTest.java
[CORE-2442](https://liquibase.jira.com/browse/CORE-2442) Make UpdateGenerator more resilent to parameter names and values that contain the pattern to match
=> CORE-2442 Creating MD5 checksum fails if changeSet id contains the character "?"

liquibase-core/src/main/java/liquibase/util/file/FilenameUtils.java, liquibase-core/src/test/java/liquibase/util/file/FilenameUtilsTest.java
we need the same fix like #459 in the `3.4.x` branch so that we can use next minor release.
BTW I created a local release for the meantime and published it here: https://github.com/pkozelka/liquibase/releases/tag/liquibase-parent-3.4.0-pkozelka-1
=> CORE-2385 fix handling of null basePath in FilenameUtils.concat - backport to 3.4.x

liquibase-core/src/main/resources/dist/liquibase
Suggested fix: use /usr/bin/env bash instead of /bin/sh
using /bin/sh yields error output:
```
liquibase: 39: liquibase: [[: not found
```
=> Fix [[ not found error -> [[ is bash-builtin

liquibase-core/src/main/java/liquibase/database/core/SybaseASADatabase.java
To resolve unknown database : Sybase IQ that cause the error below :                                               com.sybase.jdbc4.jdbc.SybSQLException: SQL Anywhere Error -265: Procedure 'current_schema' not found
I added "Sybase IQ" to the implementation product names supported.
=> Add of new sybase IQ productname to supported names

liquibase-core/src/main/java/liquibase/datatype/core/UnknownType.java, liquibase-core/src/test/groovy/liquibase/datatype/DataTypeFactoryTest.groovy
Reverts 8713973 (unneeded due to [CORE-2217](https://liquibase.jira.com/browse/CORE-2217), [CORE-2345](https://liquibase.jira.com/browse/CORE-2345))  while retaining cd69419 (needed for [CORE-2410](https://liquibase.jira.com/browse/CORE-2410))
Adds a test case that shows CORE-2410 is fixed
=> CORE-2410 Snapshot should not include paramaters for MSSQL geometry, geography or sql_variant types

liquibase-core/src/main/java/liquibase/database/core/InformixDatabase.java
This fixes a problem with using Informix with Liquibase. The base class method causes a call to a non-existent stored procedure.
=> Informix: Return null for connection schema name

liquibase-core/src/main/java/liquibase/datatype/core/ClobType.java, liquibase-core/src/main/java/liquibase/datatype/core/TimestampType.java, liquibase-core/src/test/groovy/liquibase/datatype/DataTypeFactoryTest.groovy
[CORE-2405](https://liquibase.jira.com/browse/CORE-2405) Collation not preserved, depending on configuration
[CORE-2406](https://liquibase.jira.com/browse/CORE-2406) Escaped built-in data types should be lower case
Preserves collation and ensures compatibility with case-sensitive database collations
=> CORE-2405, CORE-2406 MSSQL data type bugs

liquibase-core/src/main/java/liquibase/changelog/ChangeSet.java, liquibase-core/src/main/java/liquibase/changelog/DatabaseChangeLog.java
[CORE-2466](https://liquibase.jira.com/browse/CORE-2466) Rollback referencing a change set in another file cannot be parsed
Makes it possible to resolve the root change log from within a nested change log. Then the root change log can be used to resolve a change set referenced in a rollback node.
Maintains the original change set reference for rollback changes that are included by reference, so that paths relative to the referenced change log file can be resolved correctly.
=> CORE-2466 Rollback referencing a change set in another file cannot be parsed

liquibase-core/src/main/java/liquibase/integration/commandline/CommandLineUtils.java
[CORE-2467](https://liquibase.jira.com/browse/CORE-2467) SSO with jtds MSSQL doesn't work after 3.3.5 for update - null user error
=> CORE-2467 Support default schema with SSO on MSSQL 2005 and later

liquibase-core/src/main/java/liquibase/sqlgenerator/core/FindForeignKeyConstraintsGeneratorMSSQL.java
[CORE-2470](https://liquibase.jira.com/browse/CORE-2470) MSSQL: FindForeignKeyConstraintsGeneratorMSSQL doesn't honor specified schema
Modifies FindForeignKeyConstraintGeneratorMSSQL to respect the specified schema and work for SQL Server 2000 and later
=> CORE-2470 Update FindForeignKeyConstraintGeneratorMSSQL to respect the specified schema

liquibase-core/src/main/java/liquibase/sqlgenerator/core/DeleteGenerator.java, liquibase-core/src/main/java/liquibase/sqlgenerator/core/UpdateDataChangeGenerator.java, liquibase-core/src/main/java/liquibase/sqlgenerator/core/UpdateGenerator.java, liquibase-core/src/main/java/liquibase/statement/UpdateExecutablePreparedStatement.java, liquibase-core/src/main/java/liquibase/util/SqlUtil.java, liquibase-core/src/test/java/liquibase/sqlgenerator/core/DeleteGeneratorTest.java, liquibase-core/src/test/java/liquibase/sqlgenerator/core/UpdateGeneratorTest.java, liquibase-core/src/test/java/liquibase/statement/UpdateExecutablePreparedStatementTest.java
Builds on [Björn Kautler's](https://github.com/Vampire) pull request [#481](https://github.com/liquibase/liquibase/pull/481) by adding additional test cases and centralizing the common code. The pre-existing `SqlUtil` seemed like the right place for the common code.
=> CORE-2490, CORE-2442 Test case improvements, centralize predicate placeholder replacing code

liquibase-core/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java
In SQLServer, I had a precondition checking for the existence of a primary key which did not behave correctly. I traced it down to the snapshot which did not find any primary keys.
When using the default schema (null), the query to fetch primary keys had a where clause like this:
WHERE [s].[name] = N'null'
so it failed as the default schema is 'dbo'
=> MSSQL snapshot did not include primary keys with default schema

liquibase-core/src/main/java/liquibase/statement/ExecutablePreparedStatementBase.java
There were checks that were based on java.io.File class which always failed when the resource was on the classpath.
=> Fixed: Absolute filename as valueLobFile would never be found by ClasspathResourceAccessor

liquibase-core/src/main/java/liquibase/database/AbstractJdbcDatabase.java, liquibase-core/src/main/java/liquibase/database/core/MSSQLDatabase.java, liquibase-core/src/main/java/liquibase/database/core/PostgresDatabase.java, liquibase-core/src/main/java/liquibase/database/core/SybaseDatabase.java
By default getConnectionSchemaName calls an sql statement that obtains
the current schema. Not only does this force a custom database to copy
the code just so it can modify the call statement, but it is also error
prone as when the base implementation evolves the changes don't occur in
overridden classes. Such error occurred when the base
getConnectionSchemaName has changes so it would return null in the case
of an OfflineConnection but PostgresDatabse still used old code and
would fail on an offline connection.
This evolution adds the getconnectionSchemaNameCallStatement that can be
overridden by databases that only need to customise the statement, that
way the logic is shared with the abstract class.
The following databases have been refactored to use the new method:
- MSSQLDatabase
- …
=> Fix error with postgres throwing an exception with an offline connection and Refactor getConnectionSchemaName to prevent code errors

liquibase-core/src/main/java/liquibase/sqlgenerator/core/AddForeignKeyConstraintGenerator.java
MS SQL Server does not understand the syntax but behaves as intended. A restrict-on-update means one must not violate the foreign key constraint which is what is enforced by the constraint anyways. The RESTRICT keyword is required for some databases, I think MySQL, which support different alternatives. Without the change <addForeignKeyConstraint onUpdate="RESTRICT"/> is doomed to fail.
=> onUpdate="RESTRICT" is to be ignored on MS SQL Server like it is done for onDelete already.

liquibase-core/src/main/java/liquibase/sqlgenerator/core/FindForeignKeyConstraintsGeneratorDerby.java
LiquiBase claims to support this, but it does not because no such class is implemented in the code base.
=> implements FindForeignKeyConstraintsGenerator for the Derby database.

liquibase-core/src/main/java/liquibase/diff/output/changelog/core/MissingTableChangeGenerator.java
JIRA: https://liquibase.jira.com/browse/CORE-1468 "Number / Numeric handling must differ between different database systems"
When generating the changelog, use the comparison database instead of the reference database to find the column types.
E.g. if your comparison database is PostgreSQL, and your reference database is Hibernate (liquibase-hibernate extension) then this will use PostgreSQL data types in the changelog, that you can properly apply to your comparison database.
Otherwise you would have to do an additional step of translating Hibernate data types (if they exist) into PostgreSQL data types, before the changelog were to become applicable to the comparison database.
**EDIT:** More specific example: Postgres has a `UUID` data type. If your field is a `java.util.UUID`, using …
=> [CORE-1468] Comparison database types for missing table

liquibase-core/src/main/resources/liquibase/parser/core/xml/dbchangelog-3.5.xsd
(Was in dbchangelog-3.4, but not dbchangelog-3.5)
=> CORE-2299 - bugfix - apply 'errorIfMissingOrEmpty' attribute for 'includeAll' to dbchangelog-3.5.xsd.

liquibase-core/src/main/java/liquibase/database/core/InformixDatabase.java
I have finally had a chance to revisit this problem. The original fix made it easy to generate the tables for the first time but it still did not support upgrading. I have fixed the getConnectionSchemaName method now to get the schema for the current session.
This has enabled us to upgrade our current database for Keycloak with the changes for the most recent version. 
There is still an issue whereby the Informix database cannot be in ANSI mode, due to the various combinations of upper- and lower-case conversion and case sensitivity (not helped by the JDBC driver). I think, though, that this will fix the problem for the majority of cases.
=> Fix schema name generation (again)

liquibase-core/src/main/java/liquibase/database/core/OracleDatabase.java, liquibase-core/src/test/java/liquibase/sqlgenerator/core/InsertOrUpdateGeneratorOracleTest.java, liquibase-core/src/test/java/liquibase/sqlgenerator/core/InsertOrUpdateGeneratorPostgresTest.java
* fix `"schema.seqname".nextval` to `"schema"."seqname".nextval`
Original:
```sql
-- Oracle
INSERT INTO mycatalog.mytable (col3) VALUES ("myschema.my_seq".nextval)
-- Postgres
INSERT INTO myschema.mytable (col3) VALUES (nextval('myschema.my_seq'))
```
Fixed:
```sql
-- Oracle
INSERT INTO mycatalog.mytable (col3) VALUES ("myschema"."my_seq".nextval)
-- Postgres
INSERT INTO myschema.mytable (col3) VALUES (nextval('myschema.my_seq'))
```
Defference is `"."` between schema name and seq. name
Changeset example:
```xml
<insert tableName="MYTABLE" schemaName="${database.defaultSchemaName}">
<column name="col3" valueSequenceNext="${database.defaultSchemaName}.my_seq"/>
...
```
=> CORE-2565 Fix oracle sequence name with schema quoting

liquibase-core/src/main/java/liquibase/changelog/ChangeSet.java
logging fix prevents stack trace in user definable log. The exception which reaches the appServer will stacktrace to stdout anyway.
=> logging fix prevents stack trace in user definable log

liquibase-core/src/main/java/liquibase/database/core/OracleDatabase.java
In Oracle 12c, creating a table with an autoincrement column makes Oracle also
create a system-generated sequence for that column. Such sequences cannot be
dropped, but only purged, since undropping the table would otherwise fail.
Attempting to drop a system-generated sequence results in an ORA-32794 error,
which would make the dropAll command fail. This change makes dropAll skip all
sequences that are system objects.
=> CORE-2579 don't drop Oracle system sequences

liquibase-core/src/main/java/liquibase/changelog/StandardChangeLogHistoryService.java
When the checksums are incompatible upgradeChecksums should be ran (in case of updateSQL command this gets skipped because the set MD5SUM null command is only written to sql file)
Because upgradeChecksums is not directly executed for updateSQL command, ValidatingVisitor should consider checksum valid if databaseChecksumsCompatible is false.
=> Added databaseChecksumsCompatible variable.

liquibase-core/src/main/java/liquibase/database/core/PostgresDatabase.java
Fixing an issue reported on the forums at http://forum.liquibase.org/topic/unable-to-generate-offline-migration-script-for-postgresql-database
=> check for no connection or offline connection

liquibase-core/src/main/java/liquibase/datatype/DatabaseDataType.java, liquibase-core/src/main/java/liquibase/datatype/core/BooleanType.java, liquibase-core/src/main/java/liquibase/datatype/core/SmallIntType.java
Fixes for following defects
1. CORE-2604:PostgreSQL datatype bit(n) column gives BOOLEAN(n) type for CreateTableChange genearated sql statement
2. CORE-2606: PostgreSQL : Table creation with datatype smallserial fails.
=>  0# Fixes for CORE-2604 and CORE- 2606

liquibase-core/pom.xml, pom.xml
The proper Maven artifact name for EasyMock is `easymock` not the camel-case `easyMock`. The camel-case spelling causes issues on case-sensitive filesystems (like those in use on Linux systems).
=> Fix the Maven artifact name for EasyMock.

liquibase-core/src/main/java/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParser.java
Formatted sql precondition does not expand changelog parameters.
=> Fix formatted sql precondition not expanding changelog parameters.

liquibase-core/src/main/java/liquibase/change/ChangeFactory.java, liquibase-core/src/main/java/liquibase/changelog/ChangeLogHistoryServiceFactory.java, liquibase-core/src/main/java/liquibase/configuration/LiquibaseConfiguration.java, liquibase-core/src/main/java/liquibase/database/DatabaseFactory.java, liquibase-core/src/main/java/liquibase/datatype/DataTypeFactory.java, liquibase-core/src/main/java/liquibase/diff/DiffGeneratorFactory.java, liquibase-core/src/main/java/liquibase/diff/compare/DatabaseObjectComparatorFactory.java, liquibase-core/src/main/java/liquibase/diff/output/changelog/ChangeGeneratorFactory.java, liquibase-core/src/main/java/liquibase/lockservice/LockServiceFactory.java, liquibase-core/src/main/java/liquibase/logging/LogFactory.java, liquibase-core/src/main/java/liquibase/osgi/OSGiUtil.java, liquibase-core/src/main/java/liquibase/parser/ChangeLogParserFactory.java, liquibase-core/src/main/java/liquibase/parser/NamespaceDetailsFactory.java, liquibase-core/src/main/java/liquibase/parser/SnapshotParserFactory.java, liquibase-core/src/main/java/liquibase/precondition/PreconditionFactory.java, liquibase-core/src/main/java/liquibase/sdk/Context.java, liquibase-core/src/main/java/liquibase/sdk/supplier/database/ConnectionConfigurationFactory.java, liquibase-core/src/main/java/liquibase/serializer/ChangeLogSerializerFactory.java, liquibase-core/src/main/java/liquibase/serializer/SnapshotSerializerFactory.java, liquibase-core/src/main/java/liquibase/servicelocator/ServiceLocator.java, liquibase-core/src/main/java/liquibase/snapshot/SnapshotGeneratorFactory.java, liquibase-core/src/main/java/liquibase/sqlgenerator/SqlGeneratorFactory.java, liquibase-core/src/main/java/liquibase/structure/core/DatabaseObjectFactory.java
This pull request is focused on resolving occurrences of Sonar rule squid:S2444 - Lazy initialization of "static" fields should be "synchronized"
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid:S2444
Please let me know if you have any questions.
Kirill Vlasov
=> Lazy initialization of "static" fields should be "synchronized"

liquibase-core/src/main/java/liquibase/change/ChangeFactory.java, liquibase-core/src/main/java/liquibase/changelog/ChangeLogHistoryServiceFactory.java, liquibase-core/src/main/java/liquibase/changelog/StandardChangeLogHistoryService.java, liquibase-core/src/main/java/liquibase/configuration/ConfigurationProperty.java, liquibase-core/src/main/java/liquibase/datatype/DataTypeFactory.java, liquibase-core/src/main/java/liquibase/diff/DiffGeneratorFactory.java, liquibase-core/src/main/java/liquibase/diff/compare/DatabaseObjectComparatorComparator.java, liquibase-core/src/main/java/liquibase/diff/output/changelog/ChangeGeneratorComparator.java, liquibase-core/src/main/java/liquibase/lockservice/LockServiceFactory.java, liquibase-core/src/main/java/liquibase/snapshot/SnapshotGeneratorComparator.java, liquibase-core/src/main/java/liquibase/sqlgenerator/SqlGeneratorComparator.java, liquibase-core/src/main/java/liquibase/util/SqlUtil.java, liquibase-core/src/main/java/liquibase/util/file/FilenameUtils.java
This pull request is focused on resolving occurrences of Sonar rule findbugs:DM_NUMBER_CTOR - Performance - Method invokes inefficient Number constructor; use static valueOf instead
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=findbugs:DM_NUMBER_CTOR
Please let me know if you have any questions.
Kirill Vlasov
=> Method invokes inefficient Number constructor

liquibase-core/src/main/java/liquibase/changelog/RanChangeSet.java, liquibase-core/src/test/java/liquibase/changelog/RanChangeSetTest.java
Currently, when running Liquibase as part of Spring Boot, having changesets set to runOnChange and loading configuration from the classpath causes the changeset to be run every time once it has changed once and creates a new EXECUTED line in the DATABASECHANGELOG, rather than a RERAN line. This is caused by the RanChangeSet.isSameAs method not stripping classpath: from both entries, meaning they are always identified as not the same when they are.
=> Update RanChangeSet to handle classpath prefix

liquibase-core/src/main/java/liquibase/database/AbstractJdbcDatabase.java, liquibase-core/src/main/java/liquibase/database/Database.java, liquibase-core/src/main/java/liquibase/sdk/database/MockDatabase.java, liquibase-core/src/main/java/liquibase/snapshot/ResultSetCache.java
Original fetch size causing SQLWarning exception with Oracle TimesTen jdbc driver.
There is no comment in oracle docu regarding setFetchSize but i have found note in squirrel forum: http://sourceforge.net/p/squirrel-sql/mailman/message/9012007/
Exception from timesten jdbc driver:
org.liquibase:liquibase-maven-plugin:3.4.2:update failed: liquibase.exception.DatabaseException: com.timesten.jdbc.JdbcOdbcSQLWarning: [TimesTen][TimesTen 11.2.2.7.0 CLIENT]Option value changed
=> Reduced fetch size. 

liquibase-core/src/main/java/liquibase/ContextExpression.java, liquibase-core/src/main/java/liquibase/changelog/ChangeLogInclude.java, liquibase-core/src/main/java/liquibase/changelog/ChangeLogIncludeAll.java, liquibase-core/src/main/java/liquibase/changelog/ChangeSet.java, liquibase-core/src/main/java/liquibase/changelog/DatabaseChangeLog.java, liquibase-core/src/main/java/liquibase/changelog/filter/ContextChangeSetFilter.java, liquibase-core/src/main/resources/liquibase/parser/core/xml/dbchangelog-3.5.xsd, liquibase-core/src/test/groovy/liquibase/changelog/DatabaseChangeLogTest.groovy
Adds ability for a change set to inherit context expressions via databaseChangeLog, include or includeAll parent containers
[CORE-155](https://liquibase.jira.com/browse/CORE-155) Default-context attribute in databaseChangeLog tag
The context expressions from the parent containers are inheritable and ANDed together logically.
Example usage:
_changelog-master.xml:_
```xml
<databaseChangeLog>
<include file="changelog-included.xml" context="d and e"/>
<includeAll ... context="f or g"/>
</databaseChangeLog>
```
_changelog-included.xml:_
```xml
<databaseChangeLog ... context="a and (b or c)">
<changeSet ... context="h or j or k">...</changeSet>
<changeSet ...>...</changeSet>
<changeSet ...>...</changeSet>
</databaseChangeLog>
```
=> CORE-155 Add ability for a change set to inherit context expressions from parent containers (WIP)

liquibase-core/src/main/java/liquibase/change/core/LoadDataChange.java
Today is possible load csv into tables with sequence columns this way:
```csv
id_pais|cod_bacen|descricao
SEQNAME.NEXVAL()|1234|BRASIL
SEQNAME.NEXVAL()|1234|ARGENTINA
```
```xml
<loadData tableName="pais" file="liquibase/seeds/pais.csv" separator="|" >
<column type="computed" name="id_pais"/>
<column type="numeric" name="cod_bacen" />
<column type="string" name="descricao" />
</loadData>
```
but it is not multidatabase compatible.. because this I propose this change:
```csv
id_pais|cod_bacen|descricao
0|1234|BRASIL
0|1234|ARGENTINA
```
```xml
<loadData tableName="pais" file="liquibase/seeds/pais.csv" separator="|" >
<column type="sequence" name="id_pais" defaultValue="pais_seq"/>
<column type="numeric" name="cod_bacen" />
<column type="string" name="descricao" />
</loadData>
```
=> Sequence Support for LoadData

liquibase-core/pom.xml, liquibase-debian/pom.xml, liquibase-integration-tests/pom.xml
This main point of this is to fix the build of liquibase-debian, which does not build in a clean environment where 3.4.2-SNAPSHOT isn't present. While fixing that, I reviewed the other poms for cleanups and removed some defaults that should be left to Maven to get right.
=> Fix build, remove defaults

liquibase-core/pom.xml, liquibase-debian/pom.xml, liquibase-integration-tests/pom.xml, liquibase-maven-plugin/pom.xml, pom.xml
I have cleaned up maven poms. More focused on using jars dependency management and also plugins. No new functionality only maintenance pull request. 
Fixed warning with duplicate javacc-maven-plugin plugin declaration.
=> maven poms clean up

liquibase-core/src/main/java/liquibase/changelog/DatabaseChangeLog.java, liquibase-core/src/test/java/liquibase/parser/core/xml/XMLChangeLogSAXParserTest.java, liquibase-core/src/test/resources/liquibase/parser/core/xml/ignoreDuplicatedChangeLogs/included.changelog1.xml, liquibase-core/src/test/resources/liquibase/parser/core/xml/ignoreDuplicatedChangeLogs/included.changelog2.xml, liquibase-core/src/test/resources/liquibase/parser/core/xml/ignoreDuplicatedChangeLogs/included.changelog3.xml, liquibase-core/src/test/resources/liquibase/parser/core/xml/ignoreDuplicatedChangeLogs/included.changelog4.xml, liquibase-core/src/test/resources/liquibase/parser/core/xml/ignoreDuplicatedChangeLogs/master.changelog.xml
Two changesets are equal they have the same
- id
- filepath
- author
- md5
- dbms
- contexts
- labels
=> Ignoring changesets that are included twice

liquibase-core/src/main/java/liquibase/datatype/core/TinyIntType.java
TINYINT should be mapped to SMALLINT in DB2.
See Table 1. http://www.ibm.com/developerworks/data/library/techarticle/dm-0807patel/
=> * fixed the mapping of TINYINT type for DB2 database

liquibase-debian/pom.xml
The Debian Policy states that symbolic links to paths one or more levels beneath the root shall be relative: https://www.debian.org/doc/debian-policy/ch-files.html#s10.5
Because the Liquibase package creates an absolute symlink from `/usr/bin/liquibase` to `/usr/lib/liquibase-X.Y.Z/liquibase`, it is broken on installations outside of `/` (for instance, using Heroku's [APT buildpack](https://github.com/heroku/heroku-buildpack-apt)).
=> deb: don't symlink binary to absolute path

liquibase-core/src/main/java/liquibase/diff/output/changelog/DiffToChangeLog.java, liquibase-core/src/main/java/liquibase/diff/output/changelog/core/MissingDataChangeGenerator.java
Using string constant instead of StandardCharsets class for compatibility with Java 6.
@nvoxland
=> Explicit UTF-8 constructing string from byte array

liquibase-core/src/main/java/liquibase/database/AbstractJdbcDatabase.java
Removing the executor invokes hashCode on the underlying connection,
which, on tomcat 8, fails if the connection has been closed.
```
...
Caused by: java.lang.reflect.UndeclaredThrowableException
at com.sun.proxy.$Proxy52.hashCode(Unknown Source)
at liquibase.database.jvm.JdbcConnection.hashCode(JdbcConnection.java:436)
at liquibase.database.AbstractJdbcDatabase.hashCode(AbstractJdbcDatabase.java:1188)
at java.util.concurrent.ConcurrentHashMap.replaceNode(ConcurrentHashMap.java:1106)
at java.util.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:1097)
at liquibase.executor.ExecutorService.clearExecutor(ExecutorService.java:42)
at liquibase.database.AbstractJdbcDatabase.close(AbstractJdbcDatabase.java:1206)
at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLi …
```
=> CORE-2780 Clear executor before closing connection

liquibase-core/src/main/java/liquibase/diff/output/changelog/DiffToChangeLog.java
Fix a NullPointerException in DiffToChangeLog.sortMissingObjects when schemaComparisons.
The following code, which can only be reached, if a DB2 database is used, will throw a NullPointerException, when getSchemaComparisons() returns null.
```java
for (CompareControl.SchemaComparison comparison : this.diffOutputControl.getSchemaComparisons()) {
```
So all the following method will not work, when using a DB2 database:
```java
liquibase.database.AbstractJdbcDatabase.dropDatabaseObjects(CatalogAndSchema)
liquibase.dbtest.AbstractIntegrationTest.generateChangeLog_noChanges()
liquibase.integration.ant.DiffDatabaseToChangeLogTask.getDiffOutputControl()
liquibase.integration.ant.GenerateChangeLogTask.getDiffOutputControl()
org.liquibase.maven.plugins.LiquibaseDatabaseDiff.performLiquibaseTask(Liq …
```
=> Fix a NullPointerException in DiffToChangeLog.sortMissingObjects

liquibase-core/src/main/java/liquibase/database/core/H2Database.java, liquibase-core/src/main/java/liquibase/datatype/core/DateTimeType.java, liquibase-core/src/main/java/liquibase/util/ISODateFormat.java, liquibase-core/src/test/groovy/liquibase/change/ColumnConfigTest.groovy, liquibase-core/src/test/groovy/liquibase/parser/core/yaml/YamlChangeLogParser_RealFile_Test.groovy, liquibase-core/src/test/java/liquibase/util/ISODateFormatTest.java
This fixes a problem exporting and importing TimeStamps with sub second precision to and from CSV files. There are 2 problems in the code:
* The sub second part of a TimeStamp is a fraction, so 1992-02-11T13:22:44.**6** is
1992-02-11T13:22:44.**600** and not 1992-02-11T13:22:44.**006**
* The sub second part of a TimeStamp can have up to 9 digits. See the added test in 
ISODateFormatTest.java
=> Handle TimeStamps with nano second precision correctly

liquibase-core/src/main/java/liquibase/diff/output/changelog/core/MissingDataExternalFileChangeGenerator.java, liquibase-core/src/main/java/liquibase/util/csv/opencsv/CSVWriter.java
At the moment CSV files created by LiquiBase reverse engineering some database cannot been read back by LiquiBase under some circumstances. There are 2 reasons for that:
* CSV files are always read with UTF-8 encoding, but written with the default system encoding.  
*  See MissingDataExternalFileChangeGenerator.java:  
```java
CSVWriter outputFile = new CSVWriter(new BufferedWriter(new FileWriter(fileName)));
...
LoadDataChange change = new LoadDataChange();
change.setFile(fileName);
change.setEncoding("UTF-8");
```
* CSVWriter and CSVParser using different escape characters  
*  See CSVWriter.java and CSVParser.java:  
```java
public static final char DEFAULT_ESCAPE_CHARACTER = '"';
```
```java
public static final char DEFAULT_ESCAPE_CHARACTER = '\\';
```
=> Make CSV files created by LiquiBase readable by Liquibase

liquibase-core/src/main/java/liquibase/database/core/DB2Database.java, liquibase-core/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java, liquibase-core/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGenerator.java, liquibase-core/src/main/java/liquibase/snapshot/jvm/SequenceSnapshotGenerator.java, liquibase-core/src/main/java/liquibase/snapshot/jvm/UniqueConstraintSnapshotGenerator.java, liquibase-core/src/main/java/liquibase/sqlgenerator/core/ReorganizeTableGeneratorDB2.java
This patch replaces the DB2Database.isZOS() and DB2Database.isAS400() methods, which were based on DatabaseMetaData.getDatabaseProductName(), which does not work correctly for some DB2 server types.
[IBM Knowledge Center - DatabaseMetaData methods for identifying the type of data server](http://www.ibm.com/support/knowledgecenter/SSEPEK_10.0.0/com.ibm.db2z10.doc.java/src/tpc/imjcc_c0053013.html)
=> Determine the DB2 data server type correctly

liquibase-core/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java, liquibase-core/src/main/java/liquibase/snapshot/jvm/SequenceSnapshotGenerator.java, liquibase-core/src/main/java/liquibase/snapshot/jvm/UniqueConstraintSnapshotGenerator.java, liquibase-core/src/main/java/liquibase/sqlgenerator/core/FindForeignKeyConstraintsGeneratorDB2.java, liquibase-core/src/main/java/liquibase/sqlgenerator/core/GetViewDefinitionGeneratorDB2.java
In DB2 z/OS the database definition is stored in different tables than in a standard DB2 LUW. With this patch LiquiBase will use the right SQLs to determine the database layout on a DB2 z/OS.
=> Add reverse engineering support for DB2 z/OS

liquibase-core/src/main/java/liquibase/parser/core/yaml/YamlSnapshotParser.java
CORE-2806 If the input stream parsing the snapshot file does not get
closed, then the process cannot delete the snapshot file after it is done
using it
=> Close input stream after parsing JSON snapshot

liquibase-core/src/main/java/liquibase/changelog/ChangeSet.java
This change fixes an issue where the ChangeSet doesn't correctly locate a changeLogFile for rollbacks if there are multiple levels of changeLog inclusion. Given the set of files below, the current code does not find the changes in changeSet1 for rolling back, because it goes directly to the root ChangeLog. Since v1/migrations.xml hasn't finished loading, the root changeLog doesn't know about any of its changes yet.
This change instead walks the tree of parent changeLogs looking for the reference, using the first one found.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<databaseChangeLog
xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog …
```
=> Traverse parent changelogs for rollbacks CORE-2844

liquibase-core/src/main/java/liquibase/datatype/core/BlobType.java
Postgres does not actually support the BINARY type.
Instead, use OID for streamable javax.sql.Blobs, and
BYTEA for everything else.
=> CORE-1863 Fix Postgres BLOB type mappings

liquibase-integration-tests/setup/postgresql/create_dbs_for_integration_tests.sql, pom.xml
(1) If possible, use a JDK7 driver with the same version number. If not, use the last version that is compatible with JDK7.
(2) SONAR fix: Reorder elements in pom.xmls to match the standard order for Maven
(3) Fix für the PostgreSQL IT setup script: Drop schema LBCAT2 on test db reset
=> 2nd round of JDK7 compatibility fixes

liquibase-core/src/main/java/liquibase/database/core/MSSQLDatabase.java
There is a bug that AbstractJdbcDatabase.quotingStrategy is ignored when 
```java
class MSSQLDatabase  {
public String escapeObjectName(String objectName, Class<? extends DatabaseObject> objectType)
```
calls directly 
```
quoteObject(objectName, objectType)
```
I think it should call 
```java
super.escapeObjectName(objectName, objectType)
```
then quotingStrategy can be used to influence quoting of objects in MS SQL scripts. It works for me on branch 3.5.x. I did not tested on master, but it seems to be same there too
=> fix the escaping of object name on the MS SQL

liquibase-core/src/main/java/liquibase/serializer/core/string/StringSnapshotSerializerReadable.java
This bugfix resolve a problem encountered when I performed a liquibase snapshot.
=> avoid null pointer exception on snapshot action

liquibase-core/src/main/java/liquibase/datatype/core/IntType.java
See https://www.postgresql.org/docs/current/static/datatype-numeric.html
=> Postgres does not support parameters for type int

liquibase-core/src/main/java/liquibase/changelog/DatabaseChangeLog.java
By now, if the object quoting strategy is changed in ```<databaseChangeLog />``` tag, this strategy will be used for the execution of a ```<changeSet />``` but not for its validation. This pull request changes the object quoting strategy, so the same strategy is used for both.
=> Different object quoting strategies are used for validation and execution of a ChangeSet.

liquibase-core/src/main/java/liquibase/change/custom/CustomChangeWrapper.java, liquibase-core/src/test/groovy/liquibase/change/custom/CustomChangeWrapperTest.groovy
When running dbDoc a custom change properties are set when
CustomChangeWrapper.validate is called. 
But since PR #88, already ran
changes are no longer validated (for performance reasons). Unfortunately that causes problems if the properties are used in composing the confirmation
message (from NPEs - causing dbDoc to fail - to wrong messages - nulls
everywhere).
=> CORE-2989: Custom change: configure change before calling getConfirmationMessage

.gitignore, liquibase-core/src/main/java/liquibase/database/AbstractJdbcDatabase.java, liquibase-core/src/main/java/liquibase/database/core/OracleDatabase.java, liquibase-core/src/test/groovy/liquibase/changelog/DatabaseChangeLogTest.groovy, liquibase-core/src/test/groovy/liquibase/parser/core/xml/XMLChangeLogSAXParser_RealFile_Test.groovy, liquibase-core/src/test/resources/liquibase/parser/core/xml/preconditionsChangeLog.xml, liquibase-core/src/test/resources/liquibase/parser/core/xml/testCasesChangeLog.xml, liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java, liquibase-integration-tests/src/test/java/liquibase/dbtest/oracle/OracleIntegrationTest.java, liquibase-integration-tests/src/test/java/liquibase/test/DatabaseTestContext.java, liquibase-integration-tests/src/test/java/liquibase/test/DatabaseTestURL.java, liquibase-integration-tests/src/test/resources/changelogs/asany/complete/root.changelog.xml, liquibase-integration-tests/src/test/resources/changelogs/cache/complete/root.changelog.xml, liquibase-integration-tests/src/test/resources/changelogs/common/includerelative/pathinclude1.changelog.xml, liquibase-integration-tests/src/test/resources/changelogs/common/pathincluded/pathinclude1.changelog.xml, liquibase-integration-tests/src/test/resources/changelogs/db2/complete/root.changelog.xml, liquibase-integration-tests/src/test/resources/changelogs/derby/complete/root.changelog.xml, liquibase-integration-tests/src/test/resources/changelogs/firebird/complete/root.changelog.xml, liquibase-integration-tests/src/test/resources/changelogs/h2/complete/root.changelog.xml, liquibase-integration-tests/src/test/resources/changelogs/hsqldb/complete/root.changelog.xml, liquibase-integration-tests/src/test/resources/changelogs/informix/complete/root.changelog.xml, liquibase-integration-tests/src/test/resources/changelogs/json/includerelative/pathinclude1.changelog.xml, liquibase-integration-tests/src/test/resources/changelogs/maxdb/complete/root.changelog.xml, liquibase-integration-tests/src/test/resources/changelogs/mssql/complete/root.changelog.xml, liquibase-integration-tests/src/test/resources/changelogs/mysql/complete/root.changelog.xml, liquibase-integration-tests/src/test/resources/changelogs/oracle/complete/root.changelog.xml, liquibase-integration-tests/src/test/resources/changelogs/pgsql/complete/root.changelog.xml, liquibase-integration-tests/src/test/resources/changelogs/sybase/complete/root.changelog.xml, liquibase-integration-tests/src/test/resources/changelogs/yaml/includerelative/pathinclude1.changelog.xml, liquibase-integration-tests/src/test/resources/liquibase/liquibase.integrationtest.properties
This PR contains the changes I needed to make on my system to allow the integration tests to work with my Oracle database.
(1) You can now configure the JDBC URL, username and password separatly for each database.
(2) The functions for testing if a string is an ISO8601-ish date/time/timestamp expression only relied on the length, which caused a bug if a timestamp had less than three fractional digits. 
(3) Modified testing change sets so that the <runningAs> tests do not contain hardcoded usernames anymore.
=> Integration tests: configurable JDBC sources and misc. fixes for Oracle Database

liquibase-core/src/main/java/liquibase/database/core/DB2Database.java
During the dropAll command Liquibase tries to delete DB2 system views. The following views are not deleteable and should be omited:
* SYSCHKCST
* SYSCST
* SYSCSTCOL
* SYSCSTDEP
* SYSKEYCST
* SYSREFCST
=>  CORE-3005 Consideration of DB2 system views

liquibase-core/src/main/java/liquibase/io/EmptyLineAndCommentSkippingInputStream.java, liquibase-core/src/test/groovy/liquibase/io/EmptyLineAndCommentSkippingInputStreamTest.groovy
Line endings are not processed correct in comment strings. 
Wrote test with different line endings for windows/unix while parsing csv.
=> CORE-1852 checksum depends on line endings and startCommentSymbol

liquibase-cdi/src/main/java/liquibase/integration/cdi/CDILiquibaseConfig.java, liquibase-cdi/src/main/java/liquibase/integration/cdi/annotations/LiquibaseType.java, liquibase-cdi/src/test/java/liquibase/integration/cdi/CDITestProducer.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseDropAll.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseMigrate.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseMigrateSQL.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseRollback.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseRollbackSQL.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseTag.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/MavenUtils.java, liquibase-maven-plugin/src/test/java/org/liquibase/maven/plugins/LiquibaseUpdateMojoTest.java
Corrected documentation type-o on line 203 "teh" is now "the".
Corrected the skip documentation default value is false.  Lines 238 & 241
=> Corrected documentation errors in AbstractLiquibaseMojo.java

liquibase-core/src/main/java/liquibase/change/core/CreateIndexChange.java, liquibase-core/src/test/groovy/liquibase/change/core/CreateIndexChangeTest.groovy
Adds a validation error if you provided an empty column name in a CreateIndexChange. Fixes https://liquibase.jira.com/browse/CORE-3014.
=> validation error on empty column name in CreateIndexChange (CORE-3014)

liquibase-core/src/main/java/liquibase/parser/core/yaml/YamlChangeLogParser.java, liquibase-core/src/test/groovy/liquibase/parser/core/yaml/YamlChangeLogParser_RealFile_Test.groovy
Replaces the generic exception message "error in yaml" by "error in file <FILENAME>" so that users using the "includeAll" feature can see in the stacktrace which file could not be parsed. Fixes https://liquibase.jira.com/browse/CORE-3013.
=> add name of invalid yaml file to error message when using "includeAll" (CORE-3013)

liquibase-core/src/main/java/liquibase/ContextExpression.java, liquibase-core/src/main/java/liquibase/changelog/DatabaseChangeLog.java, liquibase-core/src/main/java/liquibase/sqlgenerator/core/MarkChangeSetRanGenerator.java, liquibase-core/src/test/java/liquibase/sqlgenerator/core/MarkChangeSetRanGeneratorTest.java
You can also take a look at: http://stackoverflow.com/questions/43032168/context-attribute-in-include-includeall-is-not-persisted-in-databasechangelog
@mches, @nvoxland, your review will be highly appreciated.
For several reasons, we decided to stick to a formatted SQL format and since it doesn't support 'tag' attribute, we want to at least be able to track every context applied to a changeSet(fine-grained use for different environments including Production).
I know that adding something similar for 'label' is also under consideration, but it is more critical for 'context', I believe, simply because the hierarchy of 'contexts' is more compler and more difficult to trace.
=> Adding logic to persist full hierarchy of context expressions into databasechangelog table

liquibase-core/src/main/java/liquibase/util/StringUtils.java
See https://liquibase.jira.com/browse/CORE-3050.
Fix performance regression introduced by commit https://github.com/liquibase/liquibase/commit/59b5496832e829ba8943fb1da064ad1179a0ec4d.
This commit fixed a bug, but introduced a huge performance regression on big SQL scripts.
=> CORE-3050 Do not build string to check StringBuilder is empty

liquibase-core/src/main/java/liquibase/database/core/SybaseASADatabase.java, liquibase-core/src/main/java/liquibase/database/jvm/SybaseASAConnection.java
java.sql.Connection con.nativeSQL(sql)
cause the dump. A SybaseASAConnection-Delegate eliminates this call
=> CORE-3054 ASANY changeSet sql cause dump

liquibase-core/src/main/java/liquibase/changelog/DatabaseChangeLog.java
DatabaseChangeLog.include used new File(tempFile).exists() to check if
a relative path obtained from FilenameUtils.concat is valid. When
accessing a resource in a jar file, that check fails although the path
looked perfectly okay. The workaround path handling however constructs
a path by simply concatenating relativePath to basePath. Relative
paths like ../rel/ChangeLog.xml were not handled correctly.
=> CORE-3059 Fix path handling for ClassLoaderResourceAccessor

liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java, liquibase-integration-tests/src/test/java/liquibase/dbtest/mssql/AbstractMssqlIntegrationTest.java, liquibase-integration-tests/src/test/java/liquibase/dbtest/mssql/MssqlIntegrationTest.java, liquibase-integration-tests/src/test/java/liquibase/dbtest/oracle/OracleIntegrationTest.java, liquibase-integration-tests/src/test/java/liquibase/test/DatabaseTestContext.java
This is a minor change that causes any Integration Tests which are skipped because there is not a reachable database of that type to be marked as Ignored by JUnit instead of marked as Passed.
I think this is clearer and more correct.
This arose from https://liquibase.jira.com/browse/CORE-3063
=> CORE-3063 integration tests that cannot connect should be Ignored not Passed

liquibase-core/src/main/java/liquibase/precondition/core/PreconditionContainer.java, liquibase-core/src/main/java/liquibase/serializer/core/yaml/YamlSerializer.java, liquibase-core/src/test/java/liquibase/serializer/core/json/JsonChangeLogSerializerTest.java
This pullrequest resolve json serialize error, when changeset contains precondition flags: _onError_, _onFail_ or _onSqlOutput_. 
I'll give you an example. Changeset had _onError_ flag **HALT**. In that case, the property was serialized to:
`"onError": !!liquibase.precondition.core.PreconditionContainer$ErrorOption "HALT"`, what is compatible with yaml, but not json.
It is a minor change, none refactoring. I only extended used regexp and made fail-fast.
=> Fix json serialize fail on changeset precondition enums

liquibase-core/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java
At least on our system AS400JDBCDatabaseMetaData.getTables called to get views and view = null return a lot of of entries that are not really views.
For reference we use jtopen 9.3 against a v7r1 IBM i system.
The new code has the added bonus of returning OBJECT_BODY in the same query.
Full error message before this fix:
SEVERE 2017-06-28 15:52: liquibase: liquibase.exception.DatabaseException: Error getting jdbc:as400://xx.xx.xx.xx/schema view with liquibase.statement.core.GetViewDefinitionStatement@3cef309d
liquibase.exception.LiquibaseException: liquibase.command.CommandExecutionException: liquibase.exception.DatabaseException: Error getting jdbc:as400://xx.xx.xx.xx/schema view with liquibase.statement.core.GetViewDefinitionStatement@3cef309d
at …
=> Prevent liquibase.exception.DatabaseException

liquibase-core/src/main/java/liquibase/util/StringUtils.java, liquibase-core/src/main/java/liquibase/util/SystemUtils.java
I just copied StringUtils.substring(str, start, end) from apache commons lang3 to prevent the IndexOutofBoundsException thrown when attempting to parse jdk 9 version
=> Compatibility with java 9 where version can be just "9". 

liquibase-core/src/main/java/liquibase/resource/ClassLoaderResourceAccessor.java
Wheblogic path to the includeall folder starts with zip:, not file/jar. It is taken into account several lines further but not on the main check.
=> fix includeall on WebSphere and Weblogic

liquibase-core/src/main/java/liquibase/parser/core/yaml/YamlChangeLogParser.java, liquibase-core/src/main/java/liquibase/parser/core/yaml/YamlSnapshotParser.java
YAML files can contain custom object definitions, containing method
definitions, which can be executed. This can provide a means of remote
code execution.
By passing a SafeConstructor into SnakeYAML, we limit the objects it
will construct and deny this potential exploit.
Unfortunately this makes yaml.loadAs(stream, Map.class) not work because
Map is not recognised as a valid tag. Instead we can 'load' and cast to
Map. If a ClassCastException is thrown it will be caught by the catch-all
block already in place.
=> Uses SafeConstructor to enhance security

liquibase-core/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java
built-in function original_db_name was introduced in MSSQL 2008
=> CORE-3140: Invalid function original_db_name in MSSQL 2005

liquibase-core/src/main/java/liquibase/resource/FileSystemResourceAccessor.java
TL;DR: Fixes a regression in databaseChangeLog includeAll behavior on Windows after upgrading from Liquibase 3.5.0 to 3.5.3.
Note: I currently can't log in to [liquibase.jira.com](https://liquibase.jira.com) for some reason, so I'm referring to related JIRA issues here: this should fix [CORE-2851](https://liquibase.jira.com/browse/CORE-2851) (and [CORE-2898](https://liquibase.jira.com/browse/CORE-2898)).
=> Fix for file system case sensitivity in FileSystemResourceAccessor.list

liquibase-core/src/main/java/liquibase/resource/ClassLoaderResourceAccessor.java, liquibase-core/src/main/java/liquibase/util/SpringBootFatJar.java, liquibase-core/src/test/java/liquibase/util/SpringBootFatJarTest.java
Why did you make this change?
The includeAll feature doesn't work with spring-boot packaged jar files.
Something chnaged in the path format that liquibase isn't able to
handle. It attempts to load the resources in the given path, but isn't
able to find the files because the path isn't pointing to the correct
place in the jar file.
I created a simple utility class to check for the signature of
the spring boot fat jar, which is that it includes 2 exclamation points,
and modified the path to correctly load the resources in the given path.
Resolves:
https://liquibase.jira.com/browse/CORE-2863
https://liquibase.jira.com/browse/CORE-2948
=> Resolve bug in includeAll with Spring Boot

liquibase-core/src/main/java/liquibase/util/StringUtils.java, liquibase-core/src/test/groovy/liquibase/util/StringUtilsTest.groovy
Delimiter was not detected if there was a white space just before that.
In example following string "statement 1 \nGO\nstatement 2" failed when searching for \nGO delimiter within.
I've made a fix in isDelimiter() method to handle this case and also update unit test to cover it.
=> StringUtils.isDelimiter() bug fix

liquibase-core/src/main/java/liquibase/integration/commandline/Main.java, liquibase-core/src/test/java/liquibase/integration/commandline/MainTest.java
Add support to specify the tablespace name using the commandline.
=> CORE-1225 - add commandline support

liquibase-core/src/main/java/liquibase/sqlgenerator/core/AddAutoIncrementGenerator.java
AddAutoIncrement generate the statement:
ALTER TABLE <table> MODIFY <column> <datatype> DEFAULT AUTOINCREMENT
But if the column is used in an Index, you get the error: "Changes on a column with is in an Index is impossible".
The right syntax has to be:
ALTER TABLE <table> ALTER <column> SET DEFAULT AUTOINCREMENT
[jira CORE-3138](https://liquibase.jira.com/browse/CORE-3138)
=> CORE-3138: correct AddAutoIncrement for SQLAnywhere

liquibase-core/src/main/java/liquibase/integration/commandline/CommandLineUtils.java
Note: As with PR #709 I can't create an issue in GH and I _still_ can't log in to [liquibase.jira.com](https://liquibase.jira.com).
This PR removes "alter user" used for MSSQL databases in [CommandLineUtils.initializeDatabase](https://github.com/gitfool/liquibase/blob/3.5.x/liquibase-core/src/main/java/liquibase/integration/commandline/CommandLineUtils.java#L141) since unlike all other databases this is at the database level and not the session level.
The problem is that it's causing **deadlock** issues when a database schema is being provisioned via Liquibase while data is concurrently being processed in another schema in the same database!
Given the assumption that the user exists, it's reasonable to assume the user already has the default schema; Liquibase should not intervene in this …
=> Fix initializeDatabase for MSSQL

liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java
This resolves an issue where driverPropertiesFile wasn't being consumed and applied correctly.
=> [CORE-3119] setFieldValue correctly if field type = File

liquibase-core/src/main/java/liquibase/datatype/core/TimestampType.java
This is a fix for https://liquibase.jira.com/browse/CORE-3117
=> fix for CORE-3117 : H2 now supports TIMESTAMP WITH TIME ZONE data type

liquibase-core/src/main/java/liquibase/database/core/OracleDatabase.java, liquibase-core/src/test/java/liquibase/database/core/OracleDatabaseTest.java
In case of invalid date literals OracleDatabase.getDateLiteral() throws
an StringIndexOutOfBoundsException. This isn't helpful as the user can't
see the problematic input. With this change a "UNSUPPORTED:xxx" message
is created.
=> CORE-3006: Improve handling of invalid date literals

liquibase-core/src/main/java/liquibase/datatype/core/UUIDType.java
HSQL database has support for UUID since 2.3.4. Since the database implementation does not support `getDatabaseMicroVersion` I added the support for version 2.4.
This should resolve CORE-3094
=> HSQLDatabase UUID support

liquibase-core/src/main/resources/dist/liquibase.bat
Special characters passed in via command prompt are being lost.
This is due to delayedexpansion is enabled.
Solution:
Turn off delayedexpansion when it is no longer required.
How to test: connect to the database using liquibase.bat and pass in the password as an argument.
Password must contain an exclamation mark (!).
=> CORE-1609 Command Prompt: Can't connect to database with a special character in pwd

liquibase-core/src/main/java/liquibase/change/core/LoadDataChange.java, liquibase-core/src/test/groovy/liquibase/change/core/LoadDataChangeTest.groovy, liquibase-core/src/test/groovy/liquibase/change/core/LoadUpdateDataChangeTest.groovy
It should be possible to rollback chnageSet with loadUpdateData tag when using empty CSV file. File have correct column names (first row) but no data rows.
=> Hotfix 3.5.3 rollback loadUpdateData tag using empty csv

liquibase-core/src/main/java/liquibase/sqlgenerator/core/InsertOrUpdateGeneratorSybaseASA.java
SQL Anywhere need the following syntax:
`INSERT INTO <tablename> ON EXISTING UPDATE VALUES (...)`
[Docu](http://dcx.sap.com/index.html#sqla170/de/html/81712f3a6ce21014ada883e2b235cf26.html)
=> CORE-3171: loadUpdateData for SASQL

liquibase-core/src/main/java/liquibase/util/SystemUtils.java
Re-introduces the fix made in #710 **but overseen** in #688 .
=> Fixes Java9 compatibility in SystemUtils::getJavaVersionAsInt

liquibase-core/src/main/java/liquibase/change/core/AddAutoIncrementChange.java, liquibase-core/src/main/java/liquibase/dbdoc/ChangeLogWriter.java, liquibase-core/src/main/java/liquibase/dbdoc/HTMLWriter.java, liquibase-core/src/main/java/liquibase/dbdoc/TableWriter.java, liquibase-core/src/main/java/liquibase/resource/ClassLoaderResourceAccessor.java, liquibase-core/src/main/java/liquibase/resource/FileSystemResourceAccessor.java, liquibase-core/src/main/java/liquibase/sqlgenerator/core/AddDefaultValueGenerator.java
CORE-3163 dbdocs Link text case mismatch
Found a couple broken links in the dbdoc generated documentation.
Made 3 changes to fix the links.
* Changed the names of the changelog html files to be lowercase.
* Changed the href to changelog file in the authors page to be lowercase.
* The html files for columns included the schema name but the link in the table page did not.  Added the schema name to the href for the columns in the table page.
=> 3.5.x - CORE-3163 dbdocs Link text case mismatch

liquibase-core/src/main/java/liquibase/database/DatabaseFactory.java, liquibase-core/src/main/java/liquibase/database/LiquibaseExtDriver.java
Liquibase-Hibernate fails in Maven due to a classloading issue. I've added this small interface change to the main Liquibase project to allow a fix for this issue in Liquibase-Hibernate.
=> Adding hook to support liquibase hibernate extension

liquibase-core/src/main/java/liquibase/change/custom/CustomChangeWrapper.java, liquibase-core/src/main/java/liquibase/precondition/CustomPreconditionWrapper.java
To set the class name in the custom wrapper, you must call 'setClass' or 'setClassName' depending on the custom wrapper class. This pull request normalized this so both custom wrapper can be called with 'setClass' or 'setClassName'.
=> Sets class name in CustomWrapper classes must be normalized.

liquibase-core/src/main/java/liquibase/change/ColumnConfig.java, liquibase-core/src/main/java/liquibase/util/ISODateFormat.java, liquibase-core/src/test/groovy/liquibase/change/ColumnConfigTest.groovy, liquibase-core/src/test/groovy/liquibase/change/core/InsertDataChangeTest.groovy, liquibase-core/src/test/java/liquibase/serializer/core/json/JsonChangeLogSerializerTest.java, liquibase-core/src/test/java/liquibase/util/ISODateFormatTest.java
I want to share my fix for the timestamp handling whenever the change log created via liquibase contains values with fractional seconds less than 3 digits; in this case the current implementation in the corresponding "insert" always add leading zeros (e.g. 2017-01-10 10:34:12.34 -> 2017-01-10 10:34:12.[**0**]34.
My solution is to override the getSerializableFieldValue in the ColumnConfig class, using liquibase's ISODateFormat. ISODateFormat now uses java.util.Date as a fallback in the format method.
As a side effect that changes the output format in the change logs which works well for me, but I am not sure about backwards compatibility. I also had to fix the timezone for the JsonChangeLogSerializerTest.e 
I would kindly ask you to review this PR and let me know whether that this can be …
=> fix for Timestamp/Date handling

liquibase-core/src/main/java/liquibase/datatype/core/BigIntType.java
Fix error: liquibase.exception.DatabaseException: Can't specify a length, scale or storage property on type 'bigint' during table creation with type="BIGINT(19)"
=> CORE-1888: Add BigInt for Sybase (Can't specify a length)

liquibase-core/src/main/java/liquibase/database/core/H2Database.java, liquibase-core/src/main/java/liquibase/sqlgenerator/core/AlterSequenceGenerator.java, liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateSequenceGenerator.java, liquibase-core/src/test/java/liquibase/database/core/H2DatabaseTest.java, liquibase-core/src/test/java/liquibase/sqlgenerator/core/AlterSequenceGeneratorTest.java, liquibase-core/src/test/java/liquibase/sqlgenerator/core/CreateSequenceGeneratorTest.java
- checking for H2 version, accepting minValue and maxValue fro version 1.3.175 beginning
- added unit tests
Integrated and modified both commits from @fm8
see https://github.com/fm8/liquibase/commit/09225d8b35d881f0779d42bb07ccedfda7c4bb7a and https://github.com/fm8/liquibase/commit/a6450883a527f95cb0cc993e0e13c17b0b58d189
=> [CORE-2008] Add support for H2 sequences with minValue and maxValue

liquibase-core/src/main/java/liquibase/database/core/InformixDatabase.java
When using the IBM DB2 Universal JDBC (jcc) driver to connect to an Informix database the "product name" will be something like "IDS/UNIX64" or "IDS/UNIX32". Liquibase fails to recognise these databases as Informix databases. With this fix these "IDS" product names will be recognised as Informix databases.
For further  explanation:
http://forum.liquibase.org/#Topic/49382000001534007
=> Add support for Informix using IBM DB2 Universal JDBC (jcc) driver

liquibase-core/src/main/java/liquibase/integration/spring/SpringLiquibase.java, liquibase-core/src/test/java/liquibase/integration/spring/SpringLiquibaseTest.java
SpringLiquibase has been enhanced with an additional configuration field that allows users to test rollback during updating
=> CORE-2735 test rollback on update added to SpringLiquibase

liquibase-core/pom.xml, liquibase-core/src/main/java/liquibase/util/SpringBootFatJar.java, liquibase-core/src/test/java/liquibase/util/SpringBootFatJarTest.java
Original workaround introduced by PR #698.
Please refer to comment https://github.com/liquibase/liquibase/pull/698/files#r175782032 for details on the issue that this patch addresses.
In addition, this change rolls forward patch version for `core` module. I guess this was missing, since artifact version being built was 3.5.5 but the buildinfo.properties declared 3.5.4.
=> Revisit fix for "includeAll" usage with Spring Boot fat-jar

liquibase-core/src/main/java/liquibase/datatype/DataTypeFactory.java, liquibase-core/src/main/java/liquibase/datatype/DatabaseDataType.java, liquibase-core/src/main/java/liquibase/datatype/LiquibaseDataType.java, liquibase-core/src/main/java/liquibase/datatype/core/BigIntType.java, liquibase-core/src/main/java/liquibase/datatype/core/BlobType.java, liquibase-core/src/main/java/liquibase/datatype/core/BooleanType.java, liquibase-core/src/main/java/liquibase/datatype/core/CharType.java, liquibase-core/src/main/java/liquibase/datatype/core/ClobType.java, liquibase-core/src/main/java/liquibase/datatype/core/CurrencyType.java, liquibase-core/src/main/java/liquibase/datatype/core/DatabaseFunctionType.java, liquibase-core/src/main/java/liquibase/datatype/core/DateTimeType.java, liquibase-core/src/main/java/liquibase/datatype/core/DateType.java, liquibase-core/src/main/java/liquibase/datatype/core/FloatType.java, liquibase-core/src/main/java/liquibase/datatype/core/IntType.java, liquibase-core/src/main/java/liquibase/datatype/core/MediumIntType.java, liquibase-core/src/main/java/liquibase/datatype/core/NVarcharType.java, liquibase-core/src/main/java/liquibase/datatype/core/SmallIntType.java, liquibase-core/src/main/java/liquibase/datatype/core/TimeType.java, liquibase-core/src/main/java/liquibase/datatype/core/TimestampType.java, liquibase-core/src/main/java/liquibase/datatype/core/TinyIntType.java, liquibase-core/src/main/java/liquibase/datatype/core/UnknownType.java
There is a bug related with Turkish dotless i and capital I with dot causing problems with Metabase open source project using liquibase. There are some simular bug reports & fixes related with this problem such as;
[Liquibase JIRA Bug report 1](https://liquibase.jira.com/browse/CORE-2772)
[Metabase Forum](https://discourse.metabase.com/t/metabase-centos-install-error-please-help-turkish-locale/2943)
I tried to fix by making case changes according to en-US locale for database types and it should be for such SQL language-related strings, I am not aware if there are more in the project. But the case related with database types seems fixed within my Metabase build.
Information about Turkish locale differences:
[Blog article](https://haacked.com/archive/2012/07/05/turkish-i-problem-and-why-you- …
=> Turkish upper/lower case conversion bug fix for database types

liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseGenerateChangeLogMojo.java
If you run "mvn liquibase:generateChangeLog" with properties file including "diffTypes=data" the method bellow in AbstractLiquibaseMojo.java will throw IllegalAccessException because the field is private. The same for other private fields.
private boolean isCurrentFieldValueSpecified(Field f) throws IllegalAccessException {
Object currentValue = f.get(this);
...
=> BugFix: mvn liquibase:generateChangeLog throws IllegalAccessException in AbstractLiquibaseMojo.java

liquibase-core/src/main/java/liquibase/changelog/ChangeSet.java, liquibase-core/src/main/java/liquibase/changelog/DatabaseChangeLog.java, liquibase-core/src/main/java/liquibase/database/DatabaseList.java, liquibase-core/src/test/groovy/liquibase/parser/core/xml/XMLChangeLogSAXParser_RealFile_Test.groovy, liquibase-core/src/test/resources/liquibase/parser/core/xml/rollbackWithDbmsChangeLog.xml
A DBMS-specific change set referencing a DBMS-specific rollback can't be parsed on a different DBMS
e.g. MSSQL change-set referencing MSSQL rollback can't be parsed on H2.
```
<databaseChangeLog
xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.5.xsd">
<changeSet id="1" author="mches" dbms="mssql">
<createTable tableName="a">
<column name="b" type="int"/>
</createTable>
</changeSet>
<changeSet id="2" author="mches" dbms="mssql">
<dropTable tableName="a"/>
<rollback changeSetId="1" changeSetAuthor="mches"/>
</changeSet>
</databaseChangeLog>
```
Having Liquibase skip the non-matching change sets avoids the exception …
=> CORE-3180: Skip change sets that don't match on DBMS during change log parsing

liquibase-core/src/main/java/liquibase/parser/core/xml/XMLChangeLogSAXParser.java
Adds a system property `liquibase.prefer.internal.xsd` option to use internal XSD to validate changelog xml
=> [CORE-3198] configuration option to prefer internal XSD usage

liquibase-core/src/main/java/liquibase/datatype/core/ClobType.java, liquibase-core/src/test/java/liquibase/datatype/ClobTypeTest.java
Without these fixes column definitions of text/ntext where not all characters are lowercase end up with duplicate datatypes (e.g. `COL1 varchar (max) TEXT`) or are not recognized at all.
One part of the problem was introduced in #751, but even without the toUpperCase bug from that PR there are problems in the regexes.
=> Fix case sensitivity issues in MSSQL (n)text (n)varchar conversion

liquibase-core/src/main/java/liquibase/datatype/core/TimestampType.java, liquibase-core/src/test/java/liquibase/database/core/OracleDatabaseTest.java
Oracle 11g doesn't support WITHOUT clause in TIMESTAMP data type (https://docs.oracle.com/cd/B19306_01/server.102/b14225/ch4datetime.htm#sthref389).
For this reason replace TIMESTAMP WITHOUT TIME ZONE with TIMESTAMP.
=> CORE-3229 Oracle 11g doesn't support TIMESTAMP WITHOUT TIME ZONE datatype

liquibase-core/src/main/java/liquibase/change/core/LoadDataChange.java
If you normalize only LoadDataConlumnConfig's name; they may not match against tableColumns given a NullPointerException afterwards.
=> Load data is unable to find column configuration when using camel or snake case identifiers

liquibase-core/src/main/java/liquibase/util/SpringBootFatJar.java, liquibase-core/src/test/java/liquibase/util/SpringBootFatJarTest.java
CORE-3192, CORE-2863 related
Fix from https://github.com/liquibase/liquibase/pull/698 doesn't work when running unit-tests with maven. In this case dependency jars have urls like [jar:file:/path_to_module/target/module.jar!/db/changelog/] with only one exclamation point.
Here is the testcase for reproduction: https://github.com/keddok/liquibase-issue
=> Bugfix. Fixed Spring Boot fat jar resource path for unit-testing.

liquibase-core/src/main/java/liquibase/resource/ClassLoaderResourceAccessor.java
returnSet of method ClassLoaderResourceAccessor.list contains not only files but also their directories despite includeDirectories is false. This can lead to minor performance loss.
=> Bugfix. Directories included in resource list even if includeDirectories is false

liquibase-core/src/main/java/liquibase/resource/ClassLoaderResourceAccessor.java, liquibase-core/src/main/java/liquibase/util/SpringBootFatJar.java, liquibase-core/src/test/java/liquibase/util/SpringBootFatJarTest.java
Fixes https://liquibase.jira.com/browse/CORE-3213
Fixes IncludeAll in multi-modues Spring Boot's executable JAR
Remove duplicate URL to improve speed of liquibase
Avoid reuse path variable
=> [CORE-3213] includeAll will not find child changelogs in multi-modues Spring Boot's executable JAR

liquibase-core/src/main/java/liquibase/sqlgenerator/core/DropPrimaryKeyGenerator.java
Properly quote schema name and table name when dropping PostgreSQL primary key constraint;
fixes https://liquibase.jira.com/browse/CORE-3129
=> [CORE-3129] Fix dropping PostgreSQL primary key constraint

liquibase-core/src/main/java/liquibase/resource/ClassLoaderResourceAccessor.java
Merge commit `cbf6d25dd6368f936dcd27f56b9644f4b154ef13` intrudoced regression in `ClassLoaderResourceAccessor`
Usage of variable `path` was replaced by `sanitizePath` in the class in CORE-3213 (`4b451e2508f1ea4a18dbf2607b285dd1f0746dbd`)
=> Fix regression introduced by merge 3.5 to 3.6

liquibase-cdi/src/main/java/liquibase/integration/cdi/CDILiquibase.java, liquibase-cdi/src/main/java/liquibase/integration/cdi/CDILiquibaseConfig.java, liquibase-cdi/src/test/java/liquibase/integration/cdi/CDILiquibaseTest.java, liquibase-cdi/src/test/java/liquibase/integration/cdi/CDITestProducer.java
Currently the only way to disable Liquibase from running in a CDI environment is to set the system property "liquibase.should.run" to false.  It would be more useful for me to be able to provide this via a configuration setting that I can toggle via my producer for CDILiquibaseConfig.  This way I can set appropriate behavior in my application via config files instead of relying on system properties to be set. Passivity is maintained through all of this by still supporting the existing process and by defaulting the new process to enable by default.
=> Add ability to disable running of Liquibase via CDILiquibaseConfig

liquibase-core/src/main/java/liquibase/change/ChangeFactory.java
Class `javafx.scene.layout.Priority` is not presented in OpenJDK 8
=> Fix build on OpenJDK 8

liquibase-core/src/main/java/liquibase/executor/jvm/JdbcExecutor.java, liquibase-core/src/test/java/liquibase/executor/jvm/JdbcExecutorTest.java
SQLException includes an integer errorCode that can be very useful in debugging when something goes wrong.
In general, the more information available when a mistake happens the better.
The particular case that made me create this patch was calling a stored procedure where the message was just `Unhandled user-defined exception condition` (in mysql). But seeing the error code `1051` that can be looked up to mean "Unknown table" let us quickly identify the problem.
=> prints the error code on Exception

liquibase-core/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGenerator.java
in ColumnSnapshotGenerator, it is trying to get "NULLABLE" column metadata which is Integer type, and assign to an int variable. 
When running migration for RedShift, the column metadata "NULLABLE" is null, and when assigning null to int variable it raises NullPointerExeception because can not unbox null value
=> [Fix Bug] fix nullPointerException when migrating RedShift

liquibase-core/src/main/java/liquibase/database/core/OracleDatabase.java, liquibase-core/src/test/java/liquibase/database/core/OracleDatabaseTest.java
Original fix by Tim Gödde (https://github.com/liquibase/liquibase/pull/800); I fixed formatting and added test case.
https://liquibase.jira.com/browse/CORE-3221
=> CORE-3221 fix oracle date literal without millis

liquibase-core/src/main/java/liquibase/integration/spring/SpringLiquibase.java
As per Cabot's comment in the issue, "resource loader generates FilteredReactiveWebContextResource and that implementation returns false for exists()." To fix this issue an additional call for exists() is added before trying to call getURL() for the resource. If the resource does not exist, it does not make sense to try to get its URL.
=> Fixing CORE-3121  Getting a java.io.FileNotFoundException using Liquibase with Spring reactive web

liquibase-core/src/main/java/liquibase/database/core/MSSQLDatabase.java
Source for keyword for reserved ones take from [TSQL documentation](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/reserved-keywords-transact-sql?view=sql-server-2017).
=> CORE-3251 Adding restricted words for MSSQL Server Database

liquibase-core/src/main/java/liquibase/parser/core/yaml/YamlChangeLogParser.java
Parsing a yaml ChangeLog left an open InputStream from the file. If the process parsing the ChangeLog was long-running (such as a Gradle daemon) the file would be locked until the process finished.
=> CORE-3367: Clean up Yaml ChangeLog file InputStream

liquibase-core/src/main/resources/assembly/bin.xml
Signed-off-by: Anders Hammar <anders@hammar.net>
=> CORE-3222: Added missing slf4j-api dependency to assembly tar/zip

liquibase-core/src/main/java/liquibase/integration/commandline/Main.java, liquibase-core/src/test/java/liquibase/integration/commandline/MainTest.java
The verbose option was not recognised as such in the liquibase.integration.commandline.Main class. When recognised all options are expected to have a value but boolean options/flags do not necessarily need this. An option like `--verbose` does not need explicit `--verbose=true`, even the commandline help instructions says `--verbose` without a value is enough. Fixed the value issue here as well so `--verbose` now works as expected but also with `--verbose=true`.
In fact all Boolean flags work with and without `=true` value.
=> Fixes CORE-3256 Verbose flag not getting interperated during 'status' command

liquibase-core/src/main/java/liquibase/servicelocator/ServiceLocator.java
Otherwise DropAllCommand can't be located by ServiceLocator and user is required to specify VM option: -Dliquibase.scan.packages=liquibase.command,liquibase.change,liquibase.changelog,liquibase.database,liquibase.parser,liquibase.precondition,liquibase.datatype,liquibase.serializer,liquibase.sqlgenerator,liquibase.executor,liquibase.snapshot,liquibase.logging,liquibase.diff,liquibase.structure,liquibase.structurecompare,liquibase.lockservice,liquibase.sdk.database,liquibase.ext
=> Add liquibase.command to packages to scan

liquibase-core/src/main/java/liquibase/datatype/core/TimestampType.java
H2 also doesn't support TIMESTAMP WITHOUT TIME ZONE syntax
=> Fix TIMESTAP WITHOUT TIME ZONE issue for H2 database

liquibase-core/src/main/java/liquibase/changelog/ChangeLogIterator.java
Overwrite `toString()` method to return an empty string for the empty anonymous implementation of DatabaseChangeLog.
=> Fix CORE-3231: NPE in LogService.pushContext for MDCs

liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateTableGenerator.java, liquibase-core/src/test/java/liquibase/sqlgenerator/core/CreateTableGeneratorTest.java
Liquibase was ignoring DatabaseFunction value and processing only SequenceNextValueFunction when creating tables and generating column default value.
=> Fixing DatabaseFunction as default value.

liquibase-core/src/main/java/liquibase/sqlgenerator/core/AddForeignKeyConstraintGenerator.java
fix to leave out the onUpdate and onDelete part of foreign keys, when running on Firebird and RESTRICT is used.
=> CORE-3211: Firebird does not support RESTRICT option on Foreign Keys

liquibase-core/src/main/java/liquibase/executor/ExecutorService.java
computeIfAbsent avoids concurrency issues when multiple upgrades run simultaneously
=> Use computeIfAbsent to avoid concurrency issues

liquibase-core/src/main/java/liquibase/changelog/OfflineChangeLogHistoryService.java, liquibase-core/src/test/java/liquibase/changelog/OfflineChangeLogHistoryServiceTest.java
The autoclosable does not close the streams, therefore the file cant be deleted
=> Fix file replace

liquibase-debian/pom.xml, liquibase-rpm/pom.xml
Hello,
When building 3.6.x branch locally, the debian and rpm versions need to be bumped too to 3.6.4-SNAPSHOT so Maven can resolve the parent POMs.
Best regards,
Adam
=> Update versions for debian and rpm

liquibase-core/src/main/java/liquibase/statement/ExecutablePreparedStatementBase.java
When loading data from a CSV file using `<loadData>`, `ISODateFormat` constructs a `java.sql.Time` value when the column format is `HH:mm:ss`.
`PreparedStatement.setTime()` needs to be called for those values for the PostgreSQL JDBC driver to properly understand the parameter.
This is a regression we noticed when upgrading to liquibase 3.6 from 3.5. Liquibase 3.5 did not use prepared statements in that case.
=> Handle java.sql.Time when setting prepared statement parameter values

liquibase-core/src/main/java/liquibase/diff/output/changelog/core/ChangedForeignKeyChangeGenerator.java
When I am generating diff for database that has onDelete = CASCADE, liquibase sees it, but doesn't add to changelog. It just creates drop constraint and add constraint without onDelete statement.
To solve this, I've added
```
addFkChange.setOnDelete(fk.getDeleteRule());
addFkChange.setOnUpdate(fk.getUpdateRule());
```
to `ChangedForeignKeyChangeGenerator#fixChanged`
=> Generate diff with onDelete and onUpdate

liquibase-core/src/main/java/liquibase/executor/jvm/ColumnMapRowMapper.java
[`Liquibase.listUnrunChangeSets` is broken when the user's Locale is Turkish](https://github.com/liquibase/liquibase.github.com/issues/125). (See also related bugfix PR: #751)
If your locale is set to Turkish `String.toUpperCase()` surprisingly will putting dots on things for you. 
e.g. 
```clojure
;; with Locale set to Turkish
(.toUpperCase "filename") ;; -> "FİLENAME"
```
The right solution is to always use `Locale.US` for things like 
```clojure
(.toUpperCase "filename" Locale/US) ;; -> "FILENAME"
```
which are used as keys elsewhere in the codebase. 
Fixes https://github.com/liquibase/liquibase.github.com/issues/125
=> Fix Turkish uppercase column keys bug

liquibase-core/src/main/java/liquibase/database/core/MariaDBDatabase.java, liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateSequenceGenerator.java
Starting with [version 10.3](https://mariadb.com/kb/en/library/changes-improvements-in-mariadb-103/) MariaDB supports sequences. This PR introduce support through liquibase creating Sequences and default value for MariaDB. For example, following changelogs are supported through this PR:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<databaseChangeLog
xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.1.xsd">
<changeSet id="1" author="bob">
<comment>A sample change log</comment>
<createSequence cycle="true"
incrementBy="2"
maxValue="1000"
minValue="5"
ordered="true"
sequenceName="seq_id"
startValue="5"/> …
```
=> Implement Initial Sequence Support for MariaDB

liquibase-core/src/main/java/liquibase/datatype/core/IntType.java, liquibase-core/src/main/java/liquibase/datatype/core/MediumIntType.java
https://docs.oracle.com/cd/E12151_01/doc.150/e12155/oracle_mysql_compared.htm#i1027526 on section 2.3.3.1, mediumint would be suggested as NUMBER(7,0) and mediumint does not exists in Oracle.  INT gets tricky, as liquibase translate it as INTEGER.  Oracle treats INTEGER as NUMBER(38,0) which is like a BIGINT or the maximum size support.  Following the same documentation, it's probably best to be used as NUMBER(10,0).
#3292
=> Added support for Oracle datatype.  If you could refer to

liquibase-core/src/main/java/liquibase/change/core/CreateProcedureChange.java
the error text "Cannot specify either 'path' or a nested procedure text in createProcedure, " should indicate the fix is to create one of them - the error is actually that both are missing.
=> fix confusing error message

liquibase-core/src/main/java/liquibase/integration/spring/MultiTenantSpringLiquibase.java, liquibase-core/src/main/java/liquibase/integration/spring/SpringLiquibase.java
If the database is restored from a dump on another system, if the spring-boot-liquibase tries to run migration it fails as the md5 check sum validation fails on startup. With liquibase-maven-plugin, clearCheckSums command line option is available but it is not possible to do the same with spring boot liquibase integration.
Adds `clearCheckSums` property, which if set to true will call `liquibase.clearCheckSums` method before performing the update.
=> Adds clearCheckSums property in spring integration

liquibase-core/src/main/java/liquibase/integration/commandline/CommandLineOutputAppender.java, liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
1. Changed Main to check the root logger name before attempting to cast to the Logback implementation.
2. Moved all the Logback implementation specific classes into the CommandLineOutputAppender.
I don't think using the logging framework for program output is the best choice but at this point not easily changed. For now, this should at least allow the Main to be used by the gradle-liquibase plugin.
I looked at making a CommandLineLog4jOutputAppender but log4j2 is not really set up for extension. I think if someone was going to attempt this programmatically, they'd want to use the exsiting log4j2 classes and just configure the layout and filters. The log4j-slf4j-impl bridge also complicates matters because you can't publically get to the real log4j2 Logger as was done with Logback.
=> Core 3159 log binding classcast

liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java
Doing a diff with the liquibase maven plugin fails when both Envers and Java 9+ are involved, with the exact error that is described here : https://hibernate.atlassian.net/browse/HHH-12893
This is simply a fix that reproduces [what's been done here](https://github.com/highsource/maven-jaxb2-plugin/commit/7ecb8d8704cce8ff1db8d1309d005c1be1544533) but with the right packageInfoClassName as [described in a comment in the hibernate issue mentioned before](https://hibernate.atlassian.net/browse/HHH-12893?focusedCommentId=103539&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-103539)
Let me know if I you want me to reproduce it on master
=> Fixed an UnmarshalException when doing a diff with Envers on Java 9+

pom.xml
ant versions [1.5.0,1.8.1) have a dependency on Apache Commons Compress before 1.4.1 which has a vulnerability, CVE-2012-2098
https://app.snyk.io/vuln/SNYK-JAVA-ORGAPACHEANT-30510
=> Upgrade org.apache.ant:ant to 1.10.6

liquibase-core/src/main/java/liquibase/integration/spring/SpringLiquibase.java
SpringResourceOpener#list method ignores recursive parameter, whist double asterisk is required for recursive search due to the nature of ant path matchers.
=> Recursive resources lookup does not work in springboot environment

liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
I've found that after upgrade from Liquibase 3.5.5 to 3.6.3 - there is no message when databased _liquibase tag <someTag>_ executes and also there is no message when try to execute _liquibase tagExists <someTag>_
e.g. for liquibase 3.5.5 
`java -cp ./:/somedir/postgresql-42.2.5.jar:/somedir/liquibase-core-3.5.5.jar liquibase.integration.commandline.Main  --changeLogFile=liquibase/master.xml --url jdbc:postgresql://192.168.1.1:5432/postgres --username postgres --password password tagExists test`
The **tag** test does not exist in postgres@jdbc:postgresql://192.168.1.1:5432/postgres
Liquibase 'tagExists' Successful
for liquibase 3.6.3
`java -cp ./:/somedir/postgresql-42.2.5.jar:/somedir/liquibase-core-3.6.3.jar:/somedir/logback-core-1.2.3.jar:/somedir/slf4j-api-1.7.26.jar:/somedir/logback-cl …
=> Print message for liquibase tag and tagExists command to system.out

liquibase-core/src/main/java/liquibase/resource/CompositeResourceAccessor.java, liquibase-core/src/main/java/liquibase/resource/FileSystemResourceAccessor.java, liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java
This fixes a few bugs that were causing `MySQLIntegrationTest` to fail, I think caused by recent work to `ResourceAccessor`.
See my comments on https://liquibase.jira.com/browse/CORE-3063 -- what is the current plan for the integration tests?
There is still one failing test: [testAbsolutePathChangeLog](https://github.com/liquibase/liquibase/blob/658e17bb5b415cf975e63277ddc84bc8e6ed6cb2/liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java#L882) which checks that Liquibase will accept an absolute file path to a changelog. After recent changes to `ResourceAccessor`, this now fails as `new FileSystemResourceAccessor().openStream(x)` will not resolve an absolute filename `x`.
=> Core 3063 resourceaccessor fixes

.gitignore, liquibase-core/src/main/java/liquibase/diff/output/changelog/core/MissingDataExternalFileChangeGenerator.java, liquibase-debian/pom.xml, liquibase-rpm/pom.xml
`generateChangeLog` was generating empty `csv` files for all tables and also inserts for columns that are empty in the whole table.
This was bad because when the table has no data, no `type` is set on the `column` on the resulting file.
Later on, when you try to load this file it triggered a unnecessary search for the column type for each load, which was taking ~20s each.
=> generateChangeLog loadData skipping empty tables and columns

liquibase-core/src/main/java/liquibase/util/LiquibaseUtil.java
I faced with NPE while used liqubase API in my own app
`java.lang.NullPointerException
at liquibase.util.LiquibaseUtil.getBuildInfo(LiquibaseUtil.java:45)
at liquibase.util.LiquibaseUtil.getBuildVersion(LiquibaseUtil.java:17)
at liquibase.sqlgenerator.core.MarkChangeSetRanGenerator.generateSql(MarkChangeSetRanGenerator.java:91)
at liquibase.sqlgenerator.core.MarkChangeSetRanGenerator.generateSql(MarkChangeSetRanGenerator.java:25)
at liquibase.sqlgenerator.SqlGeneratorChain.generateSql(SqlGeneratorChain.java:30)
at liquibase.sqlgenerator.SqlGeneratorFactory.generateSql(SqlGeneratorFactory.java:222)
at liquibase.executor.AbstractExecutor.applyVisitors(AbstractExecutor.java:25)
at liquibase.executor.jvm.JdbcExecutor.access$600(JdbcExecutor.java:40)
at …
=> Build info value assignment fix

liquibase-core/src/test/java/liquibase/sqlgenerator/core/AddColumnGeneratorTest.java, liquibase-core/src/test/java/liquibase/sqlgenerator/core/DropColumnGeneratorTest.java
Test `liquibase.sqlgenerator.core.DropColumnGeneratorTest#testDropMultipleColumnsMySQL` has this following test assertion 
```
Assert.assertEquals("[TEST_TABLE.col1, TEST_TABLE.col2, TEST_TABLE, DEFAULT]", String.valueOf(sql[0].getAffectedDatabaseObjects()))
``` 
that asserts the `toString()` value of `affectedDatabaseObjects`. 
`affectedDatabaseObjects` is a HashSet and the `toString()` function depends on the iteration order of the hash set. However, `HashSet` does not guarantee any specific order of entries. Therefore, the assertion will fail if the order is different.
This PR proposes to use a LinkedHashSet for a deterministic order (insertion order of elements) and modifies the corresponding test assertions. 
Please let me know if you want to discuss the changes more.
=> changing HashMap to LinkedHashMap for deterministic iterations

liquibase-core/src/main/java/liquibase/change/ColumnConfig.java, liquibase-core/src/main/java/liquibase/serializer/core/xml/XMLChangeLogSerializer.java, liquibase-core/src/test/java/liquibase/serializer/core/xml/XMLChangeLogSerializerTest.java
* fix: duplicate line for `notNullConstraintName` in **ColumnConfig.java**
* fix: `referencedColumnNames` instead of `referencedTableName` in **XMLChangeLogSerializer.java**
* fix: add `notNullConstraintName`,  `referencedTableCatalogName` & `referencedTableSchemaName` in **XMLChangeLogSerializer.java**
* fix: duplicate assertion in `createNode_AddUniqueConstraintChange `test in **XMLChangeLogSerializerTest.java**
=> Some small fixes about ConstraintsConfig

liquibase-core/src/main/java/liquibase/change/ColumnConfig.java, liquibase-core/src/main/java/liquibase/diff/DiffResult.java, liquibase-core/src/main/java/liquibase/diff/compare/core/ColumnComparator.java, liquibase-core/src/main/java/liquibase/diff/output/changelog/core/UnexpectedColumnChangeGenerator.java, liquibase-core/src/main/java/liquibase/serializer/core/yaml/YamlSnapshotSerializer.java, liquibase-core/src/main/java/liquibase/snapshot/DatabaseSnapshot.java, liquibase-core/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGenerator.java, liquibase-core/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGeneratorH2.java, liquibase-core/src/main/java/liquibase/structure/core/Column.java
Generating a changelog for a descending index does not include the "descending=true" attribute
DAT-3773
=> Generated indexes are not including "desc"

liquibase-core/src/main/java/liquibase/Liquibase.java
Hi,
I am working on the Liquibase extension for the [QuarkusIO](https://quarkus.io/) framework. 
Liquibase extension PR: https://github.com/quarkusio/quarkus/pull/6334
For better integration and handling of the database connection it would be much better if the liquibase.Liquibase implements AutoClosable interface.
```
public class Liquibase implements AutoCloseable {
@Override
public void close() throws Exception {
if (database != null) {
database.close();
}
}
}
```
Would it suit you?
Regards,
Andrej
=> Make Liquibase AutoCloseable

liquibase-core/src/main/java/liquibase/configuration/GlobalConfiguration.java, liquibase-core/src/main/java/liquibase/integration/commandline/Main.java, liquibase-core/src/main/java/liquibase/structure/core/Data.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseGenerateChangeLogMojo.java
THIS IS A “DUPLICATE” ticket that was automatically created when Wes created the PR to fix DAT-4129, which has been moved to LB-185.
Please allow this to move along as a zero point ticket that tracks LB-185
As a user who wants to export ALL the data from my db when i run generatechangelog, i want to use the
--dataOutputDirectory=<mydatadir> flag and by default have all the data in csv files in a named directory.
Previously, if no --diffTypes argument is specified, the output directory was not created.  Now, the output directory is
always created if the --dataOutputDirectory is specified.
=> Enable snapshotByDefault for Data if output directory specified DAT-4129

liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
##Overall: 
`--schemas` will only work for snapshot when to the right of the command, but for other liquibase commands, like `generatechangelog`, it works and is documented as working to the left (in the "global commands" space). we need to make sure --schemas works to the standard usage (to the left of the command).
A Liquibase client was having issue running a diff between a snapshot and multiple schemas.
The user workflow was as follows:
1. Snapshot the target database with multiple schemas using the flags: "--schema=<schema1,schema2,schema3>"
2. The user conducts a few changes to the target database.
3. The user then runs a diffChangeLog between the snapshot and the target database.
Unfortunately the resulting diffChangeLog did not carry all the changes that were made in all of the …
=> Support --schemas flag both before and after the "snapshot" command

liquibase-core/src/main/java/liquibase/Liquibase.java
There is no need to force callers to handle Exception.
The implementation of the close method can currently throw only a DatabaseException. But since the library has a parent exception class - LiquibaseException - it is used instead to not force callers to change their catch clauses if additional logic is added in the future.
=> Change Liquibase#close to throw LiquibaseException

liquibase-core/src/main/java/liquibase/util/DependencyUtil.java
This PR aims to fix https://liquibase.jira.com/browse/CORE-3596
The fix is to change HashMap to LinkedHashMap so that the iteration order remains stable and the assertion failure in `liquibase.util.DependencyUtilTest#testIndependentBranchesCase` will not occur any more. In this way, the test will be more stable.
=> CORE-3596  Use LinkedHashMap for a deterministic iteration order in DependencyUtil.java

liquibase-core/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.0.xsd
Change namespace for changeAttributes type to be namespace="##other" which will cause validation of attributes
┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-175) by [Unito](https://www.unito.io/learn-more)
┆Fix Versions: Liquibase 4.0 beta 2
=> Change namespace for changeAttributes type to be namespace="##other"

liquibase-core/src/main/java/liquibase/sqlgenerator/core/SetNullableGenerator.java, liquibase-core/src/test/java/liquibase/verify/saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets/addLookupTable/firebird.sql, liquibase-core/src/test/java/liquibase/verify/saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets/addNotNullConstraint/firebird.sql, liquibase-core/src/test/java/liquibase/verify/saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets/dropNotNullConstraint/firebird.sql, liquibase-integration-tests/src/test/resources/changelogs/common/common.tests.changelog.xml, liquibase-integration-tests/src/test/resources/changelogs/firebird/complete/root.changelog.xml, liquibase-integration-tests/src/test/resources/changelogs/firebird/rollback/rollbackable.changelog.xml
**Branch: Liquibase/master**
Content copied from issue #1066 
**Description**
The change addNotNullConstraint and dropNotNullConstraint are not available for Firebird databases.
**To Reproduce**
Add the commands to a change set and run it against a Firebird database. As a result there will be the following error messages:
addNotNullConstraint is not supported on firebird
dropNotNullConstraint is not supported on firebird
**Expected behavior**
The commands should be available for Firebird databases as well.
closes #1066
┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-178) by [Unito](https://www.unito.io/learn-more)
┆Fix Versions: Liquibase 4.0 beta 2
=> #1066 addNotNullConstraint / dropNotNullConstraint not supported on Firebird

liquibase-core/src/main/java/liquibase/database/core/PostgresDatabase.java, liquibase-core/src/test/java/liquibase/sqlgenerator/core/CreateTableGeneratorTest.java
When using Liquibase to create a table with an auto-incrementing integer, the corresponding identity column in PostgreSQL is always created with the constraint `BY DEFAULT`, irrespective of the value set for the generation type.
Add support to Liquibase for the `ALWAYS` generation type when creating an auto-incrementing column in PostgreSQL. This will allow the generation type to be set to `BY DEFAULT` or `ALWAYS`. The default value if the `generationType` attribute is not specified in the column tag, remains `BY DEFAULT`.
┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-39) by [Unito](https://www.unito.io/learn-more)
=> [CORE-3520] Add support for ALWAYS generation type with PostgreSQL auto-increment column.

liquibase-core/src/main/java/liquibase/change/core/AddColumnChange.java, liquibase-core/src/test/java/liquibase/change/AddColumnChangeTest.java
┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-29) by [Unito](https://www.unito.io/learn-more)
=> CORE-3558 Unique constraint name is ignored when using the addColumn change

liquibase-maven-plugin/pom.xml
Without explicit jaxb dependency the maven plugin cannot be built with java 1.9+
┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-26) by [Unito](https://www.unito.io/learn-more)
=> Fix: Java 1.9+ versions require jaxb as separate dependency

liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
Global help should be displayed if no command.
closes #1070
┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-168) by [Unito](https://www.unito.io/learn-more)
=> Global help should be displayed if no command.

liquibase-core/src/main/java/liquibase/change/custom/CustomChangeWrapper.java, liquibase-core/src/main/java/liquibase/precondition/CustomPreconditionWrapper.java, liquibase-core/src/main/java/liquibase/serializer/core/xml/XMLChangeLogSerializer.java, liquibase-core/src/test/java/liquibase/serializer/core/xml/XMLChangeLogSerializerTest.java
Found while working on [CORE-3549][]...
Given test:
```java
import liquibase.change.custom.CustomChangeWrapper;
import liquibase.precondition.CustomPreconditionWrapper;
import liquibase.serializer.core.xml.XMLChangeLogSerializer;
CustomPreconditionWrapper customPrecondition = new CustomPreconditionWrapper();
customPrecondition.setClassName("liquibase.precondition.ExampleCustomPrecondition");
customPrecondition.setParam("name", "test_1");
customPrecondition.setParam("count", "31");
CustomChangeWrapper customChange = new CustomChangeWrapper();
customChange.setClassLoader(Thread.currentThread().getContextClassLoader());
customChange.setClass("liquibase.change.custom.ExampleCustomSqlChange");
customChange.setParam("tableName", "tab_name");
customChange.setParam("columnName", "col_name"); …
```
=> XMLSerializer: Correct Map value serialization

liquibase-core/src/main/java/liquibase/change/AbstractChange.java, liquibase-core/src/main/java/liquibase/change/ChangeParameterMetaData.java
This is currently taking most of the Liquibase initialization time on my side, which is rather slow especially when included during the startup of an application.  I've identified the following time-gobbling areas:
-   Every `Change` type is loaded and initialized (can't change much about it currently), including very slow meta-data initialization;
-   Most time-consuming `analyzeSupportedDatabases()` and `analyzeRequiredDatabases()` during the construction of `ChangeParameterMetaData` – these can be lazily evaluated, which also avoids evaluating them for any `Change` types which don't end up used;
-   Multiple unnecessary bean introspections for the same type – lesser performance impact, still unnecessary adds up:
-   `AbstractChange.createChangeMetaData()` obtains full property info, …
=> Improve ChangeFactory initialization time

base.pom.xml, liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateSequenceGenerator.java, liquibase-core/src/test/java/liquibase/sqlgenerator/core/CreateSequenceGeneratorTest.java
**Liquibase Version**: 3.8.9
**Liquibase Integration & Version**: CLI, maven
**Database Vendor & Version**: PostgreSQL 9.4
**Operating System Type & Version**: Windows 10
This fix the issue #1039 New liquibase version introduce a IF NOT EXIST in the sequence statement that is not supported for db version <= 9.4 as documented [here](https://www.postgresql.org/docs/9.5/sql-createsequence.html)
This was tested against my local db and newer version using docker image of postgresql 10.16 and 12
┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-207) by [Unito](https://www.unito.io/learn-more)
=> Fix 1039 sequence statement generation for PostgreSQL <= 9.4

liquibase-core/pom.xml, liquibase-core/src/main/java/liquibase/database/core/DerbyDatabase.java, liquibase-core/src/main/java/liquibase/integration/servlet/LiquibaseServletListener.java, liquibase-core/src/test/java/liquibase/database/core/DerbyDatabaseTest.java, liquibase-core/src/test/java/liquibase/integration/servlet/LiquibaseServletListenerTest.java, liquibase-core/src/test/java/liquibase/integration/servlet/TestInitialContextFactory.java, liquibase-core/src/test/resources/liquibase/integration/servlet/simple-changelog.xml
---
title: 'LiquibaseServletListener.contextInitialized() should not shut Embedded Derby down'
assignees: ''
---
**Liquibase Version**: 3.8.x
**Liquibase Integration & Version**: servlet
**Database Vendor & Version**: Apache Derby 10.14
In certain configurations using `LiquibaseServletListener` with Embedded Derby application may fail with `java.sql.SQLNonTransientConnectionException: No current connection.`.
Full details of *Steps To Reproduce*, *Actual Behavior*, *Expected/Desired Behavior* and *Additional Context* have been given to [CORE-3540][].  This is my suggestion of how it could be addressed.
[CORE-3540]: …
=> LiquibaseServletListener.contextInitialized() should not shut Embedded Derby down

liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateTableGenerator.java, liquibase-core/src/test/java/liquibase/sqlgenerator/core/CreateTableGeneratorTest.java
This is the same as #1058 but now for the 3.8.x branch.
Hi! SQLite does not allow adding unique constraints after table creation. So the addUniqueConstraint clause can not be used. The createTable syntax only allows single-column unique constraints even if these have the same name: see #1056 .
My proposed solution here is to combine all the columns for uniqueConstraints that have the same name. These should be the same constraint. I do not think there is a use case for defining single-column unique constraints with the exact same constraint name. I have added a test as well.
I am not a Java programmer (experience in Scala and Python) so I apologize for the clunky Java. There is probably some syntactic sugar that can be used to make the code less verbose and more readable.
Also, wow! Such …
=> Add code to allow for multiple column unique constraints on table creation.

liquibase-core/src/main/java/liquibase/change/core/LoadDataChange.java, liquibase-core/src/main/java/liquibase/statement/ExecutablePreparedStatementBase.java, liquibase-core/src/test/java/liquibase/statement/ExecutablePreparedStatementBaseTest.java
I urgently needed support for NULL date values in loadData for MSSQL. I didn't experience problems with NULL values for other data types.
* Do a code walk-through with internal Developer.
┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-24) by [Unito](https://www.unito.io/learn-more)
=> NULL date value in prepared statement requires type in MSSQL

liquibase-core/src/main/java/liquibase/snapshot/jvm/ViewSnapshotGenerator.java
After upgrading to Java 11 and comparing SqlServer with Oracle DB (ojdbc8 12.2.0.1) we discovered invalid 'carriage return' %#13; at the line ending of the SQL definition of oracle views.
This change makes sure that the lineendings are standardized.
┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-22) by [Unito](https://www.unito.io/learn-more)
┆Fix Versions: Liquibase 3.10.2
=> fixed invalid carriage return coming from oracle ojdbc8 12.2.0.1

liquibase-core/src/main/java/liquibase/change/core/LoadDataChange.java, liquibase-core/src/main/java/liquibase/diff/output/changelog/core/MissingDataExternalFileChangeGenerator.java, liquibase-core/src/main/java/liquibase/statement/ExecutablePreparedStatementBase.java
I had a problem when using the generateChangelog, and then re-importing that file into an Oracle database. I found that this problem had already been reported in [CORE-2650](https://liquibase.jira.com/browse/CORE-2650), and I have found/implemented a (in my opinion) simple/straightforward way of processing BLOB data.
The BLOB file option seems interesting, and I have tried to leave it untouched the best I can, but I do think that in the future, it would be best so simply serialize the data into Base64 and include it in the file itself (making the "export"/snapshot a bit more portable).
_I would really appreciate some feedback on this (and some other) PRs I've sent. I'm happy to do integration work or fix my changes to comply with your coding standards, etc. The tests were already failing …
=> CORE-2650 Use Base64-encoding to safely store BLOB data in CSV files

liquibase-core/src/main/java/liquibase/sqlgenerator/core/ClearDatabaseChangeLogTableGenerator.java, liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateDatabaseChangeLogLockTableGenerator.java, liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateDatabaseChangeLogTableGenerator.java, liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateDatabaseChangeLogTableGeneratorSybase.java, liquibase-core/src/main/java/liquibase/sqlgenerator/core/InitializeDatabaseChangeLogLockTableGenerator.java, liquibase-core/src/main/java/liquibase/sqlgenerator/core/LockDatabaseChangeLogGenerator.java, liquibase-core/src/main/java/liquibase/sqlgenerator/core/MarkChangeSetRanGenerator.java, liquibase-core/src/main/java/liquibase/sqlgenerator/core/RemoveChangeSetRanStatusGenerator.java, liquibase-core/src/main/java/liquibase/sqlgenerator/core/SelectFromDatabaseChangeLogGenerator.java, liquibase-core/src/main/java/liquibase/sqlgenerator/core/SelectFromDatabaseChangeLogLockGenerator.java, liquibase-core/src/main/java/liquibase/sqlgenerator/core/TagDatabaseGenerator.java, liquibase-core/src/main/java/liquibase/sqlgenerator/core/UnlockDatabaseChangeLogGenerator.java, liquibase-core/src/main/java/liquibase/sqlgenerator/core/UpdateChangeSetChecksumGenerator.java
When liquibase starts the very first time, the `databasechangelog` and `databasechangeloglock` are created using the default configuration which enforces object quoting strategy to LEGACY (this is not configurable)
However, when running a changelog that enforces a different quoting strategy (for instance `ALL`) this strategy overrides the default, and future interactions with the liquibase changelog tables will use the new strategy, thus resulting in errors like:
```java
Unexpected error running Liquibase: Error executing SQL SELECT MAX("ORDEREXECUTED") FROM "myschema"."databasechangelog": ERROR: column "ORDEREXECUTED" does not exist
Position: 12
liquibase.exception.UnexpectedLiquibaseException: liquibase.exception.DatabaseException: Error executing SQL SELECT MAX("ORDEREXECUTED") FROM …
```
=> Changes databasechangelog sql to use legacy mode

liquibase-core/src/main/java/liquibase/datatype/core/TimestampType.java, liquibase-core/src/test/groovy/liquibase/datatype/DataTypeFactoryTest.groovy
Liquibase does not currently support the `java.sql.Types.TIMESTAMP_WITH_TIMEZONE` type. For example, using `java.sql.Types.TIMESTAMP_WITH_TIMEZONE` as the column type in Liquibase generates a column with the `TIMESTAMP WITHOUT TIME ZONE` type in PostgreSQL.
Add support for the `java.sql.Types.TIMESTAMP_WITH_TIMEZONE` type to Liquibase so the correct SQL is generated for databases supporting timestamps with timezones.
1. Create a createTable changeSet with a column having `type="java.sql.Types.TIMESTAMP_WITH_TIMEZONE"` 
1. Run changeSet against postgresql or another database that supports timestamp with timezone types
1. Check that the table column was created as timestamp with timezone information
* Execute the steps as described in repro and assert the correct dataype is created on the …
=> [CORE-3525] Add support for java.sql.Types.TIMESTAMP_WITH_TIMEZONE.

liquibase-core/src/main/java/liquibase/database/core/MariaDBDatabase.java, liquibase-core/src/main/java/liquibase/snapshot/jvm/SequenceSnapshotGenerator.java
This is basically a port of [PR 1024](https://github.com/liquibase/liquibase/pull/1024), but for the 3.10.x branch.  Since MariaDB is effectively broken for MariaDB 10.3 and up, I don't think this should wait for 4.0.
I did use slightly different SQL than the original PR to account for permission problems in the innodb tables.
- - -
name: Add MariaDB 10.3 sequence suport
about: This fix will allow MariaDB users on 10.3 and up to use Liquibase.
title: ''
assignees: ''
- - -
**Liquibase Version**: 3.10.x
**Liquibase Integration & Version**: 
**Database Vendor & Version**: MariaDB 10.3 and up
MariaDB added support for sequences, Liquibase knows about the support …
=> Add MariaDB sequence support to the 3.10.x branch

liquibase-core/src/main/java/liquibase/hub/listener/HubChangeExecListener.java
…DAT-5428
- - -
title: ''
assignees: ''
- - -
* Files used - sql scripts, …
=> Do not send generated SQL or changeset body to Hub for changeLogSync DAT-5428

liquibase-core/src/main/java/liquibase/datatype/core/ClobType.java, liquibase-core/src/test/groovy/liquibase/datatype/core/ClobTypeTest.groovy
Java 8
3.6.3
**Liquibase Integration & Version**: 
Gradle
**Liquibase Extension(s) & Version**:
N/A
MsSql 2017
Ubuntu 16.04.3 LTS
When creating a table with column: 
```xml
<column name="REPRESENTATION" type="TEXT(25500)"/>
```
Liquibase converts `TEXT` to `varchar (max) (25500)`
Use Liquibase with the following change log:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.1.xsd">
<changeSet author="bburke@redhat.com" id="1.3.0">
<createTable …
```
=> Fix varchar(max) extrainfo in 3.10 branch

liquibase-core/src/main/java/liquibase/integration/spring/SpringLiquibase.java
`SpringLiquibase` `createResourceOpener()` now returns a `ResourceAccessor`, which allows it to be overridden with any kind of `ResourceAccessor`.
The reason for this change is that I would like `SpringLiquibase` to be able use the regular `ClassLoaderResourceAccessor`. Since it appears that `SpringLiquibase` handles classpath resources differently, which makes it incompatible with other methods of running liquibase (i.e. command line or maven-plugin).
This change itself does not change the behaviour of SpringLiquibase at all, it only allows classes overriding it to use a different `ResourceAccessor`
Notes:
It should be possible to merge this change to master too, however it appears that changes have already been made, such that the `SpringResourceAccessor` no longer overrides any methods …
=> SpringLiquibase ResourceAccessor is now overridable

liquibase-core/src/main/java/liquibase/snapshot/jvm/SequenceSnapshotGenerator.java
This is a copy of the change in PR https://github.com/liquibase/liquibase/pull/1001 for the 3.10.x branch
To retrieve sequence information from the database, Liquibase issues a SQL query and then retrieves the result expecting uppercase field names.
However, PostgreSQL converts all column names to lowercase, so the sequence information retrieval fails and the output of the diff command is something like this on a PostgreSQL:
Changed Sequence(s):
catalog_item_history_sequence
cacheSize changed from 'null' to '1'
dataType changed from 'null' to 'bigint'
maxValue changed from 'null' to '9223372036854775807'
minValue changed from 'null' to '1'
willCycle changed from 'null' to 'false'
This in turn results in CORE-2495, because the changelog being created contains no actual changes and is …
=> Fix for PR 1001 in 3.10.x branch

liquibase-core/src/main/java/liquibase/integration/spring/SpringLiquibase.java
- - -
name: Fix root paths for spring boot fat jar
about: replace using getResource("")
title: 'Fix root paths for spring boot fat jar'
assignees: ''
- - -
**Liquibase Version**: 3.8.9
**Liquibase Integration & Version**: spring boot
**Liquibase Extension(s) & Version**: -
**Database Vendor & Version**: -
**Operating System Type & Version**: -
The includeAll feature doesn't work with spring-boot packaged jar files.
Running getResources("") is probably supposed to return the root folders of all jars. However it's lacking some of them. I guess using this method with an empty string (addressing the Spring Boot ResourcePatternResolver) isn't really supported.
This issue appears on windows OS as well as in a linux container performing the build.
The issue came up …
=> Fix root paths for Spring Boot fat jar

liquibase-core/src/main/java/liquibase/datatype/core/BigIntType.java, liquibase-core/src/main/java/liquibase/datatype/core/IntType.java, liquibase-core/src/main/java/liquibase/datatype/core/MediumIntType.java, liquibase-core/src/main/java/liquibase/datatype/core/SmallIntType.java, liquibase-core/src/main/java/liquibase/datatype/core/TinyIntType.java, liquibase-core/src/test/groovy/liquibase/datatype/DataTypeFactoryTest.groovy, liquibase-core/src/test/java/liquibase/verify/saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets/addColumn/oracle.sql, liquibase-core/src/test/java/liquibase/verify/saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets/createTable/oracle.sql, liquibase-core/src/test/java/liquibase/verify/saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets/modifyDataType/oracle.sql, liquibase-integration-tests/src/test/java/liquibase/statementexecute/CreateDatabaseChangeLogLockTableExecuteTest.java
All integer types are represented in Oracle as number(precision, scale). The `INTEGER` keyword is converted to a number(*) by Oracle and the `MEDIUMINT` keyword is not supported.
Adopt a consistent mapping from Liquibase to Oracle numbers:
* tinyint => number(3,0)
* smallint => number(5,0)
* mediumint => number(7,0)
* integer => number(10,0)
* bigint => number(19,0)
┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-36) by [Unito](https://www.unito.io/learn-more)
┆Fix Versions: Liquibase 4.1.0
=> [CORE-3523] Consistently map Liquibase integer types to Oracle integer types

liquibase-core/src/main/java/liquibase/integration/ant/AntTaskLogService.java, liquibase-core/src/main/java/liquibase/integration/ant/BaseLiquibaseTask.java
- - -
title: ''
assignees: ''
- - -
**Liquibase Integration & Version**: Ant
Liquibase has a fairly new logging abstraction and it wasn't entirely working with the Ant tasks. The tasks were reverting to standard out logging which might make it difficult to control log levels correctly in Ant tasks.
I leveraged the new Scope system (pretty neat!) to add the AntLogService manually. This log service creates the AntTaskLogger correctly so the logger delegates to Ant's logger again.
The ant tasks once again handle Liquibase logs correctly. …
=> Fix usage of AntTaskLogger

.travis/databases.docker-compose.yml, liquibase-core/src/main/java/liquibase/change/core/AddPrimaryKeyChange.java, liquibase-core/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java, liquibase-core/src/main/java/liquibase/sqlgenerator/core/DropUniqueConstraintGenerator.java, liquibase-core/src/main/java/liquibase/statement/core/AddPrimaryKeyStatement.java, liquibase-integration-tests/src/test/java/liquibase/dbtest/cockroachdb/CockroachDBIntegrationTest.java, liquibase-integration-tests/src/test/java/liquibase/statementexecute/AddUniqueConstraintExecutorTest.java, liquibase-integration-tests/src/test/resources/changelogs/cockroachdb/complete/root.changelog.xml, liquibase-integration-tests/src/test/resources/changelogs/cockroachdb/rollback/rollbackable.changelog.xml
* Create test database and schemas in integration test setup
* Make AddPrimaryKeyStatement account for DESC primary key
* Use DROP INDEX to drop unique constraints in CockroachDB
* Fix CREATE VIEW test changeset to not reference a different schema
* Skip rollback PK test for CockroachDB
* Stop referencing DB explicitly in CockroachDB test changeset
* Skip CockroachDB testRunUpdateOnOldChangelogTableFormat
┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-856) by [Unito](https://www.unito.io/learn-more)
=> Fix CockroachDB Tests

liquibase-core/src/main/java/liquibase/change/core/LoadDataChange.java, liquibase-core/src/main/java/liquibase/change/core/LoadDataColumnConfig.java, liquibase-core/src/main/java/liquibase/sqlgenerator/core/InsertOrUpdateGenerator.java, liquibase-core/src/main/java/liquibase/statement/core/InsertStatement.java, liquibase-core/src/main/resources/liquibase/parser/core/xml/dbchangelog-3.2.xsd, liquibase-core/src/test/java/liquibase/sqlgenerator/core/InsertOrUpdateGeneratorMSSQLTest.java, liquibase-core/src/test/java/liquibase/sqlgenerator/core/InsertOrUpdateGeneratorOracleTest.java
Added option "updateable" to the column tag. This option allows you to not include a column in the update script. Default value = "true".
┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-84) by [Unito](https://www.unito.io/learn-more)
┆Fix Versions: Liquibase 4.2.0
=> Added option "updateable" to the column tag.

liquibase-core/src/main/java/liquibase/database/DatabaseFactory.java, liquibase-core/src/main/java/liquibase/integration/ant/AbstractDatabaseDiffTask.java, liquibase-core/src/main/java/liquibase/integration/ant/BaseLiquibaseTask.java, liquibase-core/src/main/java/liquibase/integration/ant/type/DatabaseType.java, liquibase-core/src/test/groovy/liquibase/change/core/DropAllForeignKeyConstraintsChangeTest.groovy, liquibase-core/src/test/java/liquibase/database/DatabaseFactoryTest.java
- - -
title: ''
assignees: ''
- - -
**Liquibase Version**: 3.10.x
**Liquibase Integration & Version**: Ant
**Operating System Type & Version**: All
Fixes #1378
I have been investigating #1378 and I believe the issue is the Ant tasks are creating the `DatabaseConnection` themselves and not respecting the logic found in the `DatabaseFactory`. This PR updates the Ant tasks to leverage the `DatabaseFactory` to keep consistent with the rest of the integration types (CLI, Maven, etc). 
This involved a small refactoring of the `DatabaseFactory` so it can accept a pre-configured `Properties` object as that is needed by Ant. The …
=> Update Ant Tasks to use DatabaseFactory rather than create connection itself

liquibase-core/src/main/java/liquibase/change/core/LoadDataChange.java, liquibase-core/src/test/groovy/liquibase/change/core/LoadUpdateDataChangeTest.groovy, liquibase-core/src/test/resources/liquibase/change/core/jhi_text.csv
- - -
title: ''
assignees: ''
- - - …
=> Fix issue with loadUpdateData GH-1489

liquibase-core/src/main/java/liquibase/sqlgenerator/core/DropDefaultValueGenerator.java
On PostgreSQL, the dropDefaultValue command only sets the default value to NULL rather than actually dropping it. 
Looking at DropDefaultValueGenerator.java, there's no mention of PostgreSQL anywhere, so it ends up using the default "SET DEFAULT NULL".
1. Create a table with an int column containing a default value of 10
1. Run a changeLog with <dropDefaultValue> for that column
1. `\d` describe that table to see that it now has a default value of null
`\d` describe that table to see that it has no default value.
┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-42) by [Unito](https://www.unito.io/learn-more)
┆Fix Versions: Community 4.2.1,Liquibase 4.2.1
=> Fix CORE-3078 bug

liquibase-dist/src/main/archive/liquibase
**Branch: Liquibase/master**
Added quotes around ${JAVA_PATH} in line 77 to avoid issues when there are spaces in the JAVA_PATH when using Emulators like "Git bash for Windows".
This fix will prevent having issues with spaces in JAVA_PATH.  For example: when running Liquibase commands in Windows with Linux/Unix like Emulators such as: "Git bash for Windows" or "Minimalist GNU for Windows" with preexisting spaces in the JAVA_PATH.
┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-173) by [Unito](https://www.unito.io/learn-more)
┆Fix Versions: Community 4.x
=> Added quotes around ${JAVA_PATH} in liquibase shell script to avoid spaces in path issues

liquibase-core/src/main/java/liquibase/datatype/core/BooleanType.java
In my last PR https://github.com/liquibase/liquibase/pull/865 I forgot a line of code to activate the boolean support.
* Do a desk check with the developer
* Verify unit or integration tests exist.
┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-28) by [Unito](https://www.unito.io/learn-more)
┆Fix Versions: Community 4.x
=> fix DB2 LUW supports boolean data type

liquibase-core/src/main/java/liquibase/change/core/AddColumnChange.java, liquibase-core/src/main/java/liquibase/sqlgenerator/core/AddColumnGeneratorDefaultClauseBeforeNotNull.java
- - -
name: Fix #1452: 'afterColumn' and 'position' not working in Firebird and Oracle databases
about: Fixes the bug as described in Issue #1452 
title: ''
assignees: ''
- - -
**Liquibase Version**: 3.8.5 - 4.1.0
**Liquibase Integration & Version**: gradle
**Database Vendor & Version**: firebird 2.5, oracle
**Operating System Type & Version**: win 10 java 8
As mentioned in #1452, this PR fixes the issue where 'afterColumn' and 'position' are ignored in the SQL generation for Firebird and Oracle databases.
See #1452 
See #1452 
See #1452 
┆Issue is synchronized with this [Jira …
=> Fixes #1452: 'afterColumn' and 'position' not working in Firebird and Oracle databases

liquibase-core/src/main/java/liquibase/parser/core/xml/LiquibaseEntityResolver.java, liquibase-core/src/main/java/liquibase/parser/core/xml/XMLChangeLogSAXParser.java
Even if the standard ResourceAccessor does not include it.
Fixes #1609
┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-1100) by [Unito](https://www.unito.io/learn-more)
=> EntityResolver should check the classpath

liquibase-core/src/main/java/liquibase/sqlgenerator/core/DropColumnGenerator.java, liquibase-core/src/main/java/liquibase/sqlgenerator/core/DropDefaultValueGenerator.java, liquibase-core/src/test/java/liquibase/sqlgenerator/core/DropColumnGeneratorTest.java
https://liquibase.jira.com/projects/CORE/issues/CORE-3594
{CODE}
RROR Reason: liquibase.exception.DatabaseException: Error executing SQL ALTER TABLE TEST DROP COLUMN COL2: The object 'DF_GENERIC_ENTITY_COL2' is dependent on column 'COL2'.
{CODE}
1. Create a changelog with the following changes:
{CODE}
<changeSet id="C1" labels="columnWithDefaultValue">
<createTable tableName="TEST">
<column name="COL1" type="int"  />
<column name="COL2" type="int" defaultValue="42" />
</changeSet>
<changeSet id="C2" labels="dropColumnWithDefaultValue>
<dropColumn tableName="TEST" columnName="COL2" />
</changeSet>
{CODE}
2. Execute a Liquibase update to deploy C1 to a SQL Server database:
{CODE}
liquibase --changeLogFile=mychangelog.xml --labels=columnWithDefaultValue update
{CODE}
3. Execute a second …
=> CORE-3594 Automatic dropping of default values on MS SQL

liquibase-core/src/test/groovy/liquibase/command/core/HistoryCommandTest.groovy
**Branch: Liquibase/master**
* \[x] Bug fix (non-breaking change which fixes an issue)
The HistoryCommandTest fails on systems with a non-US default Locale because the date in the history is formatted in a locale-specific way
* Run the test case on a system with e.g. German as default Locale
With German the test produces:
> Database updated at 09.07.19 12:15.
No matter on which system the test is running, it produces:
> Database updated at 7/9/19 12:15 PM.
* \[x] Build is successful and all new and existing tests pass
* \[ ] Added Unit Test(s)
* \[ ] Added Integration Test(s)
* \[ ] Documentation Updated
┆Issue is …
=> Fix HistoryCommandTest to run on systems having a non-US default locale

liquibase-core/src/main/java/liquibase/changelog/visitor/ValidatingVisitor.java
ValidatingVisitor.findChangeSet method
Fixes #1603
┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-1101) by [Unito](https://www.unito.io/learn-more)
=> Filename + Id + Author is not being treated as unique 

liquibase-core/src/main/java/liquibase/logging/LogFactory.java, liquibase-core/src/test/groovy/liquibase/logging/LogFactoryTest.groovy
Fixes #1641
┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-1134) by [Unito](https://www.unito.io/learn-more)
=> Add deprecated LogFactory.getInstance() to smooth upgrade to 4.x

liquibase-core/src/main/java/liquibase/integration/spring/SpringResourceAccessor.java, liquibase-core/src/main/java/liquibase/resource/ClassLoaderResourceAccessor.java
* Support classpath*:
* Correctly find classes in directories and jar files
Fixes #1657 
Fixes #1595
┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-1173) by [Unito](https://www.unito.io/learn-more)
=> Improved SpringResourceAccessor

liquibase-dist/src/main/archive/examples/xml/liquibase.sqlplus.conf
Closes #1416
* Verify the liquibase.sqlplus.path is commented out in the Windows installer.
* Verify the liquibase.sqlplus.path is commented out in the Mac installer.
┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-746) by [Unito](https://www.unito.io/learn-more)
┆Fix Versions: Community 4.3.2,Liquibase 4.3.2
=> liquibase.sqlplus.path line in liquibase/examples/xml/liquibase.sqlplus.conf should be commented out

liquibase-core/src/main/java/liquibase/change/core/LoadDataChange.java, liquibase-core/src/test/groovy/liquibase/change/core/LoadDataChangeTest.groovy
Documented on issue
https://github.com/liquibase/liquibase/issues/1091
_Copied issue description here_
**Liquibase Version**: 3.8.9
**Liquibase Integration & Version**: maven liquibase plugin, also version 3.8.9; maven version 3.6.3
**Database Vendor & Version**: SQLServer 2012
**Operating System Type & Version**: Ubuntu running Docker 19.0.3
Regardless of whether the attribute 'usePreparedStatements' is set to 'true' or 'false' in 'loadData' elements, Liquibase always uses prepared statements (so it behaves as if it were harcoded to 'true')
This is the cause why when we try to load a CSV file where a 'DATE' column is set to 'NULL' we get the following error:
```txt
Error setting up or running Liquibase:
[ERROR] Migration failed for change set …
```
=> usePreparedStatement attribute in loadData element has no effect

liquibase-core/src/main/java/liquibase/Liquibase.java, liquibase-core/src/main/java/liquibase/integration/ant/ChangeLogSyncTask.java, liquibase-core/src/main/java/liquibase/integration/commandline/Main.java, liquibase-core/src/main/resources/liquibase/i18n/liquibase-commandline-helptext.xml, liquibase-core/src/test/groovy/liquibase/LiquibaseTest.groovy, liquibase-core/src/test/groovy/liquibase/integration/ant/test/LiquibaseTagExistsCondition.groovy, liquibase-core/src/test/resources/liquibase/integration/ant/ChangeLogSyncTaskTest.xml, liquibase-core/src/test/resources/liquibase/integration/ant/changelog/simple-changelog.xml, liquibase-core/src/test/resources/liquibase/integration/ant/test/antlib.xml, liquibase-core/src/test/resources/liquibase/tagged-changelog.xml, liquibase-dist/src/main/archive/lib/liquibase_autocomplete.sh, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseChangeLogSyncMojo.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseChangeLogSyncSQLMojo.java
Add a `changelogSyncToTag` command to allow only those changeSets up to and including the specified tag to be marked as ran in the database. A similar command, `changelogSyncToTagSQL` should output the SQL to mark all changeSets upto the specified tag as ran.
Provide support for running the new commands via either the Liquibase command line, an Ant Task or the Maven plugin.
1. changelogSyncToTag
Mark all changeSets as ran in database `test` up to and including the `version_2.0` tag.
```
./liquibase \
--driver=org.postgresql.Driver \
--classpath=/tmp/postgresql-42.1.1.jre7.jar \
--url=jdbc:postgresql://localhost:5432/test \
--username=bob \
--password=t0pS3cret \
--changeLogFile=/tmp/db-changelog.xml \
changelogSyncToTag version_2.0
```
1. changeLogSyncToTagSQL
Output to STDOUT the SQL to …
=> [1133] Add changelogSyncToTag and changelogSyncToTagSQL commands

liquibase-core/src/main/java/liquibase/datatype/core/DateTimeType.java
- - -
about: NPE in DateTimeType core class
title: 'Fix For NPE'
assignees: ''
- - -
**Liquibase Version**: 4.0.0
NPE in DateTimeType in liquibase 4.0.0
More on that here: https://github.com/liquibase/liquibase/issues/1366
Generate Changelog for Oracle DB
┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-623) by [Unito](https://www.unito.io/learn-more)
┆Fix Versions: Community 4.4.0,Liquibase 4.4.0
=> #1366 DateTimeType.java:38 NullPointerException

liquibase-core/src/main/java/liquibase/sqlgenerator/core/InsertOrUpdateGeneratorPostgres.java, liquibase-core/src/test/java/liquibase/sqlgenerator/core/InsertOrUpdateGeneratorPostgresTest.java
- - -
title: ''
assignees: ''
- - -
**Liquibase Version**: 3.8.8
**Liquibase Integration & Version**: gradle (for a Spring Boot project)
**Database Vendor & Version**: PostgreSQL 9.6.12
**Operating System Type & Version**: macOS Mojave 10.14.6
Fixes https://github.com/liquibase/liquibase/issues/1205
When using `LoadUpdateData` with `onlyUpdate=true` to load data from a CSV file into a Postgres database, missing data would still be inserted into the database.
Because we specified `onlyUpdate=true`, only existing data should be updated in the database. No missing data should be inserted.
- - -
Although this bug is opened against Spring Boot, the issue reproduces in …
=> Added conditional check to make onlyUpdate flag work for Postgres DB LB-316

liquibase-core/src/main/java/liquibase/change/core/MergeColumnChange.java, liquibase-core/src/test/java/liquibase/verify/saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets/mergeColumns/mariadb.sql, liquibase-core/src/test/java/liquibase/verify/saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets/mergeColumns/mysql.sql
[https://forum.liquibase.org/t/mergecolumns-mysql/4669](https://forum.liquibase.org/t/mergecolumns-mysql/4669)
- - -
about: Fix merge column on MySql
title: Fix merge column on MySql
labels: Status:Fixed
assignees: ''
- - -
**Liquibase Version**: 4.0.1-local-SNAPSHOT
**Operating System Type & Version**: Windows 10 pro
* [x ] Bug fix (non-breaking change which fixes an issue.)
Using MySql db, and using mergeColumns chanset the result column is not correctly merged. 
```java
<changeSet …
```
=> Fixed mysql merge columns query

liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateSequenceGenerator.java, liquibase-core/src/test/java/liquibase/sqlgenerator/core/CreateSequenceGeneratorTest.java
**Liquibase Version**:  4.4.0
**Database Vendor & Version**: PostgreSQL version < 10
**Operating System Type & Version**: Mac OS Catalina 10.15.7
PostreSQL doesn't support "AS datatype" structure in sequences prior to version 10. So SQL that Liquibase generates with "AS [datatype]" fails for those postgreSQL versions. Added validation that throws error if `datatype` property in changeset is used for versions of postgre that don't support this structure.
* run PostreSQL 9.5 on perm, in docker container or elsewhere
* take changelog file from test harness https://github.com/liquibase/liquibase-test-harness/blob/974f3adeac5225929fef9580bede0ed7c72b7733/src/mai …
=> [LB-704] fixed generating sequences for postgre versions prior to 10

liquibase-core/src/main/java/liquibase/exception/ValidationErrors.java, liquibase-core/src/main/java/liquibase/sqlgenerator/core/AddDefaultValueGenerator.java, liquibase-core/src/test/groovy/liquibase/change/core/LoadDataChangeTest.groovy
Fixes #1920
I added the ability to allow empty values for required fields as needed, although it will still default to not allowing it. Searching through the code, I only found addDefaultValue with the "required" check being done for a value that could be empty, so that is all I fixed.
* Fixed Issue: [https://github.com/liquibase/liquibase/issues/1920](https://github.com/liquibase/liquibase/issues/1920)
* Local Branch: [https://github.com/liquibase/liquibase/tree/allow-empty-defaultValue](https://github.com/liquibase/liquibase/tree/allow-empty-defaultValue)
* Unit Tests: [https://github.com/liquibase/liquibase/pull/1963/checks](https://github.com/liquibase/liquibase/pull/1963/checks)
* Functional Tests: …
=> Allow empty string for defaultValue attribute

liquibase-core/src/main/java/liquibase/command/core/UpdateTestingRollbackCommandStep.java, liquibase-core/src/main/java/liquibase/hub/HubUpdater.java, liquibase-core/src/main/resources/META-INF/services/liquibase.command.CommandStep, liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/updateTestingRollback.test.groovy
Fixes #1909 
Includes new integration test. I did some manual testing of it as well through the CLI.
Used the same arguments as `update` based on looking at old Main class
- - -
* Fixed Issue: [https://github.com/liquibase/liquibase/issues/1909](https://github.com/liquibase/liquibase/issues/1909)
* Local Branch: [https://github.com/liquibase/liquibase/tree/restore-update-testing-rollback](https://github.com/liquibase/liquibase/tree/restore-update-testing-rollback)
* Unit Tests: [https://github.com/liquibase/liquibase/pull/1939/checks](https://github.com/liquibase/liquibase/pull/1939/checks)
* Functional Tests: [https://jenkins.datical.net/job/liquibase-pro/job/restore-update-testing-rollback/](https://jenkins.datical.net/job/liquibase-p …
=> Restore update testing rollback command

liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java, liquibase-cli/src/test/groovy/liquibase/integration/commandline/LiquibaseCommandLineTest.groovy, liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
Fixes #1907 
- - -
* Fixed Issue: [https://github.com/liquibase/liquibase/issues/1907](https://github.com/liquibase/liquibase/issues/1907)
* Local Branch: [https://github.com/liquibase/liquibase/tree/reintroduce-d-arguments-in-cli](https://github.com/liquibase/liquibase/tree/reintroduce-d-arguments-in-cli)
* Unit Tests: [https://github.com/liquibase/liquibase/pull/1943/checks](https://github.com/liquibase/liquibase/pull/1943/checks)
* Functional Tests: [https://jenkins.datical.net/job/liquibase-pro/job/reintroduce-d-arguments-in-cli/](https://jenkins.datical.net/job/liquibase-pro/job/reintroduce-d-arguments-in-cli/)
* Steps to Reproduce: [https://github.com/liquibase/liquibase/issues/1907](https://github.com/liquibase/liquibase/issues/1 …
=> Reintroduce support for "-D" arguments in CLI

liquibase-core/src/main/java/liquibase/changelog/DatabaseChangeLog.java, liquibase-core/src/test/groovy/liquibase/parser/core/yaml/YamlChangeLogParser_RealFile_Test.groovy, liquibase-core/src/test/resources/liquibase/parser/core/yaml/typoChangeLog.yaml
- - -
about: The Liquibase changelog parser.
title: 'Better error message for typo in "changeSet" node'
assignees: ''
- - -
**Liquibase Version**: any
**Liquibase Integration & Version**: any
When a typo in done in a changeSet, a NullPointerException is thrown, as follows:
```
java.lang.NullPointerException: Cannot get property 'changes' on null object
at liquibase.parser.core.yaml.YamlChangeLogParser_RealFile_Test.throws a nice validation error when changeSet node has typo in name(YamlChangeLogParser_RealFile_Test.groovy:121)
```
instead of a better one.
Run the unit test added in the first commit, without the second commit (or revert the second commit on this branch locally, which will show you how the test fails and the NullPointerException …
=> NullPointerException when typo present in "changeSet" node

liquibase-core/pom.xml, liquibase-core/src/main/java/liquibase/lockservice/StandardLockService.java, liquibase-core/src/test/java/liquibase/lockservice/StandardLockServiceTest.java
4.3.1 -> 4.4.0
At least spring boot, but all should be impacted
MySQL with driver 8.0.23
All
The issue #1749 occurs when the locks are listed (after the lock times out). This fixes the cast issue. This PR also include a unit test to ensure it works with java.sql.Date and LocalDateTime.
To test it, it was not easy to mock the ExecutorService as …
=> Class cast exception in standard lock service

.github/ISSUE_TEMPLATE/bug_report.md, liquibase-integration-tests/src/test/java/liquibase/statementexecute/UnlockDatabaseChangeLogExecuteTest.java
Fixes #1872
**Liquibase Version**: 3.10.3 / 4.3.4
**Liquibase Integration & Version**: gradle - 5.6
**Liquibase Extension(s) & Version**:  - 
**Database Vendor & Version**: FireBird - 3.0.7
**Operating System Type & Version**: Windows 10, 64bit, version - 1909
Liquibase fails to apply change set with following error:
nested exception is liquibase.exception.LockException: liquibase.exception.DatabaseException: conversion error from string "0" [SQLState:22018, ISC error code:335544334] [Failed SQL: (335544334) INSERT INTO DATABASECHANGELOGLOCK (ID, LOCKED) VALUES (1, 0)]
Install FireBird 3.0.7. Create user and grand permission to this user to create database. Create a database and table. Try to apply any change set.
Change set is not getting applied. It fails to create DATABASECHANGELOGLOCK …
=> Firebird3Database supports true Boolean, so isNumericBoolean should return false.

liquibase-core/src/main/java/liquibase/changelog/ChangeSet.java, liquibase-core/src/test/java/liquibase/serializer/core/json/JsonChangeLogSerializerTest.java, liquibase-core/src/test/java/liquibase/serializer/core/xml/XMLChangeLogSerializerTest.java
- - -
title: ''
assignees: ''
- - -
**Liquibase Version**: 3.10.3
**Liquibase Extension(s) & Version**: mssql-jdbc-8.4.1.jre8.jar
**Database Vendor & Version**: MSSQL
**Operating System Type & Version**: Windows 10
The logicalFilePath attribute of a ChangeSet is not serialized.
The logicalFilePath attribute of a ChangeSet is serialized.
`<changeSet author="tms"  dbms="mssql" id="1" logicalFilePath="path/to/file.json"/>`
- - -
* Fixed Issue: stand alone PR
* Local Branch: https://github.com/liquibase/liquibase/tree/LB-790
* Unit Tests: …
=> Fix logicalFilePath not being serialized - Fixes 1234

liquibase-core/src/main/java/liquibase/sqlgenerator/core/InsertOrUpdateGeneratorHsql.java, liquibase-core/src/test/groovy/liquibase/sqlgenerator/core/InsertOrUpdateGeneratorHsqlTest.groovy
- - -
about: #1562 fixes invalid update sql generated fof hsql
title: ''
assignees: ''
- - -
**Liquibase Version**: all
**Liquibase Integration & Version**: all
**Database Vendor & Version**: hsql
**Operating System Type & Version**: all
add table name and where clause to generated sql
If applicable, add screenshots to help explain your problem.
- - -
* Fixed Issue: https://github.com/liquibase/liquibase/issues/1562 
* Local Branch: https://github.com/liquibase/liquibase/tree/devorgpl-fix-1562
* Unit Tests: …
=> Fix #1562 invalid update sql generated for hsql

.github/ISSUE_TEMPLATE/bug_report.md, liquibase-core/src/main/java/liquibase/change/core/SQLFileChange.java, liquibase-core/src/test/groovy/liquibase/change/core/SQLFileChangeTest.groovy, liquibase-core/src/test/resources/com/example/my-logic.sql
Fixes #1277 
Fixes #1353
liquibase
4.3.3 and above, this PR was code code checked out on master today which was v4.4.0 level
Liquibase-core
oracle 19c
ubuntu 18.04
bug fix    sqlfile relative paths
A clear and concise description of the issue being addressed.  Additional guidance [here](https://liquibase.jira.com/wiki/spaces/LB/pages/1274904896/ …
=> relative bug fix for sql files

liquibase-core/src/main/java/liquibase/change/core/LoadDataChange.java, liquibase-core/src/test/groovy/liquibase/change/core/LoadDataChangeTest.groovy, liquibase-integration-tests/src/test/java/liquibase/dbtest/pgsql/PostgreSQLIntegrationTest.java
Data loaded from CLOB type columns is not loaded properly into PostgreSQL.
Instead of loading the content of the CLOB file, the filename is loaded.
See issue #1790 
When the data needs a prepared statement to be executed (example CLOB) and the database does not support batch mode (example PostgreSQL), the statement is executed as a normal statement and the the text string (the filename of the clob) is inserted instead of the content of the CLOB. 
4.4.0
CLI and Spring boot
PostgreSQL
Windows 10 (irrelevent)
See issue #1790 
**Automated Functional Test Requirements**
* …
=> fix loading clob data into postgres

liquibase-core/src/main/java/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParser.java, liquibase-core/src/test/groovy/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParserTest.groovy
**Liquibase Version**: 3.10.0
**Liquibase Integration & Version**: All
**Operating System Type & Version**: All
An issue spotted where empty space at the beginning of the formatted sql changelog would result in the changeset running as raw sql. This change is to find the first non empty string (or end of file) and perform the regex match to determine if the file is a formatted sql file so that the changeset is logged correctly. First time committing code here, thank you for any and all …
=> handle empty lines at start of formatted sql

liquibase-core/src/main/java/liquibase/changelog/StandardChangeLogHistoryService.java
- - -
title: 'Statement to updating MD5SUM column value changed from RawSqlStatement to UpdateStatement'
assignees: ''
- - -
**Liquibase Version**: v4.2.2
Creating an update query using UpdateStatement.
- - -
* Fixed Issue: Stand alone PR
* Local Branch: https://github.com/liquibase/liquibase/tree/biryukovpavel-master
* Unit Tests: https://github.com/liquibase/liquibase/pull/1602/checks
* Functional Tests: https://jenkins.datical.net/job/liquibase-pro/job/biryukovpavel-master/
* Steps to Reproduce: Nothing externally visible
* Guidance: 
* …
=> Changed from RawSqlStatement to UpdateStatement

liquibase-core/src/main/java/liquibase/Scope.java
**Liquibase Version**: 4.3.1
**Liquibase Integration & Version**: spring boot
**Database Vendor & Version**: MySQL 5.7.12-log
**Operating System Type & Version**: Amazon AWS RDS
We have a Spring Boot command line application that applies the same Liquibase changset concurrently to two different database instances using the Liquibase Java API. Currently this fails due to a Liquibase scope collision.
The Liquibase.update() method is run with the Java ExecutorService on two different threads. Currently the liquibase Scope class defaults to the SingletonScopeManager if no ScopeManager has been defined. This causes a problem in a multi-threaded application. Therefore we implemented a ThreadLocalScopeManager to ensure that each thread maintains it's own …
=> Ensure that the root scope is initialized correctly regardless of whether a scope manager has been configured yet or not.

liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateSequenceGenerator.java, liquibase-core/src/test/java/liquibase/sqlgenerator/core/CreateSequenceGeneratorTest.java
Fixes #1570
- - -
* Fixed Issue: https://github.com/liquibase/liquibase/issues/1570
* Local Branch: https://github.com/liquibase/liquibase/tree/h2-createsequence-datatype-fix
* Unit Tests: https://github.com/liquibase/liquibase/pull/1992/checks
* Functional Tests: https://jenkins.datical.net/job/liquibase-pro/job/h2-createsequence-datatype-fix/
* Steps to Reproduce: https://github.com/liquibase/liquibase/issues/1570
* Guidance: 
* Only impacts h2
Added unit test, plus ran `update` with a changeSet with dataType specified
```
Starting Liquibase at 11:22:43 (version 4.4.2-local-SNAPSHOT #0 built at 2021-07-18 03:14+0000)
Liquibase Version: 4.4.2-local-SNAPSHOT
Liquibase Community 4.4.2-local-SNAPSHOT by Datical
Liquibase command 'update' …
```
=> Fix createSequence for h2 when dataType is specified

liquibase-core/src/main/java/liquibase/lockservice/LockServiceFactory.java, liquibase-core/src/test/java/liquibase/lockservice/LockServiceFactoryTest.java
Fixes #1568
- - -
* Fixed Issue: https://github.com/liquibase/liquibase/issues/1568
* Local Branch: https://github.com/liquibase/liquibase/tree/lockservice_reset_sync
* Unit Tests: https://github.com/liquibase/liquibase/pull/1991/checks
* Functional Tests: https://jenkins.datical.net/job/liquibase-pro/job/lockservice_reset_sync/
* Steps to Reproduce: https://github.com/liquibase/liquibase/issues/1568
* Guidance: 
* Newly added unit test caught error before fix, passes after fix
New unit test passes
┆Issue is synchronized with this [Jiraserver Bug](https://datical.atlassian.net/browse/LB-1973) by [Unito](https://www.unito.io)
=> Improve synchronization of LockServiceFactory reset

liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java, liquibase-core/src/main/java/liquibase/configuration/core/DefaultsFileValueProvider.java, liquibase-core/src/test/groovy/liquibase/configuration/core/DefaultsFileValueProviderTest.groovy
Fixes #1892
- - -
* Fixed Issue: liquibase/liquibase#1892
* Local Branch: [https://github.com/liquibase/liquibase/tree/LB-1795](https://github.com/liquibase/liquibase/tree/LB-1795)
* Unit Tests: [https://github.com/liquibase/liquibase/pull/1893/checks](https://github.com/liquibase/liquibase/pull/1893/checks)
* Functional Tests: [https://jenkins.datical.net/job/liquibase-pro/job/LB-1795/](https://jenkins.datical.net/job/liquibase-pro/job/LB-1795/)
* Steps to Reproduce: liquibase/liquibase#1892
* Guidance:
* Change only impacts CLI
(did not save output at the time)
**Manual Tests**
:: SETUP :: 
This test requires a non-executable Jar containing the liquibase.properties and changelog file. We will create this Jar and add it to the Java …
=> CLI no longer reading defaultsFile from classpath

liquibase-core/src/main/java/liquibase/util/TableOutput.java
Previously, the table output class would incorrectly split very long strings like this:
```
+--------------------------------+-----------------------+--------------------------------+---------+------------------+
| Warn on Detection of 'REVOKE…' | SqlRevokeWarn         | This check warns a user when   | true    | <None>           |
|   Statements                   |                       |   generated or raw SQL contain |         |                  |
|                                |                       | s   'REVOKE…' statements so th |         |                  |
|                                |                       | at    they can ensure that the |         |                  |
|                                |                       |         privilege being revoke |         | …
```
=> DAT-7954: fix incorrect line breaks in TableOutput

liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy
This change complies with how Intellij Idea expects failed tests to report their "expected" and "actual" values. The ultimate purpose here is so that Intellij will add a `<Click to see difference>` button to the console output that, when clicked, will show a diff between the expected and actual.
=> render failed CommandTests in a format that Intellij Idea expects

liquibase-core/src/main/java/liquibase/ui/ConsoleUIService.java, liquibase-core/src/main/java/liquibase/ui/LoggerUIService.java, liquibase-core/src/main/java/liquibase/ui/UIService.java, liquibase-core/src/test/groovy/liquibase/ui/ConsoleUIServiceTest.groovy, liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy
Allow specifying a `currentValue` when using the `prompt` method in the `UIService`. If a non-null `currentValue` is provided, it will be shown instead of the `defaultValue`. If the input handler allows empty inputs, and the user strikes enter at the prompt when a `currentValue` is shown, that value will be returned.
=> DAT-8203: allow supplying a current value when prompting using UIService

liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy
The CommandTests framework allows for supplying a list of interactive prompt responses, and sometimes, you don't specify them correctly or configure your rule correctly. In those cases, the CLI may prompt for more parameters than you've specified, and the error message is an ArrayIndexOutOfBounds exception, which isn't immediately obvious.
=> DAT-8052: add more explicit explanation for wrong number of params in test

liquibase-core/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.6.xsd
Fixes #1760 with fix suggested by ckulenkampff  ([https://github.com/liquibase/liquibase/issues/1760#issuecomment-796692112)](https://github.com/liquibase/liquibase/issues/1760#issuecomment-796692112)).
<
!--- If you're unsure about any of these, just ask us in a comment. We're here to help|width=200,height=183!
-->
* \[ ] Build is successful and all new and existing tests pass
* \[ ] Added [Unit Test(s)](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)
* \[ ] Added [Integration …
=> Fix sqlFile encoding attribute handling

liquibase-core/src/main/java/liquibase/command/core/RegisterChangelogCommandStep.java, liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/registerChangelog.test.groovy
Use correct phrasing in the the register changelog command console outputs.
=> Use correct message in console output of register changelog command - DAT-7757

liquibase-core/src/main/java/liquibase/lockservice/StandardLockService.java
Proposed fix for [https://github.com/liquibase/liquibase/issues/1816](https://github.com/liquibase/liquibase/issues/1816)
- - -
* Fixed Issue: [https://github.com/liquibase/liquibase/issues/1816](https://github.com/liquibase/liquibase/issues/1816)
* Local Branch: [https://github.com/liquibase/liquibase/tree/stalbrecht-bugfix-1816](https://github.com/liquibase/liquibase/tree/stalbrecht-bugfix-1816)
* Unit Tests: [https://github.com/liquibase/liquibase/pull/1817/checks](https://github.com/liquibase/liquibase/pull/1817/checks)
* Functional Tests: [https://jenkins.datical.net/job/liquibase-pro/job/stalbrecht-bugfix-1816/](https://jenkins.datical.net/job/liquibase-pro/job/stalbrecht-bugfix-1816/)
* Steps to Reproduce: …
=> Added MSSQLDatabase specific error evaluation when creating lock table

liquibase-core/src/main/java/liquibase/database/core/PostgresDatabase.java, liquibase-core/src/test/groovy/liquibase/snapshot/jvm/ColumnSnapshotGeneratorTest.groovy
Arrays in Postgres do NOT have size, even if param specified - it is ignored (https://www.postgresql.org/docs/14/arrays.html)
- Files used - sql scripts, changelog …
=> [LB-2110] Fix COLUMN_SIZE for PostgreSQL NUMERIC[] datatype by adding it as unmodifiable data type for PostgresDatabase

liquibase-integration-tests/src/test/java/liquibase/dbtest/sqlite/SQLiteIntegrationTest.java, liquibase-integration-tests/src/test/java/liquibase/test/DatabaseTestContext.java, liquibase-integration-tests/src/test/resources/changelogs/sqlite/complete/root.changelog.xml, liquibase-integration-tests/src/test/resources/liquibase/liquibase.integrationtest.properties
This PR does two things:
- Automatically delete SQLite database file from disk after JVM exits from running integration tests.
- Comment out the changelog line which creates the foreign key which causes the test failures. I am unsure if this is the correct way to solve this problem. The other option for solving this problem is reverting this merge: https://github.com/liquibase/liquibase/pull/1970
=> SQLite test fixes and automatic cleanup

liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
If 'liquibase validate' finds any errors, it should throw the exception and therefore exit with a non-zero error code. 
Fixes #1006
This changes the behavior of the 'validate' command in automation, so marked it as "ReleaseMajor" so it doesn't end up in a patch release.
- - -
* Fixed Issue: [https://github.com/liquibase/liquibase/issues/1006](https://github.com/liquibase/liquibase/issues/1006)
* Local Branch: [https://github.com/liquibase/liquibase/tree/validation-errors-set-error-code](https://github.com/liquibase/liquibase/tree/validation-errors-set-error-code)
* Unit Tests: [https://github.com/liquibase/liquibase/pull/2185/checks](https://github.com/liquibase/liquibase/pull/2185/checks)
* Functional Tests: …
=> 'Validate' exit code should be 1 on error

liquibase-core/src/main/java/liquibase/parser/core/yaml/YamlChangeLogParser.java
Fixes #1988 
Problem code was caused by an incorrect merge in the changeLogId handling, so I fixed the `if` statement nesting to be correct.
- - -
* Fixed Issue: [https://github.com/liquibase/liquibase/issues/1988](https://github.com/liquibase/liquibase/issues/1988)
* Local Branch: [https://github.com/liquibase/liquibase/tree/yaml-changelog-id](https://github.com/liquibase/liquibase/tree/yaml-changelog-id)
* Unit Tests: [https://github.com/liquibase/liquibase/pull/2168/checks](https://github.com/liquibase/liquibase/pull/2168/checks)
* Functional Tests: [https://jenkins.datical.net/job/liquibase-pro/job/yaml-changelog-id/](https://jenkins.datical.net/job/liquibase-pro/job/yaml-changelog-id/)
* Steps to Reproduce: …
=> YAMLChangelogParser: Fix parsing logic around changeLogId in a Map

liquibase-core/src/main/java/liquibase/changelog/DatabaseChangeLog.java
This is **Windows** specific issue.
In 4.6.0, a change broke the ability for spring boot projects that reference their changelog files with a `classpath:` prefix to `include` files with `relativeToChangelog=true`
pom.xml file (liquibase dependency):
```
<dependency>
<groupId>org.liquibase</groupId>
<artifactId>liquibase-core</artifactId>
<version>4.6.0</version>
</dependency>
```
application.yml file:
```java
spring:
liquibase:
change-log: classpath:/db/changelog/db-changelog.yml
dataSource:
driver-class-name: com.mysql.cj.jdbc.Driver
url: "jdbc:mysql://localhost:3306/intuser_db?serverTimezone=UTC"
username: root
password: password
```
db-changelog.xml file:
```java
databaseChangeLog:
- include:
relativeToChangelogFile: true
file: 001-users.yml
- include:
relativeToChangelogFile: true …
```
=> Fix handling of relativeToChangelogFile with classpath: prefixed changelogs

liquibase-core/src/main/java/liquibase/change/ColumnConfig.java
The JDocs for two boolean methods contain an incorrect reference to `date` (likely a copy/pasted value that was not updated as were several other references) in the descriptions of `setValueBoolean(String valueBoolean)` and `setDefaultValueBoolean(String defaultValueBoolean)`.
This commit corrects both to the proper term, `boolean`.
**Liquibase Version**: 4.5.0
=> Fix minor typos in ColumnConfig.java documentation

liquibase-core/src/main/java/liquibase/change/core/LoadDataChange.java
Fixes #1984
On mysql, the jdbc batch performance we switched to seems much worse than a large insert statement on mysql.
The general preparedStatement/batch logic could use a good refactoring, but this improves performance on mysql without impacting anything else at this point.
- - -
* Fixed Issue: [https://github.com/liquibase/liquibase/issues/1984](https://github.com/liquibase/liquibase/issues/1984)
* Local Branch: [https://github.com/liquibase/liquibase/tree/improve-loaddata-mysql-performance](https://github.com/liquibase/liquibase/tree/improve-loaddata-mysql-performance)
* Tests Results: [https://github.com/liquibase/liquibase/pull/](https://github.com/liquibase/liquibase/pull/){PR ID}/checks
* Steps to Reproduce: [{LINK TO ISSUE OR "See …
=> Improve mysql loadData performance

liquibase-core/src/main/java/liquibase/util/FileUtil.java
In the event that a particular file's parent file does not exist, this change prevents a `NullPointerException`.
=> Prevent NPE in FileUtil if parent file does not exist (DAT-8275)

liquibase-core/src/main/java/liquibase/ui/interactive/AbstractCommandLineValueGetter.java, liquibase-core/src/main/java/liquibase/ui/interactive/DynamicRuleParameter.java, liquibase-core/src/main/java/liquibase/ui/interactive/IInteractivelyPromptableEnum.java, liquibase-core/src/main/java/liquibase/ui/interactive/InteractivePromptableCustomizationWrapper.java
This PR (in combination with the Pro PR) does a few small things:
- Move the interactive CLI prompting logic into the core modules so they can be used outside of pro
- Add an interface for the enum which dictates the prompting logic. This is so that we can have separate promptable enums in the core and pro code and use the same abstract prompting logic for both.
=> Move interactive prompting logic into core module (DAT-8642)

liquibase-core/pom.xml, liquibase-core/src/main/java/liquibase/Activator.java, liquibase-core/src/main/java/liquibase/Scope.java, liquibase-core/src/main/java/liquibase/change/custom/CustomChangeWrapper.java, liquibase-core/src/main/java/liquibase/osgi/Activator.java, liquibase-core/src/main/java/liquibase/util/LiquibaseUtil.java, liquibase-core/src/main/java/liquibase/util/OsgiUtil.java
see issue #2054
This patch fixes next things:
1) Java Service Loader issues -> I need to update MANIFEST file
2) loading of liquibase.build.properties file -> I need to load this file via bundle.getEntry
3) class loading problem for CustomChangeWrapper.java -> there is a problem that liquibase bundle cannot see classes from other bundles. This can be solved via dynamic import:* in MANIFEST.MF but it is not recommended way from OSGI point of view. So my solution is that there is a Activator class that is called when liquibase bundle is started or stopped. Under "start" method I registered  BundleTrackerCustomizer that checked all bundles if they contain a special manifest entry "Liquibase-Custom-Change-Packages". When the entry exists bundle will be used for searching of CustomChange …
=> [2054] fix OSGI support (manifest, class loading)

liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
fixes #2109 
- - -
* Fixed Issue: [https://github.com/liquibase/liquibase/issues/2109](https://github.com/liquibase/liquibase/issues/2109)
* Test Results: [https://github.com/liquibase/liquibase/pull/2269/checks](https://github.com/liquibase/liquibase/pull/2269/checks)
* Steps to Reproduce: [https://github.com/liquibase/liquibase/issues/2109](https://github.com/liquibase/liquibase/issues/2109)
* Guidance:
* Impact: correctly converts the old style pattern into the new version before passing it along to the normal CLI logic. The rest of the code sees it as `liquibase tag-exists --tag mytag`
Ran `liquibase tagExists myTag` against an h2 database and got "The tag 'myTag' does NOT exist in '@jdbc:h2:mem:liquibase'" as expected.
**Setup**
Execute an update command with attached changelog file …
=> Correctly handle old "liquibase tagExists myTag" style CLI structure

liquibase-core/src/main/java/liquibase/datatype/core/DoubleType.java
Pass along parsed "additional information" information to the final datatype for doubles in mysql/mariadb.
Fixes #2169 which hit the problem with "unsigned"
- - -
* Fixed Issue: [https://github.com/liquibase/liquibase/issues/2169](https://github.com/liquibase/liquibase/issues/2169)
* Test Results: [https://github.com/liquibase/liquibase/pull/2293/checks](https://github.com/liquibase/liquibase/pull/2293/checks)
* Steps to Reproduce: [{LINK TO ISSUE OR "See above"}](https://github.com/liquibase/liquibase/issues/2169)
* Guidance:
* Impact: only impacts parsing of double type for mysql/mariadb in existing changelogs
Tested that changeset
```java
<changeSet author="myUser" id="myId1">
<createTable tableName="double_test">
<column name="ID" type="CHAR(36)">
<constraints primaryKey="true"/> …
```
=> Mysql: Support additional information "double" datatypes

liquibase-core/src/main/java/liquibase/diff/output/changelog/core/ChangedColumnChangeGenerator.java, liquibase-core/src/main/java/liquibase/parser/core/xml/XMLChangeLogSAXParser.java
In 4.6.2, changesets generated due to differences in column remarks would not include the columnDataType attribute which is needed for some databases (mysql for sure).
This change adds the datatype to the generated Change if it is available.
If you create two tables on different databases with different comments like this:
```java
create table intuser_db.test_table (id int, name int COMMENT 'table 1');
create table intuser_db2.test_table (id int, name int  COMMENT 'table 2');
```
then run `liquibase diff-changelog` between the intuser_db and intuser_db2 databases, the generated changeset used to look like this:
```java
<changeSet author="nathan (generated)" id="1640195447990-1">
<setColumnRemarks columnName="name" remarks="table 2" tableName="test_table"/>
</changeSet>
```
without the …
=> Include columnDataType in generated setColumnRemarks changesets

liquibase-core/src/main/java/liquibase/changelog/visitor/RollbackVisitor.java, liquibase-core/src/main/java/liquibase/changelog/visitor/UpdateVisitor.java
Liquibase Version: 4.4.0
Liquibase Integration & Version: CLI
When use rollback command cli, i see in terminal this log:
```
Rollback to version R1.0
Liquibase Community 3.10.1 by Datical
Rolling Back Changeset:R1.0...
Rolling Back Changeset:R1.0...
Rolling Back Changeset:R1.0...
Rolling Back Changeset:R1.0...
Rolling Back Changeset:R1.0...
Liquibase: Rollback has been successful.
```
But when use update, i see only:
```
Liquibase Community 3.10.1 by Datical
Liquibase: Update has been successful.
```
PS.. use 4.4.0 version have same result:
Rollback to version R1.0
Liquibase Community 4.4.0 by Datical
####################################################
####################################################
Starting Liquibase at 19:47:49 (version 4.4.0 #11 built at 2021-06-09 16:36+0000) …
=> Output changeset execution to UI like rollback does

liquibase-core/src/main/java/liquibase/sqlgenerator/core/AddAutoIncrementGenerator.java, liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateProcedureGenerator.java, liquibase-core/src/main/java/liquibase/sqlgenerator/core/DropProcedureGenerator.java, liquibase-core/src/main/java/liquibase/sqlgenerator/core/ModifyDataTypeGenerator.java, liquibase-core/src/main/java/liquibase/sqlgenerator/core/RenameSequenceGenerator.java
**Liquibase Version**: 4.6.2
**Liquibase Extension(s) & Version**:  na
**Database Vendor & Version**: db2z 11, sqlite 3.34.0
**Operating System Type & Version**: windows 10
Some Liquibase community change types didn't throw validation errors previously ('not supported' exception) though Liquibase doesn't support them according to documentation. The list of databases and changetypes for which validation errors were added:
SQLite (createProcedure, dropProcedure, renameSequence);
DB2z (modifyDataType, addAutoIncrement)
Run update command against upper named databases/change types;
Different SQL syntax errors are thrown (liquibase tries to generate and execute queries that cause syntax errors)
Validation error (e.g. createProcedure is not allowed for …
=> [DAT-8906] Added validation errors for SQLite and DB2z databases

liquibase-core/src/main/java/liquibase/change/core/DropColumnChange.java, liquibase-core/src/main/java/liquibase/sqlgenerator/core/DropColumnGenerator.java
**Liquibase Version**: 4.3.0++
**Liquibase Extension(s) & Version**: na
**Database Vendor & Version**: DB2 on z/OS 11+
**Operating System Type & Version**: any
Starting from version 11 of DB2 on z/OS it is possible to commit statement for dropping a column:
https://www.ibm.com/docs/en/db2-for-zos/11?topic=statements-alter-table
Though a column wouldn't be dropped right after commit it is placed into REORG state and might be dropped later.
This PR is created to add a possibility to to commit such statement.
=> [DAT-8744] Drop column sql generator fix for db2z

liquibase-core/src/main/java/liquibase/lockservice/StandardLockService.java, liquibase-core/src/main/java/liquibase/ui/ConsoleUIService.java
Fixes #2309
Caused by the "are we locked?" loop we added to catch race conditions in clusters, since in "update sql" mode the table doesn't get created like it normally would.
When looking at the output SQL, I also saw that the lock table got unlocked and re-locked due to the HubService.register() logic thinking it can prompt when it really can't and so unnecessarily unlocking.
- - -
* Fixed Issue: [https://github.com/liquibase/liquibase/issues/2309](https://github.com/liquibase/liquibase/issues/2309)
* Test Results: [https://github.com/liquibase/liquibase/pull/2335/checks](https://github.com/liquibase/liquibase/pull/2335/checks)
* Steps to Reproduce: [https://github.com/liquibase/liquibase/issues/2309](https://github.com/liquibase/liquibase/issues/2309)
* Guidance:
* Impact: 
* Only …
=> Remove duplicate databasechangeloglock SQL when running update-sql against a new database

liquibase-core/src/main/java/liquibase/snapshot/jvm/UniqueConstraintSnapshotGenerator.java
**Liquibase Version**: 4.5.0
The query that is generated when retrieving all keys (ORACLE DB) does not get a table name, while the code that creates the map for  the cache gets this name from the query result, which is always null. When reading the cache, the table name is used which  results in the cache always returning an empty result.
List the steps to reproduce …
=> UniqueConstraintSnapshotGenerator - Add table name to OracleDB query

liquibase-core/src/main/javacc/liquibase/util/grammar/SimpleSqlGrammar.jj
Numero sign in Russian it's a regular symbol ([https://en.wikipedia.org/wiki/Numero_sign)](https://en.wikipedia.org/wiki/Numero_sign)). Problem was described here [https://liquibase.jira.com/browse/CORE-3326](https://liquibase.jira.com/browse/CORE-3326) and actual for lb 4.0 version
- - -
title: 'CORE-3326 Numero sign is a symbol in Russian'
assignees: ''
- - -
**Liquibase Version**: 4.0 and earlier
**Liquibase Extension(s) & Version**: any
**Database Vendor & Version**: any
**Operating System Type & Version**: any
* \[ ] Enhancement/New feature …
=> CORE-3326 Numero sign is a symbol in Russian

liquibase-core/src/main/java/liquibase/change/core/ExecuteShellCommandChange.java, liquibase-core/src/main/java/liquibase/changelog/ChangeLogIterator.java, liquibase-core/src/main/java/liquibase/changelog/ChangeSet.java, liquibase-core/src/main/resources/liquibase/examples/sql/liquibase.sqlcmd.conf, liquibase-core/src/main/resources/liquibase/examples/sql/liquibase.sqlplus.conf, liquibase-core/src/main/resources/liquibase/examples/xml/liquibase.sqlcmd.conf, liquibase-core/src/main/resources/liquibase/examples/xml/liquibase.sqlplus.conf, liquibase-extension-examples/src/main/resources/META-INF/services/liquibase.executor.Executor
=> Allow a custom executor to be specified through a property on existing Executor implementations DAT-7531

liquibase-core/src/main/java/liquibase/resource/ClassLoaderResourceAccessor.java, liquibase-core/src/test/groovy/liquibase/resource/ClassLoaderResourceAccessorTest.groovy
The ClassLoaderResourceAccessor opens resources but has no method for closing them. Add a close() method to clean it up as part of the AutoClosabable interface
- - -
* Fixed Issue: Stand alone PR
* Test Results: https://github.com/liquibase/liquibase/pull/2308/checks
* Steps to Reproduce: None
* Guidance:
* Impact: This adds a close method which our code does not use. 3rd party integrations would be able to take advantage of it, however.
Reviewed code
┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-2205) by [Unito](https://www.unito.io)
=> Make ClassLoaderResourceAccessor implement Closable

liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy
Throwing a `ComparisonFailure` exception is treated differently by Intellij Idea. Idea will include a button to show the diff between the expected and actual in the console output for the failed test, which is very convenient.
=> improve console output of failing CommandTests (DAT-9038)

liquibase-core/src/main/java/liquibase/sqlgenerator/core/RenameSequenceGenerator.java, liquibase-core/src/test/java/liquibase/verify/saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets/renameSequence/mssql.sql
Microsoft SQL Server uses the `sp_rename` function to rename sequences, and [it is spelled using lowercase letters](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-rename-transact-sql?view=sql-server-ver15). SQL Server will permit it to be spelled with uppercase letters so long as the database collation is case-insensitive. For case sensitive collations, using uppercase letters will result in an error.
=> use lowercase sp_rename function in MSSQL (LB-1763)

liquibase-core/src/main/resources/liquibase/examples/sql/example-changelog.sql
**Liquibase Version**: 4.7.0 but any
**Liquibase Integration & Version**: NA
**Database Vendor & Version**: H2
**Operating System Type & Version**: Any
When running the examples with the example-changelog.sql you cannot rollback your changes.\
This enhancement allows you to see the example scripts you would use to rollback your changes and allows you to use the rollback commands with this changelog.  Also helps the init project
Use the example example-changelog.sql in the examples/sql directory of liquibase binary install
Run `liquibase --changeLogFile=examples/sql/example-changelog.sql update`\
Run `liquibase rollbackCount 3` or any other rollback command.\
Error occurs
```
Rolling Back Changeset:example-changelog.sql::3::other.dev
Unexpected …
```
=> Added example rollback scripts

liquibase-dist/src/main/archive/lib/liquibase_autocomplete_mac.bash
**Liquibase Version**: 4.6.1 and above.
**Database Vendor & Version**: Any
**Operating System Type & Version**: MacOS (Bash)
Added auto-complete "checks" commands to the liquibase-dist/src/main/archive/lib/liquibase_autocomplete_mac.bash auto-complete scripts.
---
- Fixed Issue: Stand alone PR
- Test Results: https://github.com/liquibase/liquibase/pull/2273/checks
- Steps to Reproduce: See above
- Guidance:
- Impact: Only impacts mac autocomplete. Not linux (#2272 )
Reviewed code
**Manual Tests**
* Verify auto-complete for the Quality Checks commands using a Mac terminal. 
* 'checks run' 
* 'checks delete --check-name=<check_short_name>' 
* 'checks bulk-set' 
* 'checks show' 
* 'checks customize --check-name=<check_short_name>' 
* 'checks reset …
=> Added new Quality Checks command and subcommands (Mac specifict)

liquibase-core/pom.xml
Previously, we were renaming all org.apache.* packages, which broke any org.apache.* classes we reference but DON'T package, like Ant and Derby support.
Instead, just relocate the ones we shade into the artifact as internal dependencies.
Fixes #2391
Fixes #2388
- - -
* Fixed Issue: 
* https://github.com/liquibase/liquibase/issues/2391
* https://github.com/liquibase/liquibase/issues/2388
* Test Results: https://github.com/liquibase/liquibase/pull/2429/checks
* Steps to Reproduce: https://github.com/liquibase/liquibase/issues/2391
* Guidance:
* Impact: limits what class names get replaced with a "repackaged" package
Ran test from #2391 after limiting change
Ensured there are no unshaded non-liquibase package names in the final jar file
┆Issue is synchronized with this [Jira …
=> Don't repackage all org.apache.* classes.

liquibase-cdi/src/main/java/liquibase/integration/cdi/CDILiquibase.java, liquibase-cdi/src/test/java/liquibase/integration/cdi/CDILiquibaseTest.java
Alternative to #2355 that fixes #2354
Rather than logging the exceptions only within changeset iterator, better catch all exceptions and log them withing CDILiquibase.
- - -
* Fixed Issue: https://github.com/liquibase/liquibase/issues/2354
* Test Results: https://github.com/liquibase/liquibase/pull/2397/checks
* Steps to Reproduce: Have failing changelog in an CDI environment
* Guidance:
* Impact: Only impacts CDI
Don't have a CDI environment to test in, but code is straightforward and issue author closed #2355 in favor of this fix.
┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-2223) by [Unito](https://www.unito.io)
=> Log exceptions in CDILiquibase before rethrowing them

.github/util/ManifestReversion.java, .github/util/re-version.sh
The in-development code always builds as version "0.0.0" and as part of the release process we replace the metadata that stores that placeholder version with the correct version. There are several places where that needs to be updated, including a Bundle-Version flag in META-INF/MANIFEST.MF, and that version was not updated correctly.
This fixes the logic for that, and also adds a check to the re-version.sh script to grep for 0-SNAPSHOT and 0.0.0.SNAPSHOT strings to catch any other problem spots that might get lost.
Fixes #2361
=> Correctly set Bundle-Version in META-INF on release

liquibase-core/src/main/java/liquibase/parser/ChangeLogParser.java, liquibase-core/src/test/groovy/liquibase/parser/core/xml/XMLChangeLogSAXParserTest.groovy
It is not valid to have a file:// URL with only two forward slashes. It is valid to have either 1 or 3 forward slashes. See https://en.wikipedia.org/wiki/File_URI_scheme
=> Fix XML parsing test on Windows

liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
**Liquibase Version**: 4.5.0
[x] Bug fix (fixes #2121)
When trying to read properties files from the class path, `file.getAbsolutePath()` is used. The result is some absolute path which won't exist in the classpath on most systems.
See the description in issue #2121
- - -
* Fixed Issue: https://github.com/liquibase/liquibase/issues/2121
* Test Results: https://github.com/liquibase/liquibase/pull/2122/checks
* Steps to Reproduce: The steps in #2121 only worked when calling the old liquibase.integration.commandline.Main class directly and not using the new LiquibaseCommandLine class. So to reproduce you'll have to tweak the liquibase.bat script to use the old classname instead.
* Guidance:
* Impact: Does not impact people using the new …
=> Use path instead of absolutePath for resources

.github/workflows/snyk.yml
Fix for the {{OfflineChangeLogHistoryService}}
* populate tag to the changelog.
[https://github.com/liquibase/liquibase/issues/2219|https://github.com/liquibase/liquibase/issues/2219]
<\!--- This environment context section helps us quickly review your PR. 
Please take a minute to fill-out this information. -->
h2. Environment
*Liquibase Version*:
4.6.1 (but also affecting previous versions)
*Liquibase Integration & Version*: 
CLI & Java API
*Database Vendor & Version*:
MS SQL Server (but also affecting others)
*Operating System Type & Version*:
Ubuntu Linux (but also affecting others)
h2. Pull Request Type
<\!--- What types of changes does your code introduce?
Put an {{x}} in all the boxes that apply: 
If this PR fixes an existing GH issue, edit the next line to add "closes #XXXX" to …
=> Add offline mode support for rollbackSQL <tag>

liquibase-core/src/main/java/liquibase/sqlgenerator/core/AlterSequenceGenerator.java, liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateSequenceGenerator.java
SqlServer does not support an ordered/unordered clause in sequences and so Liquibase should throw a validation error if the user attempts to specify it in either createSequence or alterSequence.
https://docs.microsoft.com/en-us/sql/t-sql/statements/create-sequence-transact-sql?view=sql-server-ver15
Fixes #2528
=> MSSQL: Throw validation error if "ordered" is specified in createSequence/alterSequence

liquibase-dist/src/main/archive/lib/liquibase_autocomplete.sh
Liquibase Version: 4.6.1 and above.
Liquibase Integration & Version: CLI
Database Vendor & Version: Any
Operating System Type & Version: Unix/Linux (Bash)
Added auto-complete "checks" commands to the liquibase-dist/src/main/archive/lib/liquibase_autocomplete.sh auto-complete scripts.
- - -
* Fixed Issue: Stand alone PR
* Test Results: https://github.com/liquibase/liquibase/pull/2272/checks
* Steps to Reproduce: See above
* Guidance:
* Impact: Only impacts linux, not macos (#2273)
Reviewed code
┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-2224) by [Unito](https://www.unito.io)
=> Added Quality Checks commands and subcommands

.github/workflows/release-extensions.yml
**Liquibase Version**:v.4.8.0
**Liquibase Integration & Version**: NA
**Database Vendor & Version**: All
**Operating System Type & Version**:NA
Changed gh-action for v6. 
Breaking change with rest api from v4 to v6 in github-script actions.
https://github.com/actions/github-script#breaking-changes-in-v5
Run Release version action with out this change.
Error createDispatchEvent 
```
TypeError: Cannot read properties of undefined (reading 'createDispatchEvent')
Error: Unhandled error: TypeError: Cannot read properties of undefined (reading 'createDispatchEvent')
at eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:4797:16), <anonymous>:5:20)
at callAsyncFunction …
```
=> Fix release-extensions.yml action to use github.rest, like the upgraded github-script v6 requires

liquibase-core/src/main/java/liquibase/diff/DiffGeneratorFactory.java
check if referenceDatabase not null instead of referenceSnapshot.
---
- Stand alone PR
- Test Results: https://github.com/liquibase/liquibase/pull/2330/checks
- Steps to Reproduce: Not sure. The fix obviously avoids a nulls a null pointer which could happen, but I'm not sure how to set up something naturally happening in liquibase to trigger it. Not sure what could lead to a null value, but if anything does it will handle it better now. Probably needs no additional manual testing?
- Guidance:
- Impact: Stops potential null pointer
Reviewed code.
=> Correctly catch potentially null value

liquibase-core/src/main/java/liquibase/database/core/CockroachDatabase.java, liquibase-core/src/main/java/liquibase/database/core/PostgresDatabase.java
Rather than making a likely invalid SQL call to `select version()` regardless of the connection to determine if it's a cockroachdb database, first check that the URL looks like a cockroachdb database before checking whether it is or not.
Checking for both `jdbc:postgres:` and `postgres:` without the `:` to also support `jdbc:postgresql:` and `postgresql:` based on https://www.cockroachlabs.com/docs/stable/connection-parameters.html#connect-using-a-url
Fixes #2483
=> CockroachDatabase: Limit calls to version()

liquibase-core/src/main/java/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParser.java
Currently the FormattedSqlChangeLogParser's `supports()` method is hard-coded to only support files that end in `.sql`. This makes it difficult for extensions to subclass to leverage the logic in FormattedSqlChangeLogParser but use a different extension. In this case, to have use formatted *.cypher files for neo4j
=> Make FormattedSqlChangeLogParser reusable

liquibase-core/src/main/java/liquibase/util/StringUtil.java, liquibase-core/src/test/groovy/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParserTest.groovy
**Liquibase Version**: Latest (4.5.1?)
**Liquibase Integration & Version**: core
Fixes #2133 while preserving (and testing) CORE-2971.
It's a tad less aggressive regarding end delimiters.
All steps are clearly listed in the Github issue.
- - -
* Fixed Issue: https://github.com/liquibase/liquibase/issues/2133
* Test Results: https://github.com/liquibase/liquibase/pull/2135/checks
* Steps to Reproduce: https://github.com/liquibase/liquibase/issues/2133 while not impacting https://liquibase.jira.com/browse/CORE-2971
* Guidance:
* Impact: changes the handling of delimiters in parsed sql, whether it is in formatted sql or a sql/sqlFile tag
Reviewed code and verified that automated tests now check the described problem
┆Issue is synchronized with this [Jira …
=> Fix #2133 and preserve CORE-2971 (Liquibase endDelimiter does not work after upgrading from 3.10.x to 4.x)

.github/workflows/build-test-report.yml
Added https://github.com/dorny/test-reporter as an extra step in the build process. 
We are wanting to more easily see:
- All tests that ran
- Any tests that failed
- Output from failed tests
which this seems to provide. 
I also looked at:
- https://github.com/marketplace/actions/publish-unit-test-results
- https://github.com/marketplace/actions/junit-report-action
But they didn't seem to meet our needs as well.
=> Added test-reporter action

.github/util/ManifestReversion.java
Adds missing `"` into the search/replace logic that gets run at release to correctly version the MANIFEST.MF files.
The Import-Package was replacing `version="..."` with `version="...`.
I didn't see any other spots where we weren't missing characters in the replacement.
It's hard to see the result in automation, since that only happens when we start the release process, but running it locally with this change to make a "4.8.0" version, the MANIFEST.MF file looks like this:
```
Manifest-Version: 1.0
Bundle-License: http://www.apache.org/licenses/LICENSE-2.0
Bundle-SymbolicName: org.liquibase.core
Build-Number: 1581
Archiver-Version: Plexus Archiver
Built-By: runner
Liquibase-Version: 4.8.0
Bnd-LastModified: 1645220686772
Bundle-ManifestVersion: 2
Bundle-DocURL: http://www.liquibase.org …
```
=> Fix quoting for MANIFEST.MF Import-Package

liquibase-core/src/main/java/liquibase/datatype/core/DoubleType.java, liquibase-core/src/test/groovy/liquibase/datatype/core/DoubleTypeTest.groovy
Added handling for "double precision" which is a distinct type in mysql vs. just "double" https://dev.mysql.com/doc/refman/8.0/en/numeric-type-syntax.html
Fixes #2337
=> Support "double precision" type in mysql

liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java, liquibase-core/src/main/java/liquibase/GlobalConfiguration.java, liquibase-core/src/main/java/liquibase/command/AbstractCliWrapperCommandStep.java, liquibase-core/src/main/java/liquibase/command/AbstractDatabaseCommandStep.java, liquibase-core/src/main/java/liquibase/command/CommandResultsBuilder.java, liquibase-core/src/main/java/liquibase/command/CommandScope.java, liquibase-core/src/main/java/liquibase/command/core/SnapshotCommandStep.java, liquibase-core/src/main/java/liquibase/integration/commandline/Main.java, liquibase-core/src/main/java/liquibase/resource/CompositeResourceAccessor.java, liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy, liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/snapshot.test.groovy
=> Make SnapshotCommandStep use the code from InternalSnapshotCommand directly  DAT-9624

.github/workflows/build.yml
The sonar integration does not support pull_request_target and considers them as being ran against master, which is not right.
This explicitly sets the needed settings for sonar
=> Fix pull request reporting information collected by Sonar

liquibase-core/src/main/java/liquibase/logging/core/JavaLogService.java, liquibase-core/src/test/groovy/liquibase/logging/core/JavaLogServiceTest.groovy
The Class.getPackage() method can return null, especially in non-java JVM languages like clojure.
Updates the JavaLogService to use the class name as the log name if the passed class object returns a null package.
Fixes #2633
=> Correctly handle null class package names in the logging system

liquibase-core/src/main/java/liquibase/database/core/EnterpriseDBDatabase.java, liquibase-core/src/test/groovy/liquibase/database/core/EnterpriseDBDatabaseTest.groovy
The result of `version()` for EDB doesn't have "EnterpriseDB" at the beginning of the string, but can by anywhere in it.
This fixes the check to better handle different cases.
Fixes DAT-9954
Test Harness tests: https://github.com/liquibase/liquibase-test-harness/pull/209/
=> Fix EnterpriseDB database recognition

changelog.txt, liquibase-core/src/test/groovy/liquibase/configuration/core/MapConfigurationValueProviderTest.groovy
Updated ordering of storedKey and wantedKey so String.equalsIgnoreCase won't be called on a null value if passed to AbstractMapConfigurationValueProvider
Updated keyMatches in CommandLineArgumentValueProvider to ensure that the store key is a string value before calling .replace won't be called on a null value
**Liquibase Version**: 4.8.0
**Liquibase Integration & Version**: Maven
**Database Vendor & Version**:hsqldb
**Operating System Type & Version**:macOS Monterey 12.2.1
When a system has a null or empty string key for an env var it causes liquibase fail the …
=> Fix start failure with Nullpointed exception when Environment contains empty string Key (fix Issue 2631)

liquibase-core/src/main/java/liquibase/change/core/CreateTableChange.java, liquibase-core/src/main/java/liquibase/statement/core/CreateTableStatement.java
Mysql losses primary key and other information if we do a `alter column modify .... remarks` statement. 
So ensure that the initial "create" includes all the remarks and do not attempt to modify them after the fact.
Fixes #2301
Fixes #2634
Fixes #1793
Fixes #1214
Fixes #1210
Test-harness PR: https://github.com/liquibase/liquibase-test-harness/pull/211
- Impacts SQL for mysql and mariadb only
- Nothing
=> Fix createTable on Mysql not preserving primary key information when remarks also defined on the column

liquibase-core/src/main/java/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParser.java, liquibase-core/src/test/groovy/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParserTest.groovy, liquibase-integration-tests/src/test/groovy/liquibase/diffchangelog/DiffChangelogTest.groovy
=> Validate formatted SQL changelog for invalid patterns DAT-7721

liquibase-dist/pom.xml, liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/core/MSSQLTestSystem.java, pom.xml
Upgraded SqlServer jdbc driver to the newest major version
The driver changed the encryption default from "false" to "true" between the old 8.x and the new 10.x driver. That means that anyone who has a self-signed certificate in their database will need to add either `encrypt=false` OR `trustServerCertificate=true` OR add the server certificate to their java trusted certificate list.
=> Upgraded mssql driver to 10.2.0

pom.xml
Upgrade hsqldb to the latest Java 8 compatible version
=> Bump hsqldb from 2.4.0 to 2.5.2

liquibase-core/src/main/java/liquibase/license/LicenseService.java
**Liquibase Integration & Version**: N/A
Add `getExpirationDate` method to `LicenseService`.
N/A
N/A
N/A
=> add getExpirationDate method to LicenseService (DAT-10141)

liquibase-core/src/main/java/liquibase/datatype/DataTypeFactory.java, liquibase-core/src/test/groovy/liquibase/datatype/DataTypeFactoryTest.groovy
If a user specifies something that looks like a changelog parameter but doesn't match a specified parameter, liquibase simply users it as-is. 
However, the DataType.fromDescription function that is used to determine the actual datatype to return cannot correctly handle a datatype that is formatted like a changelog parameter.
This fixes the datatype handling so it handles a datatype that looks like `${ ... }` as just a datatype it doesn't understand.
```
<createTable tableName="test_table">
<column name="id" type="${invalid}"/>
</createTable>
```
Throws an `ArrayIndexOutOfBoundsException` exception
Fails with an error like `Syntax error in SQL statement "CREATE TABLE test_table (id ${INVALID }` which allows the user to recognize that they did not correctly set the changelog parameter
=> Do not throw a confusing error if a datatype specified as a changelog parameter is not expanded

liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java, liquibase-cli/src/test/groovy/liquibase/integration/commandline/LiquibaseCommandLineTest.groovy, liquibase-core/src/main/java/liquibase/integration/commandline/Main.java, liquibase-core/src/main/java/liquibase/logging/core/DefaultLogMessageFilter.java, liquibase-core/src/test/java/liquibase/integration/commandline/MainTest.java
**Liquibase Version**: 4.8.0
**Liquibase Extension(s) & Version**: none
**Database Vendor & Version**: I don't think it matters, but I tested with Postgres 12
**Operating System Type & Version**: all (I tested on Fedora35)
Fixes #1858
- Create a changelog.xml that uses a custom task (that implements `liquibase.change.custom.CustomTaskChange`).
- In the custom task, override the getConfirmationMessage method to return null:
```
@Override
public String getConfirmationMessage() {
return null;
}
```
- Run the 'update' command from the CLI, using either the `liquibase.integration.commandline.Main` or `liquibase.integration.commandline.LiquibaseCommandLine`, and setting the `--log-level=` argument (it's value …
=> Fixed NullPointerException in SecureLogFilter.isLoggable

liquibase-dist/pom.xml, liquibase-dist/src/main/assembly/assembly-bin.xml, liquibase-dist/src/main/maven/release.pom.xml, liquibase-maven-plugin/pom.xml, pom.xml
Updated shipped jaxb libraries. To continue to support libraries we use which expect `javax.xml` vs. `jakarta.xml` packages we had to stay on 2.3.x vs. upgrading to 3.x
The new `jaxb-runtime-2.3.6.jar` file replaces the old `jaxb-impl-2.3.0.jar` file. 
The `jaxb-api` and `jaxb-core` jar files have the same base names, just different versions now.
=> Upgraded jaxb libraries to the newest 2.3.x versions

liquibase-core/src/main/java/liquibase/parser/core/xml/LiquibaseEntityResolver.java, liquibase-core/src/test/groovy/liquibase/parser/core/xml/LiquibaseEntityResolverTest.groovy
There is an issue in the XSD lookup logic, where it always pulls the XSD file over the network if the primary ResourceAccessor fails to find it and the "fallback" one does.
When we'd get to the fallback code, the `&& SECURE_PARSING)` would be false and make the `if` block fail regardless of whether it found resources or not.
The standard Liquibase integrations (CLI, Maven, etc.) set up the primary resource accessor so we never hit the problem code path, but custom setups could. The integration tests, for example, did hit the problem code.
=> Fixed local XSD lookup

liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/spock/LiquibaseGlobalExtension.java, liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/spock/LiquibaseIntegrationMethodInterceptor.java, liquibase-extension-testing/src/main/resources/META-INF/services/org.spockframework.runtime.extension.IGlobalExtension
**Liquibase Integration & Version**: integration test framework
The existing integration test framework was configured to stop TestSystem's when the `cleanup:` method was called. Spock internally called this method when it finished executing all of the tests in a class. Thus, when a particular test class was completed, its TestSystem was stopped, which in some cases was premature, since other classes might use the same TestSystem.
Instead, the TestSystem's should be stopped when Spock finishes executing all of the tests in all classes.
Create two test classes, both which use the same TestSystem. Run both (through maven, or through Intellij in the …
=> stop database containers when spock execution ends

liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/spock/LiquibaseGlobalExtension.java, liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/spock/LiquibaseIntegrationMethodInterceptor.java, liquibase-extension-testing/src/main/resources/META-INF/services/org.spockframework.runtime.extension.IGlobalExtension
The existing integration test framework was configured to stop TestSystem's when the cleanup: method was called. Spock internally called this method when it finished executing all of the tests in a class. Thus, when a particular test class was completed, its TestSystem was stopped, which in some cases was premature, since other classes might use the same TestSystem.
Instead, the TestSystem's should be stopped when Spock finishes executing all of the tests in all classes.
(cherry picked from commit d2bea1a72c921e343fc9ea376e70bb6f0ac5d0aa)
A clear and concise …
=> stop database containers when spock execution ends (#2843)

liquibase-core/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGenerator.java, liquibase-core/src/test/groovy/liquibase/snapshot/jvm/ColumnSnapshotGeneratorTest.groovy
The current code recognizes `0::real` in postgresql, but not `(0)::real`. Updated the regexp to handle both
Fixes #2833 
- Only impacts handling of default values and only in postgresql
- Nothing
=> Support default values in the format `(0)::real`

liquibase-core/src/main/java/liquibase/database/core/PostgresDatabase.java
When we first connect to postgresql, we call `SET SEARCH_PATH=...` to ensure the defaultSchemaName is first in the list.
However, when we roll back the connection (which we do throughout a liquibase run to ensure we have a clean connection) the search path on the connection gets rolled back to the initial value.
This PR restores the the reset of SEARCH_PATH in the rollback operation for postgreql
- Fixes #2234 
- Fixes #2640
=> Fix handling of defaultSchemaName on Postgresql

liquibase-core/src/main/java/liquibase/util/TableOutput.java, liquibase-core/src/test/groovy/liquibase/util/TableOutputTest.groovy, liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy
**Liquibase Integration & Version**: N/A
- Change array to list in `TableOutput` method
- Add option to ignore whitespace in CommandTests "contains" comparison
=> minor refactorings to CommandTests and TableOutput (DAT-9989)

liquibase-core/src/main/java/liquibase/integration/spring/SpringResourceAccessor.java
Subclasses of [FilteredReactiveWebContextResource ](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/web/reactive/context/FilteredReactiveWebContextResource.java) and potentially others, make `exists() always returns false in order to avoid exposing the whole classpath in a non-servlet environment.` which impacts Liquibase's logic in figuring out relative paths.
The change to SpringResourceAccessor to rely on exists() was introduced in Liquibase 4.0, so this will fix some changelogs that worked in 3.x but not any versions.
Improves spring support as mentioned in #2281 for at least some configurations. 
file:/...../target/classes/liquibase/init/test.xml
```
<?xml version="1.0" encoding="UTF-8"?> …
```
=> Spring Boot: better support relativeToChangelogfile when ResourceLoaders return FilteredReactiveWebContextResources

liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java, liquibase-core/src/main/java/liquibase/integration/commandline/LiquibaseCommandLineConfiguration.java
Marked as a breaking change because 3rd party (non-liquibase) logging will no longer be logged without also specifying the --log-channels flag.
While we can't control the log configuration in most environments liquibase runs in, we do control the log setup in the CLI. 
Liquibase does not log any sensitive information, but we have no control over what other libraries will log and want to make sure nothing unexpected gets logged in user environments. 
Therefore, when applying the "logLevel" setting in the CLI, we are switching to a whitelisting of channels to include. The whitelist defaults to only "liquibase", but it can be controlled via a new `liquibase.logChannel` setting. For example, `--log-channels=liquibase,com.microsoft.sqlserver.jdbc`. We also support `--log-channels=all`
This …
=> Added whitelist for CLI log channels to include

liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java, liquibase-core/src/main/java/liquibase/license/LicenseService.java
A user could specify their license key using the `LIQUIBASE_PRO_LICENSE_KEY` property in any provider (perhaps environment variable) and specify a second license key using the `LIQUIBASE_LICENSE_KEY` property in the defaults file. The defaults file value provider is not registered until after invoking the license service's license installation code, and the license service caches installed licenses so that it does not have to recheck for license keys. However, this means that in the above example, a license specified in the defaults file is not loaded because the license in the environment variable is …
=> prefer license specified in LIQUIBASE_LICENSE_KEY edge case (DAT-10409)

liquibase-core/src/main/java/liquibase/database/core/DerbyDatabase.java
Newer versions of derby use a new driver name, and the old driver is no longer available.
Fix for Derby getDefaultDriver() method to load appropriate driver classes based on db version. 
Fixes #1835
=> Add logic to Derby.getDefaultDriver() to check for availability of different driver classes

liquibase-core/src/main/java/liquibase/lockservice/StandardLockService.java
This pull request changes the modifiers of standard lock service to protected for the case where only certain parts of the lock service need to be rewritten. 
An example is this pr in the Keyspace extension.
https://github.com/liquibase/liquibase-amazon-keyspaces/pull/8
=> Change value modifier to make StandardLockService extendable for future extension

liquibase-dist/pom.xml, liquibase-dist/src/main/archive/licenses/README.txt, liquibase-dist/src/main/assembly/assembly-bin.xml
The jaybird.jar we ship requires access to `javax.resources` which comes with the connector-api.jar.
This adds that required dependency and updates the licenses file accordingly.
Running `liquibase update` against firebird with an out-of-the-box liquibase configuration fails with a "ClassNotFound" exception
Running `liquibase update` against firebird with an out-of-the-box liquibase configuration runs successfully
=> Added connector-api.jar to internal/lib

liquibase-core/src/main/java/liquibase/GlobalConfiguration.java, liquibase-core/src/main/java/liquibase/integration/commandline/CommandLineUtils.java, liquibase-core/src/test/groovy/liquibase/integration/commandline/CommandLineUtilsTest.groovy
Adds a new `liquibase.showBanner` setting that disables the Liquibase startup banner. The start time and version information are preserved because they are informational and small.
The default value for the setting is "true".
Fixes #2681
=> Add liquibase.showBanner global configuration setting

liquibase-core/src/main/java/liquibase/integration/spring/SpringResourceAccessor.java, liquibase-core/src/test/groovy/liquibase/integration/spring/SpringResourceAccessorTest.groovy
Ensure that SpringResourceAccessor uses classpath* protocol for loading resources if no other protocol is given.
- no protocol -> classpath*:
- classpath:  -> classpath*:
- classpath*: -> classpath*:
- file:       -> file:
4.2.0
maven
none
none
Windows 11
- [ x] Bug fix (non-breaking change which fixes an issue.)
As described in #1540 it is not possible to provide changelogs …
=> Not possible to provide changelogs from outside classpath 

liquibase-core/src/main/java/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParser.java, liquibase-core/src/main/java/liquibase/parser/core/sql/SqlChangeLogParser.java, liquibase-core/src/test/groovy/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParserTest.groovy
Currently Liquibase only considers files that end in a lowercase .sql as parse-able by either the raw or formatted parsers. 
This makes those parsers recognize sql files regardless of the case of the extension.
=> Make extension matching for SQL parsers case-insensitve DAT-10265

liquibase-core/src/main/java/liquibase/command/core/ChangelogSyncSqlCommandStep.java, liquibase-core/src/main/java/liquibase/command/core/ChangelogSyncToTagSqlCommandStep.java, liquibase-core/src/main/java/liquibase/command/core/FutureRollbackCountSqlCommandStep.java, liquibase-core/src/main/java/liquibase/command/core/FutureRollbackFromTagSqlCommandStep.java, liquibase-core/src/main/java/liquibase/command/core/FutureRollbackSqlCommandStep.java, liquibase-core/src/main/java/liquibase/command/core/RollbackCountSqlCommandStep.java, liquibase-core/src/main/java/liquibase/command/core/RollbackSqlCommandStep.java, liquibase-core/src/main/java/liquibase/command/core/RollbackToDateSqlCommandStep.java, liquibase-core/src/main/java/liquibase/command/core/UpdateCountSqlCommandStep.java, liquibase-core/src/main/java/liquibase/command/core/UpdateSqlCommandStep.java, liquibase-core/src/main/java/liquibase/command/core/UpdateToTagSqlCommandStep.java, liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/changelogSyncSql.test.groovy, liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/changelogSyncToTagSql.test.groovy, liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/futureRollbackCountSql.test.groovy, liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/futureRollbackFromTagSql.test.groovy, liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/futureRollbackSql.test.groovy, liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/rollbackCountSql.test.groovy, liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/rollbackSql.test.groovy, liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/rollbackToDateSql.test.groovy, liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/updateCountSql.test.groovy, liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/updateSql.test.groovy, liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/updateToTagSql.test.groovy
With the command framework refactoring in 4.4.0, the outputDefaultSchema and outputDefaultCatalog arguments were missed. Because of that, there is no way to change the behavior away from the default value (true).
The flag is re-added as a command-level argument, since it only really applies to *Sql commands and is therefore not a global argument.
- If true, any generated SQL will have objects in the default schema fully qualified with the default schema and/or default catalog as possible. 
- If false, any generated SQL will have objects in the default schema and/or default catalog left unqualified. Objects in non-default schema/catalog are always fully qualified.
This change ensures the flag is exposed and passed along, but does not attempt to change or test the behavior as it was in 4.3 …
=> Restored outputDefaultSchema and outputDefaultCatalog command arguments

liquibase-core/src/main/java/liquibase/database/core/Firebird3Database.java, liquibase-core/src/main/java/liquibase/database/core/FirebirdDatabase.java, liquibase-core/src/main/java/liquibase/datatype/core/BooleanType.java, liquibase-core/src/main/java/liquibase/sqlgenerator/core/SetNullableGenerator.java, liquibase-core/src/main/resources/META-INF/services/liquibase.database.Database, liquibase-integration-tests/src/test/java/liquibase/statementexecute/AddUniqueConstraintExecutorTest.java, liquibase-integration-tests/src/test/java/liquibase/statementexecute/MarkChangeSetRanExecuteTest.java, liquibase-integration-tests/src/test/java/liquibase/statementexecute/RenameColumnExecuteTest.java
Fix for working with Firebird 2 and newer versions. Fixes nullables and boolean type.
Current implementation does not handle correctly working on Firebird 2.5 and Firebird 3 databases. It always assumes a Firebird 3 database, which incurs in invalid SQL statements.
The proposed fix eliminates the Firebird3Database class and instead includes a "version2" attribute in the FirebirdDatabase class. This attribute is populated when the connection is set.
I've fixed the tests and impacted classes (BooleanType and SetNullableGenerator) for this implementation.
=> Fix for working with Firebird 2 and newer versions. Fixes nullables and boolean type.

liquibase-core/src/main/java/liquibase/changelog/ChangeSet.java, liquibase-core/src/test/groovy/liquibase/changelog/ChangeSetTest.groovy
This will throw null pointer if change changelog object is null. 
**Cannot invoke "liquibase.changelog.DatabaseChangeLog.isIncludeIgnore()" because "changeLog" is null.**
Environment Production
Liquibase Version: it started in 3.7.x onward.
**public boolean isInheritableIgnore() {
DatabaseChangeLog changeLog = this.getChangeLog();
return changeLog.isIncludeIgnore();
}
This method was added in 3.7.x** 
**Following is the change list 
commit 9ae2b572c79ff0273f1dfb2f867148e74dfebb98**
Liquibase Integration & Version: Spring boot
Liquibase Extension(s) & Version: it started in 3.7.x onward.
Database Vendor & Version: Oracle
Operating System Type & Version: Windows 10
Bug fix (non-breaking change which fixes an issue.)
https://forum.liquibase.org/t/null-pointer-exception-in-liquibase-core/6838 …
=> null pointer issue if change changelog object is null

liquibase-core/src/main/java/liquibase/parser/NamespaceDetails.java, liquibase-core/src/main/java/liquibase/parser/core/xml/StandardNamespaceDetails.java, liquibase-core/src/main/java/liquibase/parser/core/xml/XMLChangeLogSAXParser.java, liquibase-core/src/main/resources/liquibase/examples/xml/blank-changelog.xml, liquibase-core/src/main/resources/liquibase/examples/xml/example-changelog.xml, liquibase-core/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd, liquibase-core/src/test/groovy/liquibase/parser/core/xml/XMLChangeLogSAXParserTest.groovy
We ship a new xsd version with each non-patch release of liquibase, but while some people find that helpful others find it overly complex. Furthermore, examples and documentation gets difficult to keep up to date when references need to be constantly updated.
This PR would solve that problem by introducing a new `dbchangelog-latest.xsd` url so people can use:
```
<databaseChangeLog
xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns:pro="http://www.liquibase.org/xml/ns/pro"
xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd
http://www.liquibase.org/xml/ns/pro http://www.liquibase.org/xml/ns/pro/liquibase-pro-latest.xsd ">
```
as an XSD reference if …
=> Introduced "latest" xsd file path

liquibase-core/src/main/java/liquibase/statement/ExecutablePreparedStatementBase.java
On postgresql if you use setBinaryStream the field must be of type bytea but a blob type is oid (ref pull request #600).  Instead you must use setBlob method to be able to insert or update data with valueBlobFile
=> Use the method setBlob to insert blob data

liquibase-core/pom.xml, liquibase-dist/pom.xml, liquibase-dist/src/main/assembly/assembly-bin.xml, liquibase-dist/src/main/maven/release.pom.xml
Rather than shading opencsv into the liquibase-core.jar, define it as a dependency in the shipped pom.xml and include it as a separate jar in the internal/lib directory. 
Opencsv has dependencies on commons-collections4, commons-lang3, and commons-text so they are will be in the internal/lib directory as well.
Partly addresses #2852 but not fully so not marking it as "fixes"
- No liquibase/repackaged directory in liquibase-core.jar anymore
- commons-collections4.jar added to to internal/lib
- commons-lang3.jar added to to internal/lib
- commons-text.jar added to to internal/lib
- opencsv.jar added to internal/lib
- Nothing else new added to internal/lib
The CLI and maven plugin should continue to handle changelogs with loadData pointing to CSV files with no issues.
=> Move opencsv to be non-shaded

liquibase-core/src/main/java/liquibase/ui/ConsoleUIService.java
=> Working on better Git Bash console solution DAT-10230

liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java
Adds a maven-native setting for the new liquibase.showBanner flag. 
With the change, running `mvn -Dliquibase.showBanner=false ...` will hide the banner. 
- Only impacts maven
- Applies to all maven commands
- Can also be set with a `<showBanner>` configuration within the maven plugin.
-Nothing
=> Added showBanner configuration to maven

liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/spock/LiquibaseIntegrationMethodInterceptor.java
Reverts removal of `interceptCleanupSpecMethod` in `LiquibaseIntegrationMethodInterceptor`. Adds comment explaining use case. 
Without this change `def cleanupSpec(){}` is completely ignored in Spock tests.
This was removed in [this commit](https://github.com/liquibase/liquibase/commit/d2bea1a72c921e343fc9ea376e70bb6f0ac5d0aa). 
N/A
Tests should still pass.
=> DAT-10314 - Reverts removal of `interceptCleanupSpecMethod`

liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
Currently `--version` output lists `internal\lib\connector-api.jar: connector-api UNKNOWN` because the connector-api.jar only defines a "specification version". This updates the message creation to use the specification version if nothing else is available as a version.
Also adds a "By ..." for the vendor information if it is present. It gets verbose for some like `internal\lib\hsqldb.jar: HSQLDB 2.5.2 By The HSQL Development Group` but others like `internal\lib\ojdbc8.jar: JDBC 21.5.0.0.0 By Oracle Corporation` were not descriptive enough without it.
- Only impacts CLI `--version` call
- Nothing
=> Add additional info in CLI's --version output

liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java, liquibase-core/src/main/java/liquibase/command/CommandFailedException.java, liquibase-core/src/main/java/liquibase/command/CommandResultsBuilder.java
Stacktraces will not be printed to the logs when a CommandFailedException is set to "hidden".
`isHidden` is perhaps not the best name we can come up with.
=> hide CommandFailedException stacktrace when thrown to set exit code (DAT-9608)

README.md, liquibase-dist/pom.xml, liquibase-dist/src/main/archive/GETTING_STARTED.txt, liquibase-dist/src/main/archive/README.txt, liquibase-dist/src/main/archive/UNINSTALL.txt
Update the year of the Liquibase copyright in the packaged .txt files to be dynamically generated at build time, and update the links in the files to point to new locations.
I added a new maven plugin because I couldn't change the format of the `maven.build.timestamp.format` because that is already used elsewhere.
=> dynamically update copyright year in txt files; also update links in txt files (DAT-10261)

liquibase-core/pom.xml, liquibase-core/src/main/javacc/liquibase/util/grammar/SimpleSqlGrammar.jj, liquibase-core/src/test/groovy/liquibase/util/SqlParserTest.groovy, liquibase-core/src/test/groovy/liquibase/util/StringUtilTest.groovy, liquibase-core/src/test/groovy/liquibase/util/grammar/SimpleSqlGrammarTest.groovy, liquibase-extension-examples/pom.xml
The sql parser did not correctly handle a string with `\`s before a closing `'` when there were more `'`s in the line.
For example, this SQL failed to split on the `#`:
```
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
#
/*!40101 SET NAMES utf8 */;
#
/*!50503 SET NAMES utf8mb4 */;
#
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
#
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
#
CREATE PROCEDURE test_procedure (
in      p1      text
)
begin
if p1 != '\\' then
select current_timestamp;
end if;
end
#
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
#
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
#
/*!40101 SET …
```
=> Improved parsing of single-quoted strings

liquibase-core/src/main/java/liquibase/command/CommandScope.java, liquibase-core/src/main/java/liquibase/exception/CommandValidationException.java, liquibase-core/src/main/java/liquibase/util/CollectionUtil.java, liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy, liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/setup/SetupModifyDbCredentials.groovy
- add createIfNull(Map) method to CollectionUtil
- expose separate validate() method in CommandScope
- add constructor to CommandValidationException(Throwable)
=> general changes to support flow file validation (DAT-10588)

liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseChecksRunMojo.java
Add the `outputFile` argument to the `checks.run` maven plugin target.
=> DAT-10260: add outputFile argument in maven plugin for checks.run target

liquibase-core/src/main/java/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParser.java, liquibase-core/src/test/groovy/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParserTest.groovy
Updates first line check on FormattedSqlChangeLogParser to check for the string `--liquibase formatted` without checking case. Previously files with `--LIQUIBASE FORMATTED SQL` as the first line would be read as raw sql not formatted sql. 
Added a new pattern in the `supports` method of `FormattedSqlChangeLogParser` instead of just using `String#matches`. 
If someone did not notice an `ALL CAPS` file like in the test case was executed as raw sql (not formatted sql) this update will cause the file to be parsed differently which could lead to unexpected behavior.
N/A
=> Formatted SQL files with uppercase in the liquibase attributes (DAT-10531)

liquibase-core/src/main/java/liquibase/command/CommandScope.java, liquibase-core/src/main/java/liquibase/io/UnclosableOutputStream.java
This change prevents individual commands from closing the output stream they are provided, which is actually `System.out`. It is bad practice for code to close `System.out` particularly because other command steps will still expect it to be open.
In very unusual circumstances, we might get more output than we did initially, because commands called after the RegisterChangelogCommandStep previously had a closed output stream. This isn't really a worry, and more of a positive thing.
=> do not allow individual commands to close the top-level OutputStream (System.out)

liquibase-core/src/main/java/liquibase/util/StringUtil.java, liquibase-core/src/test/groovy/liquibase/util/SqlParserTest.groovy
This is a bit overzealous, and removes contents of multiline comments everywhere, including in places it might not be appropriate to do so (like inside of the SQL part of the changeset, where the comments should be handled based on the stripComments setting)
=> ignore contents of multiline comments when parsing formatted SQL files (DAT-10296)

liquibase-core/src/main/java/liquibase/changelog/ExpressionExpander.java, liquibase-core/src/test/groovy/liquibase/changelog/ExpressionExpanderTest.groovy
Changes in the 4.11.0 release around changelog parameter parsing made it so we weren't correctly handling a `}` characters that appear after a changelog expression.
So just having `{test}` worked. And `{test} ${test}` worked. But `${test} {test}` did not.
This updates the parser logic to correctly handle the failing case.
Fixes #2980
- Existing tests ensure the refactoring doesn't cause other regressions
- Added test case for this new example
- Any other character combinations that were broken in 4.11.0? I don't think so, the closing bracket is the one special case we handle.
=> Fixed issue with parameter expression parsing

liquibase-core/src/main/resources/liquibase/examples/sql/liquibase.psql.conf, liquibase-core/src/main/resources/liquibase/examples/xml/liquibase.psql.conf
Adds new liquibase.psql.conf example file in support of Liquibase Pro runWith psql feature.
N/A
N/A
N/A
=> Adds liquibase.psql.conf example (DAT-10303)

liquibase-core/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java, liquibase-integration-tests/src/test/groovy/liquibase/snapshot/JdbcDatabaseSnapshotTest.groovy, liquibase-snowflake/src/main/java/liquibase/database/core/SnowflakeDatabase.java
**Liquibase Version**: 4.11
**Database Vendor & Version**: all, fix needed for Snowflake
**Operating System Type & Version**: windows 10
https://datical.atlassian.net/browse/DAT-10093
JdbcDatabaseSnapshot doesn't escape percent and underscore characters in schema names for getColumns() calls like it does for getTables (and actually getViews). For Snowflake jdbc classes this cause to dropping schema name from requests completely what causes slow performance.
According to ticket description need to have Snowflake account with a number of schemas with number of tables and number of columns to clearly see Liquibase hangs for long time performing operations.
liquibase slow performance on Snowflake DB.
Performance increase.
Come chat with us in the [Liquibase …
=> [DAT-10093] added schema escaping to getColumns call to jdbc metadata classes

liquibase-core/src/main/java/liquibase/GlobalConfiguration.java, liquibase-core/src/main/java/liquibase/Liquibase.java, liquibase-core/src/main/java/liquibase/resource/AbstractResourceAccessor.java, liquibase-core/src/main/java/liquibase/resource/ResourceAccessor.java, liquibase-core/src/main/java/liquibase/statement/ExecutablePreparedStatementBase.java, liquibase-core/src/test/groovy/liquibase/resource/FileSystemResourceAccessorTest.groovy
Currently, when the same path is found in multiple locations liquibase fails with an error.
This PR adds a new `liquibase.duplicateFileMode` global setting which defaults to "ERROR" but can also be set to "WARN".
- Existing behavior of "ERROR" logic is still the default.
- Refactored some usages of openStreams that duplicated the logic in openStream to just use openStream in order to take advantage of this new behavior.
- Searched the code for usages of openStream vs. openStreams and addressed all I found that should be updated
- Nothing
=> Added new liquibase.duplicateFileMode setting

liquibase-core/src/main/java/liquibase/datatype/core/NumberType.java, liquibase-core/src/test/groovy/liquibase/datatype/core/NumberTypeTest.groovy
when input data type has char parameters in the data type (like NUMBER(*,0) in Oracle)
catch NumberFormatException
Steps:
1. Create a table with NUMBER(*,0) type column in Oracle schema.
```sql
CREATE TABLE TEST_ASTERISK (
COLUMN1 NUMBER(*,0)
);
```
1. Try to compare this Oracle schema with any PostgreSQL schema.
Actual result: catch NumberFormatException
Hello from DBeaver.
=> Use "numeric" (without parameters) data type in PostgreSQL

liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java, liquibase-core/src/main/java/liquibase/integration/commandline/Main.java, liquibase-core/src/main/java/liquibase/util/SystemUtil.java, liquibase-core/src/test/groovy/liquibase/util/SystemUtilTest.groovy, liquibase-snowflake/src/main/java/liquibase/database/core/SnowflakeDatabase.java
The snowflake jdbc driver 3.10+ uses reflection in their arrow support which doesn't work with JDK 17 due to the java.nio module not being marked as used by the snowflake driver.
Perhaps there is a better way of solving this through Liquibase getting configured with java module definitions? Or running under a "--add-opens=java.base/java.nio=ALL-UNNAMED" type setup, but I think that is going to have to be a longer investigation than I'd like to do right now.
So, this PR makes it so if the user is running under Java 17+, when we connect to the database we set the result set format to be JSON which avoids all the problem code in the jdbc driver. If that statement throws any errors, we log it and continue on in case it's not needed.  If they are under java 17, we let them continue to use …
=> Force "json" resultset formats in Snowflake when running Java 17+

liquibase-core/src/main/java/liquibase/diff/output/changelog/DiffToChangeLog.java
PR #2585 fixed our lack of serializing runInTransaction into changelogs, but the diff logic was incorrectly setting generated changesets as runInTransaction="false" which used to be ignored and therefore defaulted back to "true" but no longer is.
- This is fixing an unreleased bug
- In the current build from master, all changesets in a generateChangeLog will have `runInTransaction="false"`. With this fix, there will be no runInTransaction flag included in the changesets, like it is in 4.12.0
- Nothing
=> Keep runInTransaction="false" from being included in generated changelogs

liquibase-core/src/main/java/liquibase/Liquibase.java, liquibase-core/src/main/java/liquibase/parser/core/xml/LiquibaseEntityResolver.java, liquibase-core/src/main/java/liquibase/parser/core/xml/XMLChangeLogSAXParser.java, liquibase-core/src/test/groovy/liquibase/parser/core/xml/LiquibaseEntityResolverTest.groovy
Warn if specified XSD version is different than the version of the build when running the `validate` command.
I made this change in a way that this check is "best effort". It should not ever cause a user to experience an uncaught exception.
It is possible that the regex I'm using is not robust enough to properly get the version out of the XSD URL. It is also possible that there is a better way to do this than using a regex.
=> warn if XSD version does not match build version in validate command (DAT-9874)

liquibase-core/src/main/java/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParser.java, liquibase-core/src/test/groovy/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParserTest.groovy
A comment that has the word "property" in it anywhere like `-- I don't know what this property does` breaks formatted sql parsing with an `Formatted SQL changelogs require known formats, such as '--property name=<property name> value=<property value>' and others to be recognized and run.` error.
Fixes DAT-10720
- Only impacts how we parse for `--property` lines in formatted sql
- Existing tests look for correct forms, and they continue to pass
- Nothing
=> Fixed Formatted SQL "property" parsing

liquibase-core/src/main/java/liquibase/database/core/DatabaseUtils.java
In postgresql and it's varients (redshift, cockroachdb, etc), the search_path that gets set based on the defaultSchemaName uses the value returned from `show search_path`. Sometimes, objects such as `$user` in that shown search path are note quoted like is needed to re-set them. 
This PR updates the logic from handling only values that start with a `$` and only on cockroachdb to handling all non-quoted values on all postgresql versions. 
The change handles cases where a value comes back already quoted from `show search_path`. 
For example, if defaultSchemaName is being set to `test`,  it will `set search_path=test, "$user", "public"` whether the original `show seach_path` returned `"$user", public` or `$user, public`.
By quoting `"public"` like that, it will enforce the case on public, …
=> Ensure Postgresql search_path entries are quoted correctly

liquibase-core/src/main/java/liquibase/integration/commandline/Main.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseFlowMojo.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseFlowMojo.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseFlowValidateMojo.java
Add a `flow` and `flow.validate` goal to the maven plugin. Also, add class check before casting in `Main.java`.
Not all Liquibase commands will work out of the box when executed through flow and the maven integration.
See above.
=> add liquibase flow and flow.validate goals to maven plugin (DAT-10576)

liquibase-dist/src/main/archive/liquibase, liquibase-dist/src/main/archive/liquibase.bat
Throw an error and fail to start Liquibase if the JAVA_HOME environment variable is set and the path it points to does not exist.
If there is an edge case we didn't think about or test for, this will prevent Liquibase from starting in those scenarios.
=> error when JAVA_HOME is set to invalid value (DAT-10545)

liquibase-core/src/test/groovy/liquibase/parser/core/yaml/YamlChangeLogParser_RealFile_Test.groovy
The regular expression was edited for time zones with a half-hour offset and a 45-minute offset so that the test could run successfully.
like : UTC−03:30 and UTC+03:30
=> Fixed test failing in different timezones

liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseLauncher.java, liquibase-core/src/main/java/liquibase/GlobalConfiguration.java, liquibase-core/src/main/java/liquibase/changelog/ChangeSet.java, liquibase-core/src/main/java/liquibase/changelog/DatabaseChangeLog.java, liquibase-core/src/main/java/liquibase/parser/ChangeLogParserConfiguration.java, liquibase-core/src/main/java/liquibase/precondition/PreconditionLogic.java, liquibase-core/src/test/groovy/liquibase/changelog/ChangeSetTest.groovy, liquibase-core/src/test/groovy/liquibase/parser/core/yaml/YamlChangeLogParser_RealFile_Test.groovy, liquibase-core/src/test/groovy/liquibase/precondition/core/PreconditionContainerTest.groovy, liquibase-core/src/test/resources/liquibase/registered-changelog.json, liquibase-core/src/test/resources/liquibase/registered-changelog.yml, liquibase-core/src/test/resources/liquibase/simple.json, liquibase-core/src/test/resources/liquibase/test-changelog.json, liquibase-core/src/test/resources/liquibase/test-changelog.yml
Currently, if you have a changelog with an unknown change type or precondition, liquibase just silently skips it. 
For example, in
```
databaseChangeLog:
- changeSet:
id: 1
author: example
changes:
- randomInvalid:
tableName: person
```
we have no `randomInvalid` type defined and so we just silently skip it and treat it as an empty changeset.
If you're using an XML format which has xsd validation and you aren't using extensions, you can't have invalid changes since the XSD will catch that. But if you're using yaml/json (or dbchangelog-ext.xsd) and misspell something or are in any format and referencing an extension change and don't have that extension available you can have it skip it.
The new `liquibase.changelogParseMode` setting can be either "STRICT" or "LAX" where "STRICT" is the new …
=> Added liquibase.changelogParseMode setting

liquibase-core/src/main/java/liquibase/serializer/core/yaml/YamlSerializer.java
We filter out type information in our YAML serialization code, including "!!int <value>" lines.  We need to handle both negative and positive values.
=> Handle negative values when filtering out "!!int" lines DAT-9528

liquibase-core/src/main/java/liquibase/changelog/DatabaseChangeLog.java
Replaces on-the-fly regular expression usage with pre-compiled versions.
Fixes #2221 
Fixes #1856
- Nothing
- Nothing
=> Improved "include" fix performance: optimized normalizePath method

liquibase-core/src/main/java/liquibase/database/core/AbstractDb2Database.java, liquibase-core/src/main/java/liquibase/database/core/Db2zDatabase.java, liquibase-core/src/test/java/liquibase/database/core/DB2DatabaseTest.java, liquibase-core/src/test/java/liquibase/database/core/DB2zDatabaseTest.java
4.11.0
Maven
DB2 11
Linux/Unix/Windows
1. In an existing DB2 database, create a table with a TIMESTAMP(12) column
2. Run generate-changelog
- Files used - sql scripts, …
=> Set max fractional timestamp digits to 12 for all DB2 editions (fix #2880)

liquibase-dist/src/main/install4j/liquibase.install4j
Upgrades the jdk installed with the windows/mac installers to 17.0.4 vs. 17.0.3
- Only impacts the installers
- Builds always use "latest" 17.x so already upgraded
- Nothing
No security issues with 17.0.3, just upgrades and bugfixes in 17.0.4
=> Upgrade installer to ship with jdk 17.0.4+8

liquibase-snowflake/src/main/java/liquibase/diff/output/changelog/core/ChangedSequenceChangeGeneratorSnowflake.java, liquibase-snowflake/src/main/java/liquibase/diff/output/changelog/core/MissingSequenceChangeGeneratorSnowflake.java, liquibase-snowflake/src/main/java/liquibase/sqlgenerator/core/CreateSequenceGeneratorSnowflake.java, liquibase-snowflake/src/main/resources/META-INF/services/liquibase.diff.output.changelog.ChangeGenerator, liquibase-snowflake/src/main/resources/META-INF/services/liquibase.sqlgenerator.SqlGenerator
Snowflake only supports operating 'startWith' and 'incrementBy' sequence attributes. The rests are set by default and are not allowed to be set or changed. In order for Liquibase to correctly work with those 'fixed' attributes we need to:
- Throw a validation error when the 'fixed' attributes are present in changesets that are being applied to Snowflake
- Include the values in JSON snapshots so the database is accurately and completely represented BUT
- Exclude the 'fixed' attributes from any changesets generated by diffChangelog or generateChangelog so that we don't generate invalid changesets
=> Changed what sequence attributes are included in diff/generate changelog for Snowflake

liquibase-snowflake/src/main/java/liquibase/snapshot/jvm/UniqueConstraintSnapshotGeneratorSnowflake.java
INFORMATION_SCHEMA in Snowflake doesn’t track ‘column_name’ attribute for constraints. As result, uniqueConstraints snapshot and changesets produced from diff/generate-changelog commands contain columnNames=”” attribute which results in Error during following update command. Currently the best workaround to get column_name for constraint is to use SHOW UNIQUE KEYS command followed by result_scan(last_query_id()) function.
=> Fix columnNames snapshot attribute of uniqueConstraints for Snowflake

liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseChangeLogMojo.java
Adds a maven-native flag for the liquibase.duplicateFileMode setting introduced in #3006
The config-level tag is `<duplicateFileMode>` and the global maven property to set is `liquibase.duplicateFileMode`
Fixes #3097
- Parsing of the value is case insensitive
- Invalid values should throw a parse value
- Applies to all maven commands that use a changelog (extends AbstractLiquibaseChangeLogMojo)
- Nothing
=> Added duplicateFileMode setting for maven plugin

changelog.txt
=> Update changelog txt

liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy
Need to use the `SearchPathResourceAccessor` constructor that takes the searchPath as the first parameter for tests.
=> Fix tests search path DAT-10431

liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateSequenceGenerator.java, liquibase-core/src/test/java/liquibase/sqlgenerator/core/CreateSequenceGeneratorTest.java, liquibase-integration-tests/src/test/resources/changelogs/h2/complete/root.changelog.xml
Currently Liquibase explicitly excludes H2 when emitting the `AS <dataType>` clause. However, H2 has support for this feature since version 2.0. This effect of this change is that the CreateSequenceGenerator will only omit the clause for versions before that.
I also extended the existing unit test to verify the new behavior. In the process I also attempted to improve the code 
for better readability and consistency. For example, I used the generatorUnderTest field instead of creating a new CreateSequenceGenerator instance.
This also fixes the issue of an unsupported "dataType" on old h2 versions being ignored instead of failing validation like it should have. This will impact on old versions of h2 using dataType as an attribute.
n/a
n/a
=> Add support for `AS <dataType>` clause for H2 since version 2.0

liquibase-core/src/main/java/liquibase/datatype/core/NumberType.java, liquibase-core/src/test/groovy/liquibase/datatype/core/NumberTypeTest.groovy
Fixes NUMBER not compatible with H2 in PostreSql compatibility mode (or suggested for h2 in general).
Full description is here - https://liquibase.jira.com/browse/CORE-3202
As H2 supports numeric, we can use it as a default type as for others DBs
=> [CORE-3202] Fix NUMBER not compatible with H2

liquibase-cli/src/main/java/liquibase/integration/commandline/CommandRunner.java, liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java, liquibase-core/src/main/java/liquibase/integration/commandline/LiquibaseCommandLineConfiguration.java
Use the PathHandlerFactory to write to files specified in the `outputFile` parameter.
This should not be a breaking change.
This is being done to support the S3 work.
=> use PathHandlerFactory for outputFile parameter (DAT-11034)

liquibase-cli/src/main/java/liquibase/integration/commandline/CommandRunner.java
… .
Do not fall back to resource accessor when trying to open OutputStream for file creation. File creation can either occur as a file in the current working directory, or somewhere else using an absolute path (like S3).
=> Do not fall back to resource accessor when trying to open OutputStream for file creation [DAT-11357] 

liquibase-core/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGenerator.java
Fixes #3147.
On MySQL 5.7.12 enums values are retrieved in the correct order.
On MySQL 8.0.28 enums values are retrieved in this order: 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 20, 19, 18, 17...
This fix adds an `order by` so enums are explicitly retrieved in the correct order.
=> fix order of enum values on MySQL 8

liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java
When using maven, if you did not specify an outputFileEncoding setting, it gave a warning about the encoding being system dependent. That is not the case, it defaults to UTF-8 so I removed the warning. We used to fall back to the system encoding instead of UTF-8, but changed that quite a while ago (maybe 4.6?)
I also cleaned up the code slightly so that there is consistent creation of the stream regardless of how the encoding was determined.
- Only impacts maven
- Nothing
=> Removed invalid warning in Maven

liquibase-core/src/main/java/liquibase/resource/PathResource.java
Only `mkdirs` of the parent if the parent is not null.
=> create parent directories only if the parent exists (DAT-11485)

liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseGenerateChangeLogMojo.java
`schemas` and `includeSchema` parameters have been added to `LiquibaseGenerateChangeLogMojo` class to let liquibase know which schemas needs to consider at the time of generating a change log, as well as whether to include schema names on it. 
Fixes #3174
- Nothing
- Nothing
N/A
=> Add schemas and includeSchema parameters to maven generateChangeLog

liquibase-dist/src/main/maven/release.pom.xml
Updates the snakeyaml dependency shipped in the liquibase-maven-plugin pom
=> Upgrade snakeyaml from 1.27 to 1.31 fixing CVE-2022-25857

liquibase-core/src/main/java/liquibase/diff/output/changelog/core/MissingDataExternalFileChangeGenerator.java
Use the complete path of the newly created resources which represent the data to be loaded.
This could break some other integration I didn't think of.
=> DAT-11591: use complete path of resource when generating load data statements

LICENSE.txt
The Apache 2 license has a section where the copyright entity and year should be included.
=> Add year and copyright owner to license

liquibase-core/src/main/java/liquibase/database/core/DatabaseUtils.java
In certain cases the search path in a postgres database can be empty (not null, but an empty string). For us it happens when running postgres with testcontainers for IT tests, probably on rollbacks (as you call initializeDatabase for every rollback to reset default schema). In case searchPath is empty we should not try and process it, just re-set the default schema.
=> Postgresql: Fix for case when current search_path is an empty string

liquibase-core/src/test/groovy/liquibase/util/FilenameUtilTest.groovy
When rollback script for "add column" change is generated, catalog name is missing from generated SQL. As a result of that the rollback may not work if the affected table is not in the default catalog.
=> Fix missing catalog on add column rollback

liquibase-dist/pom.xml
**Liquibase Version**: Any
**Operating System Type & Version**: MacOS
In #2065, OP reported Liquibase does not build on MacOS and suggested a maven setting. Here it is
Clearly stated in #2065
=> Adjust assembly plugin configuration to allow MacOS builds (fix #2065)

liquibase-core/src/main/java/liquibase/executor/jvm/JdbcExecutor.java
Fixes #3219: 
Use
<createIndex indexName="UNI500O1" tableName="UNT500O">
<column name"MDT_ID"/>
</createIndex>
and append some advanced options
<modifySql>
<append value="USING STOGROUP IGVIX001 BUFFERPOOL BP0"/>
</modifySql>
When running the update command on DB2z, the options are currently not appended.
The updateSql command, on the other hand, works correctly.
=> apply sqlVisitors to CompoundStatements on DB2z

liquibase-core/src/main/java/liquibase/command/core/InternalExecuteSqlCommandStep.java
Use the proper message for files not found when running execute-sql command.
=> DAT-11505: use proper file not found message for execute-sql

liquibase-dist/src/main/install4j/liquibase.install4j
Upgrades JDK bundled in win/mac installers to use 17.0.4.1
- Only impacts the installer
- Nothing
=> Upgraded installer to use JDK 17.0.4.1

liquibase-core/src/main/java/liquibase/datatype/core/DoubleType.java, liquibase-core/src/test/groovy/liquibase/datatype/core/DoubleTypeTest.groovy
Fix double type column parsing when double type is specified with precision (i.e. double(25)). 
Fixes #3099 
- Added logic to parse double(xy) as a "Double Precision" for H2 database.
- Only impact on H2 database.
- Nothing.
- Nothing.
=> Fix double with precision type error for H2 

liquibase-core/src/main/java/liquibase/sqlgenerator/core/RawParameterizedSqlGenerator.java, liquibase-core/src/main/resources/META-INF/services/liquibase.sqlgenerator.SqlGenerator
This prevents RawParameterizedSqlStatement to be processed during
dry-run
I started replacing most string-interpolated raw SQL statements with proper `liquibase.statement.core.RawParameterizedSqlStatement` instances in the Neo4j extension (see [PR](https://github.com/liquibase/liquibase-neo4j/pull/226)).
However, the dry-run (`updateSQL`) failed executing because there was no generator for these.
This should have no impact at all, since I believe only the Neo4j extension is currently using `RawParameterizedSqlStatement`.
There is no urgency as I already implemented the missing generator in the extension itself.
I'll remove it from the extension whenever that pull request is merged and its changes are released.
=> Add missing generator for parameterized SQL statements

.gitignore, liquibase-core/src/main/java/liquibase/database/core/DatabaseUtils.java
A null check has been added in order to avoid having issues when trying to run a Liquibase command like "generateChangeLog" proving only the `defaultSchemaName`. 
Fixes #3181 
- nothing
- nothing
- nothing
=> Add catalog null check to fix initializing a MSSQL db issue

README.md
Wording/link fixes; linking DB list to docs to reduce overhead
https://datical.atlassian.net/browse/PD-2838
=> PD-2838: pointing DB list to docs

liquibase-core/src/main/java/liquibase/Contexts.java, liquibase-core/src/main/java/liquibase/LabelExpression.java, liquibase-core/src/main/java/liquibase/Liquibase.java, liquibase-core/src/main/java/liquibase/command/core/InternalSnapshotCommandStep.java, liquibase-core/src/main/java/liquibase/command/core/SnapshotCommandStep.java, liquibase-core/src/test/groovy/liquibase/LiquibaseTest.groovy
Added `.update()`
* some JavaDocs.
**Liquibase Version**: 4.3.0
**Operating System Type & Version**: Win 10
Described in issue itself.
Described in issue itself.
Described in issue itself.
Described in issue itself.
N/A
N/A
=> Addition of liquibase.update() Enhancement Request #1614

liquibase-core/src/main/java/liquibase/sqlgenerator/core/RenameColumnGenerator.java, liquibase-integration-tests/src/test/resources/changelogs/sqlite/complete/root.changelog.xml
Updated `supports()` method logic from `RenameColumnGenerator` class to return `true` for SQLite database from version 3.25 or higher, or any other supported database.
Fixes #2925 
- Change method logic to consider SQLite DB version.
- This change only has impact on SQLite, for any other database it will keep behaving as of now.
- This method might need to be revisited once again in a future if for a newer version this change is not again supported. 
- Nothing.
=> Allow renameColumn on newer SQLite versions

liquibase-dist/src/main/maven/release.pom.xml
The CLI and overall project uses snakeyaml 1.33 but there is a separate pom.xml used for what we publish which still uses 1.32.
This upgrades that dependency to macch.
- Impacts people using liquibase as a maven dependency
- Nothing
=> Upgrade snakeyaml maven reference from 1.32 to 1.33

liquibase-core/src/main/java/liquibase/database/core/DatabaseUtils.java
We should be using our StringUtil class, not commons.lang3 versions which are not always available.
- Does not change functionality, just changes the method called
- Nothing
=> Use liquibase StringUtil not lang3.StringUtils

liquibase-core/src/main/java/liquibase/resource/AbstractPathResourceAccessor.java, liquibase-core/src/main/java/liquibase/util/FileUtil.java, liquibase-core/src/test/groovy/liquibase/resource/DirectoryResourceAccessorTest.groovy, liquibase-core/src/test/java/liquibase/verify/saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets/renameColumn/sqlite.sql
Do not allow absolute paths in this method
=> Handle absolute path in getAll method DAT-11890

liquibase-core/src/main/java/liquibase/command/AbstractCliWrapperCommandStep.java, liquibase-core/src/main/java/liquibase/configuration/ConfiguredValueModifier.java
Reduce unnecessary calls to `getArgumentValue` so that `ConfiguredValueModifier`'s aren't called more than necessary.
Resolves #3144 
This reduces the number of calls to the `ConfiguredValueModifier` from four to two. I don't think it's reasonably possible to reduce from two to one. The two calls occur in different phases of a command running: validation and execution. It seems reasonable to me that these two calls occur.
=> Reduce unnecessary calls to getArgumentValue (DAT-11785)

liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseRollbackOneChangeSetSQL.java
Adds rollback script to args map when using rollbackOneChangeSet via maven to ensure the inverse changeset is found if it is provided. 
N/A
N/A
=> Fix "No inverse to CreateProcedureChange" error when using rollbackOneChangeSetSQL (DAT-6361)

changelog.txt
This is a patch release that upgrades the HSQL driver to remove a security vulnerability.
Updates opencsv to 5.7.1
The newest HSQL driver requires Java 11
=> Update changelog with 4.17.2 changes

liquibase-cli/src/main/java/liquibase/integration/commandline/CommandRunner.java, liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java, liquibase-core/src/main/java/liquibase/changelog/ChangelogRewriter.java, liquibase-core/src/main/java/liquibase/changelog/visitor/DBDocVisitor.java, liquibase-core/src/main/java/liquibase/dbdoc/ChangeLogWriter.java, liquibase-core/src/main/java/liquibase/dbdoc/HTMLListWriter.java, liquibase-core/src/main/java/liquibase/dbdoc/HTMLWriter.java, liquibase-core/src/main/java/liquibase/diff/output/changelog/DiffToChangeLog.java, liquibase-core/src/main/java/liquibase/diff/output/changelog/core/MissingDataExternalFileChangeGenerator.java, liquibase-core/src/main/java/liquibase/integration/commandline/LiquibaseCommandLineConfiguration.java, liquibase-core/src/main/java/liquibase/integration/spring/SpringResource.java, liquibase-core/src/main/java/liquibase/resource/AbstractResource.java, liquibase-core/src/main/java/liquibase/resource/OpenOptions.java, liquibase-core/src/main/java/liquibase/resource/PathHandlerFactory.java, liquibase-core/src/main/java/liquibase/resource/PathResource.java, liquibase-core/src/main/java/liquibase/resource/Resource.java, liquibase-core/src/main/java/liquibase/resource/ResourceAccessor.java, liquibase-core/src/test/groovy/liquibase/resource/PathHandlerFactoryTest.groovy
This reverts commit 9949ca0bccd115411ad6cd45c8135d87be6d951e.
Create log files using the `PathHandler` interfaces. Add support for different `OpenOptions` for resources, like appending and truncating existing files.
- Liquibase erroneously closed the `Handler` in `LiquibaseCommandLine`. This is actually unnecessary as the Java log framework will handle closing it at the appropriate time. Additionally, Liquibase was closing the handler too early, which caused an exception to be thrown by the logging framework itself: `java.lang.IllegalStateException: Current state = FLUSHED, new state = CODING`
- Not all implementations of resource will support appending to existing files. Implementations which do not support appending will throw an exception if the file already exists and append is set to …
=> Use PathHandler for writing log files, which allows using S3 and other extensions (DAT-11515)

liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
If an update throws a LiquibaseException, rollbackOnError may be uninitialized and throws a NPE.
- None
- 
- None
=> Fixes nullpointer when dealing with LiquibaseException on updates.

liquibase-core/src/main/java/liquibase/diff/compare/CompareControl.java, liquibase-core/src/test/groovy/liquibase/diff/compare/CompareControlTest.groovy
Incorrect regex expression "." in call to 'split()'  at CompareControl constructor was causing the strings to being wrongly slit.
As this code is not used within liquibase-core, an unit test was created.
Fixes #3204 
- Code fixed
- None
- None
=> Fixed input string handling in CompareControl constructor

liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseChangeLogMojo.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java, liquibase-maven-plugin/src/test/java/org/liquibase/maven/plugins/AbstractLiquibaseChangeLogMojoTest.java
Fixes #3282 
- Maven was conflicting to find changelog file in two different paths, so this fix avoid setting a new location if there is one already defined.
- Only impacts Maven.
- Nothing
- Nothing
=> Fix getResourceAccessor logic to avoid setting changeLogDirectory when searchPath has already set

liquibase-core/src/main/java/liquibase/statement/ExecutablePreparedStatementBase.java, liquibase-integration-tests/src/test/java/liquibase/dbtest/pgsql/PostgreSQLIntegrationTest.java, liquibase-integration-tests/src/test/resources/changelogs/pgsql/complete/testBlob.changelog.xml
Postgresql defines 2 column types to handle blob types: bytea and large objects that must be declared as "oid". According to postgresql documentation, both must use different jdbc methods (https://jdbc.postgresql.org/documentation/binary-data/) . 
Until Liquibase 4.13, bytea was supported.  But https://github.com/liquibase/liquibase/pull/605 changed the methods to support large objects instead of bytea. 
This fix validates the column type and uses the appropriated jdbc method depending on it.
- A column cache has been created to make sure that snapshot data for a column is requested only once
- After this patch, both oid and bytea column types should work.
- NA
- Fixes #3165
=> Ensures that Postgresql works with blob types bytea and oid (large objects)

liquibase-core/src/main/java/liquibase/datatype/core/BigIntType.java, liquibase-core/src/main/java/liquibase/datatype/core/IntType.java, liquibase-core/src/main/java/liquibase/datatype/core/SmallIntType.java, liquibase-core/src/main/java/liquibase/datatype/core/TinyIntType.java, liquibase-core/src/test/groovy/liquibase/datatype/core/BigIntTypeTest.groovy, liquibase-core/src/test/groovy/liquibase/datatype/core/IntTypeTest.groovy, liquibase-core/src/test/groovy/liquibase/datatype/core/SmallIntTypeTest.groovy, liquibase-core/src/test/groovy/liquibase/datatype/core/TinyIntTypeTest.groovy, liquibase-integration-tests/src/test/resources/changelogs/h2/complete/root.changelog.xml
Implement support to consider integer precision by parsing to the specific integer type (tiny, integer or bigint) depending on the specified size.
Fixes #3250 
Fixes #3300 
- This change only impacts integer data type for H2.
- Nothing.
- Nothing.
=> Improve int/tinyint/smallint/bigint handling in H2

liquibase-core/src/main/java/liquibase/command/CommandScope.java, liquibase-core/src/main/java/liquibase/configuration/ConfigurationDefinition.java, liquibase-core/src/main/java/liquibase/configuration/ConfiguredValue.java, liquibase-core/src/main/java/liquibase/configuration/LiquibaseConfiguration.java, liquibase-core/src/test/groovy/liquibase/command/CommandScopeTest.groovy, liquibase-core/src/test/java/liquibase/command/core/MockCommandStep.java
Settings from CommandScope would override values from other ValueProviders, but it did it outside the normal pipeline so things like ValueModifier wasn't correctly applied.
This modifies the `ConfigurationDefinition.getCurrentConfiguredValue()` to be able to use non-global ValueProviders such as CommandScopeValueProvider and fixes CommandScope to use that.
It also adds a new ConfiguredValue.override() function for modifications of configured values that aren't coming from new providers, such as from ConfiguredValueModifier
- Preserves exiting API while adding new methods
- Nothing
Nothing
=> Better integrate CommandScope arguments into overall ValueProvider logic

liquibase-core/src/main/java/liquibase/configuration/ConfigurationDefinition.java
Readds the noarg method that was removed in #3448.
This shouldn't technically be necessary, but we're readding it anyway to try to maintain some semblance of backwards compatibility.
=> readd noarg method for CommandScope arguments for backwards compatibility

pom.xml
=> [DAT-11899] Modifies deploy plugin and distribution management.

liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseUpdate.java
Adds change exec listener and rollback on error property elements. Sets up change exec listener for mojos. Handles migration errors on updates.
N/A
N/A
N/A
=> Adds ChangeExecListener properties to maven plugin (DAT-12219)

liquibase-core/src/main/java/liquibase/logging/core/BufferedLogService.java
Makes the underlying log store for the `BufferedLogService` thread safe.
We occasionally get errors like:
```
java.util.ConcurrentModificationException
at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1043)
at java.base/java.util.ArrayList$Itr.next(ArrayList.java:997)
at liquibase.logging.core.BufferedLogService.getLogAsString(BufferedLogService.java:39)
at ...
```
in the pro integration tests, this should resolve them.
Performance impacts from the synchronized list? This is unlikely because Liquibase is not a terribly thread-heavy application.
=> make BufferedLogService thread safe

liquibase-extension-testing/src/main/java/liquibase/extension/testing/TestFilter.java
The test filtering logic needed to be expanded to match against databases that have numerics in their name, like H2.
None - this is a test only change.
=> match databases with numbers (like H2) in test filter

liquibase-core/src/main/java/liquibase/changelog/DatabaseChangeLog.java, liquibase-core/src/test/groovy/liquibase/changelog/DatabaseChangeLogTest.groovy
PR #3355 aimed to fix issues related to "./" and "../" , but by using Paths.get it is also removing trailing slashs. The changed method has logic to append the trailing slash, but it is located above the new code - so it baceme useless. This PR moves the code that fixes the path to be executed after Paths.get.
- Fixes includeAll on S3 extension.
- Tests restored as they were before #3355 
- None
- Issue raised by S3 extension tests.
=> Fixes behaviour of includeAll by keeping the trailing slash on the path

liquibase-core/src/main/java/liquibase/resource/FileSystemResourceAccessor.java, liquibase-core/src/test/groovy/liquibase/resource/FileSystemResourceAccessorTest.groovy
The class liquibase.resource.FileSystemResourceAccessor is absent from the 4.17.0 release, but it was still present in 4.16.0  and was dropped without deprecation. This PR restores the class as deprecated and add tests.
- Fixes #3478
=> Restore FileSystemResourceAccessor and add tests.

liquibase-core/src/main/java/liquibase/changelog/ChangeSet.java
Incorrect response for json,yml,xml changelogs when rollback is not supported for for json,yml and ,xml changelogs. 
The response "Liquibase does not support automatic rollback generation for raw sql changes (did you mean to specify keyword "empty" to ignore rolling back this change?)" is only for sql changelogs, but is showing for all of them. This fix narrows it to sql files.
- Used the same logic that FormattedSqlChangeLogParser.supportsExtension applies to find out if it supports the changelog file.
- Fixes #3469 
- None
=> Fix incorrect error message when rollback is not supported for for json,yml and ,xml changelogs

changelog.txt
=> update changelog txt 4.18

liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
This PR fixes a bug where a `ClassCastException` occurs when alternative logger implementations are on the classpath when the CLI is used. This was [previously fixed](https://github.com/liquibase/liquibase/blob/master/liquibase-core/src/main/java/liquibase/integration/commandline/Main.java#L290-L293) on the older legacy `Main` class but the newer `LiquibaseCommandLine` still has the issue.
Motivation is to avoid issues like [this](https://github.com/mattbertolini/liquibase-slf4j/issues/16) from being created.
None that I know of. This change is backwards compatible.
=> Avoid ClassCastException when loading LogService from Scope

liquibase-core/src/main/java/liquibase/serializer/core/yaml/YamlSnapshotSerializer.java, liquibase-core/src/main/java/liquibase/snapshot/DatabaseSnapshot.java, liquibase-core/src/main/java/liquibase/structure/core/Column.java, liquibase-core/src/main/java/liquibase/structure/core/Index.java, liquibase-integration-tests/src/test/groovy/liquibase/snapshot/IndexWithDescendingColumnSnapshotTest.groovy, liquibase-integration-tests/src/test/resources/oldSnapshotWithDescendingIndex.json
In the snapshot command, indexes with columns marked as descending were not getting serialized in a way that would allow a changelog to be successfully generated.  With this fix, columns are now explicitly serialized as objects, rather than as references to column objects.
=> Correctly handle indexes with descending columns in snapshot DAT-11447

liquibase-core/src/main/java/liquibase/changelog/ChangeSet.java
Added call to modifyChangeSet during execute method to allow thechangeSet to be correctly set on the executor
=> Added call to modifyChangeSet during execute method to allow the changeSet to be correctly set on the executor DAT-12388

liquibase-core/src/main/java/liquibase/changelog/visitor/ValidatingVisitor.java, liquibase-core/src/main/java/liquibase/exception/ValidationErrors.java, liquibase-core/src/test/groovy/liquibase/changelog/ChangeSetTest.groovy, liquibase-core/src/test/java/liquibase/changelog/visitor/ValidatingVisitorTest.java
Added validation for these attributes to ValidatingVisitor.
Tests are also added for the cases when author or id or both attributes are empty.
Tags: hacktoberfest, newbiePR
=> #1290: Forbid empty changeSet id and author

liquibase-core/src/main/java/liquibase/configuration/LiquibaseConfiguration.java
Previously, the description that comes with the ProvidedValue was always converted before display to have it's first character be lower-case.  In cases where the description is upper-case (like AWS, for instance) this doesn't make sense. So, if we detect that the description starts with at least 2 upper-case characters, we display it as-is.
=> Do not lower case the ProvidedValue description if the string is capitalized, i.e. it starts with 2 upper-case characters DAT-12614

.github/workflows/create-release.yml
=> DAT-12576 update release workflow to attach artifact by run_id

liquibase-dist/src/main/install4j/liquibase.install4j
Upgrades java minor version for installer.
- none
- none
=> Upgrades installer JDK version for next release.

liquibase-core/src/main/java/liquibase/change/core/SetColumnRemarksChange.java, liquibase-core/src/main/java/liquibase/diff/output/changelog/core/MissingViewChangeGenerator.java, liquibase-core/src/main/java/liquibase/sqlgenerator/core/SetColumnRemarksGenerator.java, liquibase-core/src/main/java/liquibase/statement/core/SetColumnRemarksStatement.java, liquibase-core/src/main/java/liquibase/util/ColumnParentType.java, liquibase-core/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd, liquibase-core/src/test/groovy/liquibase/serializer/core/string/StringChangeLogSerializerTest.groovy, liquibase-integration-tests/src/test/groovy/liquibase/command/core/GenerateChangeLogMSSQLCommandTest.groovy
Adds new attribute `columnParentType` to `SetColumnRemarksChange`. This is an string that contains two valid values `TABLE, VIEW`. This is required to enable any `setColumnRemarks` change type to know whether the owner of the column is a view or a table. The syntax for sql server (and currently _only_ SQL Server) is different between the two cases. 
For backwards compatibility it feels like an enum will be a easier solution to maintain than just an `isView` boolean attribute. Another solution could be to create a new change type `SetViewColumnRemarks` however this is ONLY currently necessary for SQL Server, so that feels a bit heavy handed and would potentially lead to some confusion as now there would be two valid ways to set column remarks for view column comments in say, postgresql. …
=> Fix MSSQL generated xml changelogs for view column comments (DAT-12835)

liquibase-core/src/main/java/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParser.java, liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy
Normalize the path of a SQL changelog file when parsing it.
Tests are added in the pro repo.
This has the potential to break some other process which expects the path to be un-normalized.
=> normalize path of SQL changelog file when parsing (DAT-11891)

liquibase-core/src/main/java/liquibase/parser/core/yaml/YamlChangeLogParser.java
A continuation of #3664, which fixes the same bug with JSON and YAML changelogs, by normalizing the file path when parsing the changelog.
Tests are in the pro repo.
=> normalize path of json and yaml changelogs when parsing (DAT-11891)

liquibase-core/src/main/java/liquibase/logging/core/DefaultLoggerConfiguration.java
DefaultLoggerConfiguration is not used anywhere. It is now deprecated and hidden from the help output.
DefaultLoggerConfiguration is not being removed yet because other extensions may use it.
=> deprecate DefaultLoggerConfiguration (DAT-11970)

liquibase-core/pom.xml
Currently XSD files can not be loaded from the liquibase-core.jar in an OSGI environment (using the `OSGiResourceAccessor`). The `LiquibaseEntityResolver` can not find the XSD resource. A workaround is to set secureParsing to false, so XSD can be looked up remotely.
The liquibase-core.jar contains two directories (packages). `liquibase` and `www.liquibase.org`. ONLY the `liquibase` package and it's sub-packages are being exported in the **MANIFEST.MF**. This means the XSD files, which are all under `www.liquibase.org.xml.ns.dbchangelog`, can not be accessed in an OSGI environment.
The reason why the XSD's are not exported in the MANIFEST.MF right now is because currently no _Export-Package_ tag is specified in the _maven-bundle-plugin_ instructions. This means the default behavior of the …
=> Update maven-bundle-plugin instructions to export package containing XSD files

liquibase-core/src/main/java/liquibase/change/AbstractChange.java, liquibase-core/src/main/java/liquibase/database/Database.java, liquibase-core/src/main/java/liquibase/exception/DatabaseIncapableOfOperation.java, liquibase-core/src/main/java/liquibase/exception/StatementNotSupportedOnDatabaseException.java, liquibase-core/src/main/java/liquibase/exception/ValidationErrors.java, liquibase-snowflake/src/main/java/liquibase/database/core/SnowflakeDatabase.java, liquibase-snowflake/src/main/java/liquibase/executor/jvm/SnowflakeJdbcExecutor.java, liquibase-snowflake/src/main/java/liquibase/sqlgenerator/core/SetColumnRemarksGeneratorSnowflake.java, liquibase-snowflake/src/main/resources/META-INF/services/liquibase.executor.Executor
Snowflake does not support setting view column comments after the view has been created, so this change warns the user of that.
Performance impact of querying the Snowflake information schema about whether an object is a view.
=> do not support setting column comments on a view in Snowflake (DAT-12530)

liquibase-core/src/main/java/liquibase/command/core/UpdateCommandStep.java, liquibase-core/src/main/java/liquibase/command/core/UpdateTestingRollbackCommandStep.java
Minimal, ensures consistent code in all CLI-Command classes.
All **but two** _CommandStep_-classes employ the following naming scheme for the  'defaultSchemaName'-Parameter:
`public static final CommandArgumentDefinition<String> DEFAULT_SCHEMA_NAME_ARG;`
Except two classes, which used:
`public static final CommandArgumentDefinition<String> DEFAULT_SCHEMA_NAME;`
This PR fixes this.
None 😉 
I started to investigate what the root cause of #3587 could be and noticed this while code-reading 😉
=> Consistent ARG-suffix for 'defaultSchemaName'-Parameter

liquibase-core/src/main/java/liquibase/integration/servlet/GenericServletListener.java
`GenericServletListener` can be either a `LiquibaseServletListener` or a `LiquibaseJakartaServletListener`.
Removing all explicit references to the former so as not to provide confusion when `LiquibaseJakartaServletListener` is used instead.
None
None
None
=> Removing explicit LiquibaseServletListener references

liquibase-core/src/main/java/liquibase/ContextExpression.java, liquibase-core/src/main/java/liquibase/LabelExpression.java, liquibase-core/src/main/java/liquibase/Liquibase.java, liquibase-core/src/main/java/liquibase/changelog/ChangeSet.java
Formats all labelFilters and contextFilters to "", not "()".
=> Standardize commandLabelFilter/commandContextFilter mdc value format (DAT-12958)

liquibase-snowflake/src/main/java/liquibase/database/core/SnowflakeDatabase.java
Add Snowflake structured data types in the unmodifiable Data Types list to avoid the incorrect results of the diffChangeLog command
Structured data types are compared incorrectly.
Structured data types in the Snowflake can not be created with parameters: https://docs.snowflake.com/en/sql-reference/data-types-semistructured.html
But the result of comparing tables with these types of columns with the diffChangeLog command will be
```sql
CREATE OR REPLACE TABLE TEST_SEMI_STRUCTURED(
var VARIANT(0),
arr ARRAY(0),
obj OBJECT(0));
```
because by default Liquibase returns data type name + parameters
And the simplest way to avoid it is adding data types in the unmodifiable types list:
https://github.com/liquibase/liquibase/blob/master/liquibase-core/src/main/java/liquibase/snapshot/jvm/ColumnSnaps …
=> Add Snowflake structured data types to unmodifiable Data Types

liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java, liquibase-core/src/main/java/liquibase/configuration/ConfigurationDefinition.java, liquibase-core/src/main/java/liquibase/integration/commandline/LiquibaseCommandLineConfiguration.java
=> hide log format parameter (DAT-13501)

liquibase-core/src/main/java/liquibase/changelog/StandardChangeLogHistoryService.java, liquibase-core/src/main/java/liquibase/executor/jvm/ChangelogJdbcMdcListener.java, liquibase-core/src/main/java/liquibase/lockservice/StandardLockService.java, liquibase-core/src/main/java/liquibase/logging/mdc/MdcKey.java, liquibase-core/src/main/java/liquibase/logging/mdc/MdcValue.java, liquibase-core/src/test/java/liquibase/lockservice/StandardLockServiceTest.java
Adds `ChangelogJdbcMdcListener` used to handle DATABASECHANGELOG and DATABASECHANGELOGLOCK queries and log relevant sql and outcomes.
=> Adds databaseChangelogTableOutcome mdc (DAT-12978)

liquibase-core/src/test/groovy/liquibase/configuration/core/EnvironmentValueProviderTest.groovy
The `getProvidedValue doesn't require license` test is looking for a `java_home` environment variable, and so it fails on any development environments where that variable is not set.
I could have tried to find a different environment variable that's consistently available across all OS's and/or used a custom map like the other tests, but because the class under test has no references to LicenseService anymore it seemed like an unnecessary test to fix.
Only removes a sometimes-failing test.
Nothing
=> Fix failing EnvironmentValueProviderTest

liquibase-core/src/main/java/liquibase/change/core/DropAllForeignKeyConstraintsChange.java, liquibase-core/src/main/java/liquibase/change/core/DropColumnChange.java, liquibase-core/src/main/java/liquibase/change/core/EmptyChange.java, liquibase-core/src/main/java/liquibase/change/core/ExecuteShellCommandChange.java, liquibase-core/src/main/java/liquibase/change/core/LoadDataChange.java, liquibase-core/src/main/java/liquibase/change/core/LoadUpdateDataChange.java, liquibase-core/src/main/java/liquibase/change/core/MergeColumnChange.java, liquibase-core/src/main/java/liquibase/change/core/RenameSequenceChange.java, liquibase-core/src/main/java/liquibase/change/core/RenameTableChange.java, liquibase-core/src/main/java/liquibase/change/core/TagDatabaseChange.java, liquibase-core/src/main/java/liquibase/change/custom/CustomChangeWrapper.java, liquibase-core/src/main/java/liquibase/changelog/ChangeSet.java, liquibase-core/src/main/java/liquibase/diff/output/changelog/core/MissingDataExternalFileChangeGenerator.java
- [X ] Enhancement/New feature (adds functionality without impacting existing logic)
We can save memory reusing the same array instance. Allocations of arrays with known lengths of zero when there is a constant for that in the class of the array's element type. Also, as zero-length arrays are immutable.
Please take a look to this PR 
https://github.com/liquibase/liquibase/pull/3500
=> Use constants instead of arrays with known lengths of zero

liquibase-core/src/main/java/liquibase/Liquibase.java, liquibase-core/src/main/java/liquibase/util/TableOutput.java
Fix logic that clear out deploymentId when calling hub.register
Since Liquibase 4.18, `StandardLockService.reset` calls out `changelogService.reset()` that clears de deployment id. HubService.regsiter is releasing the lock to wait for user input, so it's also clearing the deployment id.
=> DAT-13659 Fix nullpointers on table output

liquibase-core/src/main/java/liquibase/executor/jvm/ChangelogJdbcMdcListener.java
Skip MDC logging for MarkChangeSetRanStatement SQLs preventing skipping order executed ids.
I won't call this a fix - it's more of a temporary workaround.
=> DAT-13664 - skip MDC logging for MarkChangeSetRanStatement SQLs 

liquibase-core/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java, liquibase-core/src/main/java/liquibase/command/core/UpdateCommandStep.java, liquibase-core/src/main/java/liquibase/command/core/UpdateCountCommandStep.java, liquibase-core/src/main/java/liquibase/command/core/UpdateCountSqlCommandStep.java, liquibase-core/src/main/java/liquibase/command/core/UpdateSqlCommandStep.java, liquibase-core/src/main/java/liquibase/command/core/helpers/HubHandler.java
Authored by Alex, this fixes the hub interactions for the update-family of commands.
=> fix hub for update-family of commands (DAT-6600)

liquibase-core/src/main/java/liquibase/logging/mdc/MdcKey.java
Added keys to support MDC key/values during rollback with the SQLCMD native executor
=> Added SQLCMD keys for MDC in rollback DAT-13363

liquibase-core/src/main/java/liquibase/parser/core/yaml/YamlParser.java
Go back to the old default of allowing duplicate keys. This change was added as part of  PR https://github.com/liquibase/liquibase/pull/3632 that removed deprecate methods, but it is a behavior change that we don't want.
It breaks flow tests.
=> Rollback Snakeyaml default config to allow duplicate keys.

liquibase-core/src/main/java/liquibase/util/SqlUtil.java
DAT-13911
The generated SQL in the MDC should not include an extra semi-colon
=> Do not add endDelimiter to MDC generated SQL if it is already there DAT-13911

liquibase-core/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java, liquibase-core/src/main/java/liquibase/util/ShowSummaryUtil.java, liquibase-integration-tests/src/test/groovy/liquibase/command/util/CommandUtil.groovy, liquibase-integration-tests/src/test/groovy/liquibase/util/ShowSummaryUtilCommandTest.groovy, liquibase-integration-tests/src/test/resources/changelogs/pgsql/update/showSummaryWithLabels.xml
In the case where nothing is deployed, no summary was displayed.  Fixed and added integration test.
=> Fixed issue where summary is not displayed when nothing is deployed

liquibase-core/src/main/java/liquibase/resource/ResourceAccessor.java
https://github.com/liquibase/liquibase/pull/3620 introduced a NullPointerException in the ResourceAccessor class.
=> fix NullPointerException in ResourceAccessor

liquibase-core/src/main/java/liquibase/executor/jvm/ChangelogJdbcMdcListener.java
Downgrades  log level of message "Changelog query completed" as it is showing up too much in info logs.
=> Lowers message log level.

liquibase-core/src/main/java/liquibase/Contexts.java
Similar to how label expressions are parsed, leading slashes are stripped from contexts.
=> strip leading slashes from contexts (DAT-13994)

liquibase-core/src/main/java/liquibase/command/CommandScope.java, liquibase-core/src/main/java/liquibase/logging/mdc/MdcKey.java, liquibase-integration-tests/src/test/groovy/liquibase/command/util/CommandUtil.groovy
Added these keys to the MDC so that they will show up in structured logging
=> Add OUTPUT_FILE and OUTPUT_FILE_ENCODING to MDC DAT-14017

.github/util/re-version.sh, .github/workflows/build.yml, .github/workflows/release-published.yml
This updates the github actions to include the newly added liquibase-cdi-jakarta module.
Fixes [#3962](https://github.com/liquibase/liquibase/issues/3962)
=> Release liquibase-cdi-jakarta to maven repositories

liquibase-core/src/main/java/liquibase/changelog/StandardChangeLogHistoryService.java, liquibase-core/src/main/java/liquibase/executor/jvm/ChangelogJdbcMdcListener.java, liquibase-core/src/main/java/liquibase/lockservice/StandardLockService.java, liquibase-core/src/main/java/liquibase/sqlgenerator/SqlGeneratorFactory.java, liquibase-core/src/main/java/liquibase/util/SqlUtil.java, liquibase-core/src/test/java/liquibase/lockservice/StandardLockServiceTest.java, liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/update.test.groovy
This is a proper fix for https://github.com/liquibase/liquibase/pull/3869.
Complexity of having the SqlGeneratorFactory be responsible for storing the generated SQL in the scope using an AtomicReference. I don't know of a better way for the factory to pass the generated SQL "back" to the caller without a larger refactoring and breaking changes.
=> log generated databasechangelogsql without erroneously incrementing the order executed by 2 (DAT-13680)

liquibase-core/src/main/java/liquibase/changelog/ChangeSet.java, liquibase-core/src/main/resources/liquibase/examples/sql/liquibase.psql.conf, liquibase-core/src/main/resources/liquibase/examples/sql/liquibase.sqlcmd.conf, liquibase-core/src/main/resources/liquibase/examples/sql/liquibase.sqlplus.conf, liquibase-core/src/main/resources/liquibase/examples/xml/liquibase.psql.conf, liquibase-core/src/main/resources/liquibase/examples/xml/liquibase.sqlcmd.conf, liquibase-core/src/main/resources/liquibase/examples/xml/liquibase.sqlplus.conf, liquibase-integration-tests/src/test/groovy/liquibase/snapshot/IndexWithDescendingColumnSnapshotTest.groovy, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java
Removes `liquibase.psql/sqlcmd/sqlplus.executor` property because this property is not respected.
=> Remove native executor name property (DAT-13580)

liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
When running Main from java code like below:
```
String[] arguments = [
"--url", "jdbc:neo4j:${neo4jContainer.getBoltUrl()}",
"--username", "neo4j",
"--password", PASSWORD,
"--changeLogFile", "/changelog.xml",
"updateSQL"
].toArray()
Main.run(arguments)
```
Liquibase 4.21.0 throws the following error:
```
liquibase.exception.LiquibaseException: Unexpected error running Liquibase: Unknown reason
at liquibase.integration.commandline.Main$1.run(Main.java:465)
at liquibase.integration.commandline.Main$1.run(Main.java:234)
at liquibase.Scope.child(Scope.java:203)
at liquibase.Scope.child(Scope.java:179)
at liquibase.integration.commandline.Main.run(Main.java:234)
at liquibase.ext.neo4j.Neo4jPluginIT.runs migrations(Neo4jPluginIT.groovy:99)
Caused by: …
```
=> Add missing parameter changeLogFile to update command when running from Main

.github/workflows/release-published.yml
Javadocs extraction conflict due to both `liquibase-cdi` and `liquibase-cdi-jakarta` matching the `liquibase-cdi*.jar`.  Instead, lets use a loop to extract the dir name based on the jar file name (excluding the version and the word javadocs) and then extract the jar files there.
=> DAT-14418 javadocs extraction fix

liquibase-integration-tests/src/test/java/liquibase/statementexecute/AddUniqueConstraintExecutorTest.java, liquibase-snowflake/src/main/java/liquibase/database/core/SnowflakeDatabase.java
Make SnowflakeDatabase report catalog names in identifiers as supported feature.
Snowflake supports fully qualified names in tables/views/procedures. 
Without this, Snowflake change sets get their catalog name forcefully removed. Combined with Snowflake automatically switching current database/schema on each CREATE DATABASE statement, this discrepancy makes managing high level Snowflake objects with Liquibase very tedious & fragile, as it often can't find its DATABASECHANGELOG after having executed those change sets.
I can't find where Snowflake's support for fully qualified names is documented, but it works in our accounts.
Resolves #3036
=> SnowflakeDatabase allows catalog name in identifiers

liquibase-standard/src/main/java/liquibase/change/core/CreateProcedureChange.java, liquibase-standard/src/test/groovy/liquibase/change/core/CreateProcedureChangeTest.groovy
Rollback annotation settings for CreateProcedureChange .getProcedureText
This change was introduced by  change https://github.com/liquibase/liquibase/pull/3811  that was meant to be  a documentation update, not behavior change.
=> Fixes undesired change to CreateProcedureChange checksum generation

liquibase-standard/src/main/java/liquibase/change/core/AddDefaultValueChange.java, liquibase-standard/src/test/groovy/liquibase/change/core/AddDefaultValueChangeTest.groovy
Make sure we create new objects instead of modifying the existing ones when processing addDefaultValue change type.
It changes checksum value so it must be merged in the same release as https://github.com/liquibase/liquibase/pull/3914 .
=> Fix addDefaultValue checksum calculation when providing schema name

liquibase-standard/src/main/java/liquibase/changelog/AbstractChangeLogHistoryService.java, liquibase-standard/src/main/java/liquibase/changelog/ChangeLogIterator.java, liquibase-standard/src/main/java/liquibase/changelog/DatabaseChangeLog.java, liquibase-standard/src/main/java/liquibase/sqlgenerator/core/UpdateChangeSetChecksumGenerator.java
When updating checksums make sure to use the stored file path instead of the generated one as we changed the way that we store paths during the years.
=> Fix null md5sum issues during checksum upgrades

liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/MavenUi.java
I am categorizing this as a bugfix and not an enhancement, since I don't think that using the default `ConsoleUIService` (which writes to stdout) was intended.
With this PR, the "Running Changeset: " logs are written with the maven logger and not directly to stdout.
Impact on the codebase: minimal
Nothing
=> Fix "Running Changeset: " logs written directly to stdout instead of using the maven logger

liquibase-standard/src/main/java/liquibase/change/custom/CustomChangeWrapper.java, liquibase-standard/src/main/java/liquibase/datatype/core/BlobType.java, liquibase-standard/src/main/java/liquibase/integration/ant/AntResourceAccessor.java
- [ X] Enhancement/New feature (adds functionality without impacting existing logic)
Avoid multiple equivalent occurrences of the same expression within a method (or constructor, or class initializer) if the result of the expression can be reused.
=> Code cleanup: avoid re-calling methods

liquibase-integration-tests/src/test/resources/changelogs/mssql/complete/root.changelog.xml, liquibase-integration-tests/src/test/resources/changelogs/mssql/issues/transaction.test.sql
This PR fixes #4098. It add support for the T-SQL Keyword "TRAN".
Currently liquibase splits sql statements only, if there are not between a "BEGIN" and "END" statement. Since most database start transactions with the "BEGIN TRANSACTION" command, the StringUtil class which is responsible for splitting statements, does ignore the "BEGIN" keyword if it is followed by the keyword "TRANSACTION". 
T-SQL (the sql dialect from mssql-server) also supports a shorter version for "TRANSACTION" => "TRAN". The current version of liquibase does not check for keyword "TRAN". This pull request adds support for this keyword. 
- I just added the new keyword "TRAN" to the if statement, with intention to change as little as possible 
- the current code also supports the keyword "TRANS", I don't know any …
=> add support for the TRAN keyword (T-SQL)

liquibase-standard/src/main/java/liquibase/ChecksumVersions.java, liquibase-standard/src/main/java/liquibase/changelog/StandardChangeLogHistoryService.java, liquibase-standard/src/main/java/liquibase/changelog/filter/ShouldRunChangeSetFilter.java, liquibase-standard/src/main/java/liquibase/changelog/visitor/UpgradeCheckSumVisitor.java, liquibase-standard/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java, liquibase-standard/src/main/java/liquibase/exception/UnsupportedChecksumVersionException.java
Implementation Details
Add a new visitor class ChecksumsUpgradeVisitor to have the logic to upgrade to v9
Expected result:
After running “update” command all the v8 checksums associated with the changesets that are “checked” should be now v9 (in other words, only changesets which match the supplied filters (ie labels, contexts, dbms, etc) will have their checksums upgraded)
=> [DAT-14885] Upgrade to v9 after running liquibase update command

.github/workflows/build-branch.yml, .github/workflows/cleanup-branch-builds.yml
- cleanup branch delete job.
- We had previously specified "package-name" which contains the matrix of the packages. But it's "Required if `package-version-ids` input is not given". It fetches ALL the id's of the packages in the first run and then ofcourse it complains about "No PackageVersion with ID:" in the later runs for other packages.
=> Cleanup **DAT** branches

liquibase-standard/src/main/java/liquibase/changelog/DatabaseChangeLog.java, liquibase-standard/src/test/groovy/liquibase/changelog/DatabaseChangeLogTest.groovy
If a changelog file path starts with ".." , Liquibase was removing the first "." thus could not find the file. This PR fixes this behavior.
Bug introduced in Liquibase 4.21.0 by PR https://github.com/liquibase/liquibase/pull/3853 .
=> Fix paths starting with dot dot

liquibase-standard/src/main/java/liquibase/parser/core/yaml/YamlChangeLogParser.java, liquibase-standard/src/test/groovy/liquibase/parser/core/yaml/YamlChangeLogParser_RealFile_Test.groovy, liquibase-standard/src/test/resources/liquibase/parser/core/yaml/emptyChangeLog.yaml
This pr created for the https://github.com/liquibase/liquibase/issues/4223 issue. I have to compare xml and yml behavior for understanding expected behavior.
````console
$ ./liquibase update
####################################################
####################################################
Starting Liquibase at 21:56:52 (version 4.22.0 #9559 built at 2023-05-10 20:45+0000)
Liquibase Version: 4.22.0
Liquibase Open Source 4.22.0 by Liquibase
Database is up to date, no changesets to execute
UPDATE SUMMARY
Run:                          0
Previously run:               0
Filtered out:                 0
-------------------------------
Total change sets:            0
Liquibase command 'update' was executed successfully.
````
````console
$ ./liquibase update …
```
=> Liquibase should not fail when change log has only `databaseChangeLog` tag

liquibase-standard/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java, liquibase-standard/src/main/java/liquibase/command/core/UpdateCommandStep.java, liquibase-standard/src/main/java/liquibase/command/core/helpers/DatabaseChangelogCommandStep.java
With the latest command refactoring, we performed some changes which unintentionally stops getting the performance benefits we got after merging #2190.
In order to get the same result we come up with a new solution, that after the command refactoring was performed would be easier than reusing the same code provided by #2190. We have added a new flag (`isDBLocked`) to control whether it's needed to acquire the lock before running the update command. 
Also after command refactoring uptodateFastCheck started to provide false positives in multi tenant environments as reported on https://github.com/liquibase/liquibase/issues/4304 .
Fixes #4312 
Fixes #4304 
- With new command refactoring changes made recently and now using the new attribute added (`isDBLocked`) we think there is no need to …
=> Fix update fast check behavior

liquibase-integration-tests/src/test/groovy/liquibase/command/UpdateCommandsIntegrationTest.groovy, liquibase-standard/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java, liquibase-standard/src/main/java/liquibase/command/core/helpers/DatabaseChangelogCommandStep.java
Fix issue: #4448 
I spent a while trying to implement a `FastCheckCommandStep` class because the root cause really is `we want to not lock the database if fastcheck reports we are up to date`, but ending up stumbling on a number of issues relating to the different usages of the `LockServiceCommandStep`. Because the lock service step is so "low level" it doesn't really work to add the necessary parameters to support a fast check. I thought about implementing a `FastCheckLockServiceCommandStep` but just resolved I was getting in too deep and should be able to fix this in a few lines of code for now.
I'm not sure if `FastCheckLockServiceCommandStep` is the right move for the future or if we should choose some other route.
=> Fix deploymentId not populating after locking

liquibase-integration-tests/src/test/resources/changelogs/asany/complete/root.changelog.xml
Fixes #4413 
Despite the title and description of issue #4413, the actual cause of the failing IT was *not* an undocumented IT requirement, but the fact that the author of the IT (unintentionally) used the static prefix "liquibase" instead of the dynamic prefix provided by the test driver.
The solution hence is to replace the static prefix by the dynamic prefix. Hence, there is nothing wrong with the test documentation.
N/A
N/A
N/A
=> Fixes issue #4413: Undocumented IT requirement: Username "liquibase"

liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/generateChangelog.test.groovy, liquibase-standard/src/test/groovy/liquibase/integration/commandline/CommandLineUtilsTest.groovy, liquibase-standard/src/test/groovy/liquibase/util/csv/CSVReaderTest.groovy
CommandLineUtil was failing for german locales because we translate text we're asserting on into german.
Fixes #4216
Just fixes the test
Nothing
=> Fixed CommandLineUtilsTest for german locale

liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseDatabaseDiff.java, liquibase-standard/src/main/java/liquibase/command/core/helpers/DbUrlConnectionCommandStep.java, liquibase-standard/src/main/java/liquibase/command/core/helpers/PreCompareCommandStep.java, liquibase-standard/src/main/java/liquibase/command/core/helpers/ReferenceDbUrlConnectionCommandStep.java
MDC properties like outputSchemas, referenceSchemas, schemas, liquibaseTargetUrl, added to update and diff maven mojos.
=> add additional MDC properties to update and diff mojos (DAT-14672)

liquibase-integration-tests/src/test/resources/changelogs/common/common.tests.changelog.xml
Test timestamp_column_precision9 should test with 9 and not 6 . Seems it was changed by an unrelated PR some months ago but we need to restore the old behavior .
=> timestamp_column_precision9 should test with 9 and not 6

liquibase-standard/src/main/java/liquibase/sqlgenerator/core/AddColumnGenerator.java, liquibase-standard/src/test/java/liquibase/sqlgenerator/core/AddColumnGeneratorTest.java
Before, only `references: tablename(columnname)` worked. Now both `tablename(columnname)` and `tablename ( columnname )` work.
=> Allow whitespace within a foreign key statement

liquibase-integration-tests/src/test/resources/changelogs/asany/complete/root.changelog.xml, liquibase-integration-tests/src/test/resources/changelogs/common/common.tests.changelog.xml, liquibase-standard/src/main/java/liquibase/database/core/SybaseASADatabase.java, liquibase-standard/src/main/java/liquibase/datatype/core/TimestampType.java, liquibase-standard/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGenerator.java
Fixes #3971 
This PR tells Liquibase that SQL Anywhere is actually able to deal with the `WITH TIMEZONE` feature of the `TIMESTAMP` data type, and adds a test case to the existing integration test suite which proofs the functionality.
N/A
N/A
Developed using latest SQL Anywhere 17.0.11-7254 on Windows 10 Pro (German) as a standalone engine (hence not using Testcontainers), using latest official product documation from https://help.sap.com/docs/SAP_SQL_Anywhere/93079d4ba8e44920ae63ffb4def91f5b/81fe344c6ce21014a4f29d9e0af358b9.html?locale=en-US&q=TIMESTAMP%20WITH%20TIMEZONE.
=> Fixed #3971: "SAP SQL Anywhere 17.0.11: Liquibase incorrectly reports that TIMESTAMP requested precision is longer than TIMESTAMP supported precision"

liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java, liquibase-standard/src/main/java/liquibase/logging/mdc/MdcKey.java
=> add liquibaseHostName MDC key (DAT-14956)

liquibase-standard/src/main/java/liquibase/changelog/AbstractChangeLogHistoryService.java, liquibase-standard/src/main/java/liquibase/changelog/ChangeLogHistoryService.java, liquibase-standard/src/main/java/liquibase/changelog/OfflineChangeLogHistoryService.java, liquibase-standard/src/main/java/liquibase/changelog/StandardChangeLogHistoryService.java, liquibase-standard/src/main/java/liquibase/changelog/visitor/UpdateVisitor.java
New method liquibase.changelog.visitor.UpdateVisitor#updateCheckSumIfRequired returns null if the change set has a stored checkSum, but it should return the old checksum value.
So everytime we get here we are updating the checksums for already executed checksums with the same value. It's not breaking anything but performance will be affected.
Steps To Reproduce
Run update using a changelog with 1 changeset
Add a new changeset to changelog
Run update SQL: first changelog will have the checksum updated and the second will execute just fine.
ex:
```
UPDATE public.databasechangelog SET MD5SUM = '9:56da2f293105bdbf802515b0581600f1' WHERE ID = '2' AND AUTHOR = 'fl' AND FILENAME = 'changelogs/changelog/simple_changelog.xml';
INSERT INTO public.databasechangelog (ID, AUTHOR, FILENAME, …
```
=> Fix checksum upgrade changes preventing useless updates and using AbstractChangeLogHistoryService for extensions compatibility

liquibase-standard/src/main/java/liquibase/changelog/AbstractChangeLogHistoryService.java, liquibase-standard/src/main/java/liquibase/changelog/ChangeLogHistoryService.java, liquibase-standard/src/main/java/liquibase/changelog/OfflineChangeLogHistoryService.java, liquibase-standard/src/main/java/liquibase/changelog/StandardChangeLogHistoryService.java, liquibase-standard/src/main/java/liquibase/changelog/visitor/UpdateVisitor.java
New method liquibase.changelog.visitor.UpdateVisitor#updateCheckSumIfRequired returns null if the change set has a stored checkSum, but it should return the old checksum value.
So everytime we get here we are updating the checksums for already executed checksums with the same value. It's not breaking anything but performance will be affected.
Steps To Reproduce
Run update using a changelog with 1 changeset
Add a new changeset to changelog
Run update SQL: first changelog will have the checksum updated and the second will execute just fine.
ex:
```
UPDATE public.databasechangelog SET MD5SUM = '9:56da2f293105bdbf802515b0581600f1' WHERE ID = '2' AND AUTHOR = 'fl' AND FILENAME = 'changelogs/changelog/simple_changelog.xml';
INSERT INTO public.databasechangelog (ID, AUTHOR, FILENAME, …
```
=> [DAT-15383] Fix checksum upgrade changes preventing useless updates and using AbstractChangeLogHistoryService for extensions compatibility

liquibase-integration-tests/src/test/resources/changelogs/h2/complete/empty.runWith.changelog.xml, liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/update.test.groovy, liquibase-standard/src/main/java/liquibase/changelog/ChangeSet.java
Modifies `ChangeSet` getter to return null when runWith is set to an empty string. 
I know people aren't always necessarily fans of having logic in getters but I'd have needed to add a conditional `|| getRunWith().isEmpty()` to like 4 different places or so I opted for this route. I'd be happy to swap to the other method though and leave the getter alone.
=> Do not throw exception when runWith is empty string (DAT-14316)

liquibase-standard/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java, liquibase-standard/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGenerator.java
Fixes #4489 
Cause: There is no way to detect the size unit in the JDBC standard.
Solution: Using a native query to detect the size unit.
N/A
N/A
N/A
=> Fixed #4489: SQL Anywhere incorrectly reports VARCHAR(n CHAR) as VARCHAR(n)

liquibase-standard/src/main/java/liquibase/command/core/ChangelogSyncCommandStep.java
changelog-sync-to-tag marks as executed all changesets after upgrade to v. 4.23 if the tag  is already in database
=> [DAT-15489] Fixes changelog-sync-to-tag ignores the tag if  it is already in database after 4.23.0

liquibase-standard/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java
Update logDeploymentOutcomeMdc to add `mdc` values before logging `update` command execution result"
```
{
"timestamp": "2023-07-27T19:58:58.897Z",
"level": "INFO",
"class": "liquibase.command",
"thread": "1",
"message": "Update command completed successfully.",
"operationStart": "2023-07-27T16:58:58.367",
"liquibaseCommandName": "update",
"liquibaseInternalCommand": "update",
"liquibaseTargetUrl": "jdbc:postgresql://localhost:5438/lbcat",
"liquibaseCatalogName": "lbcat",
"liquibaseSchemaName": "",
"rollbackOnError": "true",
"commandLabelFilter": "primaryTable",
"commandContextFilter": "fltr1",
"deploymentId": "0487938863",
"changelogFile": "changelogWithDropTableNotExistChangeset.xml",
"rowsAffected": "1",
"deploymentOutcomeCount": "1",
"changesetsUpdated": {
"changeset": [
{ …
```
=> DAT-15208 :: Changeset object added back to "Update command completed successfully" JSON

liquibase-standard/src/main/java/liquibase/resource/DirectoryPathHandler.java
=> decode URL encoded path in DirectoryPathHandler (DAT-15154)

liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/DatabaseTestSystem.java
If you try to load an external driver Liquibase will throw an exception saying that it could not load java.sql.DriverManager that is a standard java class.  This PR fix the issue.
=> Fix database test system external driver load.

liquibase-standard/src/main/java/liquibase/util/SqlUtil.java
Fixes https://github.com/liquibase/liquibase/issues/4514.
This PR implements for `LONG VARCHAR` and `LONG NVARCHAR` the similar solution as implemented for `BLOB`, but with the distinction for single-quoted strings.
The fix assumes that the RDBMS is compliant with the description found at https://docs.oracle.com/javase/8/docs/api/java/sql/DatabaseMetaData.html#getColumns-java.lang.String-java.lang.String-java.lang.String-java.lang.String-:
>COLUMN_DEF String => default value for the column, which should be interpreted as a string **when the value is enclosed in single quotes** (may be `null`)
N/A
=> Fixed: LONG VARCHAR DEFAULT NULL instead of LONG VARCHAR DEFAULT 'NULL'

liquibase-standard/src/main/java/liquibase/command/core/helpers/LockServiceCommandStep.java, liquibase-standard/src/test/groovy/liquibase/ThreadLocalScopeManagerTest.groovy
Liquibase commands are not thread safe even with ThreadLocalScopeManager . 
Exception StackTrace
```
Caused by: liquibase.exception.CommandExecutionException: liquibase.exception.LockException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Error executing SQL CREATE TABLE PUBLIC.DATABASECHANGELOGLOCK (ID INT NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED TIMESTAMP, LOCKEDBY VARCHAR(255), CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY (ID)): The object is already closed [90007-193]
at liquibase.command.CommandScope.execute(CommandScope.java:235)
at liquibase.Liquibase.lambda$update$0(Liquibase.java:237)
at liquibase.Scope.lambda$child$0(Scope.java:194)
at liquibase.Scope.child(Scope.java:203)
at liquibase.Scope.child(Scope.java:193)
at …
```
=> not to use class field for thread safe.

liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java, liquibase-standard/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java
Removes duplicate init as it has been already initialized on DatabaseChangeLogCommandStep
=> Fix Regression in 4.23.1 where Log table is created multiple times for H2 and HSQLDB

liquibase-standard/src/main/java/liquibase/Liquibase.java
Fixes `Liquibase.java` rollback commands, which were missing the changelog parameters as an input.
Fixes #4406
=> Added changelog parameters to rollback commands

liquibase-standard/src/main/java/liquibase/lockservice/StandardLockService.java
Fixes #4325
If changelog-lock-wait-time-in-minutes was set to 0 and there was not a lock in the database then acquireLock was not called => 
it was not possible to acquire the lock and the error message was wrong : "Could not acquire change log lock.  Currently locked by UNKNOWN"
It's necessary to try at least one time to acquire the lock before waiting (or not if this parameter is set to 0) to retry.
I'm not able to identify if new unit / integration tests are necessary. The current tests are still OK
A PR for liquibase-mongodb is already created : https://github.com/liquibase/liquibase-mongodb/pull/375
=> fix standardlockservice when changelog-lock-wait-time-in-minutes is set to 0 and lock does not exist in database

liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java, liquibase-standard/src/main/java/liquibase/Scope.java, liquibase-standard/src/main/java/liquibase/ThreadLocalScopeManager.java, liquibase-standard/src/main/java/liquibase/command/core/helpers/AbstractOutputWriterCommandStep.java, liquibase-standard/src/main/java/liquibase/resource/ZipResourceAccessor.java, liquibase-standard/src/test/groovy/liquibase/change/StandardChangeTest.groovy, liquibase-standard/src/test/java/liquibase/TestScopeManager.java, liquibase-standard/src/test/java/liquibase/integration/ant/AbstractAntTaskTest.java, liquibase-standard/src/test/java/liquibase/verify/change/VerifyChangeClassesTest.java
This is remaining part of https://github.com/liquibase/liquibase/issues/3446
To make liquid base work with maven concurrent build (-T 1C)
It uses scope manager, but it need to be set in static so before any plugins action kick in.
Also it should not inherit any scope, so each plugin execution can start on clean scope isolated from another.
=> support concurrent build in maven plugin

liquibase-integration-tests/src/test/groovy/liquibase/command/diff/DiffIntegrationTest.groovy, liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/diff.test.groovy, liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/diffChangelog.test.groovy, liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/snapshotReference.test.groovy, liquibase-standard/src/main/java/liquibase/command/core/GenerateChangelogCommandStep.java, liquibase-standard/src/main/java/liquibase/command/core/helpers/AbstractDatabaseConnectionCommandStep.java, liquibase-standard/src/main/java/liquibase/command/core/helpers/DbUrlConnectionCommandStep.java, liquibase-standard/src/main/java/liquibase/command/core/helpers/ReferenceDbUrlConnectionCommandStep.java
Adding support to parameters referenceLiquibaseCatalogName and referenceLiquibaseSchemaName.
Instead of adding a global parameter as referenceCatalogName and referenceSchemaName, it was added as a parameter only to the commands that would use it, namely: Diff, diffChangelog and SnapshotReference .
=> Adding support to parameters referenceLiquibaseCatalogName and referenceLiquibaseSchemaName.

liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java, liquibase-cli/src/test/groovy/liquibase/integration/commandline/LiquibaseCommandLineTest.groovy
=> Make sure that the correct argument name is displayed in help for commands with aliases DAT-15681

liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java, liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/update.test.groovy, liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/updateCount.test.groovy, liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/updateCountSql.test.groovy, liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/updateSql.test.groovy, liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/updateToTag.test.groovy, liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/updateToTagSql.test.groovy, liquibase-standard/src/main/java/liquibase/changelog/ChangeSet.java, liquibase-standard/src/main/java/liquibase/changelog/visitor/ChangeExecListener.java, liquibase-standard/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java, liquibase-standard/src/main/java/liquibase/command/core/UpdateCommandStep.java, liquibase-standard/src/main/java/liquibase/logging/mdc/MdcKey.java, liquibase-standard/src/main/java/liquibase/report/UpdateReportParameters.java
=> add update report (DAT-15576)

liquibase-dist/src/main/archive/liquibase.bat
Liquibase 4.23.1 won't work on windows if there is no JAVA_HOME system variable set
when run liquibase you get the error
Files\liquibase\\jre"" was unexpected at this time.
caused by https://github.com/liquibase/liquibase/pull/4306
=> Fix liquibase 4.23.1 won't work on windows if there is no JAVA_HOME system variable set

liquibase-standard/src/main/java/liquibase/changelog/DatabaseChangeLog.java
Do not call normalizePath inside the loop for the same variable + just call it if everything else is fine.
=> Fix poor performance of listunrunchangesets

liquibase-standard/src/main/java/liquibase/datatype/core/CharType.java, liquibase-standard/src/main/java/liquibase/datatype/core/VarcharType.java, liquibase-standard/src/test/groovy/liquibase/datatype/DataTypeFactoryTest.groovy
Fixes #4682 
This PR cuts away the CHAR ending when it is found in the sole parameter, and the value's pattern is "the word CHAR follows a number". This is correct, as MSSQL expects the number to be given in characters, but just does not understand the subsequent word "CHAR".
N/A
N/A
N/A
=> Fixed: #4682 - MSSQL: Doesn't support (n CHAR) syntax, but only (n) syntax

liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/history.test.groovy, liquibase-standard/src/main/java/liquibase/command/core/InternalHistoryCommandStep.java, liquibase-standard/src/test/groovy/liquibase/command/InternalHistoryCommandStepTest.groovy
=> include tag in history tabular output (DAT-15244)

liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/MavenLog.java, liquibase-standard/src/test/groovy/liquibase/datatype/DataTypeFactoryTest.groovy
Fixes #4669 
Liquibase's assumption that a space is solely good for separating *additional information* from the type name is simply wrong. Even the ANSI SQL standard contains type names with blank in the middle.
Hence I have added those special cases that I am aware of (in my case the ones from SQL Anywhere) to the list of known excemptions.
=> Fixed: Fails to detect LONG VARCHAR as CLOB and LONG BINARY as BLOB

liquibase-standard/src/main/java/liquibase/ContextExpression.java, liquibase-standard/src/main/java/liquibase/LabelExpression.java, liquibase-standard/src/test/groovy/liquibase/ContextExpressionTest.groovy, liquibase-standard/src/test/groovy/liquibase/LabelExpressionTest.groovy
Fixes #4763 
Having a changeset like the one below:
```
<changeSet author="Liquibase" id="labelExpressionIssue" labels="foo">
<createTable tableName="TABLE_1">
<column name="COL1" type="INT"/>
</createTable>
</changeSet>
```
When a LabelExpression is defined as:
```
new LabelExpression(new String[]{"bar", "test"})
```
or:
```
new ArrayList<>(List.of("bar, test"))
```
What was happening was that labels were ignored and changesets were deployed anyway.
=> Fix LabelExpression constructors when using array or collection

liquibase-dist/pom.xml, pom.xml
As per https://oracledbwr.com/oracle-release-schedule-of-current-database-releases/ , Oracle driver 19.x is the current LTS supported version . This PR rollback Oracle driver version from 23 to 19 .
Fixes #4903
=> Rollbacks Oracle Driver to LTS series 19.x 

liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy
This changes the behavior of the `CommandTests.copyResource` method to copy the test files right before test execution, rather than copying them all at test framework startup. This is advantageous for two reasons:
- when running a subset of the command tests, the tests will run faster because there are fewer unrelated copy actions occurring
- each test is more atomic, and will rely less on the copied test artifacts from a previous test run
=> CommandTests: copy files on the fly, not at startup

liquibase-integration-tests/src/test/resources/changelogs/common/common.tests.changelog.xml, liquibase-standard/src/main/java/liquibase/precondition/core/TableIsEmptyPrecondition.java, liquibase-standard/src/main/java/liquibase/sqlgenerator/core/TableIsEmptyGenerator.java, liquibase-standard/src/main/java/liquibase/statement/core/TableIsEmptyStatement.java, liquibase-standard/src/main/resources/META-INF/services/liquibase.sqlgenerator.SqlGenerator
Optimise the logic for verifying if a table is empty: instead of selecting count the table, uses exists. 
SQL Ansi for all databases query.
NA
Added tests. Fixes #4734
=> Optimise the logic for tableIsEmpty check constraint 

.github/workflows/build-branch.yml, liquibase-standard/src/main/java/liquibase/structure/core/ForeignKey.java
Fixes #4597 
Two foreign keys with different names are by definition *different* foreign keys on all RDBMS, not just on SQL Anywhere. It is the administrator's sole discretion to design two identical foreign keys with different names.
This change affects *all* RDBMS, not just SQL Anywhere. It changes Liquibase's general behavior in such a way that the names of foreign keys *always* are considered when comparing two foreign keys. While these keys compare as "being equal", they are not "identical", hence `compare` is not be changed, while `equals` is.
N/A
N/A
=> SQL Anywhere allows two foreign keys to differ only by name

liquibase-integration-tests/src/test/groovy/liquibase/command/core/UpgradeChecksumVersionIntegrationTest.groovy, liquibase-standard/src/main/java/liquibase/changelog/visitor/ValidatingVisitor.java
Fixes #4460.
The fix ensures that the field `storedFilePath` for each `changeSet` in `UpdateChangeSetChecksumGenerator` is set. Then, the `WHERE` condition of the produced `UPDATE` statements matches the database entry for the respective change set.
=> Fetch ran change sets before updating check sums

liquibase-standard/src/main/java/liquibase/change/AbstractSQLChange.java, liquibase-standard/src/main/java/liquibase/changelog/visitor/ValidatingVisitor.java, liquibase-standard/src/main/java/liquibase/util/ValidatingVisitorUtil.java
AbstractSqlChange checksum had the checksum calculated value changed for Liquibase versions 4.19.1 to 4.23.1 due to some changes on the way that we call it when using runWith="anything". This PR validates the v8 checksum using the alternative algorithm as a way to allow users to upgrade to checksums v9 without facing any errors or unexpected behaviours
=> [DAT-15924] Handle AbstractSQLChange runWith checksum v8 variants

liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java, liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/calculateChecksum.test.groovy, liquibase-standard/src/main/java/liquibase/Liquibase.java, liquibase-standard/src/main/java/liquibase/command/core/CalculateChecksumCommandStep.java, liquibase-standard/src/main/java/liquibase/integration/commandline/Main.java
`TypeBug`       
`APIBreakingChanges`
`newContributors` 
As described in #3814 the calculate-checksum command was not able to parse arguments which contains ``::`` characters. So the user is not able to use this command in conjuction with changeset Identifiers containing ``::``.
As suggested in the issue I have split the parameter changeSetIdentifier into three seperate parameters
- changeSetPath
- changeSetId
- changeSetAuthor
Herefor I made changes to the ``CalculateChecksumCommandStep`` and introduced the parameters mentioned above. I had to adjust the calculate-checksum API in Main and the Liquibase class.
So the user has to adjust his use of the calculate-checksum command with the new parameters like so.
``liquibase calculate-checksum --changeSetPath="changelog.xml" …
=> Split calculate-checksum parameter changeSetIdentifier into changeSetPath / changesetId / changeSetAuthor 

liquibase-integration-tests/src/test/groovy/liquibase/command/core/UpgradeChecksumVersionIntegrationTest.groovy, liquibase-integration-tests/src/test/resources/changelogs/h2/checksum/create-table.sql, liquibase-integration-tests/src/test/resources/changelogs/h2/checksum/dbms-filter-changelog.xml, liquibase-standard/src/main/java/liquibase/changelog/ChangeLogIterator.java, liquibase-standard/src/main/java/liquibase/changelog/ChangeSet.java, liquibase-standard/src/main/java/liquibase/changelog/filter/DbmsChangeSetFilter.java
Checksums (v8) are calculated differently for XML changesets with the dbms attribute on the change itself (instead of the changeset) after 4.22.0 .
Fixes #4665
Fixes #4457
=> [DAT-16006] Fixing v8 Checksum calculation issue when using sql dbms attribute

liquibase-dist/src/main/archive/liquibase.bat
Fix environment variable handling in liquibase.bat
1: Don't error if JAVA_HOME is defined and surrounded by double-quotes
2: If auto-setting JAVA_HOME, fix double-backslash before jre
3: If auto-setting JAVA_HOME, remove quotes around JAVA_HOME
=> Fix liquibase bat

liquibase-standard/src/main/java/liquibase/database/AbstractJdbcDatabase.java
Fixes #4518
This PR fixes both cases described in #4518:
The solution is to lookahead (but not capture) for a subsequent opening parenthesis adjacent *after* `AS`.
The solution is to require (and capture) whitespace *before* `AS`.
The solution might be incomplete, as there might be more cases to cover, e. g. when a RDBMS allows `AS` adjacent after the quotes of a quoted view name, etc. The target of this PR is **not** to resolve hypothetical or synthetical cases, but to resolve only actual cases proven to fail in reality (here: both cases were reported to actually fail in existing SQL Anywhere databases).
N/A
N/A
=> generateChangelog creates crippled view definition SQL

liquibase-standard/src/main/java/liquibase/Liquibase.java
- [ X ] Enhancement/New feature (adds functionality without impacting existing logic)
Some update() methods were missing the '@Deprecated' annotation, which made the javadocs outdated. I added the annotation to these methods: 
- update(String contexts, Writer output)
- update(Contexts contexts, Writer output)
- update(Contexts contexts, LabelExpression labelExpression, Writer output)
- update(Contexts contexts, LabelExpression labelExpression, Writer output, boolean checkLiquibaseTables)
This will change the javadocs documentation
It's my understanding that all liquibase.update() methods are deprecated. If not, ignore this PR.
=> Add '@Deprecated' annotation to update() methods

liquibase-standard/src/main/java/liquibase/diff/compare/core/IndexComparator.java
This PR removes two unnecessary conditions, which always evaluate to `true`, as detected by IntelliJ.
The reason is: in line 71, if any of them is 0, then the method return.
And since they are the result of `list.size()`, they can not be negative.
And because of the previous two points, both must be more than 0, and so the conditions are not needed.
=> Remove unnecessary conditions in IndexComparator

liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java, liquibase-standard/src/main/java/liquibase/command/AbstractCliWrapperCommandStep.java, liquibase-standard/src/main/java/liquibase/integration/commandline/LiquibaseCommandLineConfiguration.java
If true, all command arguments marked as hidden will be shown in the help output, ignoring the hidden flag. NOTE, due to the order of value provider loading at such an early point in Liquibase startup, you MUST set this as a environment variable. Command line parameters will not be recognized.
=> add option to show hidden arguments in help output

liquibase-standard/src/main/java/liquibase/datatype/core/CharType.java, liquibase-standard/src/main/java/liquibase/datatype/core/VarcharType.java, liquibase-standard/src/test/java/liquibase/verify/saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets/mergeColumns/postgresql.sql
Fixes #4662 
This PR cuts away the CHAR ending when it is found in the sole parameter, and the value's pattern is "the word CHAR follows a number". This is correct, as PostgreSQL expects the number to be given in characters, but just does not understand the subsequent word "CHAR".
N/A
I noticed that special handling was in place producing "CHARACTER VARYING" when "CHARACTER (2147483647)" was found. I kept that solution and extended it to apply to "CHARACTER (2147483647 CHAR)", too. Nevertheless, IMHO that special handling is wrong for "CHARACTER" (while it is correct for "CHARACTER VARYING") as it produces a VARCHAR on the database, not a CHAR. As this failure existed before this PR, it is not the task of this PR to resolve that bug. Nevertheless, it makes sense to fix that in a separate …
=> Fixed: #4662 - PostgreSQL: Doesn't support (n CHAR) syntax, but only (n) syntax.

liquibase-core/pom.xml
=> Makes picocli dependency optional for core

liquibase-standard/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java
Fixes #4891.
Update the `isUpToDateFastCheck` method to include the changelog file path in the cache key, preventing the bug reported in the issue, as suggested by @nwwerum. 
I also created a simple Spring app with steps to reproduce this bug, you may find it here https://github.com/ggwadera/liquibase-bug-4891.
None as far as I know.
This bug was not captured in any of the automated tests. I tried to include a unit test for this but unfortunately I couldn't get it working. Would gladly accept any suggestions for this.
From my testing, this bug only happens with an already initialized database. When more than one `SpringLiquibase` beans are present, the first ones that have already been applied causes the `isUpToDateFastCheck` cache key to be marked as up-to-date. This prevents the …
=> Add changelog file path to upToDateFastCheck cache key (#4891)

liquibase-standard/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGenerator.java
Hello. I created a small PR for my ticket: https://github.com/liquibase/liquibase/issues/5126
As a continuous https://github.com/liquibase/liquibase/pull/4688
You can find all my examples on my ticket.
Please check and MariaDB instance, and MySQL instance.
=> 5126 fix extra column info for mariadb database

liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java, liquibase-integration-tests/src/test/java/liquibase/dbtest/oracle/OracleIntegrationTest.java, liquibase-integration-tests/src/test/resources/changelogs/common/common.tests.changelog.xml, liquibase-integration-tests/src/test/resources/changelogs/common/index.with.associatedwith.changelog.xml, liquibase-standard/src/main/java/liquibase/change/core/CreateIndexChange.java, liquibase-standard/src/test/groovy/liquibase/change/core/CreateIndexChangeTest.groovy
Fixes #4794
Change type: CreateIndex
Issue: the associatedWith property is not deserialized from the changelog definition resulting in property always being null
Resolution: set the isChangeProperty to true on the DatabaseChangeProperty decorating the property accessor. 
Bug was introduced when the DatabaseChangeProperty annotation was added due to the createChangeMetaData method in AbstractChange expecting the annotation to either exist on the property with a value of isChangeProperty=true or the annotation to be absent entirely (which was the case previously).
=> CreateIndex associatedWith property deserialization issue

liquibase-standard/src/main/java/liquibase/diff/output/changelog/core/MissingTableChangeGenerator.java, liquibase-standard/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java
=> Handles snapshot of Oracle temporary tables + ignore queue tables

liquibase-standard/src/main/java/liquibase/plugin/AbstractPluginFactory.java
- [x ] Bug fix (non-breaking change which fixes expected existing functionality)
fixes issue #5142
=> load services using ServiceLocator if allInstances is empty

liquibase-standard/src/main/java/liquibase/changelog/visitor/ValidatingVisitor.java, liquibase-standard/src/main/java/liquibase/exception/ValidationFailedException.java
Currently onErrorMessage and onFailMessage are logged only if the log-level property is set to something higher than info. As they are custom error messages they should be logged everytime an error occurs.
=> Makes sure that precondition onErrorMessage and onFailMessage are logged when an error happens

liquibase-standard/src/main/java/liquibase/changelog/RanChangeSet.java, liquibase-standard/src/test/java/liquibase/changelog/RanChangeSetTest.java
Liquibase path handling has changed over time leading to valid paths not being accepted thus breaking changesets. This fix aims to check for all possible path variations that Liquibase used over time.
=> Fix Liquibase changeset relative path check

liquibase-standard/src/main/java/liquibase/statement/ExecutablePreparedStatementBase.java, liquibase-standard/src/test/java/liquibase/statement/InsertExecutablePreparedStatementTest.java
Apply SQL visitors to, and log, prepared SQL.
Fixes #5098.
New API `protected String applyVisitors(String sql, List<SqlVisitor> sqlVisitors)` on `ExecutablePreparedStatementBase` is exposed to subclasses.
An extension which extends `ExecutablePreparedStatementBase` or implements `ExecutablePreparedStatement` could require some changes to adopt the the desired behavior.
=> Apply SQL visitors to prepared SQL

liquibase-standard/src/main/java/liquibase/configuration/core/EnvironmentValueProvider.java, liquibase-standard/src/test/groovy/liquibase/configuration/core/EnvironmentValueProviderTest.groovy
Do not warn on unrecognized LIQUIBASE_ environment variables when the environment variable matches an alias.
=> Do not warn when env var matches argument alias (DAT-16117)

liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/changelogSync.test.groovy, liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/markNextChangesetRan.test.groovy, liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/tag.test.groovy, liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/update.test.groovy, liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/updateCount.test.groovy, liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/updateTestingRollback.test.groovy, liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/updateToTag.test.groovy, liquibase-standard/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java, liquibase-standard/src/main/java/liquibase/command/core/MarkNextChangesetRanCommandStep.java, liquibase-standard/src/test/groovy/liquibase/util/TestUtil.groovy
=> generate deployment ID for all update family commands (DAT-16240)

liquibase-standard/src/main/java/liquibase/changelog/visitor/UpdateVisitor.java
Invoke database.commit only if something was executed
When running over large changesets , every commit means a request and for cloud databases it means a new request to the cloud that can take up some time.
=> Invoke database.commit only if needed

liquibase-standard/src/main/java/liquibase/util/ValidatingVisitorUtil.java
Requires https://github.com/liquibase/liquibase-pro/pull/1342
If we ignore 4.21.x generated checksums this whole PR could be ignored and we would only have 1 line change in pro code.
=> Fixes problematic V8 checksums for pro CreateFunctionChange

liquibase-standard/src/main/java/liquibase/plugin/AbstractPluginFactory.java, liquibase-standard/src/main/java/liquibase/report/UpdateReportParameters.java
=> Added tag attribute to update report parameters DAT-15640

.github/workflows/release-published.yml
chore(release-published.yml): add SFTP upload step for Liquibase index.htm file to remote directory '/xml/ns/dbchangelog/'
I am reusing the generated `index.htm` file from the previous workflow step:
```
- name: Index.htm file upload
env:
AWS_ACCESS_KEY_ID: ${{ secrets.LIQUIBASEORIGIN_ACCESS_KEY_ID }}
AWS_SECRET_ACCESS_KEY: ${{ secrets.LIQUIBASEORIGIN_SECRET_ACCESS_KEY }}
AWS_DEFAULT_REGION: us-east-1
run: |
version=${{ needs.setup.outputs.version }}
arr=(${version//./ })
xsd_version=${arr[0]}"."${arr[1]}
mkdir index-file
aws s3 cp s3://liquibaseorg-origin/xml/ns/dbchangelog/index.htm index-file
if ! grep -q ${xsd_version} index-file/index.htm ; then
sed -ie "s/<\/ul>/  <li><a href=\"\/xml\/ns\/dbchangelog\/dbchangelog-${xsd_version}.xsd\">dbchangelog-${xsd_version}.xsd<\/a><\/li>\n<\/ul>/ …
```
=> DAT-16300      WPEngine :: Update index.html with the released version of OSS xsd

liquibase-standard/src/main/java/liquibase/Liquibase.java, liquibase-standard/src/main/java/liquibase/command/core/CalculateChecksumCommandStep.java, liquibase-standard/src/test/groovy/liquibase/command/CalculateChecksumCommandStepTest.groovy
Fixes #5225 
`CalculateCheckSum()` Liquibase API method was failing, because internally when using the command step we were proving both arguments at the same time and this was causing a validation to return an error because both argument options were provided at the same time when only one should be provided at a single time. This error has been fixed and some unit tests have been added.
- None
- None
-
=> Fix calculateCheckSum issue when using Liquibase API method

liquibase-standard/pom.xml
=> Add missing classes to osgi.serviceloader

liquibase-integration-tests/src/test/resources/changelogs/common/common.tests.changelog.xml, liquibase-standard/src/main/java/liquibase/precondition/core/ColumnExistsPrecondition.java
- Handled DatabaseException thrown by PreparedStatement when the table is missing
- Added integration test
Fixes #5271
Fixes #5246 
- [x ] Bug fix (non-breaking change which fixes expected existing functionality)
This PR fixes a bug introduced in 4.25.0 where ColumnExistsPrecondition fails with an error PreconditionErrorException when table that is supposed to contain the column is missing.
=> Fix #5271: ColumnExistsPrecondition throws error when table is missing

liquibase-cli/src/test/groovy/liquibase/integration/commandline/LiquibaseCommandLineTest.groovy, liquibase-standard/src/main/java/liquibase/GlobalConfiguration.java, liquibase-standard/src/main/java/liquibase/changelog/ChangeLogIterator.java, liquibase-standard/src/main/java/liquibase/changelog/visitor/ValidatingVisitor.java, liquibase-standard/src/test/groovy/liquibase/parser/core/xml/XMLChangeLogSAXParserTest.groovy
Adjust duplicate changeset validation
Added logic in the class to handle duplicate changeset identifiers based on a global configuration flag. This change provides an allowance for duplicated changesets but only when the flag is enabled in GlobalConfiguration. This was done to maintain backward compatibility with versions prior to 4.19.1 where ignoring duplicates was the default behavior (PR #3790) .
when this flag is set to true Liquibase won't fail with message:
```
Unexpected error running Liquibase: Validation Failed:
1 changesets had duplicate identifiers
a.xml::20231024-122624-01::fl
```
Fix #3881
=> Global flag to restore behaviour of not failing on duplicated changeset identifiers 

liquibase-standard/src/main/java/liquibase/integration/spring/SpringLiquibase.java
`TypeBug`
After liquibase changelog is applied to a Derby embedded database in Spring Boot context, database is shut down. Spring Boot application cannot run any further, as there is no connection available anymore. Sometimes it still works as the shutdown command isn't executed relyably.
Logic adapted from liquibase.integration.servlet.GenericServletListener.
Not sure why shutdown enabled is the default for Derby databases. Maybe worth to change the default, maybe worth allowing the setting to be overwritten with a property as stated here, but it doesn't work.
https://stackoverflow.com/questions/47314248/why-derby-connection-closed-after-liquibase-update
=> Disable Derby shutdown in Spring Boot context

liquibase-standard/src/main/java/liquibase/change/custom/CustomChangeWrapper.java
CustomTaskChanges were being executed twice: one to generate logs (and they don't generate any), and the other one was the actual run.
This PR prevents log generation execution.
=> Don't execute CustomTaskChanges twice

.github/workflows/build.yml
To ensure that runs for the master branch are not canceled when a new run is triggered, we can modify the group definition in the concurrency block. By creating a separate group for the master branch, we can prevent runs on the master branch from canceling each other.
=> cancel concurrent runs for non-master branches

liquibase-standard/src/main/java/liquibase/integration/commandline/CommandLineUtils.java
PR #4635 added new parameters to some methods in CommandLineUtils, but those methods are used by some extensions and maybe people that uses Liquibase. This PR restore the old methods signatures passing default values for the new parameters and deprecate them.
Example failure: https://github.com/liquibase/liquibase-vertica/actions/runs/7285058778/job/19851361305#step:8:2090
=> Restore and deprecate API methods used by extensions.

liquibase-integration-tests/src/test/groovy/liquibase/command/core/RollbackIntegrationTest.groovy, liquibase-integration-tests/src/test/groovy/liquibase/command/core/UpgradeChecksumVersionIntegrationTest.groovy, liquibase-integration-tests/src/test/groovy/liquibase/command/diff/DiffIntegrationTest.groovy, liquibase-integration-tests/src/test/groovy/liquibase/util/ShowSummaryUtilCommandTest.groovy
=> switch integration tests to use h2 where possible (DAT-16015)

liquibase-standard/src/main/java/liquibase/change/ChangeParameterMetaData.java, liquibase-standard/src/main/java/liquibase/parser/core/ParsedNode.java, liquibase-standard/src/test/groovy/liquibase/change/ChangeParameterMetaDataConversionTest.groovy, liquibase-standard/src/test/groovy/liquibase/parser/core/ParsedNodeTest.groovy, liquibase-standard/src/test/groovy/liquibase/parser/core/xml/XMLChangeLogSAXParser_RealFile_Test.groovy, liquibase-standard/src/test/groovy/liquibase/resource/ClassLoaderResourceAccessorTest.groovy, liquibase-standard/src/test/groovy/liquibase/resource/DirectoryResourceAccessorTest.groovy, liquibase-standard/src/test/groovy/liquibase/resource/FileSystemResourceAccessorTest.groovy, liquibase-standard/src/test/java/com/example/liquibase/change/ChangeWithPrimitiveFields.java, liquibase-standard/src/test/resources/liquibase/parser/core/xml/primitiveChangeLog.xml
This adds support for primitive types, particularly for custom change fields.
It could potentially change the converted value type of existing changes, but that's unlikely as the modified function only returns primitive types if explicitly requested.
Since such requests would fail in the past, I doubt this change will have an impact.
Changing existing `Change` subclasses to migrate from boxed types to primitive types is likely a bad idea since it may change the generated check sum.
The general change proposed here is however useful for new changes.
N/A
=> Introduce support for primitive types

liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/spock/LiquibaseIntegrationMethodInterceptor.java
Due to a combination of the logic in `liquibase-extension-testing` used to determine whether a particular test class matches the specified databases, and the fact that the integration tests run in a matrix in GHA, test classes with more than one `DatabaseTestSystem` specified will not run on any platform in GHA. This PR prevents someone from accidentally creating a test class that has more than one `DatabaseTestSystem`.
=> prevent multiple databases in test classes

liquibase-extension-testing/pom.xml, liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/wrapper/DockerDatabaseWrapper.java
=> map testcontainers to random available host port

.snyk
chore(.snyk): remove .snyk file as it is no longer needed for vulnerability management
=> DAT-15853  DevOps :: Deprecate Snyk and replace with GHAS

liquibase-snowflake/src/main/java/liquibase/datatype/core/ClobTypeSnowflake.java, liquibase-snowflake/src/main/resources/META-INF/services/liquibase.datatype.LiquibaseDataType, liquibase-snowflake/src/test/java/liquibase/datatype/ClobTypeSnowflakeTest.java
Added clob support (that is mapped to varchar max) for Snowflake. Now dbclh table should work fine.
=> [DAT-16607] Added clob support (that is mapped to varchar max) for Snowflake

liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/spock/LiquibaseIntegrationMethodInterceptor.java, liquibase-integration-tests/src/test/groovy/liquibase/command/core/ClearCheckSumsIntegrationTest.groovy, liquibase-integration-tests/src/test/groovy/liquibase/command/core/GenerateChangeLogMySQLIntegrationTest.groovy
=> automatically run dropall before and after all integration tests

liquibase-standard/src/main/java/liquibase/lockservice/LockService.java, liquibase-standard/src/main/java/liquibase/lockservice/MockLockService.java, liquibase-standard/src/main/java/liquibase/lockservice/OfflineLockService.java
When creating a new class that implements LockService interface, parameter names are inherited by default, with an existing typo in the word 'Lock'. Fixed that.
There is no impact of existing realizations, StandardLockService already has this typo fixed.
=> fixed typo that is inherited to other extensions

liquibase-standard/src/main/java/liquibase/change/custom/CustomChangeWrapper.java
CustomSQLChanges were being executed twice: one to generate logs and the other one was the actual run.
This PR prevents log generation execution.
This fixes #5523
=> Don't execute CustomSqlChanges to generate logs

liquibase-standard/src/main/java/liquibase/datatype/core/BooleanType.java, liquibase-standard/src/test/java/liquibase/sqlgenerator/core/AddColumnGeneratorTest.java
For boolean columns on MariaDB, go back from `TINYINT` to `TINYINT(1)` like it was before 4.25.1. See #5489 for more details.
Fixes #5489
Test Harness PR: https://github.com/liquibase/liquibase-test-harness/pull/727
=> MariaDB boolean: back to TINYINT(1) instead of TINYINT (MySQL)

liquibase-standard/src/main/java/liquibase/changelog/ChangeLogHistoryServiceFactory.java, liquibase-standard/src/test/groovy/liquibase/ThreadLocalScopeManagerTest.groovy
Make ChangelogHistoryServiceFactory#getChangeLogService synchronized to avoid concurrency issues when retreiving the ChangelogService. This problem was revealed in [these](https://github.com/liquibase/liquibase/actions/runs/7786641501/attempts/1) [previous](https://github.com/liquibase/liquibase/actions/runs/7786641501/job/21232934858) runs.
Resolves the error: 
```java.util.concurrent.ExecutionException: java.lang.IllegalStateException: liquibase.exception.LiquibaseException: liquibase.exception.DatabaseException: java.lang.NullPointerException: Cannot invoke "liquibase.changelog.ChangeLogHistoryService.getNextSequenceValue()" because the return value of "liquibase.changelog.ChangeLogHistoryServiceFactory.getChangeLogService(liquibase.database.Database)" is null```
This method has …
=> Fix ChangelogHistoryService NPE when running concurrently

liquibase-standard/src/main/java/liquibase/changelog/visitor/UpdateVisitor.java
In an effort to prevent exceptions from listeners causing an out-of-sync situation with the database changelog table, the update listeners are now fired after updating the DBCL table. The concern here is that some listener might throw an exception which causes the write to the DBCL table to not occur, yet the actual changeset contents have already been executed and persisted.
The database object quoting strategy is now being reset before the listeners are fired. If a listener depended on the object quoting strategy being set to some other value, this could break the listener.
=> fire update listeners after updating DBCL table (DAT-16772)

liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java
=> expand values for url, username, password that use secrets vaults in maven plugin (DAT-16431)

liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/diffChangelog.test.groovy, liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/generateChangelog.test.groovy, liquibase-standard/src/main/java/liquibase/command/core/DiffChangelogCommandStep.java, liquibase-standard/src/main/java/liquibase/command/core/GenerateChangelogCommandStep.java, liquibase-standard/src/main/java/liquibase/command/core/helpers/AbstractChangelogCommandStep.java, liquibase-standard/src/main/java/liquibase/diff/output/changelog/DiffToChangeLog.java
=> Handle java.lang.StackOverflowError when running generate-changelog (DAT-16812)

liquibase-extension-testing/src/main/resources/liquibase.sdk.yaml
MySql uses a new versioning strategy that makes it so any 8.1+.x releases are innovation releases. This is not semver, so updating to say, 8.3.0 CAN include breaking changes. Pinning to 8.0. Check [here](https://dev.mysql.com/blog-archive/introducing-mysql-innovation-and-long-term-support-lts-versions/) for more details.
=> Pin mysql testing version to latest major release (DAT-16706)

liquibase-standard/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java
=> fix: treats potential nullpointer exception after a lock exception

liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseChecksRunMojo.java
=> add sqlParserExceptionLogAtLevel param to checks.run maven target (DAT-16309)

liquibase-integration-tests/src/test/groovy/liquibase/command/core/UnexpectedChangeSetIntegrationTest.groovy, liquibase-integration-tests/src/test/groovy/liquibase/command/util/CommandUtil.groovy, liquibase-standard/src/main/java/liquibase/changelog/RanChangeSet.java, liquibase-standard/src/main/java/liquibase/changelog/visitor/ExpectedChangesVisitor.java
Issue #5442 outlines an odd behavior where the `unexpected-changesets` command shows the `tag` changeset as unexpected. If using the `tag` command itself, a changeset is not added to the changelog, but an internal Liquibase changeset will be added to the DBCL table. This would cause the `unexpected-changesets `to always show the internal Liquibase changeset as unexpected. Side note, the `generate-changelog` does not create the changeset in a changelog if it exists in the DBCL, so there isn't a way to make the tag expected.
This fix adds a function that is called first to determine if the file path is the **liquibase-internal** changeset. If it is, it removes it from the unexpected list. 
Fixes #5442 
I couldn't find a way to capture the file path for the ran changeset in the …
=> Proposed fix for #5442 - command "unexpectedChangesets" always reports at least 1 unexpected changeset with initial tag in database

liquibase-standard/src/main/java/liquibase/Scope.java, liquibase-standard/src/test/groovy/liquibase/ThreadLocalScopeManagerTest.groovy
Issues  #5426 #2433 #4173  #4314  presents the same error:  "Cannot end scope bsbacsmwja when currently at scope root" . 
The issue was narrowed down to Scope class handling of ScopeManager:
1. Thread "A" starts and creates a root scope. By doing so, Scope.getCurrentScope() returns "root"
2. Thread "A" starts a child scope "ABC". Now, Scope.getCurrentScope() returns "ABC", and parent is root (parent is saved in a non-static variable, while currentScope is static)
3. Thread "A"  is suspended and Thread "B" starts
4. Thread "B" starts.  By doing so, Scope.getCurrentScope() returns "ABC" (**hey! that's already wrong**)
5.  Thread "B" starts a child scope "DEF". Now, Scope.getCurrentScope() returns "DEF" and parent is "ABC"
6. Thread "B"  is suspended, "A"  resumes
7. Thread "A" does it's job …
=> fix: uses ThreadLocal to prevent concurrent modification on ScopeManager

liquibase-standard/src/main/java/liquibase/change/AbstractChange.java
Improve performance of `liquibase.Liquibase#getDatabaseChangeLog()` a bit. I've noticed that pattern compilation takes some time in my profile.
String.replaceAll implementation:
https://github.com/openjdk/jdk/blob/fd8adf308357355bd33916ad80e2328c35434e5a/src/java.base/share/classes/java/lang/String.java#L3110
```
public String replaceAll(String regex, String replacement) {
return Pattern.compile(regex).matcher(this).replaceAll(replacement);
}
```
=> Use static final Pattern to avoid regexp compilation each time replaceAll is called

liquibase-dist/pom.xml, liquibase-standard/src/main/java/liquibase/integration/spring/MultiTenantSpringLiquibase.java, liquibase-standard/src/main/java/liquibase/integration/spring/SpringLiquibase.java, pom.xml
The current code sometimes uses 2-space indentation and 4-space one.
I think it makes sense to format the spring package (for now) for 4-space indentation, as a preparation to work on a PR for that package.
Please let me know if 2-space one is preferred.
=> Format spring package.

liquibase-integration-tests/src/test/java/liquibase/dbtest/pgsql/PostgreSQLIntegrationTest.java, liquibase-integration-tests/src/test/resources/changelogs/yaml/create.procedure.back.compatibility.changelog.yaml, liquibase-standard/src/main/java/liquibase/change/AbstractChange.java, liquibase-standard/src/main/java/liquibase/change/ChangeParameterMetaData.java, liquibase-standard/src/main/java/liquibase/change/DatabaseChangeProperty.java, liquibase-standard/src/main/java/liquibase/change/core/CreateProcedureChange.java
=> Add backwards compatibility for procedureBody in createProcedureChange

liquibase-standard/src/main/java/liquibase/parser/AbstractFormattedChangeLogParser.java, liquibase-standard/src/main/java/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParser.java
Recently with the merge of this [PR](https://github.com/liquibase/liquibase/pull/5456/) the team has noticed this is breaking extensions, so just move the code implementation of `handleInvalidEmptyPreconditionCase` to the abstract class which should fix this issue if no extension overrides this method.
=> Default implementation of handleInvalidEmptyPreconditionCase added in AbtractFormattedChangeLogParser to avoid breaking extensions

liquibase-integration-tests/src/test/groovy/liquibase/command/core/ClearCheckSumsIntegrationTest.groovy, liquibase-standard/src/main/java/liquibase/command/core/ClearChecksumsCommandStep.java
After https://github.com/liquibase/liquibase/pull/4628 clearChecksums started to raise exceptions in empty databases. This PR fixes this behavior.
Fixes #5319
=> fix: ClearChecksums should not throw Exception in empty databases

liquibase-standard/src/main/java/liquibase/util/StringUtil.java
feat: use commons-lang3 library to improve random string generation by ~30% .
partially fix #5507
=> 5507-performance_improvements

liquibase-core/pom.xml, pom.xml
PR https://github.com/liquibase/liquibase/pull/5670/files that was just merged depends on commons-lang3. By verifying our zip & installer we can see that this library is shipped, as it is a dependency for Opencsv library. 
This library is also used in another place of the code but in an outlier case. 
So to prevent class not found issues it is being declared as a required dependency, otherwise it may brake cases where liquibase is used as a library such as Spring or Hibernate as now it will be called in every execution as per the changes on #5670.
Also adding this as a dependency allows to in remove a lot of code that is available in the library and we have been duplicating inside liquibase code.
=> feat: add commons-lang3 as a required dependency for core

liquibase-standard/src/main/java/liquibase/change/custom/CustomChangeChecksum.java, liquibase-standard/src/main/java/liquibase/change/custom/CustomChangeWrapper.java, liquibase-standard/src/test/groovy/liquibase/change/custom/CustomChangeWrapperTest.groovy, liquibase-standard/src/test/java/liquibase/change/custom/ExampleCustomSqlChangeWithChecksum.java
Adds a new optional interface: CustomChangeChecksum, that you can implement on any CustomChange.
Will let you configure how the checksum for your specific change will be calculated, if you're not happy with the default.
See discussion in #5478
Closes #5478
As previously stated, introduces the `CustomChangeChecksum` interface which you can add to your `CustomChange` implementation, in order to calculate your own checksum for your change. This will be a non-breaking change since the interface is completely optional.
The technical impact is that `CustomChangeWrapper` will look and see if the custom change implements the new interface, and then call the `generateChecksum` from that specific interface. If not, use the default one (via AbstractChange)
N/A
N/A
Question: Who updates the …
=> Add CustomChangeChecksum interface

liquibase-integration-tests/src/test/resources/changelogs/common/includerelative/pathinclude1.ignored.changelog.xml, liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/update.test.groovy, liquibase-standard/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd
The [ignore code has existed for a long time for includeAll](https://github.com/liquibase/liquibase/blob/master/liquibase-standard/src/main/java/liquibase/changelog/DatabaseChangeLog.java#L504), but it was not part of the XSD.
=> add ignore property to includeAll XSD (DAT-14921)

liquibase-integration-tests/src/test/groovy/liquibase/command/core/GenerateChangeLogMSSQLIntegrationTest.groovy, liquibase-standard/src/main/java/liquibase/command/core/GenerateChangelogCommandStep.java, liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateViewGenerator.java
=> Handle empty or null schema for CreateView with replace option DAT-16446

liquibase-cli/src/test/groovy/liquibase/integration/commandline/LiquibaseCommandLineTest.groovy, liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/dropAll.test.groovy, liquibase-standard/src/main/java/liquibase/GlobalConfiguration.java, liquibase-standard/src/main/java/liquibase/command/core/DropAllCommandStep.java
=> Add force option to dropAll DAT-16418

liquibase-standard/src/main/java/liquibase/changelog/DatabaseChangeLog.java
For some parsers, (like mongosh parsers) we need to know when modifyChangeSet flow is happening, as we can't run mongo instructions without native executor so `runWith` is required. But in modifyChangeSet flow `runWith` is added to the changeset later on, after parsing. 
Adding modifyChangeSets flag to the Scope allows parsers to read it and skip runWith validation knowing it's inner changeset and it gets 'runWith'  attribute later.
=> [DAT-16135] add new scope flag for modifyChangeSet flow

liquibase-integration-tests/src/test/groovy/liquibase/command/UpdateCommandStepIntegrationTest.groovy, liquibase-integration-tests/src/test/resources/changelogs/update.changelog.yaml, liquibase-standard/src/main/java/liquibase/changelog/ChangeSetStatus.java, liquibase-standard/src/main/java/liquibase/changelog/visitor/StatusVisitor.java
We add support to be able to generate a ChangeSetStatus without for example having to generate a checksum when it's not needed because that given ChangeSet will be skipped.
Fixes #5430
=> Support to generate a ChangeSetStatus with setting all its attributes when a changeset will be skipped 

liquibase-standard/src/main/java/liquibase/diff/output/changelog/core/MissingColumnChangeGenerator.java
When running a diffChangelog, a create table the column uses the Datatypes classes to define the column types, but an addColumn change would simply dump the database text.
This PR fixes addColumn by making it behave as createTable.
=> fix: addColumn changes are not respecting Datatypes definitions

liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java, liquibase-standard/src/main/java/liquibase/ThreadLocalScopeManager.java
ScopeManager now uses ThreadLocal to prevent concurrent modification issues. ThreadLocalScopeManager class is no longer needed.
=> Deprecate ThreadLocalScopeManager as it is no longer required

liquibase-cdi-jakarta/src/main/java/liquibase/integration/jakarta/cdi/SchemesCDIConfigBuilder.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/MavenUtils.java, liquibase-standard/src/main/java/liquibase/changelog/ChangeLogIterator.java, liquibase-standard/src/main/java/liquibase/changelog/DatabaseChangeLog.java, liquibase-standard/src/main/java/liquibase/changelog/StatusChangeLogIterator.java, liquibase-standard/src/main/java/liquibase/changelog/visitor/DBDocVisitor.java, liquibase-standard/src/main/java/liquibase/command/core/DiffChangelogCommandStep.java, liquibase-standard/src/main/java/liquibase/command/core/GenerateChangelogCommandStep.java, liquibase-standard/src/main/java/liquibase/database/AbstractJdbcDatabase.java, liquibase-standard/src/main/java/liquibase/database/core/DB2Database.java, liquibase-standard/src/main/java/liquibase/diff/output/changelog/DiffToChangeLog.java, liquibase-standard/src/main/java/liquibase/executor/jvm/StatementCreatorUtils.java, liquibase-standard/src/main/java/liquibase/integration/commandline/Main.java, liquibase-standard/src/main/java/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParser.java, liquibase-standard/src/main/java/liquibase/snapshot/ResultSetCache.java, liquibase-standard/src/main/java/liquibase/util/ObjectUtil.java, liquibase-standard/src/main/java/liquibase/util/ShowSummaryUtil.java
Retrial of https://github.com/liquibase/liquibase/pull/5776
This PR includes different changes which take advantage of Java 5/7/8 features, e.g. unnecessary boxing/unboxing, enhanced for loop, etc.
Each commit handles a specific change, which describes such change.
=> Use Java 8 features

liquibase-standard/src/main/java/liquibase/util/BooleanUtil.java, liquibase-standard/src/main/java/liquibase/util/CollectionUtil.java, liquibase-standard/src/main/java/liquibase/util/ObjectUtil.java, liquibase-standard/src/main/java/liquibase/util/StringUtil.java
=> use Apache Commons where possible, instead of homegrown solutions (DAT-17303)

liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/dropAll.test.groovy, liquibase-standard/src/main/java/liquibase/command/CommandFactory.java, liquibase-standard/src/main/java/liquibase/command/core/DropAllCommandStep.java, liquibase-standard/src/test/groovy/liquibase/command/CommandArgumentDefinitionTest.groovy
=> do not allow arguments with default values to be required (DAT-17436)

liquibase-standard/src/main/java/liquibase/changelog/StandardChangeLogHistoryService.java, liquibase-standard/src/main/java/liquibase/executor/jvm/JdbcExecutor.java, liquibase-standard/src/main/java/liquibase/sql/SqlConfiguration.java, liquibase-standard/src/main/java/liquibase/sqlgenerator/core/SelectFromDatabaseChangeLogGenerator.java, liquibase-standard/src/main/java/liquibase/statement/core/SelectFromDatabaseChangeLogStatement.java
=> optimize DBCL checksum query and set fetch size on all statements (DAT-17267)

liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseUpdateMojo.java
https://datical.atlassian.net/browse/PD-3241
Fixing `liquibase update --help` description: failOnError is a changeset attribute that should be specified in camelCase, *not* a CLI attribute that should be specified in kebab-case.
https://docs.liquibase.com/concepts/changelogs/attributes/fail-on-error.html
PR contains no changes to functionality.
=> PD-3241: failOnError syntax

liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/spock/LiquibaseIntegrationMethodInterceptor.java
Previously, drop all would be run at the end of every integration test, including if the test contained no test systems that were currently activated. In other words, drop all would be run against Snowflake after running `PSqlExecutorTest`. Because drop all on Snowflake is expensive, this means that test runs were taking minutes (possibly hours) longer than necessary.
=> only run drop all if database was used in the test

liquibase-standard/src/main/java/liquibase/diff/output/changelog/core/MissingTableChangeGenerator.java
The ordering of the Oracle SQL for global temporary tables should have `GLOBAL TEMPORARY`, not `TEMPORARY GLOBAL'.  Also, we should support the `ON COMMIT` clause.
=> Fix ordering of clause for Oracle global temporary tables SQL generation

liquibase-integration-tests/src/test/resources/changelogs/common/common.tests.changelog.xml, liquibase-standard/src/main/java/liquibase/precondition/core/UniqueConstraintExistsPrecondition.java, liquibase-standard/src/main/java/liquibase/snapshot/jvm/UniqueConstraintSnapshotGenerator.java
=> Fixed issue that unique constraint precondition does not honor schemaName attribute on MySQL

liquibase-standard/src/main/java/liquibase/precondition/core/ColumnExistsPrecondition.java
Fixes #5666 
When checking for existence of a column using a snapshot, the schema is incorrectly included, leading to an SQL query with a `null` schema. Included code to explicitly use the database default schema if none is set in the precondition.
Tested this on MySQL.
=> Fixes issue with incorrect schema in column exists precondition when checking using a snapshot

liquibase-standard/src/main/java/liquibase/database/Database.java
Invoke deprecated methods in default supports method to ensure that extensions are not broken, but one day when those are removed it will return only true
The new support `method` was introduced in PR https://github.com/liquibase/liquibase/pull/5619 so specially NoSQL databases can check for other supports as `Collections` without changing Database class and adding a `supportsCollections()` method.
In core all the locations were `supportsSequences()` existed were changed to supports(Sequence) , and all *Database classes had this new method implemented. But extensions don't have it, so they could return the wrong value. For instance, BigQuery doesn't support sequences but would start to return true to core.
With this fix we continue to return what is expected.
=> chore: invoke deprecated methods in default supports method for backwards compatibility

liquibase-integration-tests/src/test/java/liquibase/dbtest/h2/H2IntegrationTest.java
=> H2 tests may end up with an incorrect list of the standard DatabaseObject types, so we need to reset the factory

liquibase-bigquery/src/main/java/liquibase/datatype/core/BignumericDataTypeBigQuery.java, liquibase-bigquery/src/main/java/liquibase/datatype/core/BoolDataTypeBigQuery.java, liquibase-bigquery/src/main/java/liquibase/datatype/core/Float64DataTypeBigQuery.java, liquibase-bigquery/src/main/java/liquibase/datatype/core/GeographyDataTypeBigQuery.java, liquibase-bigquery/src/main/java/liquibase/datatype/core/Int64DataTypeBigQuery.java, liquibase-bigquery/src/main/java/liquibase/datatype/core/NumericDataTypeBigQuery.java, liquibase-bigquery/src/main/java/liquibase/datatype/core/StringDataTypeBigQuery.java, liquibase-bigquery/src/main/java/liquibase/sqlgenerator/BigQueryModifyDataTypeGenerator.java, liquibase-bigquery/src/main/resources/META-INF/services/liquibase.datatype.LiquibaseDataType, liquibase-bigquery/src/test/java/liquibase/datatype/core/NumericDataTypeBigQueryTest.java
2 issues here
- Added priority method to BigQueryModifyDataTypeGenerator - as it had default priority is was suppressed by other extensions in classpath. This resolved query to have `SET DATA TYPE` instead of just `TYPE`
- Fixed priorities for datatypes as NumericDataTypeBigQuery was never used and we had `NUMBER` in the query instead of `NUMERIC`
=> [DAT-17403] resolved priorities for Datatypes and ModifyDatatype generator

liquibase-integration-tests/src/test/groovy/liquibase/command/util/CommandUtil.groovy, liquibase-integration-tests/src/test/groovy/liquibase/diffchangelog/DiffChangelogMssqlIntegrationTest.groovy, liquibase-standard/src/main/java/liquibase/structure/core/PrimaryKey.java
Previously, diff-changelog would errorenously create addPrimaryKey changes which included the column direction:
```
<addPrimaryKey columnNames="ID DESC" constraintName="PK_MyTest" tableName="MyTest"/>
```
This PR changes the generated change to:
```
<addPrimaryKey columnNames="ID" constraintName="PK_MyTest" tableName="MyTest"/>
```
=> generated addPrimaryKey changes should not include column direction (DAT-17467)

liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateSequenceGenerator.java
The CREATE SEQUENCE command of Microsoft SQL Server doesn't support the `ORDER` clause (see at https://docs.microsoft.com/en-us/sql/t-sql/statements/create-sequence-transact-sql?view=sql-server-2017).
Therefore, it should be ignored for this DB as well. I have tested this change on an SQL Server 2017 (I had an error with the CREATE SEQUENCE command before, and after applying this and installing to my local Maven repo, the problem was gone).
=> Microsoft SQL Server doesn't support ORDER in sequences

liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
When the `isExpected` flag is set for a `CommandFailedException`, we shouldn't log the stack trace
=> Do not log stack trace if isExpected flag is true for CommandFailedException

liquibase-standard/src/main/java/liquibase/lockservice/DatabaseChangeLogLock.java
this is needed to be able to de-serialise it using [jackson] which relies on the default constructor & setters.
in the upcoming [liquibase-opensearch] implementation [opensearch-java] is used, which underneath is using jackson for the (de-)serialisation of classes.
specifically, this is used in the implementation of `LockService#listLocks` which needs to load `DatabaseChangeLogLock`s from the DB.
also do some minor cleanups by removing manually implemented getters & setters where lombok annotations can do the job instead (no functional impact).
this could be cleaned up even further if `Date` were replaced with `LocalTime` (which is immutable), but that'd be a bigger (breaking) change.
note that this is the same pattern as was previously done in #5336 (commit b4726a0) for `RanChangeSet` & …
=> add default constructor + setters to `DatabaseChangeLogLock`

liquibase-standard/src/main/java/liquibase/database/core/PostgresDatabase.java
Prevent resetting the search path in Postgres after a rollback if we are running in a mode that does not update the database to avoid spurious SET SEARCH_PATH SQL statements.
The logic in `DatabaseUtils.initializeDatabase` for Postgres expects changes to the SEARCH_PATH to be persisted to detect when the SEARCH_PATH is already correct(ed). However in `update-sql` mode these changes are not executed, causing the detection mechanism to fail and resulting in extra SET SEARCH_PATH statements.
I'm aware of the other change in review that will fix this issue, but that is a bigger change and might take a long time to be merged. This could be a quick win.
=> Prevent spurious SET SEARCH_PATH SQL statements for Postgres during update-sql command. Fixes #5316

.github/workflows/release-published.yml
📝 (release-published.yml): improve logic to find the stagingRepositoryId for release repository by checking if a repository is an extension before assigning it as the staging repository.
=> DAT-16264 DevOps :: liquibase build fails on Publish to Maven Central - Nexus

liquibase-standard/src/main/java/liquibase/Liquibase.java
This PR undeprecates Liquibase class methods, improves javadocs and removes deprecated dependencies/sonar warnings as requested by community in #5663, #5066, forum and other locations.
Fixes #5663
=> High Level API (aka undeprecate Liquibase class)

.github/workflows/run-functional-tests.yml, .github/workflows/run-test-harness.yml
@wwillard7800 suggested not to fail the workflow but rather skip it, and I think he is right. Another change in the PR is to add one label, runFunctional&HarnessTests, because if we add separate labels like runFunctionalTests and runHarnessTests, the second added label will generate an extra test run for the first label.
=> Skip harness and functional tests instead of failing workflow, one trigger for harness and functional to avoid multiple triggers

liquibase-integration-tests/src/test/resources/changelogs/oracle/complete/root.changelog.xml, liquibase-standard/src/main/java/liquibase/util/StringUtil.java
=> Fix SQL execution issue with endDelimiter '/' and splitStatements

liquibase-standard/src/main/java/liquibase/configuration/core/ScopeValueProvider.java, liquibase-standard/src/main/java/liquibase/configuration/core/SystemPropertyValueProvider.java
If the system properties are modified while liquibase is iterating over them within the AbstractMapConfigurationValueProvider, a ConcurrentModificationException is thrown.
The fix is the same as the second fix of [CORE-2104](https://liquibase.jira.com/browse/CORE-2104) from [2015 (3.4.1)](https://github.com/liquibase/liquibase/commit/0c42dcd9fe89cbcd82594fc3bb6cfbf2ddbf1104), cloning the system properties. However, this code [no longer](https://github.com/liquibase/liquibase/blob/v4.28.0/liquibase-standard/src/main/java/liquibase/changelog/ChangeLogParameters.java#L56) uses a for loop to iterate over the system properties.
This fixes #4908
Seperating this test case/issue is not that easy. The changes are based on this reproduction project: https://github.com/Alf-Melmac/properties-iterator …
=> Clone system properties to prevent ConcurrentModificationException

liquibase-standard/src/main/java/liquibase/util/ObjectMethods.java, liquibase-standard/src/main/java/liquibase/util/ObjectUtil.java, liquibase-standard/src/test/java/liquibase/util/ObjectMethodsTest.java
When running a big integration test suite that runs LiquiBase multiple times, I realized that LB spends a lot of time on generating the same method names again and again (e.g. given property name `name`, LB generates Strings `isName`, `getName` and `setName` many-many times).
I suggest an optimization that computes them only once and holds in a Map. 
Should make parsing big XML files faster and consume less memory.
I believe this change doesn't affect any functionality (besides the above-mentioned performance improvement).
=> Optimize parsing big xml files

liquibase-dist/expected-distribution-contents.txt, liquibase-dist/src/main/assembly/assembly-bin-common.xml
Allow slf4j library to be included in liquibase zip/installer so sqlite driver works.
Fixes #5706 .
=> chore: allow slf4j library to be included in liquibase zip/installer

liquibase-standard/src/main/java/liquibase/integration/commandline/Banner.java, liquibase-standard/src/main/resources/liquibase/i18n/liquibase-core.properties, liquibase-standard/src/main/resources/liquibase/i18n/liquibase-core_de.properties, liquibase-standard/src/test/groovy/liquibase/integration/commandline/CommandLineUtilsTest.groovy
Adding current java version to Liquibase banner in a subtle manner so this information is available to help debug support issues.
Sample output:
=> feat: add current java version to Banner

liquibase-standard/pom.xml
Fixes: https://github.com/liquibase/liquibase/issues/6020
Since LB has a compile dependency on `org.apache.commons.io` package, it is incorrect to list it as an optional dependency.
After the change the section will have:
```
Import-Package: ...,org.apache.commons.io;version="[2.16.1,3)"
```
Since `commons-io` library perform a multi-version export, this change is also putting some version constrains to pick the latest version.
=> Fix OSGi import for `org.apache.commons.io`

liquibase-standard/pom.xml
Liquibase 4.28.0 failing under OSGi because the MANIFEST.MF of liquibase-core does not contain and for liquibase.changelog.visitor.ValidatingVisitorGenerator (similar to what was fixed in https://github.com/liquibase/liquibase/pull/5498 )
The bug only takes place under OSGi (with the osgi.serviceloader loading SPI services).
The fix also only has any effect under OSGi.
=> Add osgi.serverloader manifest header entries for liquibase.changelog.visitor.ValidatingVisitorGenerator #6040 fix

liquibase-standard/src/main/java/liquibase/statement/ExecutablePreparedStatementBase.java
Fixes #6096
This change avoids creating a snapshot of the entire database structure when we are only interested in a single column
Performance profiling (both before and after) were done on liquibase v4.20.0
Before:
After:
=> Fixed performance issue with valueBlobFile on Postgres databases introduced in v4.18.0

liquibase-standard/src/main/java/liquibase/changelog/filter/LabelChangeSetFilter.java, liquibase-standard/src/test/java/liquibase/changelog/filter/LabelChangeSetFilterTest.java
Previously, the matching required a label expression to match both the change set labels AND the included labels
All the tests passed, but this change probably needs some discussion, since the code has been this way since 2018.
=> Append included labels to the changeset labels when matching DAT-16636

liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseUpdateSQL.java, liquibase-standard/src/main/java/liquibase/Liquibase.java, liquibase-standard/src/test/groovy/liquibase/util/NetUtilTest.groovy
Instead of replacing the executor with a logging executor, use `UpdateCountSqlCommandStep` and `UpdateToTagSqlCommandStep` in `liquibase:updateSql`. 
Adds two new methods to `Liquibase` class. We haven't ever actually called out `count` or `tag` in any of our update method names before on this class, but `update` has been overloaded ad nauseam so I decided to just label these exactly as to what they are doing.
=>  Do not show update summary when using update-sql via maven plugin (DAT-18323)

liquibase-standard/src/main/java/liquibase/util/StringUtil.java
SecureRandom is a robust RNG for use in security-sensitive scenarios (like generating cryptographic/private keys). For something like a random Scope ID, it is overkill, as it's slower, and becomes a potentially blocking call if the machine hasn't been on for long or have enough entropy.
~~I've looked into the original change (in commit 3daa688c6a99ed131687036ba4e40cd743c4b3c8) and it seems to have been done to improve the performance of the Scope ID generation. While it clearly did improve things, it's much better to just use a normal ThreadLocalRandom instance, that will not experience contention issues even under high traffic, and will not have the problem with depending on system entropy.~~
The original change (in commit 3daa688c6a99ed131687036ba4e40cd743c4b3c8) already did this change …
=> Make Scope ID RNG no longer use SecureRandom (fix #6178)

liquibase-standard/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java
Fixes #6054 incorrect system table queries being executed when running on the DB2i AS/400 platform by re-introducing two return statements.
=> Fixes issue 6054: incorrect system table query on DB2 AS/400 platform

liquibase-integration-tests/src/test/java/liquibase/dbtest/oracle/OracleIntegrationTest.java, liquibase-integration-tests/src/test/resources/changelogs/oracle/complete/root.changelog.xml, liquibase-integration-tests/src/test/resources/changelogs/oracle/complete/strict.changelog.xml, liquibase-standard/src/main/java/liquibase/util/StringUtil.java
Consider that you have sql endDelimiter = "/" , and the following SQL:
```
a = var1 / 
var2;
```
How Liquibase should handle it? Should we split or divide? It can be understood as:
```
a = var1 / var2; --  'division behavior'
```
or
```
a = var1 ;   
var2; -- 'strict behavior'
```
Historically, we had:
* Until v4.9.0 - Division behavior
* v4.9.0 (2022.03.17) - changed to Strict behavior - https://github.com/liquibase/liquibase/pull/2135
* v4.15.0 (2022.08.04) - rolled back to Division behavior - https://github.com/liquibase/liquibase/pull/3118
* v4.29.0 (2024-07-28) - changed to Strict behavior again! - https://github.com/liquibase/liquibase/pull/5704
Versions v4.9.0 to v4.14.x (only 5 months) were `strict` while all other versions are `division`. And with 4.29.0 we restored `strict` …
=> fix: EndDelimiter not working as expected since 4.29

changelog.txt, liquibase-dist/pom.xml, pom.xml
Changelog for 4.29.2 + revert snowflakke driver version to 3.16.1 (same as 4.29.1 ) and slf4j back to 1.x - thos ehould not have been bumped for a patch version..
=> Changelog for 4.29.2 + revert snowflake driver + slf4j versions

liquibase-standard/src/main/java/liquibase/integration/spring/SpringLiquibase.java
PR #4584 added an unchecked  exception when it should be a checked one. This PR fixes it. 
Fixes #6196
=> fix: do not throw an unchecked exception for SpringBoot 

liquibase-standard/src/main/java/liquibase/changelog/DatabaseChangeLog.java
The most important fix is line 271:
"Could not find/read changelogs from %s directory" - WHY???
This PR fixes problem https://github.com/liquibase/liquibase/issues/6264
More exactly, it adds the error details to thrown exception (which was previously swallowed).
=> #6264 append the cause of the problem to thrown exception

liquibase-standard/src/test/groovy/liquibase/changelog/DatabaseChangeLogTest.groovy
This test used to fail in Locales different than English as the expected message can be different if a translation is available
=> fix: Locale test fix

liquibase-standard/src/main/java/liquibase/analytics/SegmentAnalyticsListener.java, liquibase-standard/src/main/java/liquibase/analytics/SegmentBatch.java, liquibase-standard/src/main/java/liquibase/analytics/SegmentTrackEvent.java, liquibase-standard/src/main/java/liquibase/analytics/configuration/AnalyticsArgs.java, liquibase-standard/src/main/java/liquibase/analytics/configuration/SegmentAnalyticsConfiguration.java, liquibase-standard/src/main/java/liquibase/license/LicenseService.java
`Scope` is stored in a ThreadLocal, so we must get the owner of the license key outside of the newly created thread, because the thread has a different scope than the main Liquibase thread.
Additionally, include the last 12 characters of the license key in the userId transmitted to Segment, so that different keys for the same org can be differentiated.
=> fix userId not finding license owner correctly, include license key in userId (DAT-18653)

liquibase-standard/src/main/java/liquibase/command/core/helpers/DbUrlConnectionCommandStep.java
When executing a maven goal the database command scope argument is set up before the DbUrlConnectionCommandStep is executed. This meant that occasionally we didn't actually log all of the relevant database platform information in MDC and analytics. This change logs the mdc information regardless of whether the database was set up in the command step or elsewhere. 
This change removes an if/else that caused the bug and refactors the code to be a bit more compact, but functionally nothing should change.
=> Always add database information to MDC and analytics when running via maven (DAT-18630)

liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/EnvironmentVariableProviderForTest.groovy, liquibase-integration-tests/src/test/groovy/liquibase/StrictIntegrationTests.groovy, liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java, liquibase-integration-tests/src/test/java/liquibase/dbtest/sqlite/SQLiteIntegrationTest.java
Issue 1: The test `StrictIntegrationTests` would fail if there were pro (or other extension related) environment variables set up outside of the scope of test execution. The change to `EnvironmentVariableProviderForTest` makes it so that we do not read the existing environment variables when utilizing this provider and enables us to successfully run the test without messing with existing environment variables.
Issue 2: When running sqlite integration tests before hsqldb integration tests, the databaseobjectfactory would carry over between test executions. Since sqlite does not support sequences, this would lead to sequences not being detected in hsqldb's integration tests causing them to fail. The change to the teardown method in the sqlite tests resets the factory, allowing sequences to …
=> Fix sqlite hsqldb and environment variable tests (DAT-18646)

liquibase-integration-tests/src/test/groovy/liquibase/command/core/UpdateTestingRollbackCommandsIntegrationTest.groovy, liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/updateTestingRollback.test.groovy, liquibase-standard/src/main/java/liquibase/command/core/UpdateTestingRollbackCommandStep.java
> During testing, @James Bennett discovered that the updateTestingRollback command has a hidden argument for tag.  The argument has always been a part of the command, but was accidentally marked as hidden during command framework refactoring.  It appears to be working as designed but should be tested further after unhiding it.
With this PR, we just unhide `TAG` command argument and update the corresponding tests.
=> DAT-18563 :: Unhide tag parameter for UpdateTestingRollback command

liquibase-standard/src/main/java/liquibase/snapshot/CachedRow.java, liquibase-standard/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGenerator.java
Sample:
```java
java.lang.NullPointerException: Cannot invoke "String.replaceAll(String, String)" because "defaultValue" is null
at liquibase.snapshot.jvm.ColumnSnapshotGenerator.readDefaultValue(ColumnSnapshotGenerator.java:571)
at liquibase.snapshot.jvm.ColumnSnapshotGenerator.readColumn(ColumnSnapshotGenerator.java:291)
at liquibase.snapshot.jvm.ColumnSnapshotGenerator.addTo(ColumnSnapshotGenerator.java:204)
at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:78)
at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:49)
```
This PR fixes bug https://github.com/liquibase/liquibase/issues/6281
=> #6281 fix NPE when default value is null

liquibase-cli/pom.xml, liquibase-core/pom.xml, pom.xml
Use ${project.version} instead of ${version}; same goes for ${build.finalName}, which is recommended to switch to ${project.build.finalName}.
Finally, use version for `maven-jar-plugin` consistently.
`skipReleaseNotes`   - Don't show up on the Draft Release Notes page
`newContributors`    - New Contributors 
The project configuration in pom.xml uses two deprecated variables: ${version} and ${build.finalName}.
The warnings are issues with `mvn` version 3.9.x, possibly before.
Since the project has configured `mvn` version 3.9.5 in `.mvn/wrapper/maven-wrapper.properties`, a developer with no `mvn` installed is automatically using that version.
I am well aware that the project "only" mandates `mvn` version 3.6 as a minimum.
Fixes #6331
=> Adressing issue #6331, small changes to pom.xml files to reduce warnings shown in building

liquibase-standard/src/main/java/liquibase/change/core/AddForeignKeyConstraintChange.java, liquibase-standard/src/main/java/liquibase/command/core/helpers/AbstractChangelogCommandStep.java, liquibase-standard/src/test/resources/liquibase/change/ChangeDefinitionTest.yaml
The calls being modified here should not be in those locations as they happen before all classloading is complete, thus causing incorrect evaluations of available classes.
To be more specific, DatabaseFactory is called before classpath parameter is evaluated by command line, causing extension that provide support to other databases that are pointed out by "classpath" parameter to not be loaded.
Fix https://github.com/liquibase/liquibase-docs/issues/105
=> DAT-18191 and DAT-18192 - Fix classpath loading and incorrect configuration for addForeignKeyConstraint

ABOUT.txt, liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java, liquibase-integration-tests/src/test/java/liquibase/dbtest/mssql/MssqlIntegrationTest.java, liquibase-integration-tests/src/test/resources/changelogs/mssql/complete/root.changelog.xml, liquibase-integration-tests/src/test/resources/changelogs/mssql/issues/feature.index.include.xml, liquibase-integration-tests/src/test/resources/changelogs/mssql/rollback/rollbackable.changelog.xml, liquibase-standard/src/main/java/liquibase/change/ColumnConfig.java, liquibase-standard/src/main/java/liquibase/diff/compare/core/ColumnComparator.java, liquibase-standard/src/main/java/liquibase/diff/output/changelog/core/MissingIndexChangeGenerator.java, liquibase-standard/src/main/java/liquibase/snapshot/jvm/IndexSnapshotGenerator.java, liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateIndexGenerator.java, liquibase-standard/src/main/java/liquibase/structure/core/Column.java, liquibase-standard/src/main/java/liquibase/structure/core/Index.java, liquibase-standard/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd, liquibase-standard/src/test/groovy/liquibase/change/ColumnConfigTest.groovy
- [ X ] Enhancement/New feature (adds functionality without impacting existing logic)
Added support for specifying columns to be used in the 'Include' clause of indexes, and made generate changelog generates changes that include indexes when run against a database that uses these indexes. Tested against MSSQL.
Fixes #1697 
Here is an example changeset creating two indexes, one with and one without include:
- changeSet:
id: 1722028836430-8
author: stephenatwell (generated)
changes:
- createIndex:
columns:
- column:
descending: true
name: id
- column:
included: true
name: name
indexName: saTestInclude
tableName: person
column object now has a new boolean that states whether or not the column should go in the 'included' clause.
=> Add support for include columns in indexes

liquibase-standard/src/main/java/liquibase/precondition/core/ForeignKeyExistsPrecondition.java, liquibase-standard/src/main/java/liquibase/snapshot/DatabaseSnapshot.java, liquibase-standard/src/main/java/liquibase/snapshot/SnapshotControl.java, liquibase-standard/src/main/java/liquibase/snapshot/SnapshotGeneratorFactory.java
When using a foreignKeyConstraintExists precondition do not check for nested database objects. 
Refactors SnapshotGeneratorFactory to allow for disabling the nested search behavior by introducing a new flag searchNestedObjects to SnapshotControl. Respect this flag in DatabaseSnapshot.
The changes to the catalog/schema setup in `ForeignKeyExistsPrecondition` were necessary to fix Oracle integration tests. In the case of Oracle the schema was not found immediately, was set up to use `DEFAULT.DEFAULT`, and we were forced to iterate through objects until we reached the `includeNestedObjects` and `replaceObject` methods in `DatabaseSnapshot`. Once we reached this point the foreign key table from the example databaseObject would be updated to use the proper schema/catalog (the default …
=> Do not check for nested database objects when using foreignKeyConstraintExists precondition (DAT-18624)

liquibase-core/pom.xml
Reverts liquibase/liquibase#6117
The original MR leads to issue #6369.
=> Revert "Remove unneeded inclusion of commons-io in liquibase-core pom.xml"

liquibase-standard/src/main/java/liquibase/exception/PreconditionFailedException.java
Removal of this method is breaks extensions, such as https://github.com/liquibase/liquibase-neo4j/actions/runs/11139305021/job/30955764936 .
This method was changed by PR #6288 , so it's being restored as deprecated.
=> fix: restore public method in PreconditionFailedException

liquibase-standard/src/main/java/liquibase/database/core/PostgresDatabase.java, liquibase-standard/src/test/java/liquibase/database/core/PostgresDatabaseTest.java
Two view names - pg_stat_statements and pg_stat_statements_info (contributed by the pg_stat_statements Postgres db extension) - have been added to the systemTablesAndViews list so that they are identified as system objects in the PostgresDatabase class and thus are not dropped during the execution of the drop-all command (system objects are excluded from the change sets produced as part of taking the database snapshot for the purpose of dropping database objects). Fixes #1451 
None.
None.
None.
=> Add pg_stat_statements and pg_stat_statements_info views to the list of system tables and views to prevent them from being dropped

liquibase-standard/src/main/java/liquibase/Scope.java
When sending analytics we create a new thread to easily time out the thread in case processing takes too long. This works fine for normal use cases, but in the event we are say, redirecting the logs to a file or using structured logging with our pro extension, we need to check the liquibase configuration and grab information via the scope. This can result in unexpected errors from inside a new thread as the `scopeManager` has not been set up in this new thread. By swapping to a `InheritableThreadLocal`, we automatically transfer this scopevalue into the child thread without having to muck with copying the scope values. 
As far as I can tell this should work the same as a normal `ThreadLocal` but allow us to not need to reconfigure our scope when spawning child threads. That said, changing …
=> Allow for scopemanager to be shared between threads created by liquibase (DAT-18871)

liquibase-standard/src/main/java/liquibase/changelog/visitor/ValidatingVisitor.java, liquibase-standard/src/test/groovy/liquibase/changelog/visitor/ValidatingVisitorTest.groovy
If a changeset id is entirely blank (one or more spaces) fail validation.
Do not fail validation for changes that have already been ran. Changes that have been ran with an empty changeset id that are marked as `runOnChange` or `runAlways` WILL fail validation.
=>  Fail validation for blank changeset ids (DAT-18773)

liquibase-integration-tests/src/test/groovy/liquibase/diffchangelog/DiffChangelogIntegrationTest.groovy, liquibase-standard/src/main/java/liquibase/serializer/core/formattedsql/FormattedSqlChangeLogSerializer.java, liquibase-standard/src/test/java/liquibase/serializer/core/formattedsql/FormattedSqlChangeLogSerializerTest.java
This PR fixes an omission in `FormattedSqlChangeLogSerializer`, which today does not include `logicalFilePath` in the change-set info comment.  With this PR, it will include the logical file path if it is non-null and not empty.
Fixes #6452
=> Fix FormattedSqlChangeLogSerializer so it includes logicalFilePath in change-set info comments

liquibase-standard/src/main/java/liquibase/integration/spring/MultiTenantSpringLiquibase.java, liquibase-standard/src/main/java/liquibase/integration/spring/SpringLiquibase.java
Adding properties licenseKey and analyticsEnabled to Spring configuration.
* Review & merge this PR to Liquibase
* Release Liquibase (probably 4.30.1 or 4.31.0)
* In the following PR, fix Liquibase version and change base to Spring repo: https://github.com/filipelautert/spring-boot/pull/1/files
```
spring.liquibase.licenseKey=Mybase64KeyHere
spring.liquibase.analyticsEnabled=false
...
```
```
... liquibase.integration                    : Disabling Liquibase analytics.
... liquibase.integration                    : Using PRO licenseKey specified in Spring configuration files.
```
```
08:14:12.419 [main] INFO org.springframework.test.context.support.AnnotationConfigContextLoaderUtils -- Could not detect default configuration classes for test class [com.example.demo.DemoApplicationTests]: …
```
=> feat: add new properties to Spring configuration (analytics Enabled and pro license)

liquibase-standard/src/main/java/liquibase/integration/spring/MultiTenantSpringLiquibase.java, liquibase-standard/src/main/java/liquibase/integration/spring/SpringLiquibase.java
Fix for https://github.com/liquibase/liquibase/pull/6516 . The way that it was implemented makes the environment variable LIQUIBASE_ANALYTICS_ENABLED and system property liquibase.analytics.enabled effectively ignored, and we don't want that.
Thanks to @mches for spotting this bug.
=> fix: only set Spring  analytics scope parameter if it's defined

liquibase-standard/src/main/java/liquibase/sqlgenerator/core/AlterSequenceGenerator.java, liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateSequenceGenerator.java, liquibase-standard/src/test/resources/liquibase/change/ChangeDefinitionTest.yaml, liquibase-standard/src/test/resources/verify/saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets/createSequence/db2.sql, liquibase-standard/src/test/resources/verify/saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets/createSequence/db2i.sql
- [ x ] Bug fix (non-breaking change which fixes expected existing functionality)
Fixes #6421.
Updates database support for sequence parameters `data type` and `cache size`.
- No longer throw validation errors for HSQLDB and MSSQL when data-type is specified
- HSQLDB and DB2z are no longer forced to use BIGINT as data-types. However, they will default to it if none is specified. This is done to preserve the functionality which maintains consistent sequence data-types across database types, even those that default to INTEGER. The Db2zDatabase check has been changed to AbstractDb2Database, so DB2 is also covered by this.
- Allow cache-size to be used on all DB2 subtypes by checking instances of AbstractDb2Database
- Allow cache-size to be used on MSSQL
- Add no-cache (cache-size = 0) …
=> Fix Sequence generator - cache size, data type - for various DBs

liquibase-integration-tests/src/test/groovy/liquibase/command/core/ClearCheckSumsIntegrationTest.groovy, liquibase-integration-tests/src/test/groovy/liquibase/command/util/CommandUtil.groovy, liquibase-integration-tests/src/test/resources/changelogs/h2/complete/sqlchange.with.dbms.changelog.xml, liquibase-standard/src/main/java/liquibase/command/core/helpers/DatabaseChangelogCommandStep.java
Database object needs to be present in scope when upgradingChecksums because of dbms tags in sql changes. This method is only triggered when md5sum column is null.
Fixes #5618
=> fix: Checksum for SQL changes containing dbms attributes can get different values if md5sum column is null

.github/util/re-version.sh
This pull request includes a small change to the `.github/util/re-version.sh` file. The change involves modifying the `tar` command to no longer use the `--strip-components=1` option when extracting the `tar.gz` file. 
* [`.github/util/re-version.sh`](diffhunk://#diff-05532236ce14388a53050c18c36e556c73805595c14236636f93936059581289L179-R179): Removed the `--strip-components=1` option from the `tar` command to ensure the directory structure is preserved during extraction.
=> 🛠️ DAT-19292: fix Attach Artifacts to Draft Release failures

.github/workflows/run-tests.yml
Otherwise we are unable to build against old liquibase versions for patch releases.
Found when trying to build DAT-19258 to generate a patch release.
Branch execution: https://github.com/liquibase/liquibase/actions/runs/12651777731
=> feat(DAT-19258): should only verify test count if base branch is master

liquibase-standard/src/main/java/liquibase/configuration/ConfiguredValueModifierFactory.java
This fixes #6526 and allows the `username` and `password` attributes to be omitted in the `liquibase-maven-plugin` configuration.
=> liquibase-maven-plugin: Allow `null` arguments to `ConfiguredValueModifierFactory.override(String)`

.github/workflows/build-extension-jars.yml, .github/workflows/create-release.yml
This pull request includes several changes to the GitHub Actions workflows for building and releasing Liquibase extensions. The most significant updates involve standardizing string quotes, adding new build steps for `liquibase-checks`, and commenting out the OWASP scanner and file attachment steps in the release workflow.
* [`.github/workflows/build-extension-jars.yml`](diffhunk://#diff-dc83207379251c4eeafe63714db8ce416c176c525edf14a8bd6ad57ca0e9027bL7-R42): Changed single quotes to double quotes for consistency in the description fields and other string values. [[1]](diffhunk://#diff-dc83207379251c4eeafe63714db8ce416c176c525edf14a8bd6ad57ca0e9027bL7-R42) [[2]](diffhunk://#diff-dc83207379251c4eeafe63714db8ce416c176c525edf14a8bd6ad57ca0e9027bL71-R73) …
=> DAT-18331 PRO: integrate checks extension into tarball/zip, not mac os dmg installer

.github/workflows/build-extension-jars.yml, .github/workflows/create-release.yml
This pull request includes a new job to extract the version of `liquibase-checks` from its `pom.xml` and updates the existing build job to depend on this new job.
Changes to the `.github/workflows/build-extension-jars.yml` file:
* Added a new job `get-liquibase-checks-version` to extract the version of `liquibase-checks` from its `pom.xml` file. This job runs only if `liquibase-checks` is included in the inputs and sets an output variable `version` with the extracted version.
* Updated the `build-liquibase-checks` job to depend on the new `get-liquibase-checks-version` job. This ensures that the version is extracted before the build process begins.
=> DAT-19398 DevOps :: Fix Liquibase Checks versioning in the tarball to match the Liquibase Checks repository

.github/workflows/cleanup-branch-builds.yml, .github/workflows/cleanup-master-builds.yml
This pull request includes a change to the .github/workflows/cleanup-branch-builds.yml file to simplify the deletion of package versions in the jobs: section. It removes the usage of min-versions-to-keep that is not a [Valid Input Combination](https://github.com/marketplace/actions/delete-package-versions#valid-input-combinations) but we can use the combination of this PR based on [Delete a specific version of a package](https://github.com/marketplace/actions/delete-package-versions#delete-a-specific-version-of-a-package)
=> 🔧 fix cleanup branch builds

liquibase-standard/src/main/java/liquibase/diff/output/changelog/core/ChangedSequenceChangeGenerator.java
If minValue of a sequence has changed the change was added twice. This was introduced in commit eddde5e1d0. Only add the change once to avoid duplicate output of the same change.
There are more issues with default values for minValue for sequences in case of Oracle, but I'll analyse and report separately.
Test coverage
=> Don't add minValue change twice

.github/util/re-version.sh
This pull request includes a small change to the `.github/util/re-version.sh` script. The change adds new commands to ensure that `master-SNAPSHOT` and `release-SNAPSHOT` versions in `pom.properties` files are replaced with the new version.
* [`.github/util/re-version.sh`](diffhunk://#diff-05532236ce14388a53050c18c36e556c73805595c14236636f93936059581289R80-R81): Added commands to replace `master-SNAPSHOT` and `release-SNAPSHOT` with the new version in `pom.properties` files.
=> DAT-18516 Set correct version in pom.properties file for liquibase-commercial.jar

liquibase-standard/src/main/java/liquibase/exception/PreconditionFailedException.java, liquibase-standard/src/main/java/liquibase/sqlgenerator/core/RawParameterizedSqlGenerator.java
* undeprecate liquibase.exception.PreconditionFailedException#PreconditionFailedException(liquibase.precondition.FailedPrecondition) -> a community contributor added a new method that receives a throwable and deprecated this one, but for neo4j (and maybe other extensions) it still makes sense to have the old method.
* remove parameter validations in RawParameterizedSqlGenerator.java : we removed the validations from the executor class but they still exists in this generator. It`s interesting that they way we use RawParametrized in core don't trigger them, but Neo4j does.
=> Code review for extensions after 4.31.0 release

.github/workflows/create-release.yml, .github/workflows/dry-run-release.yml
This pull request includes changes to the `.github/workflows/dry-run-release.yml` file to update the references for the `jobs:` section. The most important changes involve modifying the `uses` attribute for two jobs to use local workflow files instead of the ones from the `liquibase/liquibase` repository.
Changes to workflow file references:
* [`.github/workflows/dry-run-release.yml`](diffhunk://#diff-da505eba40e5178912154d1d165e17f3353098ba24e44bd62d23ad028700e42aL32-R32): Updated the `uses` attribute for the `dry-run-create-release` job to reference the local `create-release.yml` file.
* [`.github/workflows/dry-run-release.yml`](diffhunk://#diff-da505eba40e5178912154d1d165e17f3353098ba24e44bd62d23ad028700e42aL65-R65): Updated the `uses` attribute for the `dry-run-release-published` job …
=> 🔧 DAT-19374

.github/workflows/release-published.yml
This pull request adds a new step to the release workflow to write a summary of the workflow execution. The summary includes a link to the triggered workflow, which helps in tracking and verifying the release process.
Key changes:
* [`.github/workflows/release-published.yml`](diffhunk://#diff-f7ca0660afb7c5d6e7220dee8a6db81db251b3c98818f4d76a3e4441b85c7a6dR411-R437): Added a new step named "Write workflow summary" that uses the `actions/github-script@v7` action to generate a summary of the Docker release workflow and includes a link to the triggered workflow.
=> DAT-18993 DevOps :: Populate the triggered job link in a step

.github/workflows/create-release.yml
This pull request includes a change to the `.github/workflows/create-release.yml` file to add a check for the existence of a release tag in the OSS repository before proceeding with attaching files to the draft release.
Key change:
* Added a new step to check if the tag already exists in the OSS repository and exit with an error if it does, to prevent attaching artifacts to an already released tag. (`.github/workflows/create-release.yml`)
=> 🔧 DAT-19341: Add check for existing OSS release tag to prevent duplicate artifacts

liquibase-integration-tests/src/test/java/liquibase/dbtest/mysql/MySQLIntegrationTest.java, liquibase-integration-tests/src/test/resources/changelogs/mysql/complete/datafiles/uuid-data.csv, liquibase-integration-tests/src/test/resources/changelogs/mysql/complete/uuid.changelog.xml, liquibase-standard/src/main/java/liquibase/statement/ExecutablePreparedStatementBase.java
As UUID for Mysql is created as char(36), when loading UUID data we need to set it as String .
Many sources in the internet suggest to create UUID columns as binary(16) in order to save space and provide better sorting , but Liquibase has been generating it as char(36) for a long time and it would be a breaking change for everyone already using it. So this PR just fixes data loading and add integration tests for Mysql UUID .
* https://dev.mysql.com/blog-archive/storing-uuid-values-in-mysql-tables/
* https://blogs.oracle.com/mysql/post/mysql-uuids
* https://dev.mysql.com/blog-archive/mysql-8-0-uuid-support/
* https://planetscale.com/blog/the-problem-with-using-a-uuid-primary-key-in-mysql
* https://dev.mysql.com/blog-archive/mysql-8-0-uuid-support/ - liquibase documentation stating that …
=> fix mysql uuid load data issue

liquibase-integration-tests/src/test/groovy/liquibase/changeType/ChangeLogIncludeTest.groovy, liquibase-integration-tests/src/test/resources/changelogs/changeType/include/changelog-level3.xml, liquibase-integration-tests/src/test/resources/changelogs/changeType/include/changelog-mid.xml, liquibase-integration-tests/src/test/resources/changelogs/changeType/include/changelog-pages.xml, liquibase-integration-tests/src/test/resources/changelogs/changeType/include/changelog-teams.xml, liquibase-integration-tests/src/test/resources/changelogs/changeType/include/changelog-users.xml, liquibase-integration-tests/src/test/resources/changelogs/changeType/include/changelog.xml, liquibase-standard/src/main/java/liquibase/changelog/DatabaseChangeLog.java
Don't ignore logicalFilePath & parent tree cascading when including changelogs. 
Right now this kind of including fails:
```
parent, using logicalFilePath = bla
child1 -> with change named = change, logicalFilePath = child1
child2 -> with change named = change, logicalFilePath = child2
```
As it produces th following changeset id, ignoring the child logicalFilePath:
```
bla:change
bla:change
```
This fix makes it produces the expected changeset ids:
```
child1:change
child2:change
```
This fix also accounts for more levels, so you can have:
```
parent, using logicalFilePath = bla
mid, using logicalFilePath = mid
child1 -> with change named = change, logicalFilePath = child1
child2 -> with change named = change, logicalFilePath = child2
mid2, no logicalFilePath
child3 -> with change named …
```
=> Don't ignore logicalFilePath when including changelogs

.github/workflows/release-published.yml
This pull request includes changes to the `.github/workflows/release-published.yml` file to correct a parameter name and add a new job for publishing assets to an internal Nexus repository.
Parameter name correction:
* Changed `filename` to `fileName` in multiple steps to ensure consistency and correctness. [[1]](diffhunk://#diff-f7ca0660afb7c5d6e7220dee8a6db81db251b3c98818f4d76a3e4441b85c7a6dL132-R132) [[2]](diffhunk://#diff-f7ca0660afb7c5d6e7220dee8a6db81db251b3c98818f4d76a3e4441b85c7a6dL232-R232) [[3]](diffhunk://#diff-f7ca0660afb7c5d6e7220dee8a6db81db251b3c98818f4d76a3e4441b85c7a6dL491-R491)
New job addition:
* Added a new job `publish_assets_to_internal_nexus` to publish OSS released assets to `repo.liquibase.net`, including steps to download released assets and publish them to the …
=> ✨ feat: DAT-19341:publish_assets_to_internal_nexus repo.liquibase.net

.github/workflows/release-published.yml
This pull request includes changes to the `.github/workflows/release-published.yml` file to update the process for publishing OSS released assets. The main change is switching from publishing to an internal Nexus repository to publishing to an S3 bucket.
Changes to publishing process:
* Renamed the job from `publish_assets_to_internal_nexus` to `publish_assets_to_s3_bucket` and updated the job name to reflect the new destination.
* Removed the environment variables related to Nexus and added AWS credentials for accessing the S3 bucket.
* Removed the step that checks if the version already exists in Nexus, as this is no longer relevant.
* Updated the publishing step to use `aws s3 sync` instead of Maven commands for deploying files to the S3 bucket.
=> 🔧 DAT-19341: publish oss released assets to s3

.github/workflows/build-extension-jars.yml
This pull request includes updates to the `.github/workflows/build-extension-jars.yml` file to improve the build process for Liquibase extensions. The most important changes include updating the workflow to use a specific branch, adding the branch input parameter, and ensuring the correct branch is checked out during various steps.
Updates to the build process:
* [`.github/workflows/build-extension-jars.yml`](diffhunk://#diff-dc83207379251c4eeafe63714db8ce416c176c525edf14a8bd6ad57ca0e9027bL123-R127): Changed the workflow reference to use the `DAT-19574` branch instead of `main` for the `publish-for-liquibase.yml` workflow.
* [`.github/workflows/build-extension-jars.yml`](diffhunk://#diff-dc83207379251c4eeafe63714db8ce416c176c525edf14a8bd6ad57ca0e9027bL123-R127): Added the `branch` input …
=> 🔧 DAT-19574: git checkout a specific branch from input parameter

.github/workflows/build-extension-jars.yml
This pull request includes changes to the `.github/workflows/build-extension-jars.yml` file to introduce a new job for determining the appropriate branch to use for extensions. This ensures that the correct branch is referenced throughout the workflow. The most important changes include adding the `matching-branch-logic` job and updating various jobs to depend on its output.
Improvements to branch handling:
* Added a new job `matching-branch-logic` to determine the appropriate branch for extensions based on the input branch.
* Updated the `build-liquibase-checks` job to depend on the `matching-branch-logic` job and use its output for the branch reference.
* Updated the `build-and-deploy-extensions` job to depend on the `matching-branch-logic` job.
* Modified the `Checkout liquibase-pro` …
=> ✨ Add matching branch logic to workflow for dynamic branch handling

.github/workflows/build-extension-jars.yml
This pull request includes a change to the `.github/workflows/build-extension-jars.yml` file to improve the shell script syntax. The most important change is:
* Updated the `run` script to use proper shell script syntax by adding square brackets around the condition and quoting the `$GITHUB_OUTPUT` variable.
=> 🔧 Fix syntax for branch comparison in workflow script

.github/workflows/build-extension-jars.yml
For failure here:
https://github.com/liquibase/liquibase/actions/runs/13246462172/job/36974852699#step:3:4
We do not have a `main` PRO branch. 
This pull request includes several changes to the `.github/workflows/build-extension-jars.yml` file to improve the handling of branch logic for different types of builds. The changes primarily involve renaming and adding new job steps to better manage branch references for extensions and pro builds.
Branch logic improvements:
* Renamed `matching-branch-logic` to `matching-branch-logic-extensions` for better clarity and distinction between different branch logics.
* Added a new job `matching-branch-logic-pro` to handle branch logic specifically for pro builds. This includes determining the appropriate branch to use based on the input branch. …
=> 🔧 Refactor matching branch logic in workflow for PRO repo

.github/workflows/release-published.yml
This pull request includes modifications to the GitHub Actions workflow configuration in the `.github/workflows/release-published.yml` file. The changes involve re-adding and updating the job for generating SBOMs (Software Bill of Materials) for Liquibase and Liquibase Pro.
Changes to the GitHub Actions workflow:
* Removed the `trigger-sbom-generation-lb-lbpo` job and then re-added it with updated dependencies and parameters. The job now depends on both the `setup` and `update-docs-oss-pro-version` jobs and includes an updated `client-payload` for the repository dispatch step. [[1]](diffhunk://#diff-f7ca0660afb7c5d6e7220dee8a6db81db251b3c98818f4d76a3e4441b85c7a6dL255-L274) [[2]](diffhunk://#diff-f7ca0660afb7c5d6e7220dee8a6db81db251b3c98818f4d76a3e4441b85c7a6dR482-R502)
=> 🔧 Fix/generate-oss-pro-sbom-reports

liquibase-standard/src/main/java/liquibase/snapshot/jvm/SequenceSnapshotGenerator.java
In commit 88beffd sequence configuration values with Oracle defaults have been converted to null to exclude them from the change log. Unfortunatelly this broke the ability to create correct diffs in the situation where the new state should be the default value (which is currently represented as null and therefore not included in the change log).
Restore capturing of all attributes like it is done for other databases and elements.
Fixes #6632
Needs to be built and verified in the environment where we originally detected the issue.
No regression tests?
=> Snapshot all configuration values for Oracle sequences

liquibase-standard/src/main/java/liquibase/datatype/core/BooleanType.java, liquibase-standard/src/test/groovy/liquibase/datatype/DataTypeFactoryTest.groovy, liquibase-standard/src/test/groovy/liquibase/datatype/core/BooleanTypeTest.groovy
Fixes #4677 
For a changeset like the one below:
```xml
<createTable name="T">
<column defaultValueNumeric="0" name="c" type="BIT"/>
</createTable>
```
The below invalid SQL was being generated:
```
"c" BIT DEFAULT FALSE...
```
But even though it was:
```
"c" BIT DEFAULT 0
```
This is not allowed for Postgres. So basically, this PR is making `BIT` be treated and converted into a `BOOLEAN` type and then assigning the expected value.
=> Fix BIT column type handling for Postgres

liquibase-integration-tests/src/test/java/liquibase/threading/LiquibaseTest.java, liquibase-integration-tests/src/test/java/liquibase/threading/LiquibaseThreadingTest.java, liquibase-integration-tests/src/test/java/liquibase/threading/MemoryDatabase.java, liquibase-integration-tests/src/test/resources/changelogs/threading/changelog-1.xml, liquibase-integration-tests/src/test/resources/changelogs/threading/changelog.xml, liquibase-standard/src/main/java/liquibase/Scope.java
fix InheritableThreadLocal inconsistent behavior in threadpool environments by just copying the required objects.
Fix #6588
We need to re-execute the tests from https://datical.atlassian.net/browse/DAT-18871 and make sure that it still works fine.
=> Fix concurrency issues in multithread environments

.github/workflows/run-tests.yml
This pull request updates the GitHub Actions workflow to use a newer version of the Ubuntu operating system for running tests. The most important changes involve updating the OS version from Ubuntu 20.04 to Ubuntu 22.04 in various job configurations within the `.github/workflows/run-tests.yml` file.
Updates to OS version:
* Changed `runs-on` from `ubuntu-20.04` to `ubuntu-22.04` in the `setup` job.
* Updated the matrix configuration to use `ubuntu-22.04` instead of `ubuntu-20.04`.
* Modified the condition for checking unit test counts to use `ubuntu-22.04`.
* Updated the condition for uploading artifacts for Java 17 builds to use `ubuntu-22.04`. [[1]](diffhunk://#diff-7314d0ebbd2e9537ae4889316745b4fd2fa43cb86275c9caae18a86ba228b642L254-R254) …
=> 🔧 Update GitHub Actions workflow to use Ubuntu 22.04

liquibase-cli/pom.xml, liquibase-cli/src/main/java/liquibase/integration/commandline/CommandLineArgumentValueProvider.java
Fix liquibase-cli deployed to Maven Central is unusable as standard is not published. So we remove the reference for it and let people include liquibase-core manually.
Fixes #6145
=> fix liquibase-cli dependencies when deploying to Maven Central

liquibase-integration-tests/src/test/groovy/liquibase/command/core/GenerateChangeLogMSSQLIntegrationTest.groovy, liquibase-integration-tests/src/test/resources/changelogs/mssql/issues/decimal.sequence.sql, liquibase-standard/src/main/java/liquibase/snapshot/jvm/SequenceSnapshotGenerator.java
When snapshotting a sequence created with decimal(19) because we cast everything to a bigint we may hit an arithmetic overflow when casting the min, max, or start value of the sequence. 
This change:
1. Captures the data type and precision of the decimal sequence in our snapshot query
2. Generates the correct sql if we have a decimal sequence. Previously all MSSQL snapshots were assumed to be of type bigint, which is not necessary to include in your create sequence statement. 
Are there other data types that I should worry about while I'm here? I very intentionally did not add the data type for all sequences so as to not produce differences in diff from a previously generated changelog.
=> Fix snapshot for MSSQL decimal sequences (DAT-19504)

liquibase-standard/src/main/java/liquibase/command/core/helpers/DatabaseChangelogCommandStep.java
fix #5197: Ensure contexts from properties object are not ignored
This commit fixes an issue where context values defined in CHANGELOG_PARAMETERS object were being ignored by the cDatabaseChangelogCommandStep .
Now it extracts contexts and labels from the command scope and if present sets them in the changeLogParameters, otherwise don't use them. 
* Contexts and labels from dedicated parameters have priority over the values from the changeLogParameters object. Usually dedicated parameters come from the command line while changeLogParameters object comes from Liquibase class/maven. 
It was broken since 4.22.0 (command refactoring)
=> fix #5197: Ensure contexts from properties object are not ignored

liquibase-standard/src/main/java/liquibase/snapshot/SnapshotGeneratorChain.java, liquibase-standard/src/main/java/liquibase/snapshot/jvm/JdbcSnapshotGenerator.java, liquibase-standard/src/test/groovy/liquibase/snapshot/SnapshotGeneratorChainTest.groovy
Brings back what had to be rolledback from PR #5619 to be tested again and fix what is required.
The original code allowed only one Generator as top level for the chain. This PR improves chain handler to make sure that all subscribed generators are called.
Pro PR companion: https://github.com/liquibase/liquibase-pro/pull/1650
=> feat: improve snapshot generation for NOSQL databases

liquibase-integration-tests/src/test/groovy/liquibase/command/core/RollbackIntegrationTest.groovy, liquibase-integration-tests/src/test/resources/changelogs/common/test.tag.not.removed.by.rollback.xml, liquibase-standard/src/main/java/liquibase/change/core/TagDatabaseChange.java, liquibase-standard/src/main/java/liquibase/changelog/filter/AfterTagChangeSetFilter.java, liquibase-standard/src/main/java/liquibase/command/core/RollbackCommandStep.java, liquibase-standard/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd, liquibase-standard/src/test/java/liquibase/changelog/filter/AfterTagChangeSetFilterTest.java, liquibase-standard/src/test/resources/liquibase/change/ChangeDefinitionTest.yaml
Implement functionality to preserve tags when performing rollback operations in Liquibase, by adding a new `keepTagOnRollback` parameter to the `tag` change type.
This ensures tag information is maintained in the database change history during rollback scenarios, providing better traceability and consistency for database version control.
The `keepTagOnRollback` flag is not stored in dbcl table, but is always reloaded from the changelog. It's also not used to calculate the checksum. 
So you can change the value and it will be reflected in the next execution.
Fixes #6728
=> feat: new tagDatabase parameter to keep tag on rollback

liquibase-integration-tests/src/test/groovy/liquibase/command/UpdateCommandsIntegrationTest.groovy, liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseUpdateSQL.java, liquibase-standard/src/main/java/liquibase/Liquibase.java, liquibase-standard/src/main/java/liquibase/integration/commandline/Main.java
feat: Rename misleading update methods in Liquibase class
This change clarifies the API by giving methods names that accurately reflect their behavior. The old method names were misleading because they suggested database modification when they actually only generate SQL statements.
- Deprecated the `update(Writer)` variants that write SQL to output
- Added new `updateSql()` method that better describes what the function does
- Updated all references in tests and plugins to use the new method
=> feat: Rename misleading update methods in Liquibase class

liquibase-standard/src/main/java/liquibase/command/CommandFactory.java, liquibase-standard/src/main/java/liquibase/command/CommandStep.java, liquibase-standard/src/main/java/liquibase/command/core/InternalSnapshotCommandStep.java, liquibase-standard/src/main/java/liquibase/command/core/helpers/AbstractArgumentCommandStep.java, liquibase-standard/src/main/java/liquibase/command/core/helpers/AbstractHelperCommandStep.java, liquibase-standard/src/main/java/liquibase/command/core/helpers/ShowSummaryArgument.java, liquibase-standard/src/main/java/liquibase/util/HelpUtil.java
This PR ensures that commands are correctly marked as internal when all of their pipeline steps are internal. It adds logic to `CommandFactory.adjustCommandDefinitionForSteps()` to track if all steps are internal, and then sets the command definition's internal status accordingly.
It also removes the command name hiding functionality from helper classes. It:
1. Removes the `adjustCommandDefinition()` method from `AbstractArgumentCommandStep`
2. Removes the same method override from `ShowSummaryArgument`
3. Removes the utility method `hideCommandNameInHelpView()` from `HelpUtil`
This change simplifies the codebase by relying on the `isInternal()` method alone to determine command visibility, eliminating redundant code that manipulated command definitions directly.
=> feat: Improve Command Definition Internal Status Inheritance

liquibase-standard/src/main/java/liquibase/analytics/LiquibaseAnalyticsListener.java
The isEnabled method was being called while determining priority, which was unnecessary when multiple analytics listeners are on the classpath. This change delays the call to the isEnabled flag until after priority has been determined, which means that it should only be called once.
=> DAT-20082: analytics: don't needlessly call isEnabled method when determining priority

liquibase-standard/src/main/java/liquibase/command/core/CalculateChecksumCommandStep.java, liquibase-standard/src/main/java/liquibase/command/core/TagCommandStep.java, liquibase-standard/src/main/java/liquibase/command/core/TagExistsCommandStep.java, liquibase-standard/src/main/java/liquibase/command/core/helpers/AbstractChangelogCommandStep.java, liquibase-standard/src/main/java/liquibase/command/core/helpers/AbstractDatabaseConnectionCommandStep.java, liquibase-standard/src/main/java/liquibase/command/core/helpers/ChangeExecListenerCommandStep.java, liquibase-standard/src/main/java/liquibase/command/core/helpers/DatabaseChangelogCommandStep.java, liquibase-standard/src/main/java/liquibase/command/core/helpers/DbUrlConnectionCommandStep.java, liquibase-standard/src/main/java/liquibase/command/core/helpers/LockServiceCommandStep.java, liquibase-standard/src/main/java/liquibase/command/core/helpers/PreCompareCommandStep.java, liquibase-standard/src/main/java/liquibase/command/core/helpers/ReferenceDbUrlConnectionCommandStep.java, liquibase-standard/src/main/java/liquibase/command/core/helpers/ShowSummaryArgument.java
without this it is not possible to use the constants from the outside, in which case one instead has to manually write the magic string, which is error-prone.
other command names are already public and can already be used from the outside.
this has been done using search & replace and should've solved it for all existing commands.
n/a
n/a
i noticed this for `TagCommandStep` while working on `liquibase-opensearch` but decided to fix it for all of them.
you might want to add an automated test (based on reflection) which ensures that all `COMMAND_NAME` and `*_ARG` fields in `liquibase.command.core.*CommandStep` classes are always `public` to ensure that this doesn't happen again? but please do so in a follow-up PR as i'd like to see this land in the next release so that i can clean up my …
=> make all command names public

liquibase-integration-tests/src/test/groovy/MySQLTest.groovy, liquibase-integration-tests/src/test/groovy/liquibase/MssqlTest.groovy
Very simple fix, some groovy tests uses wrong variable names (like `var postgres = ...` but actually it's about `mysql` test)   
I was reading the code to understand a thing and then I found out the wrong names.
Very simple fix.
N/A.
Fixes #6933
=> fix: Integration-Tests - Groovy - Wrong variable names

liquibase-integration-tests/src/test/java/liquibase/dbtest/pgsql/PostgreSQLIntegrationTest.java, liquibase-standard/src/main/java/liquibase/change/core/CreateIndexChange.java, liquibase-standard/src/main/java/liquibase/diff/output/changelog/core/ChangedIndexChangeGenerator.java, liquibase-standard/src/main/java/liquibase/diff/output/changelog/core/MissingIndexChangeGenerator.java, liquibase-standard/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java, liquibase-standard/src/main/java/liquibase/snapshot/jvm/IndexSnapshotGenerator.java, liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateIndexGenerator.java, liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateIndexGeneratorPostgres.java, liquibase-standard/src/main/java/liquibase/statement/core/CreateIndexStatement.java, liquibase-standard/src/main/java/liquibase/structure/core/Index.java, liquibase-standard/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd, liquibase-standard/src/test/java/liquibase/sqlgenerator/core/CreateIndexGeneratorPostgresTest.java, liquibase-standard/src/test/resources/liquibase/change/ChangeDefinitionTest.yaml
This enhancement allows specifying index types like btree, gin, gist, etc. when creating/snapshoting indexes in PostgreSQL, providing better control over index behavior and performance.
1. Adds a `using` property to `CreateIndexChange` and `Index` classes
2. Enhances JDBC snapshot capabilities to capture index types from PostgreSQL
3. Updates `CreateIndexGeneratorPostgres` to include the USING clause in SQL generation
4. Extends schema definitions by adding the `using` attribute to createIndex in XML
5. Updates related generators and statement classes to support the new property
=> feat: Add PostgreSQL Index Function Support via USING Clause

.github/workflows/release-published.yml
This pull request modifies the `.github/workflows/release-published.yml` file to adjust permissions and remove an unused job. The most significant changes include updating permissions for several jobs and deleting the `trigger-sbom-generation-lb-lbpo` job.
* Added `issues: write` to the `permissions` section to enable issue-related actions.
* Changed `permission-contents` from `read` to `write` for multiple jobs to allow write access to repository contents:
- For the `liquibase/docker` release job.
- For the `liquibase/liquibase-infrastructure` release job.
- For the `Repository Dispatch` job.
- For the `Checkout repository` job.
* Removed the `trigger-sbom-generation-lb-lbpo` job, which was responsible for generating SBOMs for `liquibase` and `liquibase-pro`. This includes deleting its …
=> ♻️ (release-published.yml): update permissions to allow write access for issues and adjust GitHub App token permissions

.github/workflows/release-published.yml
This pull request updates the `.github/workflows/release-published.yml` file to enhance security by using a GitHub App token for repository access instead of the default `GITHUB_TOKEN`. The most important changes are outlined below:
* **GitHub App Token Integration**: Added a new step, `Get GitHub App token`, which uses the `actions/create-github-app-token@v2` action to generate a GitHub App token. This step retrieves the token using the app's ID and private key, ensuring more secure access to the `liquibase-pro` repository.
* **Token Replacement**: Updated the `Download liquibase-pro xsd` step to use the newly generated GitHub App token (`steps.get-token.outputs.token`) instead of the default `GITHUB_TOKEN`. This change aligns with the enhanced security approach.
=> ♻️ DAT-20252: add GitHub App token retrieval for access token

.github/workflows/release-published.yml
This pull request updates the `.github/workflows/release-published.yml` file to enhance security by replacing the default GitHub token with a GitHub App token for accessing the `liquibase-pro` repository.
* Added a new step, "Get GitHub App token," to generate a GitHub App token using the app ID and private key stored in secrets. This token is scoped to the `liquibase-pro` repository with `read` permissions for contents.
* Updated the "Download liquibase-pro xsd" step to use the newly generated GitHub App token instead of the default `GITHUB_TOKEN`.
=> DAT-20252: use Github App Token

.github/workflows/release-published.yml
This pull request updates the workflow for determining the latest and previous version tags in the `.github/workflows/release-published.yml` file. It replaces the previous implementation with a more robust method for fetching and processing semver tags.
* Updated the logic for fetching the latest and previous version tags to ensure proper handling of semver tags, including stripping the `v` prefix and sorting by creation date.
Tested locally:
=> 🔧 DAT-20252: get latest_version and previous_version for OSS

.github/workflows/run-tests.yml
This pull request updates the workflow configuration in `.github/workflows/run-tests.yml` to modify a specific job parameter.
Workflow configuration update:
* Replaced the `generate_sbom` parameter with `generate_fossa_3p_license_report` in the `jobs` section of the workflow file. This change likely reflects a shift in the type of reporting or analysis being prioritized.
=> DAT-20186 Update run-tests.yml

liquibase-standard/src/main/java/liquibase/change/ColumnConfig.java, liquibase-standard/src/test/groovy/liquibase/change/ColumnConfigTest.groovy
- Introduced `rawDateValue` with getter and setter annotations to preserve original date input.
- Updated `setValueDate` and `load` methods to initialize `rawDateValue`.
Fixes #6983
=> feat: add rawDateValue field to store unprocessed date input in ColumnConfig

liquibase-standard/src/main/java/liquibase/snapshot/SnapshotGeneratorChain.java
- Initialize objectToSnapshot as null , so if nothing is found we return null
- Updated `SnapshotGeneratorChain` to pass `example` only if the previous generator could not find it.
- Don't overwrite the existing snapshot if the current generator returns null.
=> fix: update snapshot logic to handle null snapshot returns

liquibase-standard/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java
PR https://github.com/liquibase/liquibase/pull/6901 introduced index function snapshot capabilities for Postgresql database, but cockroachDB seems to be different and their indexes have more features (like primary and secundary, auto indexes, etc) . So do not snapshot index type for cockroach DB as indexes behave different on this database and we don't know where to find it.
=> fix: do not snapshot index type for cockroach DB as indexes behave different on this database and we don't know wher eto find it.

liquibase-standard/src/main/java/liquibase/changelog/DatabaseChangeLog.java
This pull request introduces a mechanism to exclude resources located in liquibase `internal `directory when searching for changelog resources to be included. It also adds a utility method to retrieve the URI of this internal directory. Below is a summary of the most important changes:
* Updated the `findResources` method in `DatabaseChangeLog` to exclude resources located in the `internal` subdirectory of the Liquibase home directory. This is determined by checking if the resource URI starts with `jar:<LiquibaseHome>/internal`.
How to reproduce it: 
Create a changelog.yml like this one: 
```
databaseChangeLog:
- includeAll:
path: .
endsWithFilter: .sql
```
Notice that we are not using `relativeToChangelogFile: true` neither `searchPath` property. So you need to be inside the directory …
=> feat: add logic to exclude resources from liquibaseHomeUri/internal in resource processing for includeAll

liquibase-standard/src/main/java/liquibase/change/ColumnConfig.java
This pull request introduces a small fix to the `ColumnConfig.java` file, specifically within the `getSerializableFieldValue` method. The change ensures that the `rawDateValue` field is excluded from checksum calculations by returning `null` for this field.
Caused by https://github.com/liquibase/liquibase/pull/7046
Fixes https://github.com/liquibase/liquibase/issues/7100
=> fix: prevent rawDateValue from being used for checksum calculations

liquibase-dist/pom.xml, liquibase-standard/pom.xml, liquibase-standard/src/test/groovy/liquibase/change/core/LoadDataChangeTest.groovy, liquibase-standard/src/test/resources/liquibase/change/core/sample.data.with.blank.line.csv, pom.xml
This pull request rolls back the OpenCSV version to 5.10 to address an issue with loading CSV files that include empty lines. A corresponding test has been added to ensure this functionality works as expected.
No significant impacts on the codebase. The change only affects the OpenCSV dependency version and resolves related issues with CSV processing.
Fixes #7020
None identified.
None.
=> Rollback OpenCSV version to 5.10 and address CSV loading issue

liquibase-standard/src/main/java/liquibase/sqlgenerator/core/RenameColumnGenerator.java, liquibase-standard/src/test/resources/liquibase/change/ChangeDefinitionTest.yaml, liquibase-standard/src/test/resources/verify/saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets/renameColumn/mariadb.sql, liquibase-standard/src/test/resources/verify/saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets/renameColumn/mysql.sql
Fixes #6876
- [x ] Bug fix (non-breaking change which fixes expected existing functionality)
From MySQL v8, rename column is introduced to rename column without altering the column definition, which could cause default value to be reset
RenameColumnGeneratorTest unit test is commented out due to past issue so UT is not implemented for this change
=> fix: Change the rename column query for mysql v8 and later using rename column to

liquibase-integration-tests/src/test/groovy/liquibase/command/core/GenerateChangeLogPostgresqlIntegrationTest.groovy, liquibase-standard/src/main/java/liquibase/command/core/GenerateChangelogCommandStep.java
=> Handle situation that occurs when generateChangeLog is run with diffTypes=data

.github/workflows/release-published.yml
This pull request makes a small change to the `.github/workflows/release-published.yml` workflow file, specifically by removing a step that dispatched an event to the `liquibase-aws-license-service` repository to update its `pom.xml` with the latest OSS release version.
=> DAT-20693: Remove repository dispatch step for updating pom.xml for aws-license-service

.github/workflows/release-published.yml
This pull request removes the `update-docs-oss-pro-version` job from the `.github/workflows/release-published.yml` workflow. This job previously handled updating OSS and PRO documentation tags based on OSS releases, including fetching secrets, generating tokens, checking out the repository, determining release versions, and dispatching events to the documentation repository.
**Workflow simplification:**
* Removed the entire `update-docs-oss-pro-version` job, which included steps for AWS credential configuration, secret retrieval, GitHub App token generation, repository checkout, version determination, and repository dispatch for documentation updates.
=> Remove update-docs-oss-pro-version job
