liquibase/liquibase

liquibase-core/src/main/java/liquibase/changelog/RanChangeSet.java, liquibase-core/src/main/java/liquibase/lockservice/StandardLockService.java
In order to develop extension for NoSQL databases like Cassandra, few private members needs to be make protected so I can extend LockService.
=> Chnages needed for extension development for NoSQL databases

liquibase-core/src/main/java/liquibase/Labels.java
A minor change to the internal data type.
=> switch from HashSet to LinkedHashSet so that the object retains ordering

liquibase-core/src/main/java/liquibase/changelog/ChangeLogParameters.java
CORE-2262 3.3.2 ant task dies on NPE in ChangeLogParameters - check for "currentLabelExpression == null" before using it.
=> Core-2262 3.3.2 ant task dies on NPE in ChangeLogParameters

liquibase-core/src/main/resources/dist/liquibase
Remove 'Liquibase Home is not set.' from stdout.
Output of updateSQL should not contain this line
=> Remove 'Liquibase Home is not set.' from stdout

liquibase-core/src/main/java/liquibase/datatype/core/IntType.java, liquibase-core/src/test/groovy/liquibase/datatype/DataTypeFactoryTest.groovy
Issue https://liquibase.jira.com/browse/CORE-2304 resolved with this
=> Added recognition for the INT4 alias for the int datatype

liquibase-core/pom.xml, liquibase-core/src/test/groovy/liquibase/change/ColumnConfigTest.groovy, liquibase-core/src/test/groovy/liquibase/change/ConstraintsConfigTest.groovy, liquibase-core/src/test/groovy/liquibase/change/core/LoadUpdateDataChangeTest.groovy, pom.xml
[CORE-2296 Upgrade Groovy and Spock to maintained versions](https://liquibase.jira.com/browse/CORE-2296)
=> CORE-2296 Upgrade Groovy and Spock to maintained versions

liquibase-core/src/main/java/liquibase/diff/output/changelog/core/ChangedSequenceChangeGenerator.java, liquibase-core/src/main/java/liquibase/sqlgenerator/core/TagDatabaseGenerator.java, liquibase-core/src/test/java/liquibase/sqlgenerator/core/TagDatabaseGeneratorTest.java
[CORE-2321](https://liquibase.jira.com/browse/CORE-2321) Update MSSQL query to use a safer, backward-compatible UPDATE statement rather than a MERGE
=> CORE-2321 Update MSSQL query to use UPDATE statement rather than a MERGE

liquibase-core/src/main/java/liquibase/Liquibase.java, liquibase-core/src/main/java/liquibase/changelog/filter/UpToTagChangeSetFilter.java, liquibase-core/src/main/java/liquibase/integration/ant/DatabaseRollbackFutureTask.java, liquibase-core/src/main/java/liquibase/integration/commandline/Main.java, liquibase-core/src/main/java/liquibase/integration/spring/SpringLiquibase.java, liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseFutureRollbackSQL.java
[CORE-2322](https://liquibase.jira.com/browse/CORE-2322) Add ability to update to a tag
Rebased [PR#394](https://github.com/liquibase/liquibase/pull/394) against master (3.4.x).
=> CORE-2322 Add ability to update to a tag 

liquibase-core/src/main/java/liquibase/change/AbstractChange.java, liquibase-core/src/main/java/liquibase/serializer/AbstractLiquibaseSerializable.java
[CORE-2302](https://liquibase.jira.com/browse/CORE-2302) Add ability to load nested object/collection properties and BigDecimal properties automatically
Added further type validation to avoid instantiating interfaces and abstract classes
=> CORE-2302 Add further type validation

liquibase-core/src/main/java/liquibase/datatype/core/BigIntType.java, liquibase-core/src/main/java/liquibase/datatype/core/IntType.java, liquibase-core/src/main/java/liquibase/datatype/core/MediumIntType.java, liquibase-core/src/main/java/liquibase/datatype/core/SmallIntType.java, liquibase-core/src/main/java/liquibase/datatype/core/TinyIntType.java, liquibase-core/src/test/groovy/liquibase/datatype/DataTypeFactoryTest.groovy
[CORE-2300](https://liquibase.jira.com/browse/CORE-2300) Unsigned Int / Bigint cannot be created
=> CORE-2300 Unsigned Int / Bigint cannot be created

liquibase-core/src/test/groovy/liquibase/datatype/DataTypeFactoryTest.groovy
A few of the test cases I added were incorrect. This should take care of it. Sorry about that.
=> CORE-2300 Fix a few incorrect test cases

.gitignore, liquibase-core/pom.xml, liquibase-core/src/main/java/liquibase/change/core/SQLFileChange.java, liquibase-core/src/main/java/liquibase/changelog/ChangeLogParameters.java, liquibase-core/src/main/java/liquibase/changelog/DatabaseChangeLog.java, liquibase-core/src/main/java/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParser.java, liquibase-core/src/main/java/liquibase/parser/core/yaml/YamlChangeLogParser.java, liquibase-core/src/main/java/liquibase/precondition/core/ChangeLogPropertyDefinedPrecondition.java, liquibase-core/src/main/resources/liquibase/parser/core/xml/dbchangelog-3.4.xsd, liquibase-core/src/test/java/liquibase/LiquibaseTest.java, liquibase-core/src/test/java/liquibase/changelog/ChangeLogParametersTest.java, liquibase-core/src/test/java/liquibase/changelog/ExpressionExpanderTest.java, liquibase-maven-plugin/pom.xml
please see: https://liquibase.jira.com/browse/CORE-2309
=> CORE-2309: enhancement for global and local properties

liquibase-core/src/main/java/liquibase/changelog/OfflineChangeLogHistoryService.java, liquibase-core/src/main/java/liquibase/database/core/MySQLDatabase.java
Fixed offline running with mysql DB and no version specified
=> Fixed offline running with mysql DB and no version specified

liquibase-core/src/main/java/liquibase/database/OfflineConnection.java, liquibase-core/src/main/java/liquibase/database/core/MSSQLDatabase.java, liquibase-core/src/test/java/liquibase/database/core/MSSQLDatabaseTest.java
[CORE-2363](https://liquibase.jira.com/browse/CORE-2363) Improve robustness of MSSQL database case-insensitivity check
Accounts for OfflineConnection and exceptional database names
=> CORE-2363 Improve robustness of MSSQL database case-insensitivity check

liquibase-core/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java, liquibase-core/src/main/java/liquibase/snapshot/ResultSetCache.java, liquibase-core/src/main/java/liquibase/snapshot/jvm/UniqueConstraintSnapshotGenerator.java, liquibase-core/src/main/java/liquibase/sqlgenerator/core/AddPrimaryKeyGeneratorInformix.java, liquibase-core/src/main/java/liquibase/sqlgenerator/core/AddUniqueConstraintGeneratorInformix.java
Hello Nathan,
I have made some changes to the change log generator to correctly make unique constraints for informix.
Thanks.
=> Fix unique constraint generator for informix

liquibase-core/src/main/java/liquibase/changelog/OfflineChangeLogHistoryService.java
Fixes a bug that prevents using OfflineConnection to perform updateSQL functionality programmatically.
=> Fix CSV header and String array size

liquibase-core/src/main/java/liquibase/serializer/AbstractLiquibaseSerializable.java, liquibase-core/src/main/java/liquibase/serializer/ChangeLogSerializer.java, liquibase-core/src/main/java/liquibase/serializer/ChangeLogSerializerFactory.java, liquibase-core/src/main/java/liquibase/serializer/LiquibaseSerializable.java, liquibase-core/src/main/java/liquibase/serializer/LiquibaseSerializer.java, liquibase-core/src/main/java/liquibase/serializer/ReflectionSerializer.java, liquibase-core/src/main/java/liquibase/serializer/SnapshotSerializer.java, liquibase-core/src/main/java/liquibase/serializer/SnapshotSerializerFactory.java, liquibase-core/src/main/java/liquibase/serializer/core/formattedsql/FormattedSqlChangeLogSerializer.java, liquibase-core/src/main/java/liquibase/serializer/core/json/JsonChangeLogSerializer.java, liquibase-core/src/main/java/liquibase/serializer/core/json/JsonSnapshotSerializer.java, liquibase-core/src/main/java/liquibase/serializer/core/string/StringChangeLogSerializer.java, liquibase-core/src/main/java/liquibase/serializer/core/string/StringSnapshotSerializer.java, liquibase-core/src/main/java/liquibase/serializer/core/string/StringSnapshotSerializerReadable.java, liquibase-core/src/main/java/liquibase/serializer/core/xml/XMLChangeLogSerializer.java, liquibase-core/src/main/java/liquibase/serializer/core/yaml/YamlChangeLogSerializer.java, liquibase-core/src/main/java/liquibase/serializer/core/yaml/YamlSerializer.java, liquibase-core/src/main/java/liquibase/serializer/core/yaml/YamlSnapshotSerializer.java, liquibase-core/src/main/java/liquibase/servicelocator/PrioritizedService.java, liquibase-core/src/test/java/liquibase/serializer/ChangeLogSerializerFactoryTest.java, liquibase-core/src/test/java/liquibase/serializer/MockChangeLogSerializer.java, liquibase-core/src/test/java/liquibase/serializer/ReflectionSerializerTest.java
[CORE-2340] (https://liquibase.jira.com/browse/CORE-2340) Add support for extensions to override the built-in change log, snapshot serializers
=> CORE-2340 Add support for extensions to override the built-in change log, snapshot serializers

liquibase-core/src/main/java/liquibase/datatype/core/UnknownType.java
[CORE-2345] (https://liquibase.jira.com/browse/CORE-2345) Add XML Type
I found some code that could be removed from UnknownType
=> CORE-2345 Remove special cases for XML types

liquibase-core/src/main/java/liquibase/sqlgenerator/core/DropDefaultValueGenerator.java
[CORE-14](https://liquibase.jira.com/browse/CORE-14) Improves robustness of the dynamic SQL generation for dropping a default constraint on SQL Server 2000 and later versions.
=> CORE-14 Dropping default values with MS-SQL

liquibase-core/src/main/java/liquibase/changelog/OfflineChangeLogHistoryService.java, liquibase-core/src/main/java/liquibase/database/OfflineConnection.java, liquibase-core/src/test/java/liquibase/changelog/OfflineChangeLogHistoryServiceTest.java
https://liquibase.jira.com/browse/CORE-2334
=> Disable  DATABASECHANGELOG table creation when running offline

liquibase-core/src/main/java/liquibase/changelog/RanChangeSet.java, liquibase-core/src/main/java/liquibase/changelog/filter/NotRanChangeSetFilter.java, liquibase-core/src/main/java/liquibase/changelog/visitor/ValidatingVisitor.java
This is a hack as the concept of storing the path seems to be broken or at least I do not understand it yet.
=> Fixed the classpath handling to make DbDoc work

liquibase-core/src/test/groovy/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParserTest.groovy, liquibase-core/src/test/resources/liquibase/parser/core/yaml/logicalPathChangeLog.yaml, liquibase-core/src/test/resources/liquibase/parser/core/yaml/testCasesChangeLog.yaml
[CORE-2383](https://liquibase.jira.com/browse/CORE-2383)
=> CORE-2383 Fix broken test

liquibase-core/src/main/java/liquibase/integration/commandline/CommandLineUtils.java
[CORE-2386](https://liquibase.jira.com/browse/CORE-2386) For MSSQL, escape username, which could be a domain-qualified Windows account e.g. DOMAIN\user
=> CORE-2386 For MSSQL, escape username

liquibase-core/pom.xml, liquibase-core/src/main/java/liquibase/changelog/OfflineChangeLogHistoryService.java, liquibase-core/src/main/java/liquibase/util/SqlParser.java, liquibase-core/src/main/java/liquibase/util/StringClauses.java, liquibase-core/src/main/java/liquibase/util/StringUtils.java, liquibase-core/src/main/java/liquibase/util/Validate.java, liquibase-core/src/main/javacc/liquibase/util/grammer/SimpleSqlGrammer.jj, liquibase-core/src/test/groovy/liquibase/change/core/SQLFileChangeTest.groovy, liquibase-core/src/test/groovy/liquibase/util/SqlParserTest.groovy, liquibase-core/src/test/groovy/liquibase/util/StringClausesTest.groovy, liquibase-core/src/test/java/liquibase/change/AbstractSQLChangeTest.java
=> Use a grammer for parsing SQL rather than regexps (CORE-2336)

liquibase-core/src/main/java/liquibase/sqlgenerator/core/DeleteGenerator.java, liquibase-core/src/test/java/liquibase/sqlgenerator/core/DeleteGeneratorTest.java
[CORE-2438](https://liquibase.jira.com/browse/CORE-2438) Quote special characters \ and $ in regex replacement strings
=> CORE-2438 DeleteGenerator does not handle parameter names and values with $ or \ properly

liquibase-core/src/main/java/liquibase/change/AbstractChange.java, liquibase-core/src/main/java/liquibase/change/ChangeParameterMetaData.java, liquibase-core/src/main/java/liquibase/util/beans/BeanIntrospector.java, liquibase-core/src/main/java/liquibase/util/beans/DefaultBeanIntrospector.java, liquibase-core/src/main/java/liquibase/util/beans/FluentPropertyBeanIntrospector.java, liquibase-core/src/main/java/liquibase/util/beans/IntrospectionContext.java, liquibase-core/src/main/java/liquibase/util/beans/PropertyUtils.java, liquibase-core/src/test/java/com/example/liquibase/change/ColumnConfig.java, liquibase-core/src/test/java/com/example/liquibase/change/ComputedConfig.java, liquibase-core/src/test/java/com/example/liquibase/change/CreateTableExampleChange.java, liquibase-core/src/test/java/com/example/liquibase/change/DefaultConstraintConfig.java, liquibase-core/src/test/java/com/example/liquibase/change/IdentityConfig.java, liquibase-core/src/test/java/com/example/liquibase/change/KeyColumnConfig.java, liquibase-core/src/test/java/com/example/liquibase/change/PrimaryKeyConfig.java, liquibase-core/src/test/java/com/example/liquibase/change/UniqueConstraintConfig.java
[CORE-2419](https://liquibase.jira.com/browse/CORE-2419) Support fluent/builder-style change properties
=> CORE-2419 Support fluent/builder-style change properties

liquibase-core/src/main/java/liquibase/Liquibase.java
[CORE-2451](https://liquibase.jira.com/browse/CORE-2451) Output USE <database> statement for SQL Server
=> CORE-2451 Output USE <database> statement for SQL Server

liquibase-core/src/main/java/liquibase/database/core/MSSQLDatabase.java
[CORE-2452](https://liquibase.jira.com/browse/CORE-2452) Quote index name on SQL Server
=> CORE-2452 Quote index name on SQL Server

liquibase-core/src/main/java/liquibase/sqlgenerator/core/DropPrimaryKeyGenerator.java
[CORE-2471](https://liquibase.jira.com/browse/CORE-2471) MSSQL: DropPrimaryKeyGenerator should use qualified path to the "schemas" view
=> CORE-2471 Fix dynamic SQL generation for dropping a primary key on MSSQL

liquibase-core/src/main/java/liquibase/lockservice/StandardLockService.java
Fixes a typo and a copy&paste error in StandardLockService regarding changelog lock recheck time.
=> Fix StandardLockService recheck time

liquibase-core/src/main/java/liquibase/database/core/DerbyDatabase.java
=> Derby sequenceCurrentValue Incorrect SQL

liquibase-core/src/main/java/liquibase/sqlgenerator/core/DeleteGenerator.java, liquibase-core/src/main/java/liquibase/sqlgenerator/core/UpdateDataChangeGenerator.java, liquibase-core/src/main/java/liquibase/statement/UpdateExecutablePreparedStatement.java
I would have refactored out the where parameters handling from all three occurrences into a method of a helper class, but I was not sure which helper class is suitable for this.
=> Fix and unify where parameters handling

liquibase-core/src/main/java/liquibase/diff/output/changelog/DiffToChangeLog.java
A self-closing `<databaseChangeLog/>` XML element,
such as the empty one generated by `generateChangelog`,
would cause malformed XML when `diffChangeLog` was run.
To reproduce the original bug, run `generateChangelog` immediately followed by `diffChangeLog`.
`generateChangelog` will correctly produce an empty `<databaseChangeLog/>` XML element. However, prior to this commit, `diffChangeLog` fails to overwrite the self-closing `<databaseChangeLog/>` with an opening tag.
(Java 1.8.0_51 on Windows.)
=> Fix XML for diffChangeLog if empty element

liquibase-core/src/main/java/liquibase/datatype/core/FloatType.java
See http://www.h2database.com/html/datatypes.html#double_type
=> H2 uses REAL instead of FLOAT

liquibase-core/src/main/java/liquibase/database/AbstractJdbcDatabase.java, liquibase-core/src/main/java/liquibase/database/core/OracleDatabase.java, liquibase-core/src/main/java/liquibase/statement/ExecutablePreparedStatementBase.java
apply the change to the 3.4.x branch
=> CORE-2543 - added timestamp support for oracle sql generation

liquibase-core/src/main/java/liquibase/change/core/LoadDataChange.java
- Also - fix the line number display when they don't match (was off by 1).
=> CORE-2539 - CSV # of elements must exactly match # of headers.

liquibase-core/src/main/java/liquibase/util/SqlUtil.java
=> CORE-2555: Also support the uppercase B'0' notation.

liquibase-core/src/main/java/liquibase/lockservice/StandardLockService.java
This is trying a pragmatic fix for this MSSQL NOCOUNT issue as no row count is available here. 
In my installation with MS SQL Server 2008 R2 the update always returns -1 when NOCOUNT is enabled.
This leads to the situation that the lock of the row succeeds, and the unlock fails. 
This fix makes both the lock and unlock succeed and will print a warning message.
As this code still accepts a "-1" when locking the row, this might lead to a race condition when locking the database for a migration. But this is already the case with the current setup.
The alternative would be to issue a "set nocount on" once a "-1" is received and to retry the statement. But this could be a second ticket.
Please let me know if this works for you.
Best regards,
Alexander …
=> CORE-910: Handle MSSQL returning rowcounts of -1 when NOCOUNT enabled

liquibase-core/src/main/java/liquibase/sqlgenerator/core/InsertSetGenerator.java
Fix for the CORE-2610 issue related to loadData : https://liquibase.jira.com/browse/CORE-2610
=> Fix for CORE-2610

liquibase-core/src/main/java/liquibase/diff/output/StandardObjectChangeFilter.java
Happens in this case:
https://github.com/liquibase/liquibase-hibernate/issues/101
=> FIxing NPE when object name is null

liquibase-core/src/main/java/liquibase/changelog/StandardChangeLogHistoryService.java, liquibase-core/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java
Ensure columns exist before getting type and size of columns.
=> Fix NPE in Standard Changelog History Service in certain cases

liquibase-core/src/main/java/liquibase/sqlgenerator/core/SetColumnRemarksGenerator.java, liquibase-core/src/main/java/liquibase/sqlgenerator/core/SetTableRemarksGenerator.java
See http://forum.liquibase.org/topic/h2-remark-support-for-columns-and-tables
=> Add column remark support for H2.

liquibase-core/src/main/java/liquibase/change/core/AddColumnChange.java, liquibase-core/src/test/java/liquibase/change/AddColumnChangeTest.java
Hi,
I made a fix to move the addition of reorg table statement outside of the add column loop so it creates a single reorg at the end.
Thanks & Regards,
Smruti..
=> CORE-2704 DB2 - multiple reorgs created

liquibase-core/src/main/java/liquibase/sqlgenerator/core/SetColumnRemarksGenerator.java, liquibase-core/src/main/java/liquibase/sqlgenerator/core/SetTableRemarksGenerator.java
Please merge this for ASANY databases
Thanks
=> SQL Anywhere has also a Standard-SQL "comment on" statement

liquibase-core/src/main/java/liquibase/diff/output/changelog/DiffToChangeLog.java, liquibase-core/src/main/java/liquibase/diff/output/changelog/core/MissingDataChangeGenerator.java
@nvoxland Please review and let me know if/what further steps I should take.
=> Explicit UTF_8 constructing string from byte array

liquibase-core/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java
Update to support DB2 for the iSeries.  With this version many of the commands which were failing before are able to complete succesfully.  A new referential constraint query for DB2i was created and executed in the appropriate places.  The DB2i query was built based on the documentation for version 7.3 of DB2 for i.
https://www.ibm.com/support/knowledgecenter/ssw_ibm_i_73/db2/rbafzcatalog.htm
As indicated in the link, it is preferred to use SYSIBM for querying instead of QSYS2 for performance reasons.  This was tested and verified on a DB2 for i database running version 7.2.
=> Update for DB2 iSeries support

liquibase-core/src/main/java/liquibase/change/core/LoadDataChange.java, liquibase-core/src/main/java/liquibase/database/AbstractJdbcDatabase.java, liquibase-core/src/main/java/liquibase/database/core/OracleDatabase.java, liquibase-core/src/main/java/liquibase/statement/BatchInsertExecutablePreparedStatement.java, liquibase-core/src/main/java/liquibase/statement/ExecutablePreparedStatementBase.java, liquibase-core/src/test/java/liquibase/change/custom/ExampleCustomSqlChange.java, liquibase-integration-tests/setup/oracle/build.xml, liquibase-integration-tests/setup/oracle/oracle.install.changelog.xml, liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java, liquibase-integration-tests/src/test/java/liquibase/dbtest/oracle/OracleIntegrationTest.java, liquibase-integration-tests/src/test/resources/changelogs/oracle/complete/batchInsert.changelog.xml, liquibase-integration-tests/src/test/resources/changelogs/oracle/complete/batchInsert.csv, liquibase-integration-tests/src/test/resources/changelogs/oracle/complete/root.changelog.xml
=> CORE-3000 BatchInsertExecutablePreparedStatement

liquibase-core/src/main/java/liquibase/sqlgenerator/core/DropDefaultValueGenerator.java
=> CORE-3009 ASANY Drop Default Value failed

liquibase-core/src/main/java/liquibase/changelog/DatabaseChangeLog.java, liquibase-core/src/test/java/liquibase/changelog/UnknownChangeLogFormatLoggingTest.java, liquibase-core/src/test/resources/liquibase/parser/core/xml/unknownIncludedFileChangeLog.xml
Fixes [CORE-3020](https://liquibase.jira.com/browse/CORE-3020).
=>  CORE-3020 No warning when included file doesn't exist (missing extension)

liquibase-core/src/main/java/liquibase/integration/spring/SpringLiquibase.java
That is a simple PR, simple refactoring, no functionality affected.
=> refactoring: extract methods, decrease level on indention

liquibase-core/src/main/java/liquibase/datatype/core/BlobType.java, liquibase-core/src/main/java/liquibase/datatype/core/TimestampType.java
Hi,
this PR is to fix null pointer
=> Bug fix for null pointer

liquibase-core/src/main/java/liquibase/database/core/SybaseASADatabase.java, liquibase-core/src/main/java/liquibase/snapshot/jvm/SequenceSnapshotGenerator.java, liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateSequenceGenerator.java
Sequence-Generation and Sequence-DropAll-Support implemented
=> CORE-3055: ASANY supports Sequences

.travis.yml, liquibase-core/src/main/java/liquibase/database/AbstractJdbcDatabase.java, liquibase-integration-tests/pom.xml, liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java, liquibase-integration-tests/src/test/java/liquibase/dbtest/asany/SybaseASAIntegrationTest.java, liquibase-integration-tests/src/test/java/liquibase/dbtest/derby/DerbyIntegrationTest.java, liquibase-integration-tests/src/test/java/liquibase/dbtest/firebird/FirebirdIntegrationTest.java, liquibase-integration-tests/src/test/java/liquibase/dbtest/h2/H2IntegrationTest.java, liquibase-integration-tests/src/test/java/liquibase/dbtest/hsqldb/HsqlIntegrationTest.java, liquibase-integration-tests/src/test/java/liquibase/dbtest/informix/InformixIntegrationTest.java, liquibase-integration-tests/src/test/java/liquibase/dbtest/mssql/AbstractMssqlIntegrationTest.java, liquibase-integration-tests/src/test/java/liquibase/dbtest/mssql/MssqlIntegrationTest.java, liquibase-integration-tests/src/test/java/liquibase/dbtest/mysql/MySQLIntegrationTest.java, liquibase-integration-tests/src/test/java/liquibase/dbtest/oracle/OracleIntegrationTest.java, liquibase-integration-tests/src/test/java/liquibase/dbtest/pgsql/PostgreSQLIntegrationTest.java, liquibase-integration-tests/src/test/java/liquibase/dbtest/sqlite/SQLiteIntegrationTest.java, liquibase-integration-tests/src/test/java/liquibase/statementexecute/AddColumnExecutorTest.java, liquibase-integration-tests/src/test/java/liquibase/statementexecute/AddUniqueConstraintExecutorTest.java, liquibase-integration-tests/src/test/java/liquibase/statementexecute/CreateDatabaseChangeLogLockTableExecuteTest.java, liquibase-integration-tests/src/test/java/liquibase/statementexecute/MarkChangeSetRanExecuteTest.java, liquibase-integration-tests/src/test/java/liquibase/statementexecute/RenameColumnExecuteTest.java, liquibase-integration-tests/src/test/java/liquibase/test/DatabaseTestContext.java, liquibase-integration-tests/src/test/resources/liquibase/liquibase.integrationtest.properties, liquibase-integration-tests/src/test/resources/travis-ci/mysql-setup.sql
Please see the discussion at https://liquibase.jira.com/browse/CORE-3063
* 8e90aff2 shows the changes necessary for H2IntegrationTest and MySQLIntegrationTest to pass for me.
The rest of this branch is an attempt to get travis-ci to run all the integration tests that currently pass.
=> CORE-3063 run integration tests in travis-ci for Pull Requests

liquibase-core/src/main/java/liquibase/command/core/DiffCommand.java, liquibase-core/src/main/java/liquibase/diff/output/ObjectChangeFilter.java, liquibase-core/src/main/java/liquibase/diff/output/StandardObjectChangeFilter.java, liquibase-core/src/main/java/liquibase/integration/commandline/CommandLineUtils.java, liquibase-core/src/main/java/liquibase/integration/commandline/Main.java, liquibase-core/src/main/java/liquibase/snapshot/DatabaseSnapshot.java, liquibase-core/src/main/java/liquibase/snapshot/SnapshotControl.java, liquibase-core/src/test/groovy/liquibase/diff/output/StandardObjectChangeFilterTest.groovy, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseDatabaseDiff.java
Proposed fix for issue CORE-3079.
=> CORE-3079  Make includeObjects and excludeObjects affect which objects are snapshotted

liquibase-core/src/test/java/liquibase/changelog/UnknownChangeLogFormatLoggingTest.java, liquibase-debian/src/deb/control/control, liquibase-rpm/pom.xml
Fix the local maven build and fix an error in the CircleCI build
=> Fix maven build

liquibase-core/src/main/java/liquibase/diff/output/changelog/core/MissingTableChangeGenerator.java
When column is the only part of unique constraint mark it unique in column specification rather than creating addUniqueConstraint after table creation.
This allows the following from MySQL to be correctly migrated from DB to change log via generateChangelog command:
CREATE TABLE AAA (
c1_auto_increment MEDIUMINT NOT NULL AUTO_INCREMENT UNIQUE,
c2_pk MEDIUMINT NOT NULL,
c3_pk MEDIUMINT NOT NULL,
PRIMARY KEY (c2_pk, c3_pk)
);
Before the fix generateChangeLog output had 2 parts:
1. create table AAA(
c1_auto_increment[auto_increment:true],
c2_pk[pk:true],
c3_pk[pk:true],
)
2. addUniqueConstraint
Step 1 fails because you can't create auto increment column that is not part of any key.
After the fix the output has 1 change:
1. create table AAA(
c1_auto_increment[auto_increment:true, …
=> Fix: generateChangeLog handles AUTO_INCREMENT UNIQUE column incorrectly.

liquibase-core/src/main/java/liquibase/changelog/DatabaseChangeLog.java, liquibase-core/src/test/groovy/liquibase/changelog/DatabaseChangeLogTest.groovy, liquibase-core/src/test/java/liquibase/changelog/ReversedChangeLogNamesComparator.java
Fixed missing reference substitution.
=> CORE-3123 fix includeAll comparator set up

liquibase-core/src/main/java/liquibase/sqlgenerator/core/DropIndexGenerator.java
please see [CORE-3106](https://liquibase.jira.com/projects/CORE/issues/CORE-3055)
=> CORE-3106: DROP INDEX has to be specify the tablename AND indexname

liquibase-core/src/main/java/liquibase/change/core/AddUniqueConstraintChange.java
=> CORE-3002: Revert Unique Index failed for SQLAnywhere

liquibase-core/src/main/java/liquibase/resource/FileSystemResourceAccessor.java
Fixes https://github.com/liquibase/liquibase/pull/734
=> Fix root path to work on Mac and Windows

liquibase-core/src/main/java/liquibase/datatype/core/UUIDType.java
It's the version tracked by spring boot 2.0.x
=> Backport #699 to the 3.5 branch

liquibase-core/src/main/java/liquibase/sqlgenerator/core/InsertOrUpdateGeneratorH2.java, liquibase-core/src/test/java/liquibase/sqlgenerator/core/InsertOrUpdateGeneratorH2Test.java
This PR is essentially the same as #682 | [CORE-3040](https://liquibase.jira.com/browse/CORE-3040) but for H2.
=> Fix InsertOrUpdateGeneratorH2

liquibase-core/src/main/java/liquibase/util/SpringBootFatJar.java, liquibase-core/src/test/java/liquibase/util/SpringBootFatJarTest.java
Add test cases and make test pass
=> Could not load change log in Spring boot nested jar

liquibase-core/src/main/java/liquibase/sqlgenerator/SqlGeneratorFactory.java, liquibase-core/src/test/java/liquibase/sqlgenerator/SqlGeneratorFactoryTest.java
CORE-3335. Fix for https://liquibase.jira.com/browse/CORE-3335. Fix problem with register/unregister SqlGenerators, add tests, small formatting.
=> CORE-3335 Fix problem with register/unregister SqlGenerators, add tests, small formatting.

liquibase-core/src/main/java/liquibase/command/core/DiffCommand.java
Change-Id: I675d62ae759793e0656fa549fac747def53689ba
Fix on diff databases. Besides the description on core-3100, this was also claiming inexistent differences.
=> CORE-3100 fix

liquibase-core/src/main/java/liquibase/changelog/DatabaseChangeLog.java, liquibase-core/src/main/java/liquibase/integration/spring/SpringLiquibase.java
https://liquibase.jira.com/browse/CORE-3192
=> Fix for bug: Error while including resources with includeAll directive.

liquibase-cdi/pom.xml, liquibase-core/pom.xml, liquibase-core/src/main/java/liquibase/resource/ClassLoaderResourceAccessor.java, liquibase-debian/pom.xml, liquibase-rpm/pom.xml, pom.xml
Reverts liquibase/liquibase#816
=> Revert "Fix for bug: Error while including resources with includeAll directiv…"

liquibase-core/src/main/java/liquibase/changelog/OfflineChangeLogHistoryService.java
Fixed issue [CORE-3089](https://liquibase.jira.com/browse/CORE-3089) and refactored to prevent regression in future
=> CORE-3089 Fix

liquibase-core/src/main/java/liquibase/util/BooleanParser.java, liquibase-core/src/test/java/liquibase/util/BooleanParserTest.java
Code cleanup to use more readable and faster operation
=> Refactored BooleanParser and test

liquibase-core/src/test/groovy/liquibase/datatype/DataTypeFactoryTest.groovy, liquibase-core/src/test/groovy/liquibase/resource/ClassLoaderResourceAccessorTest.groovy, liquibase-core/src/test/java/liquibase/datatype/ClobTypeTest.java, liquibase-core/src/test/java/liquibase/util/SpringBootFatJarTest.java
- reactivate tests
- Fix test expectations
- Do not influence other tests
=> Reactivate And Fix Tests

liquibase-core/src/main/java/liquibase/database/core/MariaDBDatabase.java
MariaDb since version 5.3  has time fractional support (https://mariadb.com/kb/en/library/microseconds-in-mariadb/), but liquibase doesn't support it for MariaDB, because MySQLDatabase (superclass of MariaDBDatabase) has method getMaxFractionalDigitsForTimestamp(), which return 0 for all MariaDB 5.3.x-5.5.x versions.
=> add MariaDB precision for TIME, DATETIME, and TIMESTAMP types for old MariaDB releases

liquibase-core/src/main/java/liquibase/AbstractExtensibleObject.java, liquibase-core/src/main/java/liquibase/structure/core/ForeignKey.java
Such change should increase performance and make code cleaner.
=> Changed for-loop for addAll method on collections

liquibase-core/src/main/java/liquibase/parser/ChangeLogParserFactory.java, liquibase-core/src/main/java/liquibase/servicelocator/PrioritizedService.java, liquibase-core/src/test/java/liquibase/changelog/ChangeLogParserFactoryTest.java, liquibase-core/src/test/java/liquibase/parser/ChangeLogParserFactoryTest.java, liquibase-core/src/test/java/liquibase/parser/MockChangeLogParser.java
=> Cleanup for MockChangeLog and ChangeLogParserFactory

liquibase-core/src/main/java/liquibase/database/core/DB2Database.java, liquibase-core/src/main/java/liquibase/datatype/core/BooleanType.java, liquibase-core/src/main/java/liquibase/lockservice/StandardLockService.java, liquibase-core/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java
As described here: https://liquibase.jira.com/browse/CORE-3388
This implementation is supporting boolean in DB LUW from version 11.1.1.1
=> DB2 LUW supports boolean data type column from version 11.1.1.1 [CORE-3388]

liquibase-core/src/main/java/liquibase/changelog/ChangeLogParameters.java, liquibase-core/src/test/java/liquibase/changelog/ChangeLogParametersTest.java
Proposal for implementation of [CORE-3205]
=> [CORE-3205] Change Log Parameters from Environment Variable

liquibase-core/src/main/java/liquibase/database/core/Firebird3Database.java, liquibase-core/src/main/java/liquibase/datatype/core/BooleanType.java
support firebird 3.0 type boolean
=> support boolean in firebird 3.0

.travis.yml, liquibase-core/src/main/java/liquibase/database/core/Ingres9Database.java, liquibase-core/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java, liquibase-core/src/main/java/liquibase/snapshot/jvm/UniqueConstraintSnapshotGenerator.java, liquibase-core/src/test/java/liquibase/change/ChangeParameterMetaDataTest.java
=> Ingres ext

liquibase-core/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.6.xsd
Type xsd:string added to where element of update element
=> [CORE-3411] - Type xsd:string added to where element of update element

liquibase-core/src/main/java/liquibase/sqlgenerator/core/SetNullableGenerator.java
Pull request for [CORE-3375](https://liquibase.jira.com/browse/CORE-3375)
=> CORE-3375 Don't require columnDataType on H2 for addNotNullConstraint

liquibase-core/src/main/java/liquibase/diff/output/changelog/DiffToChangeLog.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseDatabaseDiff.java
This proposed fix should prevent creation of empty changesets.
=> fix issue of creating empty changesets

liquibase-core/src/main/java/liquibase/database/core/OracleDatabase.java
Support for Oracle Proxy User through jdbc url sintax:
--url=jdbc:oracle:thin:PROXY_USER/@host:port/servicename
=> Using proxy user for Oracle Connections

base.pom.xml, default-site-macros.vm, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseChangeLogSyncMojo.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseChangeLogSyncSQLMojo.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseClearChecksumsMojo.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseDBDocMojo.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseDatabaseDiff.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseDropAll.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseFutureRollbackSQL.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseGenerateChangeLogMojo.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseListLocksMojo.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseReleaseLocksMojo.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseReportStatusMojo.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseRollback.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseRollbackSQL.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseTag.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseUpdate.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseUpdateSQL.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseUpdateTestingRollback.java, maven-site.vm
Updates to improve how the liquibase-maven-plugin documentation is generated, to make it look better in the liquibase.github.com website.
=> Fix site gen

liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
=> Fixed dataOutputDirectory parameter that was not being allowed

liquibase-dist/src/main/archive/GETTING_STARTED.txt
SQL was incorrect, corrected so it would function correctly.
=> SQL Correction in GET_STARTED.txt

liquibase-dist/src/main/archive/GETTING_STARTED.txt
=> Update to Get_Started.txt

liquibase-dist/src/main/archive/GETTING_STARTED.txt
=> Corrected Grammar

liquibase-dist/src/main/archive/README.txt
Removed trailing / still in the document.
=> Removed trailing /

liquibase-core/src/main/java/liquibase/database/core/MySQLDatabase.java
=> Updated mysql driver class

liquibase-dist/src/main/archive/examples/xml/sample.changelog.xml
changed Id of second changeset to 3. Per Mario. Advised us to keep the concepts simple.
=> Update to sample.changelog

liquibase-core/src/main/java/liquibase/Liquibase.java
Cherry-pick from master, PR #978
=> Make Liquibase AutoCloseable

liquibase-core/src/main/java/liquibase/command/core/HistoryCommand.java, liquibase-core/src/main/java/liquibase/integration/commandline/Main.java, liquibase-core/src/main/resources/liquibase/i18n/liquibase-commandline-helptext.xml, liquibase-core/src/test/groovy/liquibase/command/core/HistoryCommandTest.groovy, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseHistoryMojo.java
=> Added "history" command

base.pom.xml, liquibase-dist/pom.xml
=> Re-enable jacoco

liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseRollbackOneChangeSetSQL.java
=> Loaded changeSet proerties for rollbackOneChangeSetSQL

.travis.yml, .travis/databases.docker-compose.yml, .travis/maven.settings.xml, .travis/mysql-init.sql, liquibase-core/src/main/java/liquibase/sqlgenerator/core/MarkChangeSetRanGenerator.java, liquibase-integration-tests/src/test/java/liquibase/statementexecute/MarkChangeSetRanExecuteTest.java
---
Liquibase Version: '3.8.x'
---
- [X ] Bug fix (non-breaking change which fixes an issue)
Applying Travis config from master to the 3.8.x branch
=> Enable 3.8.x builds on Travis

liquibase-core/src/main/java/liquibase/datatype/core/SmallIntType.java
Added Postgres to the list of database which do not need arguments with SMALLINT
=> Added Postgres to the list of database which do not need arguments with SMALLINT DAT-4370

liquibase-core/src/main/java/liquibase/diff/output/changelog/DiffToChangeLog.java
Do not remove function parens from names when calculating dependencies
=> Fix NPE in dependency calculation when objects have no schema

liquibase-core/src/test/groovy/liquibase/command/core/HistoryCommandTest.groovy, liquibase-maven-plugin/pom.xml
---
title: 'Fix for test break when building with Java > 8
assignees: ''
---
A clear and concise description of the issue being addressed.
- Exact commands used - CLI, maven, gradle, …
=> Fix for test break when building with Java > 8

liquibase-core/src/main/java/liquibase/changelog/ChangeLogIterator.java, liquibase-core/src/main/java/liquibase/changelog/ChangeSet.java, liquibase-core/src/main/java/liquibase/database/DatabaseConnection.java, liquibase-core/src/main/java/liquibase/executor/AbstractExecutor.java, liquibase-core/src/main/java/liquibase/executor/Executor.java, liquibase-core/src/main/java/liquibase/executor/ExecutorService.java, liquibase-core/src/main/java/liquibase/executor/LoggingExecutor.java, liquibase-core/src/main/java/liquibase/executor/jvm/JdbcExecutor.java, liquibase-core/src/main/java/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParser.java, liquibase-core/src/main/java/liquibase/util/LiquibaseUtil.java, liquibase-core/src/main/resources/liquibase/i18n/liquibase-core.properties, liquibase-dist/src/main/archive/examples/xml/liquibase.sqlplus.conf
---
title: ''
assignees: ''
---
A clear and concise description of the issue being addressed.
A clear and concise …
=> Native executor implementation created DAT-4387

liquibase-core/src/main/java/liquibase/integration/commandline/Main.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseDatabaseDiff.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseRollbackOneChangeSetMojo.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseRollbackOneChangeSetSQL.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseRollbackOneUpdateMojo.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseRollbackOneUpdateSQL.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/MavenUtils.java
---
about: Report invalid format option even when no license DAT-4575
title: ''
assignees: ''
---
A clear and concise description of the issue being addressed.
- Exact commands used - CLI, maven, gradle, spring boot, servlet, …
=> Report invalid format option even when no license DAT-4575

liquibase-dist/src/main/archive/liquibase.bat
… with quotes around it LB-224
---
title: ''
assignees: ''
---
- Files used - sql …
=> Removing quotes around JAVA_HOME in case JAVA_HOME was originally set with quotes around it LB-224

liquibase-core/src/main/resources/liquibase/i18n/liquibase-commandline-helptext.xml
---
title: ''
assignees: ''
--- …
=> Added help text for the 'runWith' command line option DAT-4751

liquibase-dist/src/main/archive/examples/sql/liquibase.properties, liquibase-dist/src/main/archive/examples/xml/liquibase.properties
---
title: ''
assignees: ''
--- …
=> Re-worded sample properties file text LB-227 LB-228

liquibase-core/src/main/java/liquibase/changelog/visitor/RollbackVisitor.java
…-4657
---
title: ''
assignees: ''
---
- Files used - sql scripts, changelog …
=> Do not show "Rolling back" log message when using LoggingExecutor DAT-4657

liquibase-core/src/main/java/liquibase/change/ColumnConfig.java, liquibase-core/src/main/java/liquibase/change/ConstraintsConfig.java, liquibase-core/src/main/java/liquibase/change/core/AddColumnChange.java, liquibase-core/src/main/java/liquibase/change/core/CreateTableChange.java, liquibase-core/src/main/java/liquibase/diff/output/changelog/core/ChangedColumnChangeGenerator.java, liquibase-core/src/main/java/liquibase/diff/output/changelog/core/MissingColumnChangeGenerator.java, liquibase-core/src/main/java/liquibase/diff/output/changelog/core/MissingTableChangeGenerator.java, liquibase-core/src/main/java/liquibase/serializer/core/xml/XMLChangeLogSerializer.java, liquibase-core/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGenerator.java, liquibase-core/src/main/java/liquibase/structure/core/Column.java, liquibase-core/src/test/groovy/liquibase/change/ConstraintsConfigTest.groovy, liquibase-core/src/test/java/liquibase/serializer/core/xml/XMLChangeLogSerializerTest.java
This is the same as my previous pull request for this issue, but done against the 3.8.x branch.
┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-53) by [Unito](https://www.unito.io/learn-more)
=> Core 3463 fix for validateX attributes of constraintsConfig

liquibase-core/src/main/java/liquibase/database/core/PostgresDatabase.java, liquibase-core/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGenerator.java
…ay data type for Postgres DAT-4453
---
title: ''
assignees: ''
---
- Files used - …
=> Changes merged in from Datical branch to fix issue with capturing array data type for Postgres DAT-4453

liquibase-core/src/main/java/liquibase/command/core/DiffToChangeLogCommand.java, liquibase-core/src/main/java/liquibase/command/core/GenerateChangeLogCommand.java, liquibase-core/src/main/java/liquibase/diff/output/changelog/core/MissingDataChangeGenerator.java, liquibase-integration-tests/src/test/java/liquibase/dbtest/pgsql/PostgreSQLIntegrationTest.java
---
title: ''
assignees: ''
--- …
=> Use QUOTE_ALL_OBJECTS for generateChangelog/diff/diffToChangeLog

liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
---
title: ''
assignees: ''
--- …
=> Do not print message about license key when none set DAT-4844

liquibase-core/src/main/java/liquibase/diff/compare/core/TableComparator.java, liquibase-core/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java, liquibase-core/src/main/java/liquibase/snapshot/jvm/TableSnapshotGenerator.java, liquibase-core/src/main/java/liquibase/structure/core/Table.java
---
title: ''
assignees: ''
--- …
=> Always include tablespace in snapshot and handle default value use case DAT-4084

liquibase-core/src/main/java/liquibase/change/core/CreateProcedureChange.java, liquibase-core/src/main/java/liquibase/change/core/CreateViewChange.java, liquibase-core/src/main/java/liquibase/change/core/SQLFileChange.java, liquibase-core/src/main/java/liquibase/changelog/ChangeSet.java, liquibase-core/src/main/java/liquibase/changelog/DatabaseChangeLog.java, liquibase-core/src/main/java/liquibase/changelog/RanChangeSet.java, liquibase-core/src/main/java/liquibase/changelog/StandardChangeLogHistoryService.java, liquibase-core/src/main/java/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParser.java, liquibase-core/src/main/java/liquibase/parser/core/sql/SqlChangeLogParser.java, liquibase-core/src/main/java/liquibase/parser/core/xml/XMLChangeLogSAXParser.java, liquibase-core/src/main/java/liquibase/resource/ClassLoaderResourceAccessor.java, liquibase-core/src/main/java/liquibase/resource/CompositeResourceAccessor.java, liquibase-core/src/main/java/liquibase/resource/FileSystemResourceAccessor.java, liquibase-core/src/main/java/liquibase/resource/ResourceAccessor.java, liquibase-core/src/main/java/liquibase/sdk/resource/MockResourceAccessor.java, liquibase-core/src/main/java/liquibase/sdk/supplier/resource/ResourceSupplier.java, liquibase-core/src/main/java/liquibase/sqlgenerator/core/RemoveChangeSetRanStatusGenerator.java, liquibase-core/src/main/java/liquibase/util/FileUtil.java, liquibase-core/src/test/groovy/liquibase/change/core/SQLFileChangeTest.groovy, liquibase-core/src/test/groovy/liquibase/changelog/DatabaseChangeLogTest.groovy, liquibase-core/src/test/groovy/liquibase/parser/core/xml/XMLChangeLogSAXParser_RealFile_Test.groovy, liquibase-core/src/test/groovy/liquibase/resource/AbstractResourceAccessorTest.groovy, liquibase-core/src/test/resources/liquibase/integration/ant/ChangeLogDirectoryTest.xml, liquibase-core/src/test/resources/liquibase/integration/ant/ChangeLogSyncTaskTest.xml, liquibase-core/src/test/resources/liquibase/integration/ant/DatabaseRollbackFutureTaskTest.xml, liquibase-core/src/test/resources/liquibase/integration/ant/DatabaseRollbackTaskTest.xml, liquibase-core/src/test/resources/liquibase/integration/ant/DatabaseUpdateTaskTest.xml
#1225
LB-337
---
title: ''
assignees: ''
---
- Files used - sql scripts, changelog …
=> Improved "file not found" error message

liquibase-core/src/main/java/liquibase/database/core/DatabaseUtils.java, liquibase-core/src/main/java/liquibase/database/core/PostgresDatabase.java, liquibase-core/src/main/java/liquibase/integration/commandline/CommandLineUtils.java
- - -
title: ''
assignees: ''
- - - …
=>  Handle Postgres resetting SEARCH_PATH after rollback LB-225

liquibase-core/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.10.xsd, liquibase-dist/src/main/archive/examples/xml/blank.changelog.xml, liquibase-dist/src/main/archive/examples/xml/sample.changelog.xml, liquibase-integration-tests/src/test/resources/changelogs/oracle/complete/sqlplusExecutor.xml
- - -
title: ''
assignees: ''
- - - …
=> Created 3.10 xsds and moved runWith out of 3.9

liquibase-core/src/main/java/liquibase/sqlgenerator/core/AddDefaultValueGeneratorInformix.java, liquibase-core/src/test/java/liquibase/sqlgenerator/core/AddDefaultValueGeneratorInformixTest.java
Commit 1d6e13a144940dd233b5852698720dcf465c3d47 ported to branch 3.5.x
┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-112) by [Unito](https://www.unito.io/learn-more)
┆Fix Versions: Liquibase 3.10.2
=> Informix data type generation with Default Value cause

liquibase-core/src/main/java/liquibase/database/jvm/JdbcConnection.java
- - -
title: ''
assignees: ''
- - - …
=> Display exception error message when unable to connect to database LB-367

.gitignore, liquibase-core/src/main/java/liquibase/diff/output/changelog/DiffToChangeLog.java, liquibase-core/src/test/java/liquibase/diff/output/changelog/DiffToChangeLogTest.java
- - -
title: ''
assignees: ''
- - - …
=> Add any node types discovered from the runAfter and runBefore types to the Map DAT-4050

liquibase-core/src/main/java/liquibase/snapshot/jvm/UniqueConstraintSnapshotGenerator.java
Fixed #1199
┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-376) by [Unito](https://www.unito.io/learn-more)
=> Liquibase 3.6.0+ run slowly with unique column constraints

liquibase-core/src/main/java/liquibase/integration/commandline/CommandLineUtils.java
DAT-4928
---
title: ''
assignees: ''
---
- Files used - sql scripts, changelog …
=> Add Banner in log out put that directs users to online resources

liquibase-core/src/main/java/liquibase/command/core/RegisterChangeLogCommand.java, liquibase-core/src/main/java/liquibase/command/core/SyncHubCommand.java, liquibase-core/src/main/java/liquibase/configuration/HubConfiguration.java, liquibase-core/src/main/java/liquibase/hub/HubServiceFactory.java, liquibase-core/src/main/java/liquibase/hub/LiquibaseHubSecurityException.java, liquibase-core/src/main/java/liquibase/hub/core/HttpClient.java, liquibase-core/src/main/java/liquibase/hub/core/OnlineHubService.java, liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
DAT-4991
- - -
title: ''
assignees: ''
- - - …
=> Improved error messages when hub is not available

liquibase-core/src/main/java/liquibase/configuration/ConfigurationProperty.java, liquibase-core/src/main/java/liquibase/configuration/ConfigurationValueHandler.java, liquibase-core/src/main/java/liquibase/configuration/HubConfiguration.java, liquibase-core/src/test/groovy/liquibase/configuration/HubConfigurationTest.groovy, liquibase-core/src/test/java/liquibase/configuration/LiquibaseConfigurationTest.java
DAT-5072
- - -
title: ''
assignees: ''
- - - …
=> Trailing slash in liquibase.hub.url returns confusing error.

liquibase-core/src/main/java/liquibase/Liquibase.java, liquibase-core/src/main/java/liquibase/hub/core/OnlineHubService.java, liquibase-core/src/main/java/liquibase/hub/listener/HubChangeExecListener.java, liquibase-core/src/main/java/liquibase/hub/model/HubChange.java, liquibase-core/src/test/resources/META-INF/services/liquibase.executor.Executor, liquibase-integration-tests/src/test/groovy/liquibase/hub/OnlineHubServiceTest.groovy, liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java
- - -
title: ''
assignees: ''
- - - …
=> Finished implementation for updateCount and updateToTag Hub DAT-4899

liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
DAT-5089
- - -
title: ''
assignees: ''
- - - …
=> Synchub reports success for bogus values passed to hubEnvironmentId

liquibase-core/src/main/java/liquibase/Liquibase.java, liquibase-core/src/main/java/liquibase/hub/listener/HubChangeExecListener.java
- - -
title: ''
assignees: ''
- - - …
=> Added hub integration for changelog sync DAT-4901

liquibase-core/src/main/java/liquibase/hub/core/OnlineHubService.java, liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
DAT-5152
- - -
title: ''
assignees: ''
- - - …
=> update outputs the incorrect error message when Hub is offline.

liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
- - -
title: ''
assignees: ''
- - - …
=> Do not require URL for registerChangeLog DAT-5092

liquibase-core/src/main/java/liquibase/Liquibase.java
- - -
title: ''
assignees: ''
- - - …
=> Generate deployment ID for update to tag DAT-5259

liquibase-core/src/main/java/liquibase/Liquibase.java, liquibase-core/src/main/java/liquibase/hub/listener/HubChangeExecListener.java
- - -
title: ''
assignees: ''
- - - …
=> Hub integration for rollback by script DAT-5180

liquibase-core/src/main/resources/liquibase/i18n/liquibase-commandline-helptext.xml
- - -
title: ''
assignees: ''
- - - …
=> Help for Hub DAT-4987

liquibase-dist/src/main/archive/lib/liquibase_autocomplete.sh, liquibase-dist/src/main/archive/lib/liquibase_autocomplete_mac.bash
- - -
title: ''
assignees: ''
- - - …
=> Added registerChangeLog and syncHub to autocomplete scripts DAT-5185

liquibase-core/src/main/java/liquibase/hub/LiquibaseHubRedirectException.java, liquibase-core/src/main/java/liquibase/hub/core/HttpClient.java
- - -
title: ''
assignees: ''
- - - …
=> Handle non-JSON return content from Hub DAT-5306

liquibase-core/src/main/java/liquibase/Liquibase.java, liquibase-core/src/main/java/liquibase/hub/HubUpdater.java
- - -
title: ''
assignees: ''
- - - …
=> Do not send information to Hub for updateSQL DAT-5307

liquibase-core/src/main/java/liquibase/change/core/CreateTableChange.java, liquibase-core/src/main/java/liquibase/datatype/LiquibaseDataType.java, liquibase-core/src/main/java/liquibase/datatype/core/BigIntType.java, liquibase-core/src/main/java/liquibase/datatype/core/DecimalType.java, liquibase-core/src/main/java/liquibase/datatype/core/IntType.java, liquibase-core/src/main/java/liquibase/datatype/core/MediumIntType.java, liquibase-core/src/main/java/liquibase/datatype/core/NumberType.java, liquibase-core/src/main/java/liquibase/datatype/core/SmallIntType.java, liquibase-core/src/main/java/liquibase/datatype/core/TinyIntType.java, liquibase-core/src/main/java/liquibase/datatype/core/UnknownType.java
This hopefully fixes #1009
Some notes:
* This fix only applies to the `CreateTableChange` possible we need to include it in other places too
* The postgres tests don't seem, to run fine on my laptop, so it is hard to test this for me (some pointers would be appreciated).
┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-4) by [Unito](https://www.unito.io/learn-more)
=> Potential fix for generated columns on postgres

liquibase-core/src/main/java/liquibase/integration/commandline/CommandLineUtils.java
DAT-5410
- - -
title: ''
assignees: ''
- - - …
=> Update banner to indicate liquibase.com/support

liquibase-core/src/main/java/liquibase/Liquibase.java, liquibase-core/src/main/java/liquibase/command/core/RegisterChangeLogCommand.java, liquibase-core/src/main/java/liquibase/command/core/SyncHubCommand.java, liquibase-core/src/main/java/liquibase/hub/HubService.java, liquibase-core/src/main/java/liquibase/hub/HubUpdater.java, liquibase-core/src/main/java/liquibase/hub/core/MockHubService.java, liquibase-core/src/main/java/liquibase/hub/core/OfflineHubService.java, liquibase-core/src/main/java/liquibase/hub/core/OnlineHubService.java, liquibase-core/src/main/java/liquibase/hub/listener/HubChangeExecListener.java
- - -
title: ''
assignees: ''
- - - …
=> Caching for performance DAT-5371

liquibase-core/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.7.xsd, liquibase-core/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.8.xsd, liquibase-core/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.9.xsd
- - -
title: ''
assignees: ''
- - -
**Liquibase Version**: since 3.7
**Liquibase Integration & Version**: spring
Issue described also here [CORE-3534](https://liquibase.jira.com/browse/CORE-3534)
Our spring boot application fails to run any xml changescript linking to an xsd version > 3.6 as the xsd is invalid:
`Caused by: oracle.xml.parser.schema.XSDException: Invalid value 'validateForeignKey ' for attribute: 'name'`
This PR removes the offending space in the affected xsd files.
If this PR gets accepted the published xsds on http://www.liquibase.org/xml/ns/dbchangelog need to be updated as well. …
=> Fix xsd, remove surplus space after validateForeignKey

liquibase-core/src/main/java/liquibase/Liquibase.java, liquibase-core/src/main/java/liquibase/command/core/DropAllCommand.java, liquibase-core/src/main/java/liquibase/hub/HubUpdater.java, liquibase-core/src/main/java/liquibase/integration/commandline/Main.java, liquibase-core/src/test/groovy/liquibase/command/core/DropAllCommandTest.groovy, liquibase-core/src/test/java/liquibase/integration/commandline/MainTest.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseDropAll.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseSyncHubMojo.java
- - -
title: ''
assignees: ''
- - - …
=> Call syncHub at the end of dropAll DAT-5103

liquibase-core/src/main/java/liquibase/Liquibase.java, liquibase-core/src/main/java/liquibase/changelog/ChangeLogIterator.java, liquibase-core/src/main/java/liquibase/hub/listener/HubChangeExecListener.java, liquibase-core/src/test/groovy/liquibase/command/core/SyncHubCommandTest.groovy
- - -
title: ''
assignees: ''
- - - …
=> Capture the log for each change set to send to Hub DAT-5436

liquibase-core/src/main/java/liquibase/Liquibase.java, liquibase-core/src/main/java/liquibase/hub/listener/HubChangeExecListener.java
- - -
title: ''
assignees: ''
- - - …
=> Make count messages be log level FINE DAT-5481

liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseChangeLogMojo.java
DAT-5469
- - -
title: ''
assignees: ''
- - - …
=> Rename hubMode and hubApiKey maven configuration parameters

liquibase-core/src/main/java/liquibase/hub/core/OnlineHubService.java
- - -
title: ''
assignees: ''
- - - …
=> Do not show communication failure message for Hub if no API key DAT-5468

base.pom.xml, liquibase-core/src/main/java/liquibase/command/core/RegisterChangeLogCommand.java, liquibase-core/src/main/java/liquibase/parser/core/xml/XMLChangeLogSAXParser.java, liquibase-core/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.1.xsd, liquibase-dist/src/main/archive/examples/xml/blank.changelog.xml, liquibase-dist/src/main/archive/examples/xml/sample.changelog.xml
* Create new 4.1 xsd
DAT-5442
- - -
title: ''
assignees: ''
- - -
* Files used - …
=> Upgarde XSD to 4.1 DAT-5442

liquibase-core/src/main/java/liquibase/datatype/core/BigIntType.java, liquibase-core/src/main/java/liquibase/datatype/core/IntType.java, liquibase-core/src/main/java/liquibase/datatype/core/MediumIntType.java, liquibase-core/src/main/java/liquibase/datatype/core/SmallIntType.java, liquibase-core/src/main/java/liquibase/datatype/core/TinyIntType.java, liquibase-core/src/test/groovy/liquibase/datatype/DataTypeFactoryTest.groovy, liquibase-core/src/test/java/liquibase/verify/saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets/addColumn/oracle.sql, liquibase-core/src/test/java/liquibase/verify/saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets/createTable/oracle.sql, liquibase-core/src/test/java/liquibase/verify/saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets/modifyDataType/oracle.sql, liquibase-integration-tests/src/test/java/liquibase/statementexecute/CreateDatabaseChangeLogLockTableExecuteTest.java
Reverts liquibase/liquibase#945
┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-694) by [Unito](https://www.unito.io/learn-more)
=> Revert "[CORE-3523] Consistently map Liquibase integer types to Oracle integer types"

liquibase-core/src/main/java/liquibase/database/core/OracleDatabase.java
---
title: 'Fix for 1081 on 3.10.x'
assignees: ''
---
**Liquibase Version**:3.10.x
**Liquibase Integration & Version**: All
**Database Vendor & Version**: Oracle
**Operating System Type & Version**: NA
Fix for #1081 on the 3.10.x branch
See #1081 
See #1081
See #1081 
If applicable, add screenshots to help explain your problem.
=> Fix1081on3.10.x

liquibase-core/src/main/java/liquibase/hub/listener/HubChangeExecListener.java
- - -
title: ''
assignees: ''
- - - …
=> If the changelog has not been registered then show a message that says so DAT-5394

liquibase-core/src/main/java/liquibase/command/core/RegisterChangeLogCommand.java, liquibase-core/src/main/java/liquibase/hub/HubService.java, liquibase-core/src/main/java/liquibase/hub/core/MockHubService.java, liquibase-core/src/main/java/liquibase/hub/core/OfflineHubService.java, liquibase-core/src/main/java/liquibase/hub/core/OnlineHubService.java
DAT-5445
- - -
title: ''
assignees: ''
- - - …
=> NPE thrown when hubProjectId does not have permissions to a project

liquibase-core/src/main/java/liquibase/command/core/DropAllCommand.java, liquibase-core/src/main/java/liquibase/command/core/SyncHubCommand.java, liquibase-core/src/main/java/liquibase/integration/commandline/Main.java, liquibase-core/src/test/groovy/liquibase/command/core/DropAllCommandTest.groovy, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseDropAll.java
- - -
title: ''
assignees: ''
- - - …
=> Show warning message if changelog not registered when hub key exists and mode not off DAT-5522

liquibase-core/src/main/java/liquibase/hub/listener/HubChangeExecListener.java
…T-5634
- - -
title: ''
assignees: ''
- - - …
=> Check for API key before complaining about Hub when doing rollback DAT-5634

liquibase-core/src/main/java/liquibase/change/core/LoadDataChange.java, liquibase-core/src/main/java/liquibase/database/core/OracleDatabase.java
Fix issues dealing with loadData GH-1251
- - -
title: ''
assignees: ''
- - -
* …
=> Fix merge issue in OracleDatabase GH-1251

liquibase-core/src/main/java/liquibase/change/core/LoadDataChange.java
- - -
title: ''
assignees: ''
- - - …
=> Do not use batched statements for Postgres LoadDataChange LB-744

liquibase-core/src/main/java/liquibase/diff/output/changelog/core/MissingTableChangeGenerator.java, liquibase-core/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java, liquibase-core/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGenerator.java
- - -
title: ''
assignees: ''
- - - …
=> Handle MSSQL computed columns in generate changelog LB-366

liquibase-core/src/main/java/liquibase/diff/output/changelog/DiffToChangeLog.java, liquibase-core/src/main/java/liquibase/resource/ClassLoaderResourceAccessor.java, liquibase-core/src/main/java/liquibase/serializer/core/formattedsql/FormattedSqlChangeLogSerializer.java
… DAT-4673
- - -
title: ''
assignees: ''
- - -
* Files used - sql scripts, …
=> Load a Database object from the diff operation into the current scope DAT-4673

liquibase-core/src/main/java/liquibase/changelog/ChangeSet.java, liquibase-core/src/test/groovy/liquibase/changelog/ChangeSetTest.groovy
Fixes #1438 
- - -
about: Fix changeset dbms field serialisation 
title: Fix changeset dbms field serialisation 
labels: Status:Fixed
assignees: ''
- - -
**Liquibase Version**: 4.1.1-local-SNAPSHOT
**Operating System Type & Version**: MacOS 10.15.6
* [x ] Bug fix (non-breaking change which fixes an issue.)
Serialisation of multiple dbms values in changeset is not happening correctly
Create a changeset with multiple dbms e.g 'dbms1, dbms2' and ask for serialisation of dbms field
Serialisation of multiple dbms adds ',xxx' between multiple dbms serialised value
Serialisation of multiple dbms add ',' between multiple dbms serialised value
Add any other context …
=> Fix #1438 - changeset dbms field serialization

liquibase-core/src/main/java/liquibase/Liquibase.java, liquibase-core/src/main/java/liquibase/database/core/MySQLDatabase.java, liquibase-core/src/main/java/liquibase/hub/core/OnlineHubService.java
- - -
title: ''
assignees: ''
- - - …
=> Show error message to console when unable to retrieve changelog from Hub DAT-5666

liquibase-core/src/main/java/liquibase/precondition/core/PreconditionContainer.java
- - -
title: ''
assignees: ''
- - - …
=> Show warning level message when precondition onFail=WARN LB 654

liquibase-core/src/main/java/liquibase/database/core/MySQLDatabase.java, liquibase-core/src/main/java/liquibase/snapshot/jvm/ForeignKeySnapshotGenerator.java
- - -
title: ''
assignees: ''
- - - …
=> Remove check for MySQL constraints bug LB-868

liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
…re is a URL specified LB-737
- - -
title: ''
assignees: ''
- - -
* Files used - …
=> We do not need to connect to the DB for registerChangeLog even if there is a URL specified LB-737

liquibase-core/src/main/java/liquibase/hub/HubUpdater.java
- - -
title: ''
assignees: ''
- - - …
=> Send database/driver version information to Hub DAT-5545

liquibase-core/src/main/java/liquibase/executor/ExecutorService.java
- - -
title: ''
assignees: ''
- - - …
=> Fixes #1402 by using a ConcurrentHashMap

liquibase-core/src/main/java/liquibase/hub/listener/HubChangeExecListener.java
- - -
title: ''
assignees: ''
- - - …
=> Handle exceptions coming from generateSQL DAT-5620

liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
- - -
title: ''
assignees: ''
- - - …
=> Make the unexpectedChangeSets command require a changelog LB-375

liquibase-core/src/main/java/liquibase/snapshot/jvm/UniqueConstraintSnapshotGenerator.java
Reverted a previous commit that assumed all databases support bulk-querying constraint columns. Then, incorporated changes from #1479 to increase the number of databases that do support them.
Fixes #1477
┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-952) by [Unito](https://www.unito.io/learn-more)
=> Fixed UniqueConstraintSnapshotGenerator

liquibase-core/src/main/resources/liquibase/banner.txt
DAT-6032
- - -
title: ''
assignees: ''
- - - …
=> Add hub to banner.txt

liquibase-core/src/main/java/liquibase/command/core/RegisterChangeLogCommand.java, liquibase-core/src/main/java/liquibase/parser/core/yaml/YamlChangeLogParser.java, liquibase-core/src/test/groovy/liquibase/command/core/RegisterChangeLogCommandTest.groovy
…T-5674
- - -
title: ''
assignees: ''
- - - …
=> Extended RegisterChangeLogCommand support to JSON and YAML formats DAT-5674

liquibase-core/src/main/java/liquibase/command/core/RegisterChangeLogCommand.java
DAT-6116
- - -
title: ''
assignees: ''
- - - …
=> Do not register JSON with extra spaces in front of changeLogId  DAT-6116

liquibase-core/src/main/java/liquibase/database/core/CockroachDatabase.java
=> Fixed null pointer exception when statement is returned null

liquibase-core/src/main/java/liquibase/command/core/RegisterChangeLogCommand.java, liquibase-core/src/test/groovy/liquibase/command/core/RegisterChangeLogCommandTest.groovy, liquibase-core/src/test/resources/liquibase/test-changelog-empty.xml
- - -
title: ''
assignees: ''
- - - …
=> Handle empty change with self closing tag DAT-5699

base.pom.xml, liquibase-core/src/main/java/liquibase/command/core/RegisterChangeLogCommand.java
LB-1078
- - -
title: ''
assignees: ''
- - - …
=> Updated snakeyaml to 1.27

liquibase-core/src/main/java/liquibase/ui/ConsoleUIService.java
DAT-6340
- - -
title: ''
assignees: ''
- - - …
=> Updated headless property messaging

liquibase-core/src/main/java/liquibase/change/core/AddColumnChange.java, liquibase-core/src/main/java/liquibase/sqlgenerator/core/AddColumnGeneratorDefaultClauseBeforeNotNull.java
**Liquibase Version**: 4.3
**Liquibase Integration & Version**: All
**Liquibase Extension(s) & Version**: None
**Database Vendor & Version**:Firebird and Oracle
**Operating System Type & Version**:N/A
* [ x] Bug fix (non-breaking change which fixes an issue.)
Rolling back changes from #1485 since they create invalid sql code for Firebird and Oracle
There is not support for adding a column in a certain position in Firebird or Oracle.
In Firebird you can add it and then move it.
Add a changeset similar to this one with an existing table MI6 that contains at least 2 columns
Position is 1 based in Firebird 1.0 and above
```
<changeSet author="test" dbms="firebird" id="Test" objectQuotingStrategy="LEGACY"> 
<addColumn tableName="MI6"> 
<column name="James" position="2" type="int" …
```
=> Rollback changes to Firebird and Oracle from 1485

liquibase-core/src/main/java/liquibase/Liquibase.java
The 4.3.x code has changed enough from PR#998 that I re-did the fix against that branch instead of resolving the conflicts.
LB-14
┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-1108) by [Unito](https://www.unito.io/learn-more)
=> Fix NPE when output writer is null

liquibase-core/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.3.xsd
Fixes #1628
┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-1113) by [Unito](https://www.unito.io/learn-more)
=> Include existing dropPrimaryKey.dropIndex attribute in xsd

liquibase-core/src/main/java/liquibase/Liquibase.java, liquibase-core/src/main/java/liquibase/hub/HubService.java, liquibase-core/src/main/java/liquibase/hub/HubUpdater.java, liquibase-core/src/main/java/liquibase/hub/core/MockHubService.java, liquibase-core/src/main/java/liquibase/hub/core/OfflineHubService.java, liquibase-core/src/main/java/liquibase/hub/core/OnlineHubService.java, liquibase-core/src/main/java/liquibase/hub/model/HubLink.java, liquibase-dist/src/main/archive/liquibase
┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-1090) by [Unito](https://www.unito.io/learn-more)
=> Show Report URL Link after Operation

liquibase-core/src/main/java/liquibase/database/DatabaseFactory.java, liquibase-core/src/main/java/liquibase/database/jvm/JdbcConnection.java, liquibase-core/src/test/groovy/liquibase/database/jvm/JdbcConnectionTest.groovy
┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-1153) by [Unito](https://www.unito.io/learn-more)
=> Hide passwords from generated URLs

liquibase-core/src/main/java/liquibase/Liquibase.java, liquibase-core/src/main/java/liquibase/changelog/visitor/LoggingChangeExecListener.java, liquibase-core/src/main/java/liquibase/hub/listener/HubChangeExecListener.java
=> LB 1151 Handle existence of ChangeExecListener

liquibase-core/src/main/java/liquibase/changelog/StandardChangeLogHistoryService.java
Fixes #1639
┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-1172) by [Unito](https://www.unito.io/learn-more)
=> Support drivers that return a LocalDateTime for dates

liquibase-core/src/main/java/liquibase/integration/spring/SpringResourceAccessor.java, liquibase-core/src/main/java/liquibase/parser/core/xml/LiquibaseEntityResolver.java, liquibase-core/src/main/java/liquibase/resource/ClassLoaderResourceAccessor.java, liquibase-core/src/test/groovy/liquibase/integration/spring/SpringResourceAccessorTest.groovy
Fixes #1595
┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-1247) by [Unito](https://www.unito.io/learn-more)
=> Use classpath*: for searching in SpringResourceAccessor

liquibase-core/src/main/java/liquibase/resource/ClassLoaderResourceAccessor.java
Configurations containing resources in jars
Fixes #1436
┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-1218) by [Unito](https://www.unito.io/learn-more)
=>  includeAll not working with some ClassLoaderResourceAccessor

liquibase-dist/pom.xml, liquibase-dist/src/main/install4j/liquibase.install4j
=> Bundle installers with latest LTS jre

liquibase-core/src/main/java/liquibase/integration/ant/BaseLiquibaseTask.java, liquibase-core/src/main/java/liquibase/integration/commandline/Main.java, liquibase-core/src/main/java/liquibase/integration/servlet/LiquibaseServletListener.java, liquibase-core/src/main/java/liquibase/integration/spring/SpringLiquibase.java, liquibase-core/src/main/java/liquibase/ui/ConsoleUIService.java, liquibase-core/src/test/groovy/liquibase/ui/ConsoleUIServiceTest.groovy, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java
=> Default ConsoleUIService.allowPrompt to false LB-1220

liquibase-core/src/main/java/liquibase/hub/core/HttpClient.java
=> Modified 401 message coming back from Hub DAT-6465

liquibase-core/src/main/java/liquibase/changelog/ChangelogRewriter.java, liquibase-core/src/main/java/liquibase/hub/HubUpdater.java, liquibase-core/src/test/groovy/liquibase/changelog/ChangeLogRewriterTest.groovy
end of registration
DAT-6842
* Exact commands used - CLI, maven, gradle, spring …
=> Correctly update the changeLogId in the DatabaseChangeLog object at the end of registration DAT 6842

liquibase-core/src/main/java/liquibase/diff/compare/core/IndexComparator.java
=> Handle possible null objects in the reference or comparison lists LB 1115

liquibase-core/src/main/java/liquibase/Liquibase.java
=> Fix changeLogSync issue when Hub settings exist DAT-6938

liquibase-core/src/main/java/liquibase/database/core/PostgresDatabase.java, liquibase-core/src/test/java/liquibase/database/core/PostgresDatabaseTest.java
- - -
name: Pull Request. Fixed wrongly generated PKs for PostgreSQL.
about: In case of long PostgreSQL table names (more that 63 bytes) generates PK names are truncated with '_pkey' suffixes.
title: ''
assignees: ''
- - -
4.0.0 + 
List the steps to reproduce the …
=> Issue-1483: Fixed wrongly generated PKs for PostgreSQL.

liquibase-core/src/main/java/liquibase/statement/ExecutablePreparedStatementBase.java
LB-921
┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-1733) by [Unito](https://www.unito.io)
=> Expose changeset and resourceAccessor readers

liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseDatabaseDiff.java
=> Obsfucate reference password during verbose output LB-1740

liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseRegisterChangeLogMojo.java, liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseSyncHubMojo.java
=> Handle null project Id in Maven integration for registerChangeLog and syncHub DAT-7318

liquibase-core/src/main/java/liquibase/command/core/RegisterChangelogCommandStep.java
=> Improve hub project registration success msg with project name DAT-7175

liquibase-core/src/main/java/liquibase/Liquibase.java, liquibase-core/src/main/java/liquibase/hub/HubService.java, liquibase-core/src/main/java/liquibase/hub/HubServiceFactory.java, liquibase-core/src/main/java/liquibase/hub/HubUpdater.java, liquibase-core/src/main/java/liquibase/hub/core/MockHubService.java, liquibase-core/src/main/java/liquibase/hub/core/StandardHubService.java
=> Added operationCommand string to Operation POST in Hub DAT-6686

liquibase-dist/pom.xml, liquibase-dist/src/main/install4j/liquibase.install4j
DAT-7337
Uploaded JRE tar gz file uploaded to the location https://artifactory.datical.net/artifactory/datical-files-public/java/ …
=> upgrade JRE to 11.0.11.9 DAT-7337

liquibase-core/src/main/java/liquibase/hub/core/StandardHubService.java
=> when hub is unavailable, do not block lb operations DAT-6770

base.pom.xml, liquibase-integration-tests/docker/docker-compose.yml, liquibase-integration-tests/docker/mariadb-init.sql, liquibase-integration-tests/src/test/resources/liquibase/liquibase.integrationtest.jenkins.properties, liquibase-integration-tests/src/test/resources/liquibase/liquibase.integrationtest.properties
Add mariadb to integration test platforms
=> DAT-7232 add mariadb to integration test platforms

liquibase-core/src/main/java/liquibase/command/core/InternalDropAllCommandStep.java, liquibase-core/src/main/java/liquibase/hub/core/MockHubService.java, liquibase-core/src/main/java/liquibase/snapshot/jvm/UniqueConstraintSnapshotGenerator.java
=> Added table name to unique constraints cache key for MySQL LB-1593

liquibase-core/src/main/java/liquibase/change/AbstractSQLChange.java, liquibase-core/src/main/java/liquibase/changelog/ChangeSet.java, liquibase-core/src/main/java/liquibase/command/core/InternalExecuteSqlCommandStep.java, liquibase-core/src/main/java/liquibase/util/StringUtil.java, liquibase-core/src/test/groovy/liquibase/util/StringUtilTest.groovy
=> Fix bug in StringUtil.mergeTokens when there are tokens left over.  Also deprecated and renamed method DAT-7376

liquibase-core/src/main/java/liquibase/changelog/ChangeLogParameters.java
=> Resolve nested properties correctly DAT-7294

base.pom.xml, liquibase-integration-tests/docker/docker-compose.yml, liquibase-integration-tests/docker/mariadb-init.sql, liquibase-integration-tests/src/test/resources/liquibase/liquibase.integrationtest.jenkins.properties, liquibase-integration-tests/src/test/resources/liquibase/liquibase.integrationtest.properties
=> Enable integration tests to run on MariaDB DAT-7547

liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseUnexpectedChangeSetsMojo.java
=> Added Maven goal for unexpectedChangeSets LB-766

liquibase-core/src/main/java/liquibase/change/custom/CustomChangeWrapper.java, liquibase-core/src/test/groovy/liquibase/change/custom/CustomChangeWrapperTest.groovy
- - -
title: ''
assignees: ''
- - -
**Liquibase Version**: 3.10
Refer to issue #1591
Refer to issue #1591
Refer to issue #1591
Refer to issue #1591
- - -
* Fixed Issue: https://github.com/liquibase/liquibase/issues/1591
* Local Branch: https://github.com/liquibase/liquibase/tree/LB-1054
* Unit Tests: https://github.com/liquibase/liquibase/pull/1592/checks
* Functional Tests: https://jenkins.datical.net/job/liquibase-pro/job/LB-1054/
* Steps to Reproduce: https://github.com/liquibase/liquibase/issues/1591
* Guidance: 
* Requires a custom …
=> Add a validation error to fix #1591

liquibase-core/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java
**Liquibase Version**: 4.0.0
**Database Vendor & Version**: DB2 for AS400
See https://github.com/liquibase/liquibase/issues/1411 
- - -
* Fixed Issue: https://github.com/liquibase/liquibase/issues/1411 
* Local Branch: https://github.com/liquibase/liquibase/tree/wardvijf-1411-foreign-keys-db2-as400
* Unit Tests: https://github.com/liquibase/liquibase/pull/1412/checks
* Functional Tests: https://jenkins.datical.net/job/liquibase-pro/job/wardvijf-1411-foreign-keys-db2-as400/
* Steps to Reproduce: https://github.com/liquibase/liquibase/issues/1411 
* Guidance: 
* Only impacts DB2 on as400
Just code reviewed
┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-684) by [Unito](https://www.unito.io)
┆Fix …
=> Fixes #1411 by adding a separate query fr DB2 on AS400

liquibase-core/src/main/java/liquibase/changelog/ChangeLogHistoryServiceFactory.java
static methods synchronize on class object and normal methods synchronize on this. So the code here can throw a NullpointerException:
```
@Test
public void concurrency() {
IntStream.range(1, 100000).parallel().mapToObj(x -> {
ChangeLogHistoryServiceFactory.getInstance().resetAll();
return "";
}).collect(Collectors.toList());
}
```
- - -
title: 'Concurrency Bugfix'
assignees: ''
- - -
**Liquibase Version**: 3.8.7
**Database Vendor & Version**: H2, Oracle, Postgres
**Operating System Type & Version**: 
- - -
* Fixed Issue: Stand alone PR
* Local Branch: https://github.com/liquibase/liquibase/tree/Olard-patch-2
* Unit Tests: …
=> Fix synchronization in ChangeLogHistoryServiceFactory.java

liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java, liquibase-cli/src/test/groovy/liquibase/integration/commandline/LiquibaseCommandLineTest.groovy, liquibase-core/src/main/java/liquibase/GlobalConfiguration.java, liquibase-core/src/main/java/liquibase/configuration/LiquibaseConfiguration.java, liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
=> global option should be renamed to liquibaseTablespaceName DAT-7676

base.pom.xml, liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java, liquibase-core/src/main/java/liquibase/command/CommandDefinition.java, liquibase-core/src/main/java/liquibase/util/TableOutput.java, liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy
=> Modified CommandTests error message to show actual exception during load.  Added class for tabular output. DAT-7736

liquibase-core/src/main/java/liquibase/example/StartH2Main.java
Sonar scan identifying security hotspot issue in class for starting H2 example database.
N/A
N/A
Sonar scan does not identify line as a security hotspot
=> DAT-7815: resolve Sonar security hotspot issue in H2 example class

liquibase-core/src/main/java/liquibase/util/StringUtil.java, liquibase-core/src/main/java/liquibase/util/TableOutput.java, liquibase-core/src/test/groovy/liquibase/util/TableOutputTest.groovy
=> Added tabular output capability DAT-7748

liquibase-core/src/main/java/liquibase/util/StringUtil.java
Add the `splitByCharacterType` method from Apache Commons Lang `StringUtils` to the Liquibase `StringUtil`.
A clear and concise description of what happens in the software **before** this pull request.
- Include console output if relevant
- Include log files if available.
A clear and …
=> DAT-7746: move splitByCharacterType method to main Liquibase source

liquibase-core/src/main/java/liquibase/sqlgenerator/core/MarkChangeSetRanGenerator.java, liquibase-core/src/test/java/liquibase/sqlgenerator/core/MarkChangeSetRanGeneratorTest.java, liquibase-integration-tests/src/test/java/liquibase/statementexecute/MarkChangeSetRanExecuteTest.java
**Liquibase Integration & Version**:
The DBCL table should be updated with the new labels, contexts, and comments from rerunning changesets.
1. Create a rerunnable changeset.
```
--liquibase formatted sql
--changeset author:id labels:July2021 runOnChange:true
create or replace view myview as select * from atable;
```
2.  Run `liquibase update`.
3.  Modify the changeset by updating the changeset and giving it a new label.
```
--liquibase formatted sql
--changeset author:id labels:Aug2021 runOnChange:true
create or replace view myview as select * from atable where 1=1;
```
4.  Run `liquibase update`.
5.  Query the DATABASECHANGELOG tables
```
select id, author, …
```
=> DAT-7512: update comments, contexts, and labels columns in DBCL when rerunning changesets

liquibase-core/src/main/java/liquibase/snapshot/jvm/UniqueConstraintSnapshotGenerator.java, liquibase-core/src/test/java/liquibase/database/core/DB2zDatabaseTest.java, liquibase-integration-tests/src/test/java/liquibase/dbtest/db2z/DB2ZIntegrationTest.java, liquibase-integration-tests/src/test/java/liquibase/dbtest/db2z/DB2zIntegrationTest.java, liquibase-integration-tests/src/test/resources/changelogs/db2z/complete/included.changelog.xml, liquibase-integration-tests/src/test/resources/changelogs/db2z/complete/renamed.changelog.xml, liquibase-integration-tests/src/test/resources/changelogs/db2z/complete/root.changelog.xml, liquibase-integration-tests/src/test/resources/changelogs/db2z/rollback/rollbackable.changelog.xml, liquibase-integration-tests/src/test/resources/liquibase/liquibase.integrationtest.jenkins.properties, liquibase-integration-tests/src/test/resources/liquibase/liquibase.integrationtest.properties
Fixes #1730
**Liquibase Version**: 4.2.2
**Liquibase Integration & Version**: Maven
**Database Vendor & Version**: com.ibm.db2:db2jcc_license_cisuz & 9.7.5
**Operating System Type & Version**: Windows 10
I tried to implement Liquibase for my IBM DB2 zos database and when i run liquibase:generateChangeLog command, I’m getting the following error.
Error setting up or running Liquibase: liquibase.command.CommandExcecutionExceptoin: liquibase.exception.DatabaseException: Error executing SQL select CONSTRAINT_NAME, COLUMN_LIST as COLUMN_NAME, constraint_schema as CONSTRAINT_CONTAINER from information_schema.constraints where constraint_type=‘UNIQUE’ and …; DB2 SQL Error: SQLCODE=-204, SQLSTATE=42704, SQLERRMC=INFORMATION_SCHEMA.CONSTRAINTS, …
=> Fix UniqueConstraint snapshot query on db2z

liquibase-core/pom.xml
Add optional import on javax.activation package, avoiding the
NoClassDefFoundError error in OSGi environments on Java 11
- - -
about: Avoiding the NoClassDefFoundError error in OSGi environments on Java 11
title: ''
assignees: ''
- - -
**Liquibase Version**: 3.10.3
**Liquibase Integration & Version**: Maven build, running in Apache Karaf 4.2.9
**Database Vendor & Version**: HSQL for testing liquibase
**Operating System Type & Version**: Linux, openjdk build 11.0.9+11
Fixes #1254 with a build on Java 11 running in Java 11.
Help needed to test on Java 8/9/10 runtime, or builds produced by lower versions on Java 11.
I hope this one-liner will warrant a 3.10.4 release, despite the intentions stated in …
=> [CORE-1254] Fix OSGiResourceAccessor failing due to javax.activation

liquibase-core/src/main/java/liquibase/ui/ConsoleUIService.java, liquibase-core/src/main/java/liquibase/util/StringUtil.java, liquibase-core/src/test/groovy/liquibase/ui/ConsoleUIServiceTest.groovy, liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy
=> DAT-7798 Method to create byte array from string using encoding moved to StringUtil

liquibase-core/src/main/java/liquibase/util/TableOutput.java
=> DAT-7801: make TableOutput null safe and add additional entry point

liquibase-core/src/main/java/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParser.java, liquibase-core/src/main/java/liquibase/util/StringUtil.java, liquibase-core/src/test/groovy/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParserTest.groovy, liquibase-core/src/test/groovy/liquibase/util/StringUtilTest.groovy
* \[ ] Bug fix (non-breaking change which fixes an issue.)
* \[x] Enhancement/New feature (non-breaking change which adds functionality)
In YAML, JSON and XML changelogs, we can specify very descriptive changeset ids with spaces, e.g. "delete the …
=> Add support for changeset ids and authors with spaces in formattedsql changelogs.

liquibase-core/src/main/java/liquibase/hub/HubUpdater.java, liquibase-core/src/test/java/liquibase/datatype/BooleanTypeTest.java
Signed-off-by:Nathan Erwin <nathan.d.erwin@gmail.com>
- - -
Fixes #1357
about: bit column default values in PostgreSQL
title: ''
assignees: ''
- - -
**Liquibase Version**: 4.1.1
**Liquibase Integration & Version**: Maven
**Liquibase Extension(s) & Version**: postgresql-42.1.1.jar
**Database Vendor & Version**: PostgreSQL 13.0
**Operating System Type & Version**: Ubuntu 20.04.1 LTS
See #1357 
See #1357 
An `UnexpectedLiquibaseException` is thrown because boolean values are expected for the default value.
Allow setting a bit string as the …
=> Fixes Postgresql bit column support

liquibase-core/src/main/java/liquibase/command/core/InternalGenerateChangelogCommandStep.java, liquibase-core/src/main/java/liquibase/serializer/core/formattedsql/FormattedSqlChangeLogSerializer.java
=> Modified FormattedSqlChangeLogSerializer to allow extension DAT 7391

liquibase-core/src/main/java/liquibase/database/core/MariaDBDatabase.java, liquibase-core/src/main/java/liquibase/database/core/MySQLDatabase.java, liquibase-core/src/main/java/liquibase/snapshot/CachedRow.java
=> Handle issues with MariaDB/Clustrix DAT-7879

liquibase-core/src/main/java/liquibase/util/TableOutput.java
=> DAT-7928: properly split when the phrase is equal to the max length and a space needs to be added to the part

liquibase-core/src/main/java/liquibase/util/TableOutput.java
=> DAT-7981: handle line separators in TableOutput

liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
=> Make service discoverable for testing purposes DAT-8029

liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
=> Handle sub-commands parameter help correctly DAT-8005

liquibase-core/src/main/java/liquibase/util/StringUtil.java
=> Added method to handle wrapping with padding

liquibase-core/src/main/java/liquibase/command/core/DiffChangelogCommandStep.java, liquibase-core/src/main/java/liquibase/command/core/GenerateChangelogCommandStep.java, liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/generateChangelog.test.groovy
=> LB-1529 Add --includeTablespace argument to generateChangeLog

liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/diffChangelog.test.groovy
=> Fix integration test

liquibase-dist/src/main/archive/licenses/Liquibase Pro EULA Software License Subscription and Support Agreement.txt
=> updated eula license agreement with liquibase

.github/workflows/snyk.yml
Added snyk security scan as a nightly action
=> Added snyk configuration

base.pom.xml
=> udpate liquibase version to 4.6.0

changelog.txt
=> update changelog.txt with 4.6.0

liquibase-dist/src/main/archive/examples/xml/blank.changelog.xml, liquibase-dist/src/main/archive/examples/xml/sample.changelog.xml
=> update xsd to 4.6

base.pom.xml, changelog.txt
=> update version to 4.6.1

liquibase-core/src/main/java/liquibase/snapshot/DatabaseSnapshot.java, liquibase-integration-tests/src/test/resources/changelogs/pgsql/complete/root.changelog.xml
LB-373 fixes GH issue #1260 
- Exact commands used - CLI, maven, gradle, spring …
=> Handle multi-column indexes during JSON snapshot LB-373

.github/workflows/build.yml, liquibase-core/src/test/groovy/liquibase/util/LiquibaseUtilTest.groovy, liquibase-dist/pom.xml, pom.xml
Merged github action config to master, but there needs to be some changes. Going through a PR vs. committing directly to master.
=> Fixing and improving Github Actions

pom.xml
Temporary fix for failing CDI test on Java 16
=> Make CDILiquibaseTest pass

liquibase-core/src/main/java/liquibase/util/TableOutput.java
Using the table output class, a row which contains a line separator but is still shorter than the maxwidth of the column will not be split onto two lines.
A clear and concise description of what happens in the software **before** this pull request.
- Include console output if relevant …
=> Properly split table rows which contain a line separator (DAT-8492)

liquibase-core/src/main/java/liquibase/GlobalConfiguration.java, liquibase-core/src/main/java/liquibase/configuration/core/DefaultsFileValueProvider.java, liquibase-core/src/main/java/liquibase/hub/model/HubChange.java, liquibase-core/src/test/groovy/liquibase/configuration/core/DefaultsFileValueProviderTest.groovy, liquibase-core/src/test/groovy/liquibase/hub/model/HubChangeTest.groovy
=> Correctly default strict setting and use global configuration DAT-8547

liquibase-core/src/main/java/liquibase/sqlgenerator/core/AlterSequenceGenerator.java, liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateSequenceGenerator.java, liquibase-core/src/test/java/liquibase/sqlgenerator/core/AlterSequenceGeneratorTest.java
=> Incubyteco issue 1990

.github/workflows/release-extensions.yml
- Changes the release-extensions action to be an easier-to-work-with matrix style
- Adds the rest of the extensions that can be automated this way to the list
=> Improve extension release list

.github/util/package-install4j.sh, .github/util/re-version.sh, .github/util/sign-artifacts.sh, .github/util/workflow-helper.js, .github/workflows/create-release.yml, .github/workflows/release-published.yml
Finishes converting/testing the release process to be now driven via github actions
=> Automate release process via github actions

liquibase-dist/src/main/archive/licenses/README.txt
=> remove unused log4j references

liquibase-core/src/main/java/liquibase/hub/HubService.java, liquibase-core/src/main/java/liquibase/hub/HubServiceFactory.java, liquibase-core/src/main/java/liquibase/hub/core/MockHubService.java, liquibase-core/src/main/java/liquibase/hub/core/StandardHubService.java, liquibase-core/src/main/java/liquibase/hub/model/ApiKey.java, liquibase-core/src/main/java/liquibase/hub/model/CoreInitOnboardingResponse.java, liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/setup/SetupCleanResources.groovy
=> Initial implementation of init hub DAT-8769

changelog.txt, liquibase-core/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.7.xsd
=> update changelog and xsd

liquibase-core/src/main/java/liquibase/hub/HubService.java, liquibase-core/src/main/java/liquibase/hub/HubServiceFactory.java, liquibase-core/src/main/java/liquibase/hub/core/MockHubService.java, liquibase-core/src/main/java/liquibase/hub/core/StandardHubService.java
=> update HubService to allow POSTing operation for an organization (DAT-8776)

liquibase-core/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.7.xsd
**Liquibase Version**:4.6.x
**Liquibase Integration & Version**: Any
**Database Vendor & Version**:Any
**Operating System Type & Version**:Any
The comments for changelog attributes are marked as changeset attributes
Changed the comment to match the xsd element that it was meant for.
When searching for changelog attributes the comment for changelog is marked as a changeset attribute
Search for changelog attributes
and the comment shows that it is a changeset attribute
Change comment to match attribute
If applicable, add screenshots to help explain your problem.
=> Updated comment field for changeLog attributes

SECURITY.md
After discussion with the Liquibase InfoSec Team I am submitting this first version of Liquibase's Responsible Disclosure Policy to be added to the CORE Liquibase repo.
=> Liquibase Responsible Disclosure Policy

.github/workflows/build.yml
=> DAT-9170 add install4j signing to all builds

.github/workflows/build.yml, liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/core/MSSQLTestSystem.java, liquibase-integration-tests/src/test/java/liquibase/statementexecute/AbstractExecuteTest.java, liquibase-integration-tests/src/test/java/liquibase/statementexecute/AddAutoIncrementExecuteTest.java, liquibase-integration-tests/src/test/java/liquibase/statementexecute/AddColumnExecutorTest.java, liquibase-integration-tests/src/test/java/liquibase/statementexecute/AddUniqueConstraintExecutorTest.java, liquibase-integration-tests/src/test/java/liquibase/statementexecute/RenameColumnExecuteTest.java
=> Turn off MSSQL for AbstractExecuteTests

.github/workflows/build.yml
DAT-9268 execute setup and build only if human has applied label  SafeToBuild
- …
=> DAT-9268 execute setup and build only if human has applied label 

liquibase-core/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.8.xsd
=> create liquibase changelog xsd 4.8.0

changelog.txt
=> update changelog 4.8.0

liquibase-core/src/main/resources/liquibase/examples/json/example-changelog.json, liquibase-core/src/main/resources/liquibase/examples/sql/example-changelog.sql, liquibase-core/src/main/resources/liquibase/examples/xml/example-changelog.xml, liquibase-core/src/main/resources/liquibase/examples/yaml/example-changelog.yaml
**Liquibase Version**:4.7.1
**Liquibase Integration & Version**: <CLI, maven, gradle, spring boot, servlet, etc.>
**Database Vendor & Version**:h2
**Operating System Type & Version**:NA
Made example changelogs more consistant.
You will need 2 database instances.
Run update with example-changelog.xml on first database instance.
Run update with example-changelog.yaml on second database instance.
Execute diff command.
Second database instance has missing columns in Person and Company tables.
There are no differences.
If applicable, add screenshots to help explain your problem.
=> Made example changelogs more consistant. PR-2484

.github/workflows/build.yml
DAT-9268 rewrite condition checking for labeled event
- Exact commands used - …
=> DAT-9268 rewrite condition checking for labeled event

liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseValidate.java, liquibase-maven-plugin/src/test/java/org/liquibase/maven/plugins/LiquibaseValidateMojoTest.java, liquibase-maven-plugin/src/test/resources/validate/plugin_config.xml
**Liquibase Version**: 
**Liquibase Integration & Version**: maven 2.0.5 -> latest
In our CI Merge Request flow we would like to use Liquibase's validate functionality, but is was unavailable in the maven-liquibase-plugin. We think that this functionality would be useful for others, too.
Add validate goal to pom.xml, it will fail:
```
<plugin>
<groupId>org.liquibase</groupId>
<artifactId>liquibase-maven-plugin</artifactId>
<version></version>
<configuration>
<verbose>true</verbose>
<promptOnNonLocalDatabase>false</promptOnNonLocalDatabase>
</configuration>
<executions>
<execution>
<id>liquibase-validate</id>
<phase>process-resources</phase>
<goals>
<goal>validate</goal>
</goals> …
```
=> Add validate goal to maven-liquibase-plugin

.github/pull_request_template.md
Replaced direction to go to discord for help with direction to go to Forum in  Help call to action on PR tempalte …
=> replaced discord with forum

.github/workflows/url-check.yml, .github/workflows/url-test.md
=> DAT-9212 add smoke test action

liquibase-core/src/main/java/liquibase/sqlgenerator/core/InsertOrUpdateGeneratorHsql.java, liquibase-core/src/test/groovy/liquibase/sqlgenerator/core/InsertOrUpdateGeneratorHsqlTest.groovy
issue #2375 update statement when onlyUpdate is false;
reverted changes from PR #1563 so now it covers both onlyUpdate options
**Liquibase Version**: 4.5.0
**Liquibase Integration & Version**: -
**Liquibase Extension(s) & Version**: -
**Database Vendor & Version**: HSQLDB 2.6.0
**Operating System Type & Version**: ALL
closes #2375 ; Update part of sql generated for updateOnly: true/false options should be different. 
- Please be precise and ensure private information is …
=> issue #2375 update statement when onlyUpdate is false;

.github/workflows/url-check.yml, .github/workflows/url-test.md
=> DAT-9212 rename job and add slack notification

.github/workflows/build.yml, liquibase-core/src/test/groovy/liquibase/util/TestUtil.groovy
=> GitHub action dat 8923

.github/workflows/build.yml, liquibase-core/src/test/groovy/liquibase/util/TestUtil.groovy
Reverts liquibase/liquibase#2583
=> Revert "GitHub action dat 8923"

.github/workflows/url-check.yml, .github/workflows/url-test.md
=> DAT-9212 rebased; try a different url checker action

.snyk
=> DAT-9617 ignore liquibase version vuln

liquibase-core/src/main/java/liquibase/command/core/SnapshotCommandStep.java, liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/snapshot.test.groovy
=> Added --schemas argument to snapshot command DAT-9433

liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java, liquibase-integration-tests/src/test/java/liquibase/dbtest/sqlite/SQLiteIntegrationTest.java
**Liquibase Version**: 4.7.1
**Liquibase Integration & Version**: core
**Liquibase Extension(s) & Version**: none
**Database Vendor & Version**: Postgres 12
**Operating System Type & Version**: all (tested on Mac OS 10.15.7)
Added integration test showing that #1712 can no longer be reproduced
- TableExistsPrecondition correctly identifies existing tables by name
- TableExistsPrecondition correctly identifies existing tables by name
Depends on changes done [in this PR]https://github.com/liquibase/liquibase/pull/2529. Will rebase before merging. 
=> Add test for TableExistsPrecondition

liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy
=> Execute clean up even when unexpected exception thrown DAT-9683

liquibase-core/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.9.xsd
=> Created dbchangelog xsd

changelog.txt
=> updated changelog txt

.github/util/package-install4j.sh, .github/util/re-version.sh, .github/util/sign-artifacts.sh, .github/workflows/build.yml, .github/workflows/create-release.yml, liquibase-dist/src/main/install4j/liquibase.install4j
DAT-9524 enable apple notarization of macos installer
=> DAT-9524 enable apple notarization of macos installer 

.github/workflows/build.yml
=> DAT-9546 fail pr builds via gatekeeper job

.github/workflows/build.yml
Run corresponding test-harness tests on PRs
=> Run test-harness on PRs

.github/workflows/build.yml, liquibase-core/src/main/java/liquibase/change/AbstractChange.java
=> switch to using forked github action in build

liquibase-core/src/main/java/liquibase/license/LicenseServiceUtils.java
Makes the trial URL public so it can be accessed elsewhere.
N/A
N/A
N/A
=> make trial URL public (DAT-9626)

liquibase-dist/pom.xml, pom.xml
Upgrades mariadb driver to the current 3.0.4 version
Creating a manual PR since I couldn't find the dependabot one.
=> Upgrade mariadb driver to 3.0.4

liquibase-dist/pom.xml, pom.xml
Upgraded oracle driver to the newest major version
=> Upgraded oracle driver to 21.5.0.0

liquibase-maven-plugin/pom.xml
=> Add scope to maven dependencies

changelog.txt
=> update changelog to 4.10.0

.github/workflows/build.yml
**Liquibase Integration & Version**: N/A
Oracle integration tests frequently fail with the following error:
```
transfer failed for https://repo.maven.apache.org/maven2/org/firebirdsql/jdbc/jaybird/4.0.6.java8/jaybird-4.0.6.java8.pom: Connection timed out (Read failed)
```
Run the integration test suite in GitHub Actions.
Oracle integration tests fail with the above error.
Oracle integration tests do not fail.
This issue in another repository provided the suggestion on how to fix this: https://github.com/actions/virtual-environments/issues/1499#issuecomment-689467080
=> resolve oracle integration test maven connection timeout issue (DAT-10239)

liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/TestSystem.java, liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/TestSystemFactory.java, liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/spock/LiquibaseIntegrationMethodInterceptor.java
**Liquibase Integration & Version**: test system framework
Add a property called "liquibase.sdk.testSystem.skip" to the test system framework. This property works in conjunction with the "liquibase.sdk.testSystem.test" property, allowing developers to run all test system frameworks, and exclude a subset of them.
N/A
N/A
N/A
=> Test System Framework: add support for "liquibase.sdk.testSystem.skip" property

liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/TestSystem.java, liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/TestSystemFactory.java, liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/spock/LiquibaseIntegrationMethodInterceptor.java
Add a property called "liquibase.sdk.testSystem.skip" to the test system framework. This property works in conjunction with the "liquibase.sdk.testSystem.test" property, allowing developers to run all test system frameworks, and exclude a subset of them.
(cherry picked from commit 8d3abcdf19de204dbc519d350f7374f4137eb8bb)
- Ensure …
=> Test System Framework: add support for "liquibase.sdk.testSystem.skip" property (#2838)

liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java
Some properties in the property file were not being loaded if they were not specified in their individual mojo definitions.
Run a liquibase maven command with a pro license key specified in the property file as `liquibase.pro.licenseKey`
Pro license key is not loaded.
Pro license key is loaded.
=> register DefaultsFileValueProvider inside maven commands (DAT-10003)

liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy, liquibase-extension-testing/src/main/java/liquibase/extension/testing/TestFilter.java
**Liquibase Integration & Version**: test framework
Add support for filtering by command test definition, so that only a single command test can be run. Fix bug which prevented using only an include or exclude string for the command test filter.
N/A
Specifying only an include string for the command test filter is ignored.
Specifying only an include string is allowed and recognized.
=> improve Command Test filtering logic

liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/core/MSSQLTestSystem.java
to be aded to jdbc url
- Exact commands used - CLI, maven, gradle, spring boot, …
=> driver version upgrade requires to add trustServerCertificate

liquibase-core/src/main/java/liquibase/configuration/LiquibaseConfiguration.java
=> resolve code review comment

liquibase-core/src/main/java/liquibase/hub/core/StandardHubService.java
=> Filter out license key strings for Hub communication DAT-10522

.github/ISSUE_TEMPLATE/bug_report.md
=> Issue Template: added infrastructure type in environment context

liquibase-dist/src/main/maven/release.pom.xml
We do not actually use the beanutils code paths from opencsv, so we should exclude it
- Matches what we ship with the CLI
- Nothing
=> Exclude beanutils from dependency list

liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy, liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/setup/SetupModifyDbCredentials.groovy
Added ability to modify the .flow file to add database credentials to help test Flow
=> Added testing framework modifications for flow DAT 10586

liquibase-core/src/test/groovy/liquibase/parser/core/xml/LiquibaseEntityResolverTest.groovy
=> replace next with latest for xsd

liquibase-integration-tests/src/test/groovy/liquibase/command/core/ListLocksTest.groovy
Add test for list locks command for MariaDB
=> add ListLocksTest for MariaDB (DAT-10798)

liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy
Support setting `searchPath` in a command test definition.
This should not impact any existing command tests.
=> support setting searchPath in CommandTests (DAT-11055)

liquibase-core/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.15.xsd
=> add dbchangelog 4.15 xsd

liquibase-core/src/main/java/liquibase/resource/PathHandlerFactory.java
PathHandler.getResource was not respecting the searchPath setting.
Breaking changes this could cause in other places.
=> respect searchPath when using PathHandlerFactory

.github/workflows/build.yml
DAT-11427 add manual build trigger for QA team
- Nothing
- Nothing
=> DAT-11427 add manual build trigger

liquibase-core/src/main/java/liquibase/util/FilenameUtil.java
Add `concatWithForwardSlash` method to `FilenameUtil`
=> add concatWithForwardSlash method to FilenameUtil (DAT-11053)

liquibase-core/src/main/java/liquibase/changelog/ChangelogRewriter.java, liquibase-core/src/main/java/liquibase/command/core/AbstractHubChangelogCommandStep.java, liquibase-core/src/main/java/liquibase/command/core/DeactivateChangelogCommandStep.java, liquibase-core/src/main/java/liquibase/command/core/RegisterChangelogCommandStep.java
Register and deactivate changelogs in S3.
=> register and deactivate changelogs in S3 (DAT-11050)

liquibase-core/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java, liquibase-core/src/main/java/liquibase/snapshot/ResultSetCache.java
This is useful in case an extension has to override
liquibase.snapshot.jvm.UniqueConstraintSnapshotGenerator#listConstraints.
4.5.0
CLI
liquibase-hanadb
SAP HANA
see https://github.com/liquibase/liquibase-hanadb/issues/69
- Please be precise and ensure …
=> Make liquibase.snapshot.ResultSetCache an extensible class.

.github/workflows/release-published.yml
=> DAT-10128 add javadocs automation

liquibase-core/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.16.xsd
=> update changelog xsd to 4.16

changelog.txt
=> Update changelog txt to 4.16

liquibase-core/src/main/java/liquibase/Liquibase.java, liquibase-core/src/main/java/liquibase/changelog/visitor/DBDocVisitor.java, liquibase-core/src/main/java/liquibase/dbdoc/AuthorListWriter.java, liquibase-core/src/main/java/liquibase/dbdoc/AuthorWriter.java, liquibase-core/src/main/java/liquibase/dbdoc/ChangeLogListWriter.java, liquibase-core/src/main/java/liquibase/dbdoc/ChangeLogWriter.java, liquibase-core/src/main/java/liquibase/dbdoc/ColumnWriter.java, liquibase-core/src/main/java/liquibase/dbdoc/HTMLListWriter.java, liquibase-core/src/main/java/liquibase/dbdoc/HTMLWriter.java, liquibase-core/src/main/java/liquibase/dbdoc/PendingChangesWriter.java, liquibase-core/src/main/java/liquibase/dbdoc/PendingSQLWriter.java, liquibase-core/src/main/java/liquibase/dbdoc/RecentChangesWriter.java, liquibase-core/src/main/java/liquibase/dbdoc/TableListWriter.java, liquibase-core/src/main/java/liquibase/dbdoc/TableWriter.java
Use the new `Resource` classes in the db-doc command, to support writing files to S3.
=> use Resource classes in db-doc command (DAT-11549)

liquibase-core/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.17.xsd
Created changelog for 4.17 release.
- Nothing
=> Created 4.17 dbchangelog.xml file

changelog.txt
Updated changelog txt with fixes that went in 4.17.1 patch release
=> Updated changelog txt with 4.17.1 changes

liquibase-core/src/main/java/liquibase/change/core/CreateProcedureChange.java, liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/DatabaseTestSystem.java
Add auto rollback for CreateProcedureChange. Add test helper methods to DatabaseTestSystem.
=> add autorollback for CreateProcedureChange (DAT-10234)

liquibase-core/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGeneratorOracle.java
=> Modify getPriority method for the Oracle column snapshot generator class DAT-11512

liquibase-cli/src/main/java/liquibase/integration/commandline/CommandRunner.java, liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java, liquibase-core/src/main/java/liquibase/changelog/ChangelogRewriter.java, liquibase-core/src/main/java/liquibase/changelog/visitor/DBDocVisitor.java, liquibase-core/src/main/java/liquibase/dbdoc/ChangeLogWriter.java, liquibase-core/src/main/java/liquibase/dbdoc/HTMLListWriter.java, liquibase-core/src/main/java/liquibase/dbdoc/HTMLWriter.java, liquibase-core/src/main/java/liquibase/diff/output/changelog/DiffToChangeLog.java, liquibase-core/src/main/java/liquibase/diff/output/changelog/core/MissingDataExternalFileChangeGenerator.java, liquibase-core/src/main/java/liquibase/integration/commandline/LiquibaseCommandLineConfiguration.java, liquibase-core/src/main/java/liquibase/integration/spring/SpringResource.java, liquibase-core/src/main/java/liquibase/resource/AbstractResource.java, liquibase-core/src/main/java/liquibase/resource/OpenOptions.java, liquibase-core/src/main/java/liquibase/resource/PathHandlerFactory.java, liquibase-core/src/main/java/liquibase/resource/PathResource.java, liquibase-core/src/main/java/liquibase/resource/Resource.java, liquibase-core/src/main/java/liquibase/resource/ResourceAccessor.java, liquibase-core/src/test/groovy/liquibase/resource/PathHandlerFactoryTest.groovy
Reverts liquibase/liquibase#3368
=> Use PathHandler for writing log files, which allows using S3 and other extensions (DAT-11515)

liquibase-core/src/main/java/liquibase/change/core/CreateViewChange.java, liquibase-core/src/main/java/liquibase/change/core/DropViewChange.java, liquibase-core/src/main/java/liquibase/sqlgenerator/core/DropViewGenerator.java, liquibase-core/src/main/java/liquibase/statement/core/DropViewStatement.java, liquibase-core/src/test/java/liquibase/statement/core/DropViewStatementTest.java, liquibase-integration-tests/src/test/resources/changelogs/common/common.tests.changelog.xml
Add "ifExists" flag to the "dropView" statement, if the attribute is set to true, then the migration can progress further even when the view is not there.   
The change is backward compatible, so if that attribute is not specified, the same 'drop view X' statement is generated as before.
None
-
=> Add 'ifExists' parameter to the dropView statement

liquibase-core/src/main/java/liquibase/configuration/LiquibaseConfiguration.java
This change avoids potential issues with values that are provided by a value modifier extension by simplifying the way that we log the configuration values.
=> DAT-12400: do not convert configuration values when logging

liquibase-cli/pom.xml, liquibase-integration-tests/src/test/groovy/liquibase/diffchangelog/DiffChangelogTest.groovy
DiffchangelogTest  integration tests have been failing as it's complaining it cannot perform a commit when auto-commit mode is enabled. Here we are just disabled auto-commit mode to fix this issue.
- Nothing
- Nothing
- Nothing
=> Fix int test diff changelog test

liquibase-core/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.18.xsd
Created xsd for 4.18 release
None
None
=> Created dbchangelog 4.18

README.md
DUMMY COMMIT TO FORCE REBUILD OF MASTER!
=> Update README.md - added a . to the end of the file

liquibase-core/src/test/java/liquibase/change/AbstractSQLChangeTest.java, liquibase-core/src/test/java/liquibase/changelog/ChangeLogIteratorTest.java, liquibase-core/src/test/java/liquibase/database/core/PostgresDatabaseTest.java, liquibase-core/src/test/java/liquibase/executor/jvm/JdbcExecutorTest.java, liquibase-core/src/test/java/liquibase/integration/commandline/MainTest.java, liquibase-core/src/test/java/liquibase/integration/servlet/LiquibaseServletListenerTest.java, liquibase-core/src/test/java/liquibase/lockservice/LockServiceFactoryTest.java, liquibase-core/src/test/java/liquibase/precondition/PreconditionFactoryTest.java, liquibase-core/src/test/java/liquibase/serializer/ChangeLogSerializerFactoryTest.java, liquibase-core/src/test/java/liquibase/sqlgenerator/SqlGeneratorFactoryTest.java, liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java, liquibase-integration-tests/src/test/java/liquibase/dbtest/mssql/MssqlIntegrationTest.java, liquibase-maven-plugin/src/test/java/org/liquibase/maven/plugins/AbstractLiquibaseChangeLogMojoTest.java
- [X ] Enhancement/New feature (adds functionality without impacting existing logic)
Simplify assert calls and replaced with simpler and equivalent calls.
N/A
N/A
Just apply to test files.
=> Simplify assert calls and replaced with simpler and equivalent calls.

liquibase-dist/pom.xml
* Mariadb-client 3.1.0 removed optional tag from waffle and now it's bringing this dependency that increases liquibase dist file in 4mb.  
* There is an jira ticket for that, but I'm not sure if they are going to rollback this change: https://jira.mariadb.org/browse/CONJ-1025
-NA
- Mariadb users may have issues when using this WAFFLE - Windows Authentication Framework - as the had before.
- NA
=> Adds exclusions for mariadb newly added waffle dependency.

.github/util/package-install4j.sh, .github/workflows/installer-build-check.yml
=> DAT-12365 update install4j script to version 10.x

liquibase-core/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/db-changelog-4.19.xsd
=> update changelog version - 4.19

changelog.txt
changelog txt has been updated with 4.19 changes
=> changelog txt has been updated with 4.19 changes

.github/workflows/build-branch.yml, .github/workflows/build-main.yml, liquibase-extension-testing/pom.xml
Adds profile to enable publishing of liquibase-extension-testing module. 
Should only publish on pipelines that have the environment variable `TARGET_ARTIFACT_REPOSITORY` set to value  `github`. 
Profile activation via properties is case-sensitive!
N/A
=> Publish liquibase-extension-testing to github packages (DAT-12833)

.github/pull_request_template.md
Add comments around helper text in PR template so that it is easier to fill out the PR description.
=> PR template: add comments around help text

liquibase-core/src/main/java/liquibase/integration/commandline/LiquibaseCommandLineConfiguration.java, liquibase-core/src/main/java/liquibase/logging/LogFormat.java
Add an option to print structured logs in JSON format, without minifying them.
=> add pretty-printed-json format for log output (DAT-13000)

.github/workflows/snyk.yml
AdoptOpenJDK has moved to the Eclipse Foundation and now distributes binaries under the new name "Eclipse Temurin"
- If there is NOT an existing issue, consider …
=> Migrate setup-java action to use Temurin

.github/workflows/cleanup-branch-builds.yml
=> DAT-13269 pass proper branch name and add required field

liquibase-core/src/main/java/liquibase/Liquibase.java, liquibase-core/src/main/java/liquibase/changelog/visitor/DefaultChangeExecListener.java, liquibase-core/src/main/java/liquibase/hub/listener/HubChangeExecListener.java, liquibase-core/src/main/java/liquibase/integration/commandline/Main.java, liquibase-core/src/main/java/liquibase/logging/mdc/MdcKey.java
Adds deploymentOutcomeCount to MDC. Uses changeExecListener to find count of ran changesets. 
Slightly reworks how the DefaultChangeExecListener and HubChangeExecListener are setup in a very awkward manor. I'm not sure if this is necessarily the best approach.
=> Adds deploymentOutcomeCount to MDC (DAT-12979)

liquibase-core/src/main/java/liquibase/changelog/ChangeSet.java
=> Add changesetComment, changesetLabel mdc values (DAT-12919)

liquibase-core/src/main/java/liquibase/Liquibase.java, liquibase-core/src/main/java/liquibase/logging/mdc/MdcKey.java
=> add MDC for rollback-to-date (DAT-13027)

liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
=> DAT-13145: set log level to severe if using a log file with no log level set

liquibase-core/src/main/java/liquibase/changelog/ChangeSet.java, liquibase-core/src/main/java/liquibase/changelog/StandardChangeLogHistoryService.java, liquibase-core/src/main/java/liquibase/executor/jvm/ChangelogJdbcMdcListener.java, liquibase-core/src/main/java/liquibase/executor/jvm/JdbcExecutor.java, liquibase-core/src/main/java/liquibase/lockservice/StandardLockService.java, liquibase-core/src/main/java/liquibase/logging/mdc/MdcKey.java, liquibase-core/src/main/java/liquibase/logging/mdc/MdcValue.java, liquibase-core/src/main/java/liquibase/util/SqlUtil.java, liquibase-core/src/test/java/liquibase/lockservice/StandardLockServiceTest.java
Adds databaseChangelogSQL mdc key, populates via StandardChangelogHistoryService and StandardLockService. Moves changesetSql mdc population into Changeset class. 
‼️ This makes it so that end delimiters (ex: `;`) are included in the changesetSql mdc value. ‼️ I can control this, but because I'm now handling the sql at a level above statement execution it made the most sense to take this route to me. We're not always, but sometimes working with more than one statement per change.
=> Adds databaseChangelogSQL mdc key (DAT-13092)

.github/workflows/build.yml
=> github-action-DAT-13527

.github/workflows/build.yml
The GitHub action s4u/setup-maven-action is a "catch-all" and contains a few different actions, many of which are unnecessary. This change simplifies the logic by calling the stCarolas/setup-maven action directly, rather than through another layer.
I don't know for certain that this will fix the issue with the branch builds, but it is my best educated guess at the moment.
=> set up maven using simpler GitHub action

changelog.txt
=> Updated changelog txt with new PRs

.github/workflows/build-main.yml, .github/workflows/release-published.yml
=> Pin build to Maven 3.8.7

.github/workflows/build.yml
Pin maven version for sonar scan to fix build.
=> pin maven version for sonar scan

.github/workflows/build.yml
Pin Maven to 3.8.7 everywhere we use Maven
=> Pin Maven to 3.8.7 in other places

.github/workflows/build-main.yml
=> One more pin to maven 3.8.7

.github/workflows/build-branch.yml
=> more maven version pinning

.github/workflows/build-branch.yml, .github/workflows/build-main.yml, .github/workflows/build.yml, .github/workflows/release-published.yml
=> use variable for maven version

liquibase-core/src/main/java/liquibase/change/AbstractChange.java, liquibase-core/src/main/java/liquibase/change/AbstractSQLChange.java, liquibase-core/src/main/java/liquibase/change/CheckSum.java, liquibase-core/src/main/java/liquibase/change/core/CreateProcedureChange.java, liquibase-core/src/main/java/liquibase/change/core/CreateViewChange.java, liquibase-core/src/main/java/liquibase/changelog/ChangeSet.java, liquibase-core/src/main/java/liquibase/changelog/filter/DbmsChangeSetFilter.java, liquibase-core/src/main/java/liquibase/sql/visitor/AbstractSqlVisitor.java, liquibase-core/src/test/groovy/liquibase/change/AbstractChangeTest.groovy, liquibase-core/src/test/groovy/liquibase/change/core/CreateProcedureChangeTest.groovy, liquibase-core/src/test/groovy/liquibase/change/core/CreateViewChangeTest.groovy, liquibase-core/src/test/groovy/liquibase/changelog/filter/ShouldRunChangeSetFilterTest.groovy, liquibase-core/src/test/groovy/liquibase/hub/model/HubChangeTest.groovy, liquibase-core/src/test/java/liquibase/change/AbstractSQLChangeTest.java, liquibase-core/src/test/java/liquibase/change/CheckSumTest.java, liquibase-integration-tests/src/test/java/liquibase/statementexecute/MarkChangeSetRanExecuteTest.java, liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/calculateChecksum.test.groovy
This reverts commit ba254bde638459810409c8a717cd757165670b50.
Reverts PR https://github.com/liquibase/liquibase/pull/3790
=> Revert "Fix CheckSum generation issues + CURRENT_CHECKSUM_ALGORITHM_VERSION updated from 8 to 9."

liquibase-core/src/main/java/liquibase/Liquibase.java, liquibase-core/src/main/java/liquibase/command/core/DropAllCommand.java, liquibase-core/src/main/java/liquibase/command/core/InternalDropAllCommandStep.java, liquibase-core/src/main/java/liquibase/hub/HubUpdater.java, liquibase-core/src/main/java/liquibase/hub/listener/HubChangeExecListener.java, liquibase-core/src/test/groovy/liquibase/LiquibaseTest.groovy, liquibase-core/src/test/groovy/liquibase/integration/commandline/CommandLineUtilsTest.groovy, liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/dropAll.test.groovy
Remove Liquibase Hub autoregistration prompts.
=> remove Liquibase Hub autoregistration prompts (DAT-13419)

liquibase-core/src/main/java/liquibase/parser/core/yaml/YamlParser.java, liquibase-core/src/main/java/liquibase/util/SnakeYamlUtil.java
Safely call snakeyaml method that had signature changes in 1.3? series.
Changes to show the warning message only once.
None
Closes #3878
=> Safely call snakeyaml methods that have been changed in last versions.

liquibase-core/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.20.xsd
db changelog xsd has been udpated to the version 4.20
=> update db changelog xsd to 4.20

changelog.txt
Updated changelog txt with 4.20 fixes and enhancements
=> Updated changelog txt with 4.20 Fixes/Enhancements

liquibase-dist/src/main/maven/release.pom.xml
Upgrade was missing for installer causing integration tests to fail.
=> Upgrades snakeyaml for installer

.snyk
=> Ignore Snyk 0-SNAPSHOT version warning for liquibase-core.

liquibase-core/src/main/java/liquibase/Liquibase.java, liquibase-core/src/main/java/liquibase/command/core/ReleaseLocksCommandStep.java, liquibase-core/src/main/java/liquibase/integration/commandline/Main.java, liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/releaseLocks.test.groovy
Reverts liquibase/liquibase#3932 - merged before testing was finished.
=> Revert "DAT-6617 - Refactor ReleaseLocksCommand "

liquibase-dist/src/main/install4j/liquibase.install4j
Fixes #3860 
- None
- None
- None
=> JVM installer upgraded to version 17.0.6+10

liquibase-core/src/main/java/liquibase/logging/mdc/MdcKey.java
Added keys for SQLCMD MDC entries
=> Added SQLCMD MDC keys DAT-13366

liquibase-core/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java
DAT-13939
The ChangeExecListener was not created before exception handling which caused problems showing the correct error message to the user.
=> Create the change exec listener earlier so that it is available if there is an exception DAT-13939

liquibase-core/src/main/java/liquibase/command/core/UpdateCountCommandStep.java, liquibase-core/src/main/java/liquibase/logging/mdc/MdcKey.java
=> add MDC for update-count (DAT-13040)

liquibase-core/src/main/java/liquibase/logging/mdc/MdcKey.java
=> add rollback on error MDC to update family of commands (DAT-13884)

liquibase-core/src/main/java/liquibase/command/AbstractDatabaseConnectionCommandStep.java, liquibase-core/src/main/java/liquibase/logging/mdc/MdcKey.java
Added the Liquibase schema and catalog names to MDC
=> Added Liquibase schema and catalog to MDC DAT-13873

pom.xml
Fixes snyk report https://github.com/liquibase/liquibase/commit/13af94dc342569e4f5603d337c8d7900420d0667/checks
=> Upgrade spring 5 version

liquibase-core/src/main/java/liquibase/changelog/DatabaseChangeLog.java, liquibase-core/src/main/java/liquibase/parser/ChangeLogParserConfiguration.java, liquibase-core/src/test/groovy/liquibase/changelog/DatabaseChangeLogTest.groovy
Update configuration and property names from ON_MISSING_INCLUDE [PR](https://github.com/liquibase/liquibase/pull/3081/files#diff-aa48067e063025d44c345be096a80f0f123742edcd77367cc38e410057c27162)
Fixes #3898 
- None
- None. This is just a minor refactoring with the intention to have more specific names and more clear documentation.
- None
=> Rename ON_MISSING_INCLUDE_FILE configuration and property names

.github/workflows/release-extensions.yml
Mongo Extension will be released independent of liquibase
=> removeMongoExtensionRelease

liquibase-core/src/main/java/liquibase/changelog/filter/ContextChangeSetFilter.java, liquibase-core/src/main/java/liquibase/changelog/filter/DbmsChangeSetFilter.java, liquibase-core/src/main/java/liquibase/changelog/filter/LabelChangeSetFilter.java, liquibase-core/src/main/java/liquibase/util/ShowSummaryUtil.java
=> rename changeset filter MDC names (DAT-14020)

liquibase-core/src/main/java/liquibase/command/core/helpers/AbstractDatabaseConnectionCommandStep.java, liquibase-core/src/main/java/liquibase/command/core/helpers/DbUrlConnectionCommandStep.java, liquibase-core/src/main/java/liquibase/command/core/helpers/ReferenceDbUrlConnectionCommandStep.java
=> same value is shown for both "liquibaseTargetUrl" and "liquibaseReferenceUrl" (DAT-14071)

liquibase-core/src/main/java/liquibase/util/SnakeYamlUtil.java
Lowers stack trace log level so it doesn't cause confusion to users.
=> Lowers Snakeyaml log level for warning stack traces

liquibase-core/src/main/java/liquibase/datatype/core/BlobType.java, liquibase-core/src/main/java/liquibase/dbdoc/TableWriter.java, liquibase-core/src/main/java/liquibase/hub/core/StandardHubService.java, liquibase-core/src/main/java/liquibase/integration/servlet/GenericServletListener.java, liquibase-core/src/main/java/liquibase/precondition/core/ColumnExistsPrecondition.java, liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateTableGeneratorInformix.java, liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateViewGenerator.java, liquibase-extension-examples/src/main/java/liquibase/executor/jvm/ExampleExecutor.java
1. This pull request removes all instances of unused parameters and local variables throughout the codebase. The removal of these unused elements simplifies the code, improves its readability, and reduces the potential for confusion or errors caused by obsolete or redundant code.
2. The changes in this pull request eliminate all instances of unused variables and parameters in the code, streamlining the implementation and making it easier to understand and maintain. By reducing clutter and unused elements, the code is more efficient, more reliable, and easier to modify or extend in the future.
3. In this pull request, we've refactored the code to remove all unused variables and parameters. This change makes the code more straightforward and easier to follow, while also reducing the …
=> * Remove unused parameters and local variables

liquibase-core/src/main/java/liquibase/change/core/SQLFileChange.java, liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy
Quality checks uses a cache so that SQL files do not have to be read multiple times, subsequent reads will hit the cache. The key for the cache was the standard `hashCode` which, for SQLFileChange, did not provide sufficient entropy to avoid incorrect cache hits, because it did not include the path of the SQL file being included.
=> add additional information to toString/describe methods of SQLFileChange (DAT-13789)

liquibase-integration-tests/src/test/groovy/liquibase/command/util/CommandUtil.groovy
Update `Show-Summary` argument reference from `UpdateCommandStep.SHOW_SUMMARY` to `ShowSummaryArgument.SHOW_SUMMARY` in order to fix `GenerateChangelogMySQLCommandTest`.
- None
- None
- Nothing
=> Update ShowSummary argument reference from CommandUtil class to fix failing integration tests

liquibase-integration-tests/src/test/groovy/liquibase/command/util/CommandUtil.groovy
=> Test fix DAT-14096

liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateTableGenerator.java, liquibase-integration-tests/src/test/resources/changelogs/pgsql/complete/root.changelog.xml
PR https://github.com/liquibase/liquibase/pull/3108 introduced the new table type field, but it is never being used. This PR fixes the usage logic around it.
None
None
🤦‍♂️
=> Appends the table type to the statement using it.

liquibase-core/src/main/java/liquibase/changelog/ChangeSet.java
=> DAT-14072: ensure that "changesetOutcome: failed" MDC shows up in logs

.github/workflows/build.yml
Resolves DAT-14192. Should stabilize unit tests.
=> Update runner image for pr builds (DAT-14192)

liquibase-core/src/main/java/liquibase/Liquibase.java, liquibase-core/src/main/java/liquibase/command/core/AbstractRollbackCommandStep.java, liquibase-core/src/main/java/liquibase/command/core/RollbackCommandStep.java, liquibase-core/src/main/java/liquibase/command/core/RollbackSqlCommandStep.java, liquibase-core/src/main/java/liquibase/command/core/RollbackToDateCommandStep.java, liquibase-core/src/main/java/liquibase/command/core/RollbackToDateSqlCommandStep.java, liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/rollbackToDate.test.groovy, liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/rollbackToDateSql.test.groovy
=> [DAT-6629] Refactoring of rollbackToDate[SQL] command.

liquibase-core/src/main/java/liquibase/command/CommandScope.java
=> Fix logging.

liquibase-core/src/main/java/liquibase/changelog/ChangeSet.java, liquibase-core/src/main/java/liquibase/command/CommandScope.java, liquibase-core/src/main/java/liquibase/command/core/RollbackToDateCommandStep.java, liquibase-integration-tests/src/test/groovy/liquibase/command/util/CommandUtil.groovy
=> Added changesetOperationStop time to exception handling also made all start/stop times be UTC DAT-13963

liquibase-core/src/test/java/liquibase/integration/spring/SpringResourceAccessorLoaderTest.java
There were two `SpringResourceAccessorTest`s, one groovy one java. This renames the java one to avoid conflicts.
=> Renames duplicated test name

liquibase-core/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.21.xsd
=> Created 4.21 changelog xsd

liquibase-core/src/main/java/liquibase/integration/commandline/LiquibaseCommandLineConfiguration.java
=> DAT-14365: unhide log-format parameter

changelog.txt
Updated changelog txt content with 4.21 and 4.21.1
=> updated changelog txt to 4.21

README.md
=> remove Hub mention from readme

liquibase-core/src/main/java/liquibase/Liquibase.java, liquibase-core/src/main/java/liquibase/command/core/StatusCommandStep.java, liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/status.test.groovy
=> DAT-6633: refactor status command to use command framework

liquibase-standard/src/main/java/liquibase/command/CommandScope.java, liquibase-standard/src/main/resources/liquibase/examples/yaml/liquibase.customlogdata.yaml
=> add excludeData to sample file (DAT-14295)

liquibase-standard/src/main/java/liquibase/Liquibase.java
=> include changelog file when running status command from Liquibase class (DAT-14659)

.github/workflows/cleanup-branch-builds.yml
=> testing-DAT-14686

liquibase-cli/src/test/groovy/liquibase/integration/commandline/LiquibaseCommandLineTest.groovy, liquibase-standard/src/main/java/liquibase/command/core/helpers/AbstractHelperCommandStep.java
Command pipelines which consist entirely of helper commands should not be displayed in the help output.
=> remove helper commands from help output (DAT-14674)

liquibase-standard/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.22.xsd
=> update changelog to 4.22

liquibase-standard/src/main/java/liquibase/logging/core/NoOpLogService.java, liquibase-standard/src/main/java/liquibase/logging/core/NoOpLogger.java
=> add no-op logger and log service (DAT-14148)

liquibase-integration-tests/src/test/groovy/liquibase/diffchangelog/DiffChangelogIntegrationTest.groovy, liquibase-integration-tests/src/test/java/liquibase/statementexecute/AbstractExecuteTest.java
=> Fix flaky postgres tests

liquibase-integration-tests/src/test/groovy/liquibase/snapshot/IndexWithDescendingColumnSnapshotIntegrationTest.groovy
=> Fix index descending column snapshot test

liquibase-integration-tests/src/test/groovy/liquibase/command/core/MssqlMergeIntegrationTest.groovy, liquibase-integration-tests/src/test/resources/changelogs/mssql/issues/merge.statement.changelog.sql, liquibase-standard/src/main/java/liquibase/changelog/ChangeSet.java, liquibase-standard/src/main/java/liquibase/database/core/MSSQLDatabase.java, liquibase-standard/src/main/java/liquibase/sql/visitor/AppendSqlIfNotPresentVisitor.java
For SQL Server, if a delimiter has not been specified, then add one.
https://learn.microsoft.com/en-us/sql/t-sql/language-elements/transact-sql-syntax-conventions-transact-sql?redirectedfrom=MSDN&view=sql-server-ver16
`Transact-SQL statement terminator. Although the semicolon isn't required for most statements in this version of SQL Server, it will be required in a future version.`
=> For SQL Server, if a delimiter has not been specified, then add one. DAT-13998

liquibase-integration-tests/src/test/resources/changelogs/h2/rollback/empty.rollback.changelog.sql, liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/rollbackCount.test.groovy, liquibase-standard/src/main/java/liquibase/command/core/AbstractRollbackCommandStep.java
Adds log message mentioning nothing has been rolled back.
=> Log when no changesets have been rolled back (DAT-11575)

.github/workflows/build.yml
Updated build to test with Java 20, since that is the currently supported non-LTS version, not 18
Only changes build logic
Nothing
=> Test with java 20 instead of 18, as 18 is no longer supported by oracle

liquibase-integration-tests/src/test/groovy/liquibase/command/core/DbDocPostgresIntegrationTest.groovy, liquibase-integration-tests/src/test/resources/changelogs/pgsql/complete/basic.formatted.sql, liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/dbDoc.test.groovy, liquibase-standard/src/main/java/liquibase/Liquibase.java, liquibase-standard/src/main/java/liquibase/command/core/DbDocCommandStep.java
Refactors db-doc command to use command framework. Adds new integration test.
=> Refactor db-doc command to use command framework (DAT-6605)

liquibase-dist/src/main/archive/README.txt
=> Fix installer README message

liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/markNextChangesetRan.test.groovy, liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/markNextChangesetRanSql.test.groovy, liquibase-standard/src/main/java/liquibase/Liquibase.java, liquibase-standard/src/main/java/liquibase/command/core/MarkNextChangesetRanCommandStep.java, liquibase-standard/src/main/java/liquibase/command/core/MarkNextChangesetRanSqlCommandStep.java, liquibase-standard/src/main/java/liquibase/command/core/helpers/DatabaseChangelogCommandStep.java
=> refactor mark-next-changeset-ran command family (DAT-6615, DAT-6616)

liquibase-dist/src/main/install4j/liquibase.install4j
Update version of JVM installer - it can be merged/reviewed after 4.22.0 release.
=> Updates installer JVM version.

liquibase-cli/src/test/groovy/liquibase/integration/commandline/LiquibaseCommandLineTest.groovy, liquibase-standard/src/main/java/liquibase/executor/jvm/JdbcExecutor.java, liquibase-standard/src/main/java/liquibase/sql/SqlConfiguration.java, liquibase-standard/src/test/groovy/liquibase/util/StringUtilTest.groovy
=> Show MSSQL PRINT output by showing SQL Warnings if they exist DAT-8708

.github/workflows/snyk.yml
=> Upgrades snyk java version.

liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/updateTestingRollback.test.groovy, liquibase-standard/src/main/java/liquibase/Liquibase.java, liquibase-standard/src/main/java/liquibase/command/core/UpdateTestingRollbackCommandStep.java
=> refactor update-testing-rollback command (DAT-6640)

liquibase-standard/src/main/java/liquibase/lockservice/StandardLockService.java
On success would previously only print `Successfully released` not `Successfully released change log lock`. This PR updates to read `Successfully released change log lock`
=> Cleanup logging for releasing locks.

liquibase-standard/src/main/java/liquibase/command/core/ValidateCommandStep.java
This was erroneously removed during the command refactor.
=> Adds back validation message to validate command (DAT-14859)

liquibase-standard/src/main/java/liquibase/ChecksumVersions.java, liquibase-standard/src/main/java/liquibase/Scope.java, liquibase-standard/src/main/java/liquibase/change/AbstractChange.java, liquibase-standard/src/main/java/liquibase/change/ChangeFactory.java, liquibase-standard/src/main/java/liquibase/change/CheckSum.java, liquibase-standard/src/main/java/liquibase/changelog/ChangeSetStatus.java, liquibase-standard/src/main/java/liquibase/changelog/OfflineChangeLogHistoryService.java, liquibase-standard/src/main/java/liquibase/changelog/RanChangeSet.java, liquibase-standard/src/main/java/liquibase/changelog/StandardChangeLogHistoryService.java, liquibase-standard/src/main/java/liquibase/changelog/visitor/UpdateVisitor.java, liquibase-standard/src/main/java/liquibase/command/core/CalculateChecksumCommandStep.java, liquibase-standard/src/main/java/liquibase/integration/commandline/LiquibaseCommandLineConfiguration.java, liquibase-standard/src/main/java/liquibase/sqlgenerator/core/MarkChangeSetRanGenerator.java, liquibase-standard/src/main/java/liquibase/sqlgenerator/core/UpdateChangeSetChecksumGenerator.java, liquibase-standard/src/test/groovy/liquibase/change/AbstractChangeTest.groovy, liquibase-standard/src/test/groovy/liquibase/change/core/CreateProcedureChangeTest.groovy, liquibase-standard/src/test/groovy/liquibase/change/core/CreateViewChangeTest.groovy, liquibase-standard/src/test/groovy/liquibase/change/core/LoadDataChangeTest.groovy, liquibase-standard/src/test/groovy/liquibase/change/core/LoadUpdateDataChangeTest.groovy, liquibase-standard/src/test/groovy/liquibase/change/core/SQLFileChangeTest.groovy, liquibase-standard/src/test/java/liquibase/change/AbstractSQLChangeTest.java, liquibase-standard/src/test/java/liquibase/change/ChangeFactoryTest.java, liquibase-standard/src/test/java/liquibase/change/CheckSumTest.java, liquibase-standard/src/test/java/liquibase/sqlgenerator/core/UpdateChangeSetChecksumGeneratorTest.java
=> provide option to set "current" checksum version, remove ChecksumVersions.latest (DAT-14931)

liquibase-extension-testing/src/main/resources/liquibase.sdk.yaml
=> use latest mysql version in integration tests (DAT-13283)

liquibase-integration-tests/src/test/groovy/liquibase/command/util/CommandUtil.groovy
=> fix mssql integration test timeout

liquibase-standard/src/main/java/liquibase/ChecksumVersion.java, liquibase-standard/src/main/java/liquibase/Scope.java, liquibase-standard/src/main/java/liquibase/change/CheckSum.java, liquibase-standard/src/main/java/liquibase/changelog/ChangeSetStatus.java, liquibase-standard/src/main/java/liquibase/changelog/OfflineChangeLogHistoryService.java, liquibase-standard/src/main/java/liquibase/changelog/RanChangeSet.java, liquibase-standard/src/main/java/liquibase/changelog/StandardChangeLogHistoryService.java, liquibase-standard/src/main/java/liquibase/changelog/visitor/UpdateVisitor.java, liquibase-standard/src/main/java/liquibase/command/core/CalculateChecksumCommandStep.java, liquibase-standard/src/main/java/liquibase/integration/commandline/LiquibaseCommandLineConfiguration.java, liquibase-standard/src/main/java/liquibase/sqlgenerator/core/MarkChangeSetRanGenerator.java, liquibase-standard/src/main/java/liquibase/sqlgenerator/core/UpdateChangeSetChecksumGenerator.java, liquibase-standard/src/test/groovy/liquibase/change/AbstractChangeTest.groovy, liquibase-standard/src/test/groovy/liquibase/change/core/CreateProcedureChangeTest.groovy, liquibase-standard/src/test/groovy/liquibase/change/core/CreateViewChangeTest.groovy, liquibase-standard/src/test/groovy/liquibase/change/core/LoadDataChangeTest.groovy, liquibase-standard/src/test/groovy/liquibase/change/core/LoadUpdateDataChangeTest.groovy, liquibase-standard/src/test/groovy/liquibase/change/core/SQLFileChangeTest.groovy, liquibase-standard/src/test/java/liquibase/change/CheckSumTest.java, liquibase-standard/src/test/java/liquibase/sqlgenerator/core/UpdateChangeSetChecksumGeneratorTest.java
=> remove checksum-version config property (DAT-14931)

.github/workflows/release-published.yml
=> swap erz for ruslan as approver.  Add Sayali.

liquibase-integration-tests/src/test/groovy/liquibase/command/core/UpgradeChecksumVersionIntegrationTest.groovy, liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/updateToTag.test.groovy, liquibase-standard/src/main/java/liquibase/changelog/filter/UpToTagChangeSetFilter.java, liquibase-standard/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java, liquibase-standard/src/main/java/liquibase/command/core/UpdateToTagCommandStep.java, liquibase-standard/src/test/groovy/liquibase/change/ChangeDefinitionTest.groovy
Upgrade the checksums when executing targeted Update-to-tag and update-one-changeset commands
=> Upgrade the checksums when executing targeted Update-to-tag and update-one-changeset commands (DAT-15139)

liquibase-integration-tests/src/test/java/liquibase/dbtest/pgsql/PostgreSQLIntegrationTest.java
=> Fix master build tests

.github/util/package-install4j.sh
Apple is deprecating alttool in favor of notarytool.  The latest version of install4j has this change in their release notes.
=> DAT-15240 test latest version of install4j

liquibase-standard/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.23.xsd
=> Creates XSD for 4.23.0 release

changelog.txt
=> Adding changelog for 4.23.0 release

liquibase-standard/src/main/java/liquibase/changelog/DatabaseChangeLog.java, liquibase-standard/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.23.xsd, liquibase-standard/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd, liquibase-standard/src/test/groovy/liquibase/changelog/DatabaseChangeLogTest.groovy
Fix release blocker issue. introduced by https://github.com/liquibase/liquibase/pull/3901 .
=> Rollback errorIfMissingOrEmpty parameter for includeAll tag

.github/workflows/release-published.yml
During the ReleasePublished job for the Manual approval required for workflow run, the ${version} was not getting populated as it was running outside the scope of run block. So fixed the issue by directly setting the `version`  as `${{ needs.setup.outputs.version }}`
=> Fix manual trigger job ${version}

.github/dependabot.yml, .github/workflows/cleanup-branch-builds.yml, .github/workflows/cleanup-master-builds.yml
master branch build failures due to updated package `actions/delete-package-versions@v4`
=> Fix cleanup branches dat branches

liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateSequenceGenerator.java, liquibase-standard/src/test/java/liquibase/sqlgenerator/core/CreateSequenceGeneratorTest.java
Fixes #4415 
In addition to the original issue description, not only the reported bug is fixed, but also the support for CREATE SEQUENCE was extended in alignment with the latest product manual.
N/A
N/A
N/A
=> Fixes issue #4415: "Wrong DDL syntax CREATE SEQUENCE ... AS ..."

liquibase-dist/src/main/archive/liquibase.bat, liquibase-integration-tests/src/test/groovy/liquibase/command/ChangelogSyncIntegrationTest.groovy, liquibase-standard/src/main/java/liquibase/command/core/ChangelogSyncCommandStep.java
Resolves other issues relating to #4448 where changelogsync no longer populated deploymentId.
=> Fix changelogsync no longer generating deployment id.

liquibase-standard/src/main/java/liquibase/changelog/ChangeLogHistoryService.java, liquibase-standard/src/main/java/liquibase/plugin/Plugin.java
This PR adds documentation to people extending Liquibase as a library that may face API changes .
=> Improvements after 4230

.github/workflows/cleanup-branch-builds.yml
=> fix version package-version-ids

liquibase-standard/src/main/java/liquibase/changelog/AbstractChangeLogHistoryService.java, liquibase-standard/src/main/java/liquibase/changelog/ChangeLogHistoryService.java, liquibase-standard/src/main/java/liquibase/changelog/OfflineChangeLogHistoryService.java, liquibase-standard/src/main/java/liquibase/changelog/StandardChangeLogHistoryService.java, liquibase-standard/src/main/java/liquibase/changelog/visitor/UpdateVisitor.java
Reverts liquibase/liquibase#4452
=> Revert "Fix checksum upgrade changes preventing useless updates and using AbstractChangeLogHistoryService for extensions compatibility"

.github/workflows/build.yml
=> resolve comment in build.yml file

liquibase-dist/pom.xml, pom.xml
Rollback snowflake driver to 3.13.32 due to build failures.
Harness rollback PR: https://github.com/liquibase/liquibase-test-harness/pull/595
Pro-tests PR: https://github.com/liquibase/liquibase-pro-tests/pull/887
=> [DAT-15369]  Rollback snowflake driver to 3.13.32 due to build failures.

liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy
Exclude certain tests from executing on certain platforms.
On master, this is the result of the command tests execution:
```
2023-07-12T19:21:25.5594901Z [INFO] Running liquibase.integrationtest.LiquibaseCoreExtensionTests
2023-07-12T19:21:42.5335293Z [INFO] Tests run: 328, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 16.96 s -- in liquibase.integrationtest.LiquibaseCoreExtensionTests
```
=> exclude certain command tests from executing on certain platforms

liquibase-standard/src/main/java/liquibase/integration/commandline/Main.java
=> fix format argument for history command (DAT-13382)

LICENSE.txt
=> bump LICENSE.txt year to 2023 (DAT-13059)

liquibase-standard/src/main/java/liquibase/change/core/SQLFileChange.java, liquibase-standard/src/main/java/liquibase/parser/ChangeLogParserConfiguration.java
Throw an exception during the validation stage of the sqlFile change type if the specified sql file does not exist.
=> throw validation error on missing sqlFile (DAT-14920)

liquibase-standard/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java, liquibase-standard/src/main/java/liquibase/command/core/UpdateCommandStep.java, liquibase-standard/src/main/java/liquibase/command/core/UpdateCountCommandStep.java, liquibase-standard/src/main/java/liquibase/command/core/UpdateToTagCommandStep.java, liquibase-standard/src/main/java/liquibase/executor/jvm/JdbcExecutor.java, liquibase-standard/src/main/java/liquibase/logging/mdc/MdcKey.java, liquibase-standard/src/main/resources/liquibase/i18n/liquibase-core.properties
=> DAT-14929: include rows affected in update command console output

liquibase-dist/pom.xml, pom.xml
=> fix local dev builds

.github/workflows/build-branch.yml, liquibase-dist/pom.xml, liquibase-maven-plugin/pom.xml
=> switch deploy.repositoryId to match other name changes (DAT-14615)

.github/workflows/build-main.yml, .github/workflows/release-published.yml
=> set server-id to liquibase in other workflow files (DAT-14615)

.github/workflows/build-branch.yml, .github/workflows/build-main.yml, .github/workflows/release-published.yml, liquibase-dist/pom.xml, liquibase-maven-plugin/pom.xml, pom.xml
=> test functional tests with recent commits reverted

.github/workflows/build.yml
=> remove useless check

.github/workflows/build.yml
Reverts liquibase/liquibase#4544
=> Revert "DAT-15470"

liquibase-dist/pom.xml, pom.xml
=> move repositories block into profile activated only on GHA (DAT-14615)
