.github/workflows/build-branch.yml

run Functional tests on any branch

run tests on any branch

---

.github/workflows/build-branch.yml
.github/workflows/build-main.yml

- Removing unwanted code
- Changes to include attributes in liquibase.build.properties in master-SNAPSHOT GPM

DAT-15545-modifications

---

.github/workflows/build.yml

Fix merge conflict

---

.github/util/re-version.sh

[DAT-15622](https://datical.atlassian.net/browse/DAT-15622)
fix(re-version.sh): update jar names in the declare array to match the actual jar names
[DAT-15622]: https://datical.atlassian.net/browse/DAT-15622?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DAT-15622       Attach Artifacts To Draft Release workflow fails because artifact name has been chnaged

---

changelog.txt

Updated changelog with 4.23.1 changes

Updated changelog with 4.23.1 changes

---

.github/util/re-version.sh

Fix re-version.sh

---

.github/util/re-version.sh

Fix re-version.sh again

---

.github/util/re-version.sh
.github/workflows/build.yml
.github/workflows/create-release.yml
liquibase-dist/pom.xml

GitHub action dat 15622 build installer

---

.github/workflows/build.yml
.github/workflows/create-release.yml
liquibase-dist/pom.xml

[DAT-15622](https://datical.atlassian.net/browse/DAT-15622)
fix(build.yml): remove unnecessary module exclusion for liquibase-cdi-jakarta in the Java 8 build step
fix(build.yml): remove unnecessary module exclusion for liquibase-dist in the non-Java 8 build step
feat(build.yml): add copying of liquibase-0-SNAPSHOT.deb artifact to the artifacts folder
fix(pom.xml): update version of liquibase-commercial dependency to match project version
[DAT-15622]: https://datical.atlassian.net/browse/DAT-15622?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DAT-15622       change deb packaging generation

---

.github/util/re-version.sh
.github/workflows/create-release.yml
.github/workflows/release-published.yml

chore(create-release.yml): remove deb package from final output
chore(release-published.yml): comment out deb package upload step

chore(re-version.sh): remove reversion of deb package creation code

---

changelog.txt

Update changelog txt 4.23.1

---

liquibase-standard/src/main/java/liquibase/database/core/MSSQLDatabase.java
liquibase-standard/src/main/java/liquibase/diff/output/changelog/core/MissingDataExternalFileChangeGenerator.java

Correctly escape spaces in table name when it is used in a query DAT-11529

---

liquibase-standard/pom.xml

add Lombok (DAT-12612)

---

.github/workflows/build.yml
.github/workflows/release-published.yml
liquibase-dist/pom.xml
liquibase-dist/src/deb/control/control
liquibase-dist/src/deb/control/postinst

[DAT-15646](https://datical.atlassian.net/browse/DAT-15646)
- chore(build.yml): update Maven commands in Build & Test Java 8 and Build & Test Java non-jdk-8 jobs to exclude unnecessary modules
- chore(build.yml): remove unused upload_deb job
- chore(pom.xml): remove unused plugins and dependencies related to deb packaging
- chore(control): remove unused control file
- chore(postinst): remove unused postinst file
[DAT-15646]: https://datical.atlassian.net/browse/DAT-15646?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DAT-15646       DevOps - Reusable Debian Package Creation Workflow Migration

---

.github/workflows/build.yml

Update build.yml to use @master for call-build-branch

Update build.yml to use @master for call-build-branch

---

liquibase-standard/src/main/java/liquibase/command/CommandScope.java

Make operation start time be UTC DAT-15593

---

liquibase-standard/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd

Allow both include and includeAll to appear in modifyChangeSets tag

---

liquibase-integration-tests/src/test/groovy/liquibase/diffchangelog/DiffChangelogIntegrationTest.groovy
liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/diffChangelog.test.groovy
liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/generateChangelog.test.groovy
liquibase-standard/src/main/java/liquibase/command/core/DiffChangelogCommandStep.java
liquibase-standard/src/main/java/liquibase/command/core/GenerateChangelogCommandStep.java
liquibase-standard/src/main/java/liquibase/diff/output/changelog/DiffToChangeLog.java
liquibase-standard/src/main/java/liquibase/serializer/core/formattedsql/FormattedSqlChangeLogSerializer.java

Add labels/contexts arguments to diffChangelog and generateChangelog change sets DAT-14793

---

liquibase-standard/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd

Reverts liquibase/liquibase#4680

Revert "Allow both include and includeAll to appear in modifyChangeSets tag"

---

liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/MavenLog.java

After creating custom maven log level some tests started to fail as log level FINE was missing. Fine is the former name of DEBUG in maven..

Add alias for log level FINE in maven

---

.github/workflows/build.yml
liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java

disable the concurrency check on master branch

---

.github/workflows/build.yml

Archiving test results takes at least 5 minutes on each build step. I can't take the slowness any longer!

do not archive test results by default

---

.github/workflows/build.yml

Reverts liquibase/liquibase#4735

Revert "disable the concurrency check on master branch"

---

liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java
liquibase-integration-tests/src/test/resources/changelogs/pgsql/complete/root.changelog.xml

fix flaky UpgradeChecksumVersionIntegrationTest

---

.github/workflows/build.yml

https://liquibase.slack.com/archives/C53DX4S4W/p1692887930305269

removing workflow_run on Build Branch SNAPSHOT

---

liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/MavenLog.java

Adding more log level aliases.

---

liquibase-dist/src/main/install4j/liquibase.install4j

Upgrade installer version to 17.0.8+7

---

liquibase-standard/src/main/java/liquibase/change/core/CreateViewChange.java
liquibase-standard/src/main/java/liquibase/sqlgenerator/core/SetViewRemarksGenerator.java

Fixes #4650 
Enables COMMENT ON VIEW for SQL Anywhere simply by adding it to the list of supported RDBMS.
N/A
N/A
N/A

Fixing issue #4650

---

liquibase-standard/src/main/java/liquibase/Scope.java
liquibase-standard/src/main/java/liquibase/changelog/ExpressionExpander.java
liquibase-standard/src/main/java/liquibase/logging/mdc/MdcKey.java
liquibase-standard/src/main/java/liquibase/logging/mdc/MdcManager.java
liquibase-standard/src/main/java/liquibase/logging/mdc/NoOpMdcManager.java

change MdcManager API to accept Map<String, Object> instead of Map<String, String> (DAT-15799)

---

liquibase-standard/src/main/java/liquibase/executor/jvm/JdbcExecutor.java

Adds a private method, JdbcExecutor::setParameters, to set parameters from RawParameterizedSqlStatement to PreparedStatement.
Replaces parameters loop in JdbcExecutor::execute with setParameters. 
Replaces parameters loop in JdbcExecutor::query with setParameters.
Fixes #4588

Fixes JdbcExecutor's uses of RawParameterizedSqlStatement

---

README.md

Update README link to contribution docs

---

liquibase-dist/src/main/archive/liquibase.bat

Fix liquibase.bat java home handling under Windows

---

pom.xml

Bumps `groovy.version` from 2.5.22 to 2.5.23.
Updates `org.codehaus.groovy:groovy-bom` from 2.5.22 to 2.5.23
- [Commits](https://github.com/apache/groovy/commits)
Updates `org.codehaus.groovy:groovy-all` from 2.5.22 to 2.5.23
- [Commits](https://github.com/apache/groovy/commits)
---
updated-dependencies:
- dependency-name: org.codehaus.groovy:groovy-bom dependency-type: direct:production update-type: version-update:semver-patch
- dependency-name: org.codehaus.groovy:groovy-all dependency-type: direct:development update-type: version-update:semver-patch ...

Bump groovy.version from 2.5.22 to 2.5.23

---

.github/dependabot.yml

1. [Separate sections of the branch name with a hyphen for dependabot PR's](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#pull-request-branch-nameseparator)

Separate sections of the branch name with a hyphen for dependabot PR's (DAT-15548)

---

liquibase-standard/src/main/java/liquibase/change/AbstractSQLChange.java
liquibase-standard/src/test/groovy/liquibase/change/core/SQLFileChangeTest.groovy

DAT-15857 - Fix for checksum upgrade in runWith change sets 

---

liquibase-standard/src/main/java/liquibase/parser/AbstractFormattedChangeLogParser.java
liquibase-standard/src/main/resources/liquibase/i18n/liquibase-core.properties
liquibase-standard/src/test/groovy/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParserTest.groovy

Tweaked exception message for invalid formatted SQL file - PR against 4.23.1 base branch.
DAT-15874

Tweaked exception message for invalid formatted SQL file

---

changelog.txt

Release notes for 4.23.2

---

liquibase-standard/src/main/java/liquibase/database/AbstractJdbcDatabase.java
liquibase-standard/src/main/java/liquibase/snapshot/SnapshotGeneratorFactory.java

do not attempt to recreate DBCL when it is specified with mixed case (DAT-15570)

---

liquibase-standard/src/main/java/liquibase/configuration/ConfiguredValueModifier.java
liquibase-standard/src/main/java/liquibase/configuration/ConfiguredValueModifierFactory.java

add API to ConfiguredValueModifier that allows overriding a String (DAT-15801)

---

liquibase-standard/src/main/java/liquibase/parser/AbstractFormattedChangeLogParser.java

Fix regression in recognizing formatted SQL file DAT-15865 

---

.github/workflows/build-branch.yml

We need to get this piece code merged to master as [workflow_run](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run) only works if changes are in the `default` branch. 
Currently, I am unable to test the "trigger" of `Build Branch SNAPSHOT` after the completion of `Run Tests` workflow

using workflow_run

---

.github/workflows/build-branch.yml

Reverts liquibase/liquibase#4899

Revert "using workflow_run"

---

liquibase-standard/src/main/resources/liquibase/examples/json/liquibase.customlogdata.yaml
liquibase-standard/src/main/resources/liquibase/examples/sql/liquibase.customlogdata.yaml
liquibase-standard/src/main/resources/liquibase/examples/xml/liquibase.customlogdata.yaml
liquibase-standard/src/main/resources/liquibase/examples/yaml/liquibase.customlogdata.yaml

update example custom log data files (DAT-15796)

---

.github/workflows/build.yml

For each standalone OSS PR, we're currently triggering two builds and cancelling one. Sometimes this means that you don't get any build results in the PR, [like here](https://github.com/liquibase/liquibase/pull/4904). I don't think we need this trigger on build.yml any longer, now that we've removed the safeToBuild label logic.

remove labelled trigger from build.yml

---

liquibase-standard/src/main/java/liquibase/command/core/helpers/DbUrlConnectionCommandStep.java
liquibase-standard/src/main/java/liquibase/command/core/helpers/ReferenceDbUrlConnectionCommandStep.java
liquibase-standard/src/main/java/liquibase/integration/commandline/Main.java

obfuscate user/pass in urls entered in MDC (DAT-15860)

---

liquibase-integration-tests/src/test/java/liquibase/statementexecute/CreateDatabaseChangeLogLockTableExecuteTest.java
liquibase-standard/src/main/java/liquibase/database/core/OracleDatabase.java
liquibase-standard/src/main/java/liquibase/datatype/core/BooleanType.java

Will switch to the native oracle boolean type for >= 23c.
Fixes #4576

Use native oracle BOOLEAN for >=23c | fixes #4576

---

liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java

Fix error message validation after conflicting merges

---

liquibase-integration-tests/src/test/resources/changelogs/common/common.tests.changelog.xml

Firebird does not support afterColumn - fix tests on master

---

liquibase-standard/src/main/resources/liquibase/examples/json/liquibase.checks-package.yaml
liquibase-standard/src/main/resources/liquibase/examples/sql/liquibase.checks-package.yaml
liquibase-standard/src/main/resources/liquibase/examples/xml/liquibase.checks-package.yaml
liquibase-standard/src/main/resources/liquibase/examples/yaml/liquibase.checks-package.yaml

add example checks packages files (DAT-15594)

---

liquibase-standard/src/main/java/liquibase/changelog/visitor/UpdateVisitor.java
liquibase-standard/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java
liquibase-standard/src/main/java/liquibase/report/UpdateReportParameters.java

Adding properties to the update report template to allow all the update family commands to use reports DAT-15638

---

liquibase-extension-testing/pom.xml
liquibase-standard/src/main/java/liquibase/sqlgenerator/core/TableIsEmptyGenerator.java

Add firebird specific query to new TableIsEmpty sql generator

---

liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseLauncher.java

Check for duplicate core and commercial JARs DAT-15837 

---

liquibase-standard/src/main/java/liquibase/sqlgenerator/SqlGeneratorFactory.java

Fix typo in SqlGeneratorFactory

---

.github/workflows/create-release.yml

reverting changes for uber-jar in create-release : https://github.com/liquibase/liquibase/pull/4729
@jandroav

reverting changes for uber-jar in create-release

---

changelog.txt

updated changelog text with 4.24.0 release details

updated changelog text with 4.24.0 release details

---

liquibase-standard/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.24.xsd

Add XSD file for 4.24.0 release

---

.github/util/re-version.sh
.github/workflows/create-release.yml

fix(re-version.sh): add validation for branch name argument to prevent missing argument error
fix(create-release.yml): pass branch name argument to re-version.sh script to correctly update commercial jars

fix re-version.sh to accept release from specific branches

---

.github/workflows/create-release.yml

Update create-release.yml change to needs.setup

---

.github/util/re-version.sh

GitHub action fix re version2

---

liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/DatabaseTestSystem.java

DatabaseTestSystem: commit only if autocommit is not enabled

---

liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/diff.test.groovy
liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/diffChangelog.test.groovy
liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/snapshotReference.test.groovy
liquibase-standard/src/main/java/liquibase/command/CommandArgumentDefinition.java
liquibase-standard/src/main/java/liquibase/command/CommonArgumentNames.java
liquibase-standard/src/main/java/liquibase/database/jvm/JdbcConnection.java
liquibase-standard/src/main/java/liquibase/database/jvm/JdbcConnectionPatterns.java
liquibase-standard/src/test/groovy/liquibase/database/jvm/JdbcConnectionTest.groovy

Filter additional credential-like strings in the URL sanitization process DAT-9973

---

liquibase-standard/src/main/java/liquibase/database/core/Ingres9Database.java
liquibase-standard/src/main/java/liquibase/precondition/core/ColumnExistsPrecondition.java
liquibase-standard/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java

- [] Bug fix (non-breaking change which fixes expected existing functionality)

CodeQL scan issue fixes

---

.github/workflows/build-branch.yml

https://github.com/actions/github-script#using-a-separate-github-token
A separate token is needed only when access to a different repository required.
In this case we need commit-sha of the same repo, hence PAT ie BOT_TOKEN is not needed.

fix-branch-build BOT_TOKEN issue

---

.github/workflows/build.yml

Testing DAT-16016

---

liquibase-standard/src/main/java/liquibase/util/CollectionUtil.java

move findKeyInMapIgnoreCase to CollectionUtil

---

liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
liquibase-dist/expected-distribution-contents.txt
liquibase-dist/src/main/assembly/assembly-bin-common.xml

exclude compiler jar from dist (DAT-15636)

---

liquibase-standard/src/main/java/liquibase/datatype/core/ClobType.java
liquibase-standard/src/main/java/liquibase/datatype/core/TimestampType.java
liquibase-standard/src/test/java/liquibase/datatype/ClobTypeTest.java

Do not convert if global flag is false DAT-15745

---

liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseChecksRunMojo.java
liquibase-standard/src/main/java/liquibase/change/core/ExecuteShellCommandChange.java
liquibase-standard/src/main/java/liquibase/database/AbstractJdbcDatabase.java
liquibase-standard/src/main/java/liquibase/database/jvm/ConnectionPatterns.java
liquibase-standard/src/main/java/liquibase/lockservice/StandardLockService.java
liquibase-standard/src/test/java/liquibase/lockservice/StandardLockServiceTest.java

Fixes Sonar `BLOCKER `issues classified of types` Vulnerability and Code Smell`

[DAT-15756] Fix sonar blocker warnings

---

.github/workflows/build.yml

https://datical.atlassian.net/browse/DAT-16029
chore(build.yml): update sonar-test-scan.yml version to v0.4.7 for improved functionality and bug fixes

DAT-16029     DevOps: liquibase-pro (and possibly liquibase) sonar scans for PRs are scanning code from master

---

liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseLauncher.java

Check for other duplicate JAR files in classpath DAT-15963

---

liquibase-standard/src/main/java/liquibase/util/StringUtil.java

allow lowercasing in ToStringFormatter (DAT-15870)

---

liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java
liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java
liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/MavenUtils.java
liquibase-standard/src/main/java/liquibase/changelog/ChangeSet.java
liquibase-standard/src/main/java/liquibase/database/AbstractJdbcDatabase.java
liquibase-standard/src/main/java/liquibase/sqlgenerator/core/AddAutoIncrementGeneratorMySQL.java
liquibase-standard/src/main/java/liquibase/sqlgenerator/core/AddForeignKeyConstraintGenerator.java
liquibase-standard/src/main/java/liquibase/structure/AbstractDatabaseObject.java
liquibase-standard/src/test/groovy/liquibase/change/AbstractChangeTest.groovy
liquibase-standard/src/test/groovy/liquibase/sqlgenerator/core/CreateViewGeneratorTest.groovy
liquibase-standard/src/test/groovy/liquibase/util/CollectionUtilTest.groovy

Fix some typos.

---

liquibase-dist/src/main/assembly/assembly-bin-common.xml

Exclude newly shaded dependencies from `internal/lib` directory.

Exclude new pro dependencies from lib directory (DAT-15871)

---

liquibase-standard/src/main/java/liquibase/executor/jvm/JdbcExecutor.java
liquibase-standard/src/main/java/liquibase/snapshot/jvm/JdbcSnapshotGenerator.java

Handle some potential NPEs Github issue 5063

---

liquibase-standard/src/main/java/liquibase/util/StringUtil.java

deprecate StringUtil#wrap method (DAT-15868)

---

liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/update.test.groovy
liquibase-standard/pom.xml
liquibase-standard/src/main/java/liquibase/changelog/ChangeLogIterator.java
liquibase-standard/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java
liquibase-standard/src/main/java/liquibase/report/ShowSummaryGenerator.java
liquibase-standard/src/main/java/liquibase/report/ShowSummaryGeneratorFactory.java
liquibase-standard/src/main/java/liquibase/report/StandardShowSummaryGenerator.java
liquibase-standard/src/main/java/liquibase/util/ShowSummaryUtil.java

show failed changesets in verbose show-summary output (DAT-15141)

---

liquibase-integration-tests/src/test/groovy/liquibase/command/core/ExecuteSqlPostgresIntegrationTest.groovy
liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/executeSql.test.groovy
liquibase-standard/src/main/java/liquibase/command/core/ExecuteSqlCommandStep.java

Fixes #3351
Docs update ticket: [PD-3812](https://datical.atlassian.net/browse/PD-3812) 
- None
- None
[PD-3812]: https://datical.atlassian.net/browse/PD-3812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

execute-sql command logic updated to not display select columns sorted

---

liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseLauncher.java

Handle duplicates of the commercial JAR DAT-16059

---

liquibase-standard/src/main/java/liquibase/snapshot/jvm/ColumnAutoIncrementService.java

Fixes #4719  introduced by PR https://github.com/liquibase/liquibase/pull/4140 .

Modify MSSQL query for when obtaining autoincrement column information GH-4719

---

.github/workflows/build-azure-uber-jar.yml

fix unauthorized error for https://maven.pkg.github.com/StevenMassaro/file-replacer-maven-plugin in Build Azure Uber jar

Fix build azure uber jars

---

README.md

As confirmed [here](https://github.com/liquibase/liquibase/pull/3515#issuecomment-1775065268).

Remove a forgotten `.` in `README.md`

---

.github/workflows/build-azure-uber-jar.yml
.github/workflows/build-branch.yml
.github/workflows/build-main.yml
.github/workflows/build.yml
.github/workflows/codeql.yml
.github/workflows/create-release.yml
.github/workflows/fossa.yml
.github/workflows/installer-build-check.yml
.github/workflows/release-published.yml
.github/workflows/sync-release-master-branch.yml
.github/workflows/url-check.yml

Reverts liquibase/liquibase#4839

Revert "Bump actions/checkout from 3 to 4"

---

.github/workflows/build-azure-uber-jar.yml
.github/workflows/build-branch.yml
.github/workflows/build-main.yml
.github/workflows/build.yml
.github/workflows/codeql.yml
.github/workflows/create-release.yml
.github/workflows/fossa.yml
.github/workflows/installer-build-check.yml
.github/workflows/release-published.yml
.github/workflows/sync-release-master-branch.yml
.github/workflows/url-check.yml

This reverts commit 8c482d2f791c1238be350b2edcc719d4d069d7cc.

Revert "Revert "Bump actions/checkout from 3 to 4" (#5103)"

---

liquibase-standard/src/main/java/liquibase/Liquibase.java

Fix Liquibase.rollback scope execution

---

liquibase-standard/pom.xml
liquibase-standard/src/main/java/liquibase/parser/LiquibaseSqlParser.java
liquibase-standard/src/main/java/liquibase/parser/SqlParserFactory.java
liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateProcedureGenerator.java
liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateViewGenerator.java
liquibase-standard/src/main/java/liquibase/util/SqlParser.java
liquibase-standard/src/main/java/liquibase/util/StandardSqlParser.java
liquibase-standard/src/main/java/liquibase/util/StringUtil.java
liquibase-standard/src/test/groovy/liquibase/util/SqlParserTest.groovy

move SqlParser into factory pattern (DAT-15679)

---

.github/workflows/build-azure-uber-jar.yml

move file-replacer-maven-plugin definition to maven central

---

liquibase-dist/src/main/install4j/liquibase.install4j

Update installer JDK

---

liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseUpdate.java

When this [change](https://github.com/liquibase/liquibase/pull/4574) was added we didn't take into account also making `showSummaryOutput` available for maven plugin. That has been done in this PR.
Fixes #4987
- None
- None
- Nothing

showSummaryOutput property added for update command

---

liquibase-dist/expected-distribution-contents.txt

add new checks package file to expected-distribution-contents.txt

---

.github/workflows/create-release.yml

Removing build-azure-jar step for now due to occurring issues. Created a ticket for tracking purposes :
https://datical.atlassian.net/browse/DAT-16175

removing build-azure jar

---

liquibase-dist/src/main/assembly/assembly-bin-common.xml

Remove slf4j from installer dependencies

---

.github/workflows/release-published.yml

https://datical.atlassian.net/browse/DAT-4562
chore(release-published.yml): update package-linux action to version v0.5.6 to include latest changes and improvements

DAT-4562 Yum/RPM-based Linux distribution

---

.github/workflows/create-release.yml

There have been ongoing issue with Azure uber jar. I have created a ticket to look into it : https://datical.atlassian.net/browse/DAT-16175. Reverting the existing code for it until the ticket is resolved.

remove azure-uber jar script

---

liquibase-dist/src/main/install4j/liquibase.install4j

Go back to an installer version that supports windows and mac

---

changelog.txt
liquibase-standard/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.25.xsd

Changelog for Liquibase 4.25.0

---

changelog.txt

adding last hour changes to changelog.txt

---

.github/util/re-version.sh

Fix readme txt version

---

.github/workflows/release-published.yml

fix sed command for 4.25.0 release

---

.github/util/re-version.sh
.github/workflows/release-published.yml

fix 1: fix sed commands
fix 2: When we resolved unknown values issue with cp command from internal/lib/liquibase-core.jar to artifacts/liquibase-core-0-SNAPSHOT.jar, we forgot to change the values in `re-version.sh`

fix copying issues

---

.github/workflows/release-published.yml

Fix sed command double quotes

---

.github/workflows/create-release.yml

fix indentation create-release.yml

---

liquibase-standard/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java

add preRun method to AbstractUpdateCommandStep (DAT-15639)

---

liquibase-standard/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java

Call the preRun method earlier, before running the isUpToDate check.

call prerun method earlier (DAT-16308)

---

liquibase-dist/expected-distribution-contents.txt
liquibase-dist/src/main/archive/licenses/commercial/README.txt
liquibase-dist/src/main/archive/licenses/commercial/bsd-3-clause.txt
liquibase-dist/src/main/archive/licenses/commercial/mit.txt

Update commercial licenses

---

liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/update.test.groovy
liquibase-standard/src/main/java/liquibase/command/CommandScope.java
liquibase-standard/src/main/java/liquibase/configuration/ConfigurationDefinition.java
liquibase-standard/src/main/java/liquibase/configuration/ConfigurationValueUtils.java
liquibase-standard/src/main/java/liquibase/configuration/ConfiguredValue.java
liquibase-standard/src/main/java/liquibase/util/ValueHandlerUtil.java

Show a better message if a boolean configuration argument has bad input DAT-16276

---

liquibase-standard/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java

Fixed query for actual data type for column

---

liquibase-standard/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java

Exclude QUEUE tables from snapshoting

---

.github/workflows/build.yml
pom.xml

Profile non-jdk8 was used to upgrade mockito libraries as we still need to compile and test using Java 8.

Run tests using Java 21

---

liquibase-standard/src/main/java/liquibase/integration/spring/SpringResourceAccessor.java

fix exception misspelling

---

liquibase-standard/src/main/java/liquibase/integration/spring/SpringResourceAccessor.java
liquibase-standard/src/test/groovy/liquibase/integration/spring/SpringResourceAccessorTest.groovy
liquibase-standard/src/test/resources/liquibase/database/test-changelog with-space-in-filename.yml

Decode encoded URLs from Spring resources

---

liquibase-standard/src/main/java/liquibase/Liquibase.java

During command refactoring some rollback commands were not added to run in scope. This pr fixes it.

Run all Liquibase.rollback commands inside scope.

---

liquibase-standard/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java
liquibase-standard/src/main/java/liquibase/report/ChangesetInfo.java
liquibase-standard/src/main/java/liquibase/report/IndividualChangesetInfo.java
liquibase-standard/src/main/java/liquibase/report/OperationInfo.java
liquibase-standard/src/main/java/liquibase/report/RuntimeInfo.java
liquibase-standard/src/main/java/liquibase/report/UpdateReportParameters.java
liquibase-standard/src/main/java/liquibase/util/ShowSummaryUtil.java
liquibase-standard/src/main/java/liquibase/util/UpdateSummaryDetails.java

Reworks ShowSummaryUtil to provide an actual object that captures the show summary output so we can use it later. Add additional fields to UpdateReportParameters. 
Not sure if my approach to the ShowSummaryUtil is the best but it feels like the most straightforward without mucking around in the scope or the mdc.

Rework update summary to support reporting, add new update report fields (DAT-16207)

---

liquibase-standard/src/main/java/liquibase/logging/mdc/MdcKey.java

add new MdcKey (DAT-14570)

---

.github/workflows/build.yml
liquibase-integration-tests/src/test/groovy/liquibase/command/ChangelogSyncIntegrationTest.groovy

Rollback change to liquibase-core copy as package name is wrong inside jar file

---

liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/status.test.groovy
liquibase-standard/src/main/java/liquibase/command/core/StatusCommandStep.java

Make message grammar correct

---

.github/workflows/build.yml

fix-workflow-call-branch-name to @master

---

.github/workflows/run-tests.yml

Currently, there are 2 runs which are happening for the same commit ie push to branch and commit/ sync to branch. Consolidating it only to run tests on pull_request_target:       
- opened
- reopened
- synchronize

trigger run only on pull_request_target

---

.github/workflows/run-tests.yml

run Integration tests Runs on the build of `build_tests` runs.

integration tests fix

---

liquibase-standard/src/main/java/liquibase/parser/AbstractFormattedChangeLogParser.java
liquibase-standard/src/test/groovy/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParserTest.groovy
liquibase-standard/src/test/resources/dropTableSingular.sql

Implemented ability for formatted SQL changelog to have rollback scripts  DAT-16019

---

.github/workflows/run-tests.yml

Update run-tests.yml to run on push to master branch

---

liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy
liquibase-integration-tests/src/test/groovy/liquibase/command/util/CommandUtil.groovy
liquibase-integration-tests/src/test/groovy/liquibase/snapshot/JdbcDatabaseSnapshotIntegrationTest.groovy
liquibase-standard/src/main/java/liquibase/structure/core/Index.java

[Columnstore indexes in SQL Server](https://learn.microsoft.com/en-us/sql/t-sql/statements/create-columnstore-index-transact-sql?view=sql-server-ver16) are snapshotted with no `columns` array, only an `includedColumns` array. This PR fixes a bug which prevents deserializing the resultant snapshot file when it contains no `columns` array.

DAT-16354: fix reading snapshots when columns array does not exist in an index

---

.github/workflows/build-branch.yml
.github/workflows/build.yml
.github/workflows/run-tests.yml

fix: use first 7 digits of commit-sha
`.github/workflows/build-branch.yml`
`.github/workflows/build.yml`
`.github/workflows/run-tests.yml`
Slack chat : https://liquibase.slack.com/archives/CK9JJEENB/p1702506884392279

use first 7 digits of commit-sha

---

.github/workflows/run-tests.yml

Downgrade ubuntu runner images version as current one are failing

---

.github/workflows/run-tests.yml

Downgrade ubuntu tests version

---

.github/workflows/build-branch.yml
.github/workflows/build.yml
.github/workflows/run-tests.yml

use full commit-sha as pro-tests is failing with expecting 40 char long sha
fix: `.github/workflows/build-branch.yml`
fix: `.github/workflows/build.yml`
fix: `.github/workflows/run-tests.yml`

fix: use full commit-sha

---

.github/workflows/create-release.yml

fix: `.github/workflows/create-release.yml`: Update create-release.yml: set draft to true

Update create-release.yml: set draft to true

---

liquibase-standard/src/main/java/liquibase/parser/AbstractFormattedChangeLogParser.java
liquibase-standard/src/test/groovy/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParserTest.groovy
liquibase-standard/src/test/resources/dropTableSingular.sql

Reverts liquibase/liquibase#5312
We need to make a decision on whether to license formatted SQL rollback scripts

DAT-16494 Revert "Implemented ability for formatted SQL changelog to have rollback scripts  DAT-16019"

---

changelog.txt
liquibase-standard/src/main/java/liquibase/parser/AbstractFormattedChangeLogParser.java
liquibase-standard/src/test/groovy/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParserTest.groovy
liquibase-standard/src/test/resources/dropTableSingular.sql

…have rollback scripts  DAT-16019" (#5385)
Revert "Implemented ability for formatted SQL changelog to have rollback scripts  DAT-16019 (#5312)"
This reverts commit 541aeeac435c8f3a2d7ef16357f063858299ba69.

Sync relase and master

---

liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java

add dbcl-history configuration options to maven plugin (DAT-16280)

---

.github/workflows/build.yml
.github/workflows/run-functional-tests.yml
.github/workflows/run-test-harness.yml

adding oss_workflow_url to show from which OSS PR the run was triggered
feat: `.github/workflows/build.yml`
feat: `.github/workflows/run-functional-tests.yml`
feat: `.github/workflows/run-test-harness.yml`

DAT-16455: additional information on Triggered PRO-tests and Test-Harness runs

---

.github/workflows/run-functional-tests.yml

DAT-16455: fix name for variable ossWorkflowUrl

---

.github/workflows/run-functional-tests.yml
.github/workflows/run-test-harness.yml

DAT-16455 fix name ossWorkflowUrl

---

.github/workflows/build.yml
.github/workflows/run-functional-tests.yml
.github/workflows/run-test-harness.yml
.github/workflows/run-tests.yml

DAT-16455: set env ossWorkflowUrl

---

.github/workflows/build-azure-uber-jar.yml
.github/workflows/build.yml
.github/workflows/codeql.yml
.github/workflows/installer-build-check.yml
.github/workflows/run-tests.yml

Revert actions upload upgrade

---

liquibase-standard/src/main/java/liquibase/logging/mdc/MdcKey.java
liquibase-standard/src/main/java/liquibase/logging/mdc/MdcManager.java
liquibase-standard/src/main/java/liquibase/logging/mdc/NoOpMdcManager.java
liquibase-standard/src/main/java/liquibase/logging/mdc/customobjects/MdcChangesetExtended.java
liquibase-standard/src/test/groovy/liquibase/ScopeTest.groovy

add new method to MdcManager, add databasechangeloghistory to MDC (DAT-16369)

---

.github/workflows/run-functional-tests.yml
.github/workflows/run-test-harness.yml

Fixes #2352  so that embedded.jar files containing the changelog directory will once again work with includeAll.   The issue was that the path passed into ZipResourceAccessor was stripping off the embedded path and need the extra path elements passed in to load the filesystem correctly.

Fixes #2352 by adding support for loading embedded jar files

---

liquibase-extension-testing/src/main/resources/liquibase.sdk.yaml

We need to revert this change when test containers updates.

Workaround failing test containers startup for mysql by falling back to previous version.

---

liquibase-integration-tests/src/test/groovy/liquibase/command/core/RollbackIntegrationTest.groovy
liquibase-integration-tests/src/test/groovy/liquibase/command/core/UpgradeChecksumVersionIntegrationTest.groovy
liquibase-integration-tests/src/test/groovy/liquibase/command/util/CommandUtil.groovy
liquibase-integration-tests/src/test/resources/changelogs/common/example-changelog.xml
liquibase-standard/src/main/java/liquibase/changelog/filter/AfterTagChangeSetFilter.java
liquibase-standard/src/main/java/liquibase/integration/commandline/LiquibaseCommandLineConfiguration.java

In versions of Liquibase prior to (and including) 4.25.1, any newer duplicate tags are ignored when rolling back to the oldest version of that tag. In future versions, newer duplicate tags are rolled back when rolling back to the oldest version of that tag.

do not skip over duplicate tags when doing rollback (DAT-16277)

---

liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/spock/LiquibaseIntegrationMethodInterceptor.java
liquibase-standard/src/main/java/liquibase/logging/mdc/customobjects/MdcChangesetExtended.java

fix pro tests

---

liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseDropAll.java
liquibase-standard/src/main/java/liquibase/Liquibase.java

DAT-16527: add dropDbclhistory argument to maven dropAll command

---

.github/workflows/run-tests.yml
liquibase-integration-tests/pom.xml

skip integration tests during unit test build (DAT-16719)

---

liquibase-standard/src/main/java/liquibase/changelog/visitor/DefaultChangeExecListener.java

add getter to listeners in DefaultChangeExecListener (DAT-16655)

---

liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/spock/LiquibaseIntegrationMethodInterceptor.java

reset database object factory after each test

---

liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java

DAT-16714: change default of history property in mojo

---

liquibase-standard/src/main/java/liquibase/parser/AbstractFormattedChangeLogParser.java

additional method signatures in support of pro feature (DAT-16640)

---

liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
liquibase-standard/src/main/java/liquibase/command/CommandDefinition.java

DAT-16675: add support for command aliases

---

liquibase-standard/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java
liquibase-standard/src/main/java/liquibase/report/OperationInfo.java

Add labels, context and rollback on error info to report (DAT-16531)

---

.github/workflows/release-published.yml

feat: `.github/workflows/release-published.yml` : generate-PRO-tag when OSS new version is released using : https://github.com/peter-evans/repository-dispatch
PRO PR: https://github.com/liquibase/liquibase-pro/pull/1507

DAT-16833: generate-PRO-tag based on OSS release

---

changelog.txt
liquibase-standard/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.26.xsd

chore: 4.26.0 xsd and changelog

---

changelog.txt
liquibase-standard/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.26.xsd

Fix docs url

---

changelog.txt

chore: docs

---

changelog.txt

Removed duplicated info

---

.github/workflows/run-test-harness.yml

feat: `.github/workflows/run-test-harness.yml` : changing the ref branch to `develop`, So that the test-harness builds triggered by liquibase builds executes against the ‘develop' branch of the test-harness + the 'branch-name-snapshot’ version of the core.

DAT-16497: run tests on develop branch for TH

---

liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseDbclHistoryMojo.java

add mojo for dbclHistory command (DAT-16673)

---

liquibase-standard/src/main/java/liquibase/command/core/DropAllCommandStep.java

throw exception if drop all fails (DAT-16718)

---

.github/workflows/run-tests.yml
liquibase-standard/src/main/java/liquibase/datatype/core/UUIDType.java

enable DB2 tests (DAT-16658)

---

liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java

fix dbclHistoryEnabled property from liquibase.properties file in maven (DAT-16881)

---

liquibase-standard/src/main/java/liquibase/database/Database.java
liquibase-standard/src/main/java/liquibase/executor/jvm/ChangelogJdbcMdcListener.java

record executed SQL in ChangelogJdbcMdcListener (DAT-16886)

---

.github/workflows/build-azure-uber-jar.yml

bump version of setup-maven action

---

.github/dependabot.yml

increase dependabot limits

---

liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java

add captureExtensions and captureSql params to maven plugin (DAT-16980)

---

liquibase-standard/src/main/java/liquibase/changelog/visitor/DefaultChangeExecListener.java
liquibase-standard/src/main/java/liquibase/command/CommandScope.java
liquibase-standard/src/main/java/liquibase/command/core/AbstractRollbackCommandStep.java
liquibase-standard/src/main/java/liquibase/logging/mdc/customobjects/ExceptionDetails.java
liquibase-standard/src/main/java/liquibase/report/RollbackReportParameters.java

Rework ExceptionDetails to encapsulate building of error object. Update commandscope to reflect ExceptionDetails changes. Use lombok getters on DefaultChangeExecListener. Add pending rollbacks, exception details and failed changeset name to rollback parameters.

Rework ExceptionDetails, update rollback parameters to handle exceptions (DAT-16922)

---

liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/setup/SetupSystemProperty.groovy

add command tests setup action to set Java System Property (DAT-16420)

---

liquibase-standard/src/main/java/liquibase/report/RollbackReportParameters.java

Add new parameters to rollback report parameters.

Add deployment id and targetted changeset details to rollback report (DAT-17041)

---

liquibase-integration-tests/src/test/groovy/liquibase/command/ChangelogSyncIntegrationTest.groovy

DAT-16428
Potentially fixed by https://github.com/liquibase/liquibase/pull/5617 .

[DAT-16428]  Reenable ChangelogSyncIntegrationTest tests

---

liquibase-dist/pom.xml
pom.xml

Reverts liquibase/liquibase#5611 as it breaks integration tests

Revert "Bump net.snowflake:snowflake-jdbc from 3.14.4 to 3.15.0"

---

liquibase-standard/src/main/java/liquibase/command/core/helpers/DbUrlConnectionCommandStep.java
liquibase-standard/src/main/java/liquibase/integration/commandline/LiquibaseCommandLineConfiguration.java

load driver from global argument as well as command argument (DAT-16381)

---

liquibase-standard/src/main/java/liquibase/ui/ConsoleUIService.java

print message to console when interactive environment is not detected (DAT-17274)

---

liquibase-standard/src/main/java/liquibase/command/core/helpers/ShowSummaryArgument.java

use HelpUtil where possible (DAT-16569)

---

.github/workflows/release-published.yml

fix: we don't have maven wrapper here

---

pom.xml

If an `@Unroll` annotation is forgotten on a Spock test, it is not unrolled automatically, which essentially means that the test iterations get treated all as one large test. This PR adds an extension which recognizes this and automatically unrolls those tests with forgotten annotations.

automatically unroll Spock tests

---

liquibase-extension-testing/pom.xml
liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/spock/LiquibaseIntegrationMethodInterceptor.java
liquibase-integration-tests/src/test/groovy/liquibase/snapshot/IndexWithDescendingColumnSnapshotIntegrationTest.groovy
liquibase-integration-tests/src/test/groovy/liquibase/snapshot/JdbcDatabaseSnapshotH2IntegrationTest.groovy
liquibase-integration-tests/src/test/groovy/liquibase/snapshot/JdbcDatabaseSnapshotMSSQLIntegrationTest.groovy
liquibase-integration-tests/src/test/groovy/liquibase/snapshot/JdbcSnapshotSerializerIntegrationTest.groovy
liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java
liquibase-standard/src/main/java/liquibase/database/core/MSSQLDatabase.java
liquibase-standard/src/main/java/liquibase/sql/visitor/AppendSqlIfNotPresentVisitor.java
liquibase-standard/src/test/groovy/liquibase/change/ChangeDefinitionTest.groovy
liquibase-standard/src/test/groovy/liquibase/servicelocator/StandardServiceLocatorTest.groovy
liquibase-standard/src/test/groovy/liquibase/util/FilenameUtilTest.groovy
liquibase-standard/src/test/java/liquibase/database/AbstractJdbcDatabaseTest.java
liquibase-standard/src/test/java/liquibase/database/core/MSSQLDatabaseTest.java
pom.xml

upgrade groovy, spock and mockito to later versions (DAT-10403)

---

pom.xml

Reverts liquibase/liquibase#5728

Revert "automatically unroll Spock tests"

---

liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseLauncher.java
liquibase-cli/src/test/groovy/liquibase/integration/commandline/LiquibaseLauncherTest.groovy

Improve duplicate jar detection logic to also detect jars that do not have a version in the filename (eg: `snakeyaml.jar` and `snakeyaml-1.33.0.jar`)

detect duplicate jars that do not have a version (DAT-16044)

---

liquibase-standard/src/main/java/liquibase/changelog/DatabaseChangeLog.java
liquibase-standard/src/main/java/liquibase/changelog/RanChangeSet.java
liquibase-standard/src/test/groovy/liquibase/changelog/DatabaseChangeLogTest.groovy
liquibase-standard/src/test/java/liquibase/changelog/RanChangeSetTest.java

fixes #5724 
fixes #5681 
To handle previous changeset deployed with 4.6.0 <= liquibase < 4.23.1; where filename contains relatives paths , this PR now compares filenames of incoming changeset and already executed changeset in the same way. 
Check current PR #5681 which impact the same code.

fixes #5724: compare normalized file paths

---

liquibase-standard/src/main/java/liquibase/util/FilenameUtil.java
liquibase-standard/src/test/groovy/liquibase/util/FilenameUtilTest.groovy

The `@` character can be problematic in file names if they are used for execution of some 3rd party tools

Also replace '@' character in temporary file names DAT-17292

---

.github/workflows/run-tests.yml

use java-version 17 for sonar scan from branch fix/DAT-17391

---

liquibase-standard/src/main/java/liquibase/snapshot/jvm/IndexSnapshotGenerator.java

This is another fix for https://github.com/liquibase/liquibase-hibernate/issues/436 .

fix: keep indexes list in the order returned by database

---

liquibase-standard/src/main/java/liquibase/integration/spring/Customizer.java
liquibase-standard/src/main/java/liquibase/integration/spring/SpringLiquibase.java
liquibase-standard/src/test/java/liquibase/integration/spring/SpringLiquibaseTest.java

Fixes #5128 
This is a replacement of #5642, with tests and annotating the `Customizer` with [FunctionalInterface](https://docs.oracle.com/javase/8/docs/api/java/lang/FunctionalInterface.html).
The customizer pattern is taken from [Spring Security](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/config/Customizer.html).

Implement Customizer for SpringLiquibase.

---

liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/update.test.groovy
liquibase-standard/src/main/java/liquibase/util/ShowSummaryUtil.java

fix calculation of total change sets in update summary (DAT-17262)

---

liquibase-cli/src/main/java/liquibase/integration/commandline/CommandRunner.java
liquibase-standard/pom.xml
liquibase-standard/src/main/java/liquibase/io/OutputFileHandler.java
liquibase-standard/src/main/java/liquibase/io/OutputFileHandlerFactory.java
liquibase-standard/src/main/java/liquibase/io/StandardOutputFileHandler.java

move output file handling into factory pattern (DAT-17290)

---

liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy
liquibase-integration-tests/src/test/groovy/liquibase/command/core/GenerateChangeLogMySQLIntegrationTest.groovy
liquibase-integration-tests/src/test/groovy/liquibase/diffchangelog/DiffChangelogIntegrationTest.groovy
liquibase-integration-tests/src/test/groovy/liquibase/snapshot/IndexWithDescendingColumnSnapshotIntegrationTest.groovy
liquibase-standard/src/main/java/liquibase/Scope.java
liquibase-standard/src/main/java/liquibase/util/StringUtil.java
liquibase-standard/src/test/groovy/liquibase/ThreadLocalScopeManagerTest.groovy
liquibase-standard/src/test/groovy/liquibase/util/StringUtilTest.groovy

This PR does two things:
1- `StringUtil.randomIdentifer` has a misspelling of the correct `identifier`.
This PR deprecates the old method, and introduce a new method without the typo.
2- Remove unused private field `StringUtil.rnd`.
I am not sure what deprecation policy is in place, but the version of deprecation addition or planned removal could be added to the method description.

Introduce a method with a correct name of `StringUtil.randomIdentifer()`.

---

liquibase-standard/src/test/groovy/liquibase/change/ChangeDefinitionTest.groovy
liquibase-standard/src/test/resources/liquibase/change/ChangeDefinitionTest.yaml

unignore and fix ChangeDefinitionTest (DAT-17344)

---

.github/workflows/create-release.yml

fix:`.github/workflows/create-release.yml`: the mv command is failing with `mv: cannot stat 'download/liquibase-pro-azure-artifacts/liquibase-azure-deps-4.27.1.jar': No such file or directory` in this run : https://github.com/liquibase/liquibase/actions/runs/8742524575/job/23991045791#step:8:1200. The fix is to address the same

DAT-16515: fix the mv command

---

.github/workflows/create-release.yml

azure uber jar fix

---

.github/workflows/create-release.yml

test PR for azure uber

---

.github/workflows/create-release.yml

fix:`.github/workflows/create-release.yml`: add missing v in the uber-jar creation
- [x ] Bug fix (non-breaking change which fixes expected existing functionality)

DAT-16515: add missing v in the uber-jar creation

---

liquibase-standard/src/main/java/liquibase/command/core/AbstractRollbackCommandStep.java
liquibase-standard/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java
liquibase-standard/src/main/java/liquibase/command/core/UpdateTestingRollbackCommandStep.java
liquibase-standard/src/main/java/liquibase/report/ChangesetInfo.java

Sets up methods to handle the initial update, the rollback and the final update in the chain for update-testing-rollback operations. Enables extensions to hook in to lifecycle of update-testing-rollback without rewriting the whole class. 
I'm happy to discuss naming conventions of these methods, I'm not a huge fan as is but can't come up with anything else.

Add new lifecycle methods for UpdateTestingRollbackCommandStep (DAT-15641)

---

liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/wrapper/UnimplementedWrapper.java
liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseChangeLogMojo.java
liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java
liquibase-standard/src/main/java/liquibase/Scope.java
liquibase-standard/src/main/java/liquibase/change/AbstractChange.java
liquibase-standard/src/main/java/liquibase/change/AbstractSQLChange.java
liquibase-standard/src/main/java/liquibase/change/Change.java
liquibase-standard/src/main/java/liquibase/change/ChangeFactory.java
liquibase-standard/src/main/java/liquibase/change/core/AbstractModifyDataChange.java
liquibase-standard/src/main/java/liquibase/change/core/AddForeignKeyConstraintChange.java
liquibase-standard/src/main/java/liquibase/change/core/CreateProcedureChange.java
liquibase-standard/src/main/java/liquibase/changelog/ChangeSet.java
liquibase-standard/src/main/java/liquibase/command/AbstractCliWrapperCommandStep.java
liquibase-standard/src/main/java/liquibase/integration/servlet/GenericServletListener.java
liquibase-standard/src/main/java/liquibase/integration/spring/MultiTenantSpringLiquibase.java
liquibase-standard/src/main/java/liquibase/integration/spring/SpringLiquibase.java
liquibase-standard/src/main/java/liquibase/util/BooleanParser.java
liquibase-standard/src/main/java/liquibase/util/BooleanUtils.java
liquibase-standard/src/main/java/liquibase/util/JdbcUtils.java
liquibase-standard/src/main/java/liquibase/util/NumberUtil.java
liquibase-standard/src/main/java/liquibase/util/NumberUtils.java
liquibase-standard/src/main/java/liquibase/util/StreamUtil.java
liquibase-standard/src/main/java/liquibase/util/StringUtil.java
liquibase-standard/src/main/java/liquibase/util/file/FilenameUtils.java

It is [advised](https://docs.oracle.com/javase%2F9%2Fdocs%2Fapi%2F%2F/java/lang/Deprecated.html#:~:text=The%20@Deprecated%20annotation%20should%20always%20be%20present%20if%20the%20@deprecated%20javadoc%20tag%20is%20present,%20and%20vice-versa.) that 
> The @Deprecated annotation should always be present if the @deprecated javadoc tag is present, and vice-versa.
This PR adds `@Deprecated` annotation when `@deprecated` tag is used.
Ideally, there could be a test case, which iterates over the source code, to enforce this for future code changes.

Add `@Deprecated` annotation.

---

liquibase-integration-tests/src/test/resources/reference.json
liquibase-integration-tests/src/test/resources/snapshot1.json
liquibase-integration-tests/src/test/resources/snapshot2.json
liquibase-integration-tests/src/test/resources/target.json

DAT-16954 DevOps :: Deprecate Postgres 11

---

liquibase-standard/src/main/java/liquibase/parser/AbstractFormattedChangeLogParser.java

refactor AbstractFormattedChangeLogParser to improve reusability (DAT-16478)

---

.github/workflows/create-release.yml

DAT-16515-v

---

liquibase-extension-testing/src/main/resources/liquibase.sdk.yaml

Update db2 docker location

---

liquibase-standard/src/test/groovy/liquibase/serializer/core/string/StringSnapshotSerializerReadableTest.groovy
liquibase-standard/src/test/java/liquibase/serializer/core/formattedsql/FormattedSqlChangeLogSerializerTest.java

chore: increasing test coverage

---

.github/workflows/weekly-integration-tests.yml

cleanup weekly-integration-tests.yml (DAT-17400)

---

liquibase-integration-tests/src/test/resources/changelogs/common/common.tests.changelog.xml
liquibase-integration-tests/src/test/resources/changelogs/common/depthboundincludeall/a/a.xml
liquibase-integration-tests/src/test/resources/changelogs/common/depthboundincludeall/a/b/b.xml
liquibase-integration-tests/src/test/resources/changelogs/common/depthboundincludeall/a/b/c/c.xml
liquibase-integration-tests/src/test/resources/changelogs/common/depthboundincludeall/a/b/c/d/d.xml
liquibase-integration-tests/src/test/resources/changelogs/common/depthboundincludeall/a/b/c/d/e/e.xml
liquibase-integration-tests/src/test/resources/changelogs/common/depthboundincludeall/a/b/c/d/e/f/f.xml
liquibase-integration-tests/src/test/resources/changelogs/common/depthboundincludeall/a/b/c/d/e/f/g/g.xml
liquibase-integration-tests/src/test/resources/changelogs/common/depthboundincludeall/changelog.xml
liquibase-standard/src/main/java/liquibase/changelog/DatabaseChangeLog.java
liquibase-standard/src/main/java/liquibase/resource/AbstractPathResourceAccessor.java
liquibase-standard/src/main/java/liquibase/resource/ResourceAccessor.java
liquibase-standard/src/main/java/liquibase/sdk/resource/MockResourceAccessor.java
liquibase-standard/src/test/groovy/liquibase/changelog/DatabaseChangeLogTest.groovy

Fixes #5654 
Depth calculations were not being calculated off the target path provided in includeAll but rather the path of the changelog including the includeAll.
Code updated to address incorrect depth calculation and MUCH more testing was added

Issue 5654 includeall min max depth fixes

---

.github/workflows/fossa_ai.yml

fix: `.github/workflows/fossa_ai.yml`: Update fossa_ai.yml to use authorize

DAT-17618: Update fossa_ai.yml to use authorize

---

liquibase-standard/src/main/java/liquibase/command/core/DiffCommandStep.java
liquibase-standard/src/main/java/liquibase/diff/core/StandardDiffGenerator.java

If there were multiple usages of the standard diff generator during a command's pipeline the diff results would jump around unexpectedly. This change generates the number a single time during the diff's lifecycle, impacting diff and diff-changelog command's mdc.

Update diff summary results in mdc to not be recalculated (DAT-17096)

---

liquibase-bigquery/src/test/java/liquibase/change/BigQueryMergeColumnChangeTest.java
liquibase-bigquery/src/test/java/liquibase/database/BigQueryDatabaseUnitTest.java
liquibase-bigquery/src/test/java/liquibase/datatype/core/BignumericDataTypeBigQueryTest.java
liquibase-bigquery/src/test/java/liquibase/datatype/core/BoolDataTypeBigQueryTest.java
liquibase-bigquery/src/test/java/liquibase/datatype/core/Float64DataTypeBigQueryTest.java
liquibase-bigquery/src/test/java/liquibase/datatype/core/GeographyDataTypeBigQueryTest.java
liquibase-bigquery/src/test/java/liquibase/datatype/core/Int64DataTypeBigQueryTest.java
liquibase-bigquery/src/test/java/liquibase/datatype/core/NumberDataTypeBigQueryTest.java
liquibase-bigquery/src/test/java/liquibase/datatype/core/StringDataTypeBigQueryTest.java
liquibase-bigquery/src/test/java/liquibase/sqlgenerator/BigQueryAddColumnGeneratorTest.java
liquibase-bigquery/src/test/java/liquibase/sqlgenerator/BigQueryAddForeignKeyConstraintGeneratorTest.java
liquibase-bigquery/src/test/java/liquibase/sqlgenerator/BigQueryAddPrimaryKeyConstraintGeneratorTest.java
liquibase-bigquery/src/test/java/liquibase/sqlgenerator/BigQueryCreateDatabaseChangeLogLockTableGeneratorTest.java
liquibase-bigquery/src/test/java/liquibase/sqlgenerator/BigQueryCreateTableGeneratorTest.java
liquibase-bigquery/src/test/java/liquibase/sqlgenerator/BigQueryDeleteGeneratorTest.java
liquibase-bigquery/src/test/java/liquibase/sqlgenerator/BigQueryDropForeignKeyConstraintGeneratorTest.java
liquibase-bigquery/src/test/java/liquibase/sqlgenerator/BigQueryDropPrimaryKeyConstraintGeneratorTest.java
liquibase-bigquery/src/test/java/liquibase/sqlgenerator/BigQueryInsertOrUpdateGeneratorTest.java
liquibase-bigquery/src/test/java/liquibase/sqlgenerator/BigQueryModifyDataTypeGeneratorTest.java
liquibase-bigquery/src/test/java/liquibase/sqlgenerator/BigQueryRenameTableGeneratorTest.java
liquibase-bigquery/src/test/java/liquibase/sqlgenerator/BigQueryRenameViewGeneratorTest.java
liquibase-bigquery/src/test/java/liquibase/sqlgenerator/BigQuerySetNullableGeneratorTest.java
liquibase-bigquery/src/test/java/liquibase/sqlgenerator/BigQueryUpdateGeneratorTest.java

[DAT-17450] Add BigQuery unit tests

---

.github/workflows/create-release.yml

fix(create-release.yml): fix file naming inconsistency for liquibase-…azure-deps jar file to match the correct naming convention

BUGFIX Azure jar wrong suffix

---

changelog.txt
liquibase-standard/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.28.xsd

chore:changelog + xsd

---

liquibase-standard/src/main/java/liquibase/command/core/DiffCommandStep.java
liquibase-standard/src/main/java/liquibase/diff/core/StandardDiffGenerator.java

This reverts commit 7ffa4f54eea5710d9d13421b4d752f33d466e7eb.

Revert "Update diff summary results in mdc to not be recalculated (DAT-17096) (#5869)" (DAT-17690)

---

liquibase-integration-tests/pom.xml
liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/diffChangelog.test.groovy
liquibase-standard/src/main/java/liquibase/command/core/DiffChangelogCommandStep.java

Throw exception from diff-changelog, so that it does not exit successfully when an exception occurs.

throw exception from diff-changelog when failure occurs (DAT-17623)

---

.github/workflows/build-azure-uber-jar.yml
.github/workflows/create-release.yml
README.md
changelog.txt
liquibase-integration-tests/pom.xml
liquibase-standard/src/main/java/liquibase/command/core/DiffCommandStep.java
liquibase-standard/src/main/java/liquibase/diff/core/StandardDiffGenerator.java
liquibase-standard/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.28.xsd

Release branch build

---

.github/workflows/weekly-integration-tests.yml

feat: `.github/workflows/weekly-integration-tests.yml`: slack-notification for test failures.

DAT-17536: Update weekly-integration-tests.yml

---

liquibase-integration-tests/src/test/groovy/liquibase/command/SnapshotSnowflakeIntegrationTest.groovy
liquibase-integration-tests/src/test/groovy/liquibase/command/util/CommandUtil.groovy
liquibase-snowflake/src/main/java/liquibase/snapshot/jvm/UniqueConstraintSnapshotGeneratorSnowflake.java

fully qualify names for Snowflake unique constraints (DAT-16598)

---

.github/workflows/build.yml

Adding property to build so that liquibase-scripting shows up in the tarball

---

.github/workflows/run-tests.yml

DB2 integration tests are failing because the Docker image cannot be retrieved.  Turning them off temporarily.

Turn off DB2 integration tests until they can be fixed

---

.github/workflows/run-tests.yml

Turn off DB2 for sonar

---

.github/workflows/fossa_ai.yml

fix: `.github/workflows/fossa_ai.yml` : this commit was reverted by liquibot and merged automatically https://github.com/liquibase/liquibase/commit/372154d761bb1266e8a88b5897c1358fc9d4aaa7

Add the reverted commit back : Update fossa_ai.yml

---

liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseConnectMojo.java

Added connect command to Maven DAT-17411

---

liquibase-standard/src/main/java/liquibase/change/CheckSum.java

this is needed to be able to de-serialise it using [jackson] which relies on the getters.
in the upcoming [liquibase-opensearch] implementation [opensearch-java] is used, which underneath is using jackson for the (de-)serialisation of classes.
this is a follow-up to commit 3823f0bcb (PR #5336) where only the deserialisation was fixed (by adding a default constructor + setters).
[jackson]: https://github.com/FasterXML/jackson
[opensearch-java]: https://github.com/opensearch-project/opensearch-java/
[liquibase-opensearch]: https://github.com/liquibase/liquibase-opensearch/
n/a
n/a
also correlates with #5950 (similar pattern, for the same reason, other class)

`CheckSum`: add getter for `storedCheckSum`

---

liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java
liquibase-standard/src/main/java/liquibase/parser/core/yaml/YamlChangeLogParser.java
liquibase-standard/src/main/java/liquibase/parser/core/yaml/YamlParser.java
liquibase-standard/src/test/groovy/liquibase/parser/core/yaml/YamlChangeLogParser_RealFile_Test.groovy
liquibase-standard/src/test/resources/liquibase/parser/core/yaml/malformedDoubleChangeLog.yaml

**Liquibase Version**: all
**Liquibase Integration & Version**: all
**Liquibase Extension(s) & Version**: all
**Database Vendor & Version**: all
**Operating System Type & Version**: all
If someone makes a mistake and copy/pastes a databaseChangeLog block in,
and makes the file have two tags, the SnakeYAML parser silently covers
up the first instance with the second one, which will cause the first
block of changes to be silently omitted.
This can be very problematic and cause hard-to-debug errors, which is
why I have added a small FilterInputStream interceptor to check the
stream as it is fed into the YAML parser, for a duplicate tag. Doing it
with the FilterInputStream like this prevents the efficiency losses of
opening the file twice.
You can look at the added test; essentially, just …

Prevent silent failures when two "databaseChangeLog" tags are present

---

.github/workflows/weekly-integration-tests.yml

fix: `.github/workflows/weekly-integration-tests.yml`: fix weekly-integration-tests.yml slack notifications

fix weekly-integration-tests.yml slack notifications

---

liquibase-snowflake/src/main/java/liquibase/snapshot/jvm/UniqueConstraintSnapshotGeneratorSnowflake.java

fully qualify names of tables when snapshotting unique constraints in Snowflake (DAT-17880)

---

liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseLauncher.java
liquibase-dist/src/main/archive/lib/README.txt
liquibase-dist/src/main/assembly/assembly-bin-common.xml

Changes in liquibase OSS code to add internal/ext directory as a library directory

DAT-17768 - Add new directory internal/ext to classpath

---

.github/workflows/run-tests.yml
liquibase-extension-testing/src/main/resources/liquibase.sdk.yaml

turn on DB2 integration tests (DAT-17759)

---

liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/update.test.groovy
liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/updateCount.test.groovy
liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/updateToTag.test.groovy
liquibase-standard/src/main/java/liquibase/util/TableOutput.java
liquibase-standard/src/test/groovy/liquibase/util/TableOutputTest.groovy

fix incorrect line breaks and wrapping when generating table output (DAT-17891 and DAT-17288)

---

.github/workflows/run-functional-tests.yml
.github/workflows/run-test-harness.yml

Fix test triggers

---

.github/workflows/run-functional-tests.yml
.github/workflows/run-test-harness.yml

🔧 (workflows): set environment variables for PR branch and SHA dynamically based on the event type to improve workflow flexibility and automation.

DAT-17975   DevOps :: Triggered functional and harness tests are executed on master build

---

liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/initstartH2.test.groovy
liquibase-standard/src/main/java/liquibase/command/core/StartH2CommandStep.java
liquibase-standard/src/main/java/liquibase/command/core/StopH2CommandStep.java
liquibase-standard/src/main/resources/META-INF/services/liquibase.command.CommandStep

add detached mode for running H2 (DAT-17654)

---

.github/workflows/run-functional-tests.yml
.github/workflows/run-test-harness.yml

Changed condition to trigger tests

---

liquibase-cli/src/test/groovy/liquibase/integration/commandline/LiquibaseCommandLineTest.groovy
liquibase-standard/src/main/java/liquibase/GlobalConfiguration.java

https://datical.atlassian.net/browse/PD-3256
Providing more useful description for STRICT global config; minor tweaks to other descriptions

PD-3256: STRICT=true description

---

liquibase-integration-tests/src/test/java/liquibase/dbtest/pgsql/PostgresThreadingTest.java
liquibase-integration-tests/src/test/resources/changelogs/pgsql/pg_sleep.sql
liquibase-standard/src/main/java/liquibase/command/core/StatusCommandStep.java
liquibase-standard/src/main/java/liquibase/logging/mdc/customobjects/SimpleStatus.java

feat: Add status command output + tests to make sure that ir runs at same time than update.

---

liquibase-standard/pom.xml
pom.xml

Add direct dependencies for apache commons libraries so dependabot can alert about upgrades/security issues
Fixes #5826

feat: Add dependencies for apache commons libraries that are being used

---

.github/workflows/run-tests.yml

fix: `.github/workflows/run-tests.yml`: fix retrieval of windows value

Fix/windows value DAT-17704

---

.github/workflows/release-published.yml

feat: `.github/workflows/release-published.yml`: workflow_dispatch to docs repo for OSS and PRO version update

🛞 DAT-16651: Update docs to latest OSS-PRO version

---

.github/workflows/release-published.yml

fix: `.github/workflows/release-published.yml`: Fir minor issues with OSS/PRO version in files

DAT-16651: Fir minor issues with OSS/PRO version in files

---

liquibase-standard/src/main/java/liquibase/command/core/InternalSnapshotCommandStep.java

Do not show message for bigquery database (DAT-17497)

---

README.md
liquibase-dist/expected-distribution-contents.txt
liquibase-dist/src/main/archive/licenses/commercial/README.txt
liquibase-dist/src/main/archive/licenses/commercial/psf.txt
liquibase-dist/src/main/archive/licenses/commercial/upl.txt

Add liquibase-scripting licensing information (DAT-17798)

---

.github/workflows/weekly-integration-tests.yml

feat: `.github/workflows/weekly-integration-tests.yml`: slack notification with workflow_name

DAT-17863: slack notification with workflow_file_name

---

.github/workflows/build-branch.yml

🔧 (build-branch.yml): add authorization step to check if the event is a pull request from an external repository and set the environment accordingly

Fix sec issue forked pr gh token

---

.github/workflows/build.yml
liquibase-dist/expected-distribution-contents.txt
liquibase-dist/pom.xml
liquibase-dist/src/main/assembly/assembly-bin-checks.xml
liquibase-dist/src/main/assembly/assembly-bin-common.xml

Update extension naming (DAT-18032)

---

.github/workflows/build.yml

Fix workflow for checks extension (DAT-18032)

---

.github/util/package-install4j.sh
.github/workflows/build-extension-jars.yml
.github/workflows/create-release.yml
.github/workflows/create-standalone-zip.yml

DAT-18103 Include liquibase-scripting.jar in Liquibase zip/installer

---

.github/workflows/build-azure-uber-jar.yml
.github/workflows/create-release.yml

fix: `.github/workflows/build-azure-uber-jar.yml`: updated the upload-artifact version to @v4 as it has the improvement to download the recently uploaded artifact in the same run without waiting for the run to be completed
fixes failures: `mv: cannot stat 're-version/out/liquibase-azure-deps-4.28.1.jar': No such file or directory` https://github.com/liquibase/liquibase/actions/runs/9945454282/job/27474135013#step:11:1253
Successful run : https://github.com/liquibase/liquibase/actions/runs/9947739964/job/27481092899

update actions/upload-artifact version to v4

---

.github/workflows/run-tests.yml

only fails PRs if number of tests decreases

DAT-18195 only fail if tests are below expected count

---

liquibase-standard/src/main/java/liquibase/sqlgenerator/core/AddColumnGenerator.java
liquibase-standard/src/test/java/liquibase/sqlgenerator/core/AddColumnGeneratorTest.java

Fix defaultValueComputed inside addColumn producing bad SQL with Postgres
Fixes #6016

Fix defaultValueComputed inside addColumn producing bad SQL with Postgres

---

liquibase-core/pom.xml

Remove unneeded inclusion of commons-io in liquibase-core pom.xml

---

changelog.txt
liquibase-standard/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.29.xsd

Liquibase 4.29.0 files

---

.github/workflows/release-published.yml

feat: `.github/workflows/release-published.yml`: Update pom.xml with latest OSS Release for ` liquibase-aws-license-service` repository

🔧 DAT-17914

---

liquibase-cli/src/test/groovy/liquibase/integration/commandline/LiquibaseCommandLineTest.groovy
liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/updateSql.test.groovy
liquibase-standard/src/main/java/liquibase/executor/LoggingExecutor.java
liquibase-standard/src/main/java/liquibase/integration/commandline/LiquibaseCommandLineConfiguration.java

optionally suppress Liquibase SQL for *-sql commands (DAT-18013)

---

liquibase-standard/src/main/java/liquibase/change/AbstractSQLChange.java
liquibase-standard/src/main/java/liquibase/changeset/ChangeSetService.java
liquibase-standard/src/main/java/liquibase/parser/AbstractFormattedChangeLogParser.java

changes in support of globally setting stripComments option (DAT-17390)

---

.github/workflows/cleanup-branch-builds.yml

⬆️ (cleanup-branch-builds.yml): downgrade actions/delete-package-versions to v3 to fix compatibility issue with current workflow configuration

DAT-18250   DevOps :: Clean up branch build not working

---

liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java

maven flag for suppressLiquibaseSql (DAT-18273)

---

liquibase-standard/src/main/java/liquibase/license/LicenseInfo.java

fix case where expiration date is null in --version output (DAT-18360)

---

liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseUpdateSQL.java

Use correct method for Maven updateSQL DAT-18142

---

liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseLauncher.java
liquibase-cli/src/test/groovy/liquibase/integration/commandline/LiquibaseCommandLineTest.groovy
liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java
liquibase-standard/pom.xml
liquibase-standard/src/main/java/liquibase/Scope.java
liquibase-standard/src/main/java/liquibase/analytics/AnalyticsConfiguration.java
liquibase-standard/src/main/java/liquibase/analytics/AnalyticsOutputDestination.java
liquibase-standard/src/main/java/liquibase/analytics/CsvAnalyticsListener.java
liquibase-standard/src/main/java/liquibase/analytics/Event.java
liquibase-standard/src/main/java/liquibase/analytics/NoOpAnalyticsListener.java
liquibase-standard/src/main/java/liquibase/analytics/UsageAnalyticsFactory.java
liquibase-standard/src/main/java/liquibase/analytics/UsageAnalyticsListener.java
liquibase-standard/src/main/java/liquibase/changelog/DatabaseChangeLog.java
liquibase-standard/src/main/java/liquibase/command/CommandScope.java
liquibase-standard/src/main/java/liquibase/command/core/helpers/DbUrlConnectionCommandStep.java
liquibase-standard/src/main/java/liquibase/integration/IntegrationDetails.java
liquibase-standard/src/main/java/liquibase/integration/commandline/Main.java
liquibase-standard/src/main/java/liquibase/parser/AbstractFormattedChangeLogParser.java
liquibase-standard/src/main/java/liquibase/parser/core/json/JsonChangeLogParser.java
liquibase-standard/src/main/java/liquibase/parser/core/sql/SqlChangeLogParser.java
liquibase-standard/src/main/java/liquibase/parser/core/xml/XMLChangeLogSAXParser.java
liquibase-standard/src/main/java/liquibase/parser/core/yaml/YamlParser.java
liquibase-standard/src/main/java/liquibase/util/Cache.java
liquibase-standard/src/main/java/liquibase/util/ExceptionUtil.java
liquibase-standard/src/main/java/liquibase/util/LiquibaseLauncherSettings.java
liquibase-standard/src/main/java/liquibase/util/VersionUtils.java
liquibase-standard/src/main/resources/META-INF/services/liquibase.configuration.AutoloadedConfigurations

initial add of analytics tracking and supporting classes (DAT-17823)

---

liquibase-standard/src/main/java/liquibase/datatype/DataTypeFactory.java

Do not throw exception if data type is not supported by database

---

.github/workflows/cleanup-branch-builds.yml

fix cleanup-branch-builds.yml

---

liquibase-standard/src/main/java/liquibase/license/LicenseService.java
liquibase-standard/src/main/java/liquibase/license/LicenseServiceUtils.java

add method to LicenseService to allow custom invalid license message (DAT-18196)

---

liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseChecksMojo.java
liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseChecksRunMojo.java
liquibase-standard/src/main/java/liquibase/executor/jvm/JdbcExecutor.java
liquibase-standard/src/main/java/liquibase/logging/mdc/MdcKey.java
liquibase-standard/src/main/resources/liquibase/examples/json/liquibase.advanced.flowfile.yaml
liquibase-standard/src/main/resources/liquibase/examples/json/liquibase.checks-package.yaml
liquibase-standard/src/main/resources/liquibase/examples/json/liquibase.flowfile.yaml
liquibase-standard/src/main/resources/liquibase/examples/sql/liquibase.advanced.flowfile.yaml
liquibase-standard/src/main/resources/liquibase/examples/sql/liquibase.checks-package.yaml
liquibase-standard/src/main/resources/liquibase/examples/sql/liquibase.flowfile.yaml
liquibase-standard/src/main/resources/liquibase/examples/xml/liquibase.advanced.flowfile.yaml
liquibase-standard/src/main/resources/liquibase/examples/xml/liquibase.checks-package.yaml
liquibase-standard/src/main/resources/liquibase/examples/xml/liquibase.flowfile.yaml
liquibase-standard/src/main/resources/liquibase/examples/yaml/liquibase.advanced.flowfile.yaml
liquibase-standard/src/main/resources/liquibase/examples/yaml/liquibase.checks-package.yaml
liquibase-standard/src/main/resources/liquibase/examples/yaml/liquibase.flowfile.yaml

Changing Quality Checks -> Policy Checks

---

.github/workflows/dry-run-relase.yml

📝 (dry-run-release.yml): add a new 'notify' job to notify Slack on build failure with detailed information and a custom message using action-slack-notify GitHub Action.

DAT-18301  DevOps :: Add Dry Run capabilities to liquibase

---

.github/workflows/cleanup-branch-builds.yml

🔧 (cleanup-branch-builds.yml): improve workflow file by using proper indentation and formatting for better readability
🔧 (cleanup-branch-builds.yml): update script to fetch commits between branch and master/release using GitHub API for more accurate results

DAT-18501 DevOps :: Clean up branch build not working

---

.github/workflows/cleanup-branch-builds.yml

DAT-17957    DevOps :: Fix the “Cleanup on branch delete” job

---

.github/workflows/build-extension-jars.yml
.github/workflows/create-release.yml
.github/workflows/dry-run-release.yml
.github/workflows/release-published.yml

🔧 (build-extension-jars.yml): Add 'branch' input parameter to specify…the branch to check out during the workflow execution
🔧 (create-release.yml): Add 'dry_run' flag to indicate if the workflow is triggered to create a dry-run release
✨ (dry-run-release.yml): Add workflow for dry run release process including creating a release, getting draft release, publishing release, and cleanup tasks.
🔧 (release-published.yml): Add support for dry-run flag and dry-run release id in the workflow inputs to enable triggering a dry-run release
🔧 (release-published.yml): Update workflow to conditionally execute deployment steps based on the value of the dry_run flag to prevent executing deployment steps during a dry-run release
🔧 (release-published.yml): Add support for dry-run deployment to …

fix release workflows

---

liquibase-cli/src/test/groovy/liquibase/integration/commandline/LiquibaseCommandLineTest.groovy
liquibase-standard/pom.xml
liquibase-standard/src/main/java/liquibase/Scope.java
liquibase-standard/src/main/java/liquibase/analytics/AnalyticsOutputDestination.java
liquibase-standard/src/main/java/liquibase/analytics/CsvAnalyticsListener.java
liquibase-standard/src/main/java/liquibase/analytics/SegmentAnalyticsListener.java
liquibase-standard/src/main/java/liquibase/analytics/SegmentBatch.java
liquibase-standard/src/main/java/liquibase/analytics/TelemetryConfiguration.java
liquibase-standard/src/main/java/liquibase/command/CommandScope.java
liquibase-standard/src/main/java/liquibase/command/core/helpers/DbUrlConnectionCommandStep.java
liquibase-standard/src/main/java/liquibase/telemetry/CsvAnalyticsListener.java
liquibase-standard/src/main/java/liquibase/telemetry/Event.java
liquibase-standard/src/main/java/liquibase/telemetry/NoOpAnalyticsListener.java
liquibase-standard/src/main/java/liquibase/telemetry/SegmentAnalyticsListener.java
liquibase-standard/src/main/java/liquibase/telemetry/SegmentBatch.java
liquibase-standard/src/main/java/liquibase/telemetry/SegmentTelemetryListener.java
liquibase-standard/src/main/java/liquibase/telemetry/SegmentTrackEvent.java
liquibase-standard/src/main/java/liquibase/telemetry/TelemetryConfiguration.java
liquibase-standard/src/main/java/liquibase/telemetry/TelemetryFactory.java
liquibase-standard/src/main/java/liquibase/telemetry/TelemetryListener.java
liquibase-standard/src/main/java/liquibase/telemetry/TelemetryOutputDestination.java
liquibase-standard/src/main/java/liquibase/telemetry/configuration/RemoteTelemetryConfiguration.java
liquibase-standard/src/main/java/liquibase/telemetry/configuration/SegmentTelemetryConfiguration.java
liquibase-standard/src/main/java/liquibase/telemetry/configuration/TelemetryArgs.java
liquibase-standard/src/main/java/liquibase/telemetry/configuration/TelemetryConfiguration.java
liquibase-standard/src/main/java/liquibase/telemetry/configuration/TelemetryConfigurationFactory.java
liquibase-standard/src/main/resources/META-INF/services/liquibase.configuration.AutoloadedConfigurations
liquibase-standard/src/test/groovy/liquibase/telemetry/TelemetryArgsTest.groovy

reorganize and add enabled argument (DAT-18297)

---

.github/workflows/dry-run-release.yml
.github/workflows/release-published.yml

DAT-18302  DevOps :: Add Dry Run capabilities to liquibase packages

---

liquibase-standard/src/main/java/liquibase/telemetry/configuration/TelemetryArgs.java
liquibase-standard/src/test/groovy/liquibase/telemetry/TelemetryArgsTest.groovy

turn off pro by default/make pro opt-in (DAT-18297)

---

changelog.txt

release_4292_changelog

---

liquibase-standard/src/main/java/liquibase/database/core/PostgresDatabase.java

- [] Bug fix (non-breaking change which fixes expected existing functionality)
Fixes #6173 
Update of `MINIMUM_DBMS_MAJOR_VERSION` and `MINIMUM_DBMS_MINOR_VERSION` PostgresDatabase constants to match with the minimum version Liquibase is currently supporting.

Update Postgres database major and minor versions.

---

.github/workflows/build.yml

fix: `.github/workflows/build.yml`: Ensure the workflow can read/write branches

🔧 Ensure the workflow can read/write branches

---

liquibase-standard/src/main/java/liquibase/snapshot/SnapshotGeneratorFactory.java

For MariaDB, verify existence of the lock table a different way to suppress log message

---

liquibase-cli/src/test/groovy/liquibase/integration/commandline/LiquibasecommandLineThreadingTest.groovy
liquibase-cli/src/test/resources/changelog.xml
liquibase-standard/src/main/java/liquibase/command/CommandFactory.java

fix: do not try to reload CommandDefinitions as they are all static parameters
Fixes #6076

fix: Handle command arguments static behavior

---

liquibase-standard/src/main/java/liquibase/command/CommandFactory.java

We have tests in Pro that need to clear the command definitions cache in `CommandFactory`.  I have added
this method so that we don't have to directly access the private field.

Add method to reset command definitions cache in CommandFactory for testing

---

.github/workflows/release-published.yml

fix: `.github/workflows/release-published.yml`: Fetch all tags from the remote to Get the latest tag and the previous tag

🔧 DAT-18613: Fetch all tags from the remote

---

.github/workflows/release-published.yml

fix: `.github/workflows/release-published.yml` : Use the 'release' branch for hotfix changes; otherwise, use the 'master' branch for regular updates. This is in conjunction with updates made here : https://github.com/liquibase/liquibase/pull/6124/files

🔧 DAT-18281 : Ref branch to checkout for Released Publish

---

.github/workflows/dry-run-release.yml

Fix dry run slack users

---

liquibase-standard/src/main/java/liquibase/analytics/AnalyticsFactory.java
liquibase-standard/src/main/java/liquibase/analytics/NoOpAnalyticsListener.java
liquibase-standard/src/main/java/liquibase/analytics/SegmentAnalyticsListener.java
liquibase-standard/src/main/java/liquibase/analytics/configuration/AnalyticsArgs.java
liquibase-standard/src/main/java/liquibase/analytics/configuration/SegmentAnalyticsConfiguration.java

make log level configurable for analytics and default to off (DAT-18577)

---

liquibase-standard/src/main/java/liquibase/command/core/GenerateChangelogCommandStep.java

Log the database platform when running generate changelog in mdc and analytics (DAT-18647)

---

liquibase-snowflake/src/main/java/liquibase/executor/jvm/SnowflakeJdbcExecutor.java
liquibase-standard/src/main/java/liquibase/executor/jvm/JdbcExecutor.java

Handle offline connection for Snowflake during diff DAT-18652

---

liquibase-standard/src/main/java/liquibase/integration/IntegrationDetails.java
liquibase-standard/src/main/java/liquibase/integration/spring/SpringLiquibase.java

put integration details in scope when running via spring (DAT-18605)

---

liquibase-integration-tests/src/test/groovy/liquibase/analytics/AnalyticsIntegrationTest.groovy
liquibase-standard/src/main/java/liquibase/analytics/Event.java

recognize when Liquibase is running in a docker container (DAT-18560)

---

liquibase-extension-testing/src/main/resources/liquibase.sdk.yaml

upgrade to mssql 2022 for ITs

---

liquibase-standard/src/main/java/liquibase/analytics/Event.java

There was a possible npe introduced here that would fail building the entire event object if triggered. When this happened, no analytics would be sent to segment. This change ensures that even with an NPE the analytics event object will still be constructed.

Fix possible NPE when constructing Event object

---

liquibase-cli/src/test/groovy/liquibase/integration/commandline/LiquibaseCommandLineThreadingTest.groovy

ignore threading test

---

liquibase-integration-tests/src/test/groovy/liquibase/analytics/AnalyticsIntegrationTest.groovy
liquibase-standard/src/main/java/liquibase/analytics/Event.java

add Java API to liquibaseInterface field (DAT-18606)

---

liquibase-integration-tests/src/test/groovy/liquibase/analytics/AnalyticsIntegrationTest.groovy
liquibase-standard/src/main/java/liquibase/analytics/Event.java
liquibase-standard/src/main/java/liquibase/analytics/SegmentAnalyticsListener.java

pretty-print request body to Segment (DAT-18702)

---

liquibase-integration-tests/src/test/groovy/liquibase/analytics/AnalyticsIntegrationTest.groovy
liquibase-standard/src/main/java/liquibase/analytics/configuration/RemoteAnalyticsConfiguration.java
liquibase-standard/src/main/java/liquibase/analytics/configuration/SegmentAnalyticsConfiguration.java

handle when new properties are added to config endpoint (DAT-18723)

---

liquibase-standard/src/main/java/liquibase/command/core/UpdateToTagCommandStep.java

Initialize member variable in method to fix tests

---

liquibase-standard/src/test/groovy/liquibase/changelog/ChangeSetTest.groovy

test: change order of stream closing and file deletion

---

.github/workflows/dry-run-release.yml
.github/workflows/release-published.yml

feat: `.github/workflows/release-published.yml`: use the output value of dry-run-release.yml
feat: `.github/workflows/dry-run-release.yml` : populate the value of the branch in dry-run-release.yml and pass it as outputs

DAT-18743: dry-run: add current_branch_name

---

liquibase-integration-tests/src/test/groovy/liquibase/analytics/AnalyticsIntegrationTest.groovy
liquibase-standard/pom.xml
liquibase-standard/src/main/java/liquibase/integration/ant/BaseLiquibaseTask.java
liquibase-standard/src/test/groovy/liquibase/analytics/TestAnalyticsWebserver.groovy
liquibase-standard/src/test/groovy/liquibase/integration/ant/test/AnalyticsWebserverPostBodyIsAnt.groovy
liquibase-standard/src/test/groovy/liquibase/integration/ant/test/AntTestAnalyticsWebserver.groovy
liquibase-standard/src/test/resources/liquibase/integration/ant/DropAllTaskTest.xml
liquibase-standard/src/test/resources/liquibase/integration/ant/test/antlib.xml

specify liquibase integration when running through ant (DAT-18608)

---

liquibase-standard/src/main/java/liquibase/change/core/CreateProcedureChange.java
liquibase-standard/src/test/resources/liquibase/change/ChangeDefinitionTest.yaml

In https://github.com/liquibase/liquibase/pull/6350 the instanceOf checks were replaced with an equality check, which means that MariaDB stopped working with CreateProcedureChange's, because MariaDB extends MySQL.

fix CreateProcedureChange not working with mariadb (DAT-18495)

---

liquibase-standard/src/main/java/liquibase/sqlgenerator/core/AddColumnGenerator.java

Handle Snowflake add NOT NULL constraint DAT-18798

---

liquibase-standard/src/main/java/liquibase/analytics/configuration/AnalyticsArgs.java

change production analytics config endpoint URL (DAT-18846)

---

liquibase-dist/expected-distribution-contents-targz.txt
liquibase-dist/expected-distribution-contents-zip.txt
liquibase-dist/src/main/archive/licenses/commercial/Liquibase Pro EULA Software License Subscription and Support Agreement.txt
liquibase-dist/src/main/archive/licenses/oss/README.txt
liquibase-dist/src/main/archive/licenses/oss/usage-data.txt

update licenses (DAT-18710)

---

liquibase-integration-tests/src/test/groovy/liquibase/OracleTest.groovy
liquibase-integration-tests/src/test/groovy/liquibase/command/util/CommandUtil.groovy

add basic Oracle performance test (DAT-18578)

---

liquibase-standard/src/main/java/liquibase/analytics/AnalyticsTrackEvent.java
liquibase-standard/src/main/java/liquibase/analytics/AnonymousSeed.java

include a prefix on truly random userIds (DAT-18848)

---

liquibase-standard/src/main/java/liquibase/analytics/LiquibaseAnalyticsListener.java
liquibase-standard/src/main/java/liquibase/analytics/configuration/AnalyticsArgs.java
liquibase-standard/src/main/java/liquibase/analytics/configuration/LiquibaseRemoteAnalyticsConfiguration.java

add logging when threads time out during analytics processing, make timeout configurable (DAT-18865)

---

liquibase-standard/src/main/java/liquibase/integration/spring/MultiTenantSpringLiquibase.java

Don't log a warning when use default schema on a MultiTenantSpringLiquibase.
I think this log should no be a warning because this is a expected behavior.
Fixes #6230

refactor: use info log instead of warn when default schema is used

---

changelog.txt
liquibase-standard/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.30.xsd

Add 4.30.0 xsd and update changelog.txt

---

liquibase-standard/src/main/java/liquibase/analytics/Event.java
liquibase-standard/src/main/java/liquibase/command/CommandScope.java

Only add child events when analytics is enabled (DAT-18943)

---

.github/workflows/release-published.yml

Update release-published.yml to get the previous version

---

.github/workflows/release-published.yml

- fix: `.github/workflows/release-published.yml`: populate the client_payload "dry_run" with appropriate syntax `${{ github.event.inputs.dry_run }}`

🛞 DAT-18995: populate proper client_payload for dry_run

---

.github/workflows/release-extensions.yml

- [ x ] Bug fix (non-breaking change which fixes expected existing functionality)
Updates `os-extension-automated-release.yml` file so it points to version `main`

Change automated release file version to main

---

.github/workflows/release-published.yml

fix: `.github/workflows/release-published.yml`: default dry_run value to `false`, as I dont like seeing "empty" values in the run when it's `false`
- Some scenarios:
- if trigger is via [released_published](https://github.com/liquibase/liquibase/blob/master/.github/workflows/release-published.yml#L4) on  `on:release` then [value](https://github.com/liquibase/liquibase/compare/DAT-18995?expand=1#diff-f7ca0660afb7c5d6e7220dee8a6db81db251b3c98818f4d76a3e4441b85c7a6dR489)  is `false` 
- if trigger is via [workflow_dispatch](https://github.com/liquibase/liquibase/blob/master/.github/workflows/release-published.yml#L5) and dryRun is true, then `true` will be send [here](https://github.com/liquibase/liquibase/compare/DAT-18995?expand=1#diff-f7ca0660afb7c5d6e7220dee8a6db81db251b3c98818f4d76a3e4441 …

🔧 DAT-18995: default dry_run value to false

---

.github/workflows/fossa.yml

chore: bump upload-artifacts to v4

---

.github/workflows/release-published.yml

This pull request includes a small change to the `.github/workflows/release-published.yml` file. The change updates the way the `dryRun` parameter is referenced in the `client_payload`.
* [`.github/workflows/release-published.yml`](diffhunk://#diff-f7ca0660afb7c5d6e7220dee8a6db81db251b3c98818f4d76a3e4441b85c7a6dL489-R489): Changed the `dryRun` parameter to use `inputs.dry_run` instead of `github.event.inputs.dry_run || false`.
* 
* ## Impact

✨ DAT- 18995

---

liquibase-integration-tests/src/test/groovy/liquibase/analytics/AnalyticsIntegrationTest.groovy
liquibase-standard/src/main/java/liquibase/analytics/Event.java

recognize isIO environment variable for analytics (DAT-18906)

---

liquibase-standard/src/main/java/liquibase/resource/ClassLoaderResourceAccessor.java

This happens when running CPC via Maven
This pull request includes a change to the `ClassLoaderResourceAccessor` class to handle `.pom` files more gracefully. The change prevents an `IllegalArgumentException` by skipping `.pom` files when configuring additional resource accessors.
* [`liquibase-standard/src/main/java/liquibase/resource/ClassLoaderResourceAccessor.java`](diffhunk://#diff-b07189c0641374e310072a03619dacc80858bd313062159dff4e6a98b5a1aa37R70-R76): Added a check to skip `.pom` files in the `configureAdditionalResourceAccessors` method to avoid `IllegalArgumentException` when calling `getProtocol()`.

Fix Maven issue that produces an exception when it finds a .pom file.

---

liquibase-standard/src/main/java/liquibase/Liquibase.java

While triaging #6356 we realized there were some command methods from Liquibase class that were not including changelogParameters as a command argument.

Liquibase API :: Missing changeLogParameters argument added

---

liquibase-integration-tests/src/test/groovy/liquibase/command/update/UpdateIntegrationTest.groovy
liquibase-integration-tests/src/test/resources/changelogs/h2/update/changelogs/subChangelog.xml
liquibase-integration-tests/src/test/resources/changelogs/h2/update/master.xml
liquibase-standard/src/main/java/liquibase/changelog/DatabaseChangeLog.java

The changelog and changeset logical file paths were not superseding the one from includeAll
https://github.com/liquibase/liquibase/issues/6493

Make changelog and change set logical file path settings override the setting from includeAll - Github issue 6493

---

liquibase-standard/src/main/java/liquibase/change/core/SQLFileChange.java

`dbms` property for `SQLFile` change was not being validated, and this was causing an invalid behavior apparently changeset was being successfully deployed (an entry was added into the `DBCL` table), but since the specified database short name was not valid, nothing was being deployed in the DB.
Fixes #6484

SQLFile :: Dbms validation check added

---

liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseLauncher.java
liquibase-cli/src/main/java/liquibase/integration/commandline/util/ParameterUtil.java
liquibase-standard/src/main/java/liquibase/util/LiquibaseLauncherSettings.java

- Ensure classloader is configured correctly by calling `configureClassLoader` as soon as possible.
- Include all libraries in the new classloader to avoid library conflicts/claspath hell.
- do not use the temporary classloader as a parent, but fall back to the root classloader
- Refactor `LiquibaseLauncher` to store library URLs in a static list for reuse instead of processing them again

Fix(DAT-18813): classloader configuration in LiquibaseCommandLine

---

liquibase-standard/src/main/java/liquibase/changelog/ChangeSet.java

revert refactoring which broke structured logging

---

.github/workflows/build.yml

Fix build - remove empty space from string

---

.github/workflows/build.yml

Added liquibase-checks property

---

liquibase-standard/src/main/java/liquibase/changelog/DatabaseChangeLog.java
liquibase-standard/src/main/java/liquibase/parser/core/sql/SqlChangeLogParser.java

Do not propagate logical file path to included change sets from raw SQL changelogs  DAT-19040

---

liquibase-standard/src/main/java/liquibase/report/ChangesetInfo.java
liquibase-standard/src/main/java/liquibase/report/OperationInfo.java
liquibase-standard/src/main/java/liquibase/report/RollbackReportParameters.java
liquibase-standard/src/main/java/liquibase/report/UpdateReportParameters.java
liquibase-standard/src/main/java/liquibase/report/UpdateRollbackReportParameters.java

This pull request introduces new methods to suppress SQL and exceptions in the Liquibase reporting module. The main changes include adding methods to clear SQL statements and replace them with a placeholder, as well as methods to suppress exceptions by setting a placeholder message.
Key changes:
* [`liquibase-standard/src/main/java/liquibase/report/ChangesetInfo.java`](diffhunk://#diff-abace7388b793fe78c714a9f319ae44566c1b1cd67ace853af704937a36513e0R117-R123): Added the `suppressSql` method to clear and replace generated SQL statements with "SQL Suppressed".
* [`liquibase-standard/src/main/java/liquibase/report/OperationInfo.java`](diffhunk://#diff-ac2b66c84f2e701eaa28ddeb4ab0564ea5e491b9973a01841deb586224520214R16-R19): Added the `suppressException` method to replace exceptions with …

optionally suppress SQL in reports (DAT-17940)

---

liquibase-standard/src/main/java/liquibase/changelog/DatabaseChangeLog.java

Do not retrieve ran change sets if there is no database connection DAT-19095

---

liquibase-standard/src/main/java/liquibase/command/AbstractCommandStep.java
liquibase-standard/src/main/java/liquibase/command/core/CalculateChecksumCommandStep.java
liquibase-standard/src/main/java/liquibase/command/core/ExecuteSqlCommandStep.java

Output calculated checksum to `stdout`.

---

liquibase-standard/src/main/java/liquibase/changelog/ChangeSet.java
liquibase-standard/src/main/java/liquibase/changelog/StandardChangeLogHistoryService.java
liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateDatabaseChangeLogTableGenerator.java
liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateDatabaseChangeLogTableGeneratorSybase.java

Reverts liquibase/liquibase#5595

Revert "Add changeset execution time to output"

---

liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/history.test.groovy
liquibase-standard/src/main/java/liquibase/command/core/HistoryCommandStep.java
liquibase-standard/src/test/groovy/liquibase/command/HistoryCommandStepTest.groovy

- Added new command arguments `tags` and `tag` to filter changesets by tags
- Refactored `HistoryCommandStep` to use `getOrUpdateReportPrinter` method for better code reuse
- Updated `HistoryCommandStepTest` to include tests for the new tag filtering functionality

feat(DAT-19013): Enhance History Command to filter changesets by tags

---

.github/workflows/run-tests.yml
README.md

Use correct workflow, update workflow name to read nicely on README

Fix README workflow status

---

liquibase-standard/src/main/java/liquibase/changelog/ChangeSet.java

PR #6565 introduced a few breaking changes to the pro builds, and a change that was not related to the intention of the original PR. This PR fixes those breaking changes and reintroduces the removal of code that was unrelated to the original PR.

fix breaking changes introduced in #6565

---

liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/spock/LiquibaseIntegrationMethodInterceptor.java

Set flag to turn off compatibility check for liquibase-checks in dropAll

---

liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
liquibase-standard/src/main/java/liquibase/Scope.java
liquibase-standard/src/main/java/liquibase/command/CommandArgumentDefinition.java
liquibase-standard/src/main/java/liquibase/command/CommandFactory.java
liquibase-standard/src/main/java/liquibase/command/CommandStep.java

DAT-19268 Remove stubs, now trapping for a checks command in Main

---

.github/workflows/build.yml
.github/workflows/run-pro-build-and-test.yml

chore: remove references to branch DAT-19069

---

.github/workflows/build.yml
.github/workflows/run-tests.yml

chore: bump download actions versions

---

.github/workflows/run-pro-build-and-test.yml
.gitignore
.vscode/settings.json

chore: use target to get access to tokens

---

liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseChecksMojo.java
liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseChecksRunMojo.java
liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseChecksShowMojo.java

Handle absence or older version of checks JAR DAT-19289

---

liquibase-standard/src/main/java/liquibase/change/core/LoadDataChange.java
liquibase-standard/src/test/groovy/liquibase/change/core/LoadDataChangeTest.groovy
liquibase-standard/src/test/resources/liquibase/change/core/sample.data.for.clob.types.csv

Fix for #6539
Fixes NPE when accessing resources via `SpringResourceAccessor`.

Fix null value handling when loading resources

---

.github/workflows/run-tests.yml

fix: test counts in master

---

.github/workflows/run-tests.yml

chore: rollback test count changes as they are failing for master

---

liquibase-standard/src/main/java/liquibase/diff/compare/core/ColumnComparator.java

This was introduced in #6405. The type comparisons should be using their respective db objects.

DAT-19082: Fix issue with losing changed datatype attributes when one datatype is an int and the other is not

---

liquibase-integration-tests/src/test/resources/changelogs/h2/update/execution-parameter.xml
liquibase-standard/src/main/java/liquibase/Scope.java
liquibase-standard/src/main/java/liquibase/changelog/StandardChangeLogHistoryService.java
liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateDatabaseChangeLogTableGenerator.java
liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateDatabaseChangeLogTableGeneratorSybase.java

This (https://github.com/liquibase/liquibase/pull/5653) has introduced a breaking change causing downstream effects to some database extensions. As a result we decided to remove this until we can get a handle on how to introduce this change in a measured way.

undo UUID-ing of deployment ID (DAT-19367)

---

changelog.txt
liquibase-standard/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.31.xsd

chore: FILES FOR 4.31.0 RELEASE

---

liquibase-cdi-jakarta/pom.xml
liquibase-cdi/pom.xml

fix: add missing name tag to poms

---

.github/workflows/release-extensions.yml

FIx tag for release-extensions.yml file

---

liquibase-cdi-jakarta/pom.xml
liquibase-cdi-jakarta/src/main/maven/liquibase-deployment-pom.xslt
liquibase-cdi/pom.xml
liquibase-cdi/src/main/maven/liquibase-deployment-pom.xslt

fix: move name from maven file to pom.xml

---

.github/pull_request_template.md

OSS PR template updated with required test actions

---

liquibase-integration-tests/src/test/groovy/liquibase/command/core/GenerateChangeLogPostgresqlIntegrationTest.groovy

fix: the default schema may be changed by other tests (!?). We need to hard code it.

fix flaky test

---

liquibase-standard/src/main/java/liquibase/executor/jvm/JdbcExecutor.java

Fixes #5947 
With changes introduced as part of #5842  we were setting fetch size for all databases, but the original issue (see [DAT-17267](https://datical.atlassian.net/browse/DAT-17267)) was reported for Oracle. We didn't know it would have a negative impact on other DBs, so with this PR, we are isolating the original change to be only applicable to Oracle. 
[DAT-17267]: https://datical.atlassian.net/browse/DAT-17267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Only set fetch size for Oracle database

---

liquibase-standard/src/main/java/liquibase/snapshot/SnapshotGeneratorFactory.java

Fixes #6685 Performance issue of an incorrect extract-variable refactoring of commit 89a3c3bc0bd211c8c5862af54d7fb9a22a5577ca
The original author extracted replacedSnapshotControl as a local variable but then failed passing it down the line. Instead the original snapshotControl object got passed which seems to operate on the entire catalog instead of just the example type in question.
This surely is not limited to MariaDB and affects all database systems supported.
I deliverately assume the author of the commit mentioned above made an error. Yet I do not fully understand the exact workings of the snapshot generation.

Fixes #6685 Performance issue of v4.30.0

---

.github/util/re-version.sh
.github/workflows/build.yml
.github/workflows/create-release.yml
.github/workflows/run-tests.yml

This pull request includes significant changes to the build and packaging process, primarily focusing on the introduction of a new "minimal" version of the Liquibase distribution. The changes involve modifications to various GitHub workflow files and scripts to support this new version.
* Added steps to create and package a minimal version of Liquibase in `.github/util/re-version.sh`. This includes extracting, copying necessary files, and repackaging both the full and minimal versions.
* Updated `.github/workflows/build.yml` to build both the full and minimal versions of Liquibase, including backing up and restoring tarballs to prevent overwriting. [[1]](diffhunk://#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721L211-R240) …

DAT-19476: generate minimal tar.gz and zip for OSS

---

liquibase-integration-tests/src/test/groovy/liquibase/changeType/ChangeLogIncludeTest.groovy
liquibase-integration-tests/src/test/groovy/liquibase/command/util/CommandUtil.groovy
liquibase-integration-tests/src/test/resources/changelogs/changeType/logicalfilepath/changelog.xml
liquibase-integration-tests/src/test/resources/changelogs/changeType/logicalfilepath/included.xml
liquibase-standard/src/main/java/liquibase/changelog/AbstractChangeLogHistoryService.java
liquibase-standard/src/main/java/liquibase/changelog/ChangeLogHistoryService.java
liquibase-standard/src/main/java/liquibase/changelog/visitor/ValidatingVisitor.java
liquibase-standard/src/main/java/liquibase/sqlgenerator/core/UpdateChangeSetFilenameGenerator.java
liquibase-standard/src/main/java/liquibase/statement/core/UpdateChangeSetFilenameStatement.java
liquibase-standard/src/main/java/liquibase/util/ValidatingVisitorUtil.java
liquibase-standard/src/main/resources/META-INF/services/liquibase.sqlgenerator.SqlGenerator

fix filename that was incorrect generated during 4.31.0

---

.github/workflows/build-extension-jars.yml

fix: release build

---

liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseLauncher.java

Warn on duplicate jars when added via classpath (DAT-19275)

---

liquibase-dist/pom.xml
pom.xml

switch to new mysql driver (DAT-19393)

---

liquibase-standard/src/main/java/liquibase/executor/jvm/JdbcExecutor.java

Closes #6662
This prevents the ResultSet from leaking. 
I tested this with a patched version in my local setup and this resolved all leaked result sets in my setup.

Close ResultSet to prevent leaking it

---

liquibase-integration-tests/src/test/groovy/liquibase/OracleTest.groovy
liquibase-integration-tests/src/test/groovy/liquibase/command/util/CommandUtil.groovy
liquibase-integration-tests/src/test/resources/changelogs/common/rows-affected.xml
liquibase-standard/src/main/java/liquibase/change/core/LoadDataChange.java
liquibase-standard/src/main/java/liquibase/executor/jvm/JdbcExecutor.java
liquibase-standard/src/test/groovy/liquibase/changelog/DatabaseChangeLogTest.groovy

Only report rows affected for DML statements

---

liquibase-integration-tests/src/test/resources/changelogs/common/common.tests.changelog.xml
liquibase-snowflake/src/main/java/liquibase/datatype/core/DateTypeSnowflake.java
liquibase-snowflake/src/main/java/liquibase/datatype/core/TimeTypeSnowflake.java
liquibase-snowflake/src/main/java/liquibase/datatype/core/TimestampNTZTypeSnowflake.java
liquibase-snowflake/src/main/java/liquibase/datatype/core/TimestampTypeSnowflake.java
liquibase-snowflake/src/main/resources/META-INF/services/liquibase.datatype.LiquibaseDataType
liquibase-snowflake/src/test/java/liquibase/datatype/TimestampNTZTypeTest.java

Integration test run: https://github.com/liquibase/liquibase/actions/runs/13397761751

support default values for time, datetime, and timestamp types in Snowflake (DAT-17524)

---

liquibase-standard/src/main/java/liquibase/command/core/helpers/DbUrlConnectionCommandStep.java

Fixes [DAT-18499](https://datical.atlassian.net/browse/DAT-18499). Product confirmed changing the log level of the driver configuration is ok.
[DAT-18499]: https://datical.atlassian.net/browse/DAT-18499?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DAT-18499 Log level changed when specifying driver on the CLI

---

liquibase-snowflake/src/main/java/liquibase/sqlgenerator/core/GetViewDefinitionGeneratorSnowflake.java
liquibase-snowflake/src/test/java/liquibase/sqlgenerator/core/GetViewDefinitionGeneratorSnowflakeTest.java

improve/fix snowflake view generation SQL 

---

liquibase-cdi-jakarta/pom.xml

This reverts commit 3e3e75887fd4eb66395d51577b037f800f0b8e46.
This upgrade caused packaging to fail. See [this run](https://github.com/liquibase/liquibase/actions/runs/13549800676/job/37877213232) for an example.

Revert weld-se-core upgrade

---

liquibase-integration-tests/src/test/groovy/liquibase/command/core/GenerateChangeLogH2IntegrationTest.groovy
liquibase-integration-tests/src/test/groovy/liquibase/diffchangelog/DiffChangelogIntegrationTest.groovy
liquibase-standard/src/main/java/liquibase/resource/AbstractResource.java

Also, clean up some tests which are leaving a directory around.  I am merging this ticket early, to make the checks extension build a little simpler.  The added method is not used anywhere else but checks.
DAT-19408

Added method to return the original path for a Resource

---

liquibase-standard/src/main/java/liquibase/change/core/LoadDataChange.java
liquibase-standard/src/test/groovy/liquibase/change/core/LoadDataChangeTest.groovy
liquibase-standard/src/test/resources/liquibase/change/core/sample.data.for.clob.types.csv

Fix LoadData issues for CLOB Values Containing Invalid File Path Characters 

---

liquibase-integration-tests/src/test/groovy/liquibase/command/core/GenerateChangeLogMSSQLIntegrationTest.groovy
liquibase-integration-tests/src/test/resources/changelogs/mssql/issues/user.defined.types.sql
liquibase-standard/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java

Moves mssql data type snapshot query post-processing to extract method to not step on original processing.

Do not include size on user defined types (DAT-19150)

---

liquibase-standard/src/main/java/liquibase/sqlgenerator/core/InsertGenerator.java

refactor InsertGenerator so that it can be overridden more easily (DAT-19678)

---

liquibase-integration-tests/src/test/groovy/liquibase/command/core/GenerateChangeLogH2IntegrationTest.groovy
liquibase-integration-tests/src/test/groovy/liquibase/diffchangelog/DiffChangelogIntegrationTest.groovy
liquibase-standard/src/main/java/liquibase/precondition/core/ColumnExistsPrecondition.java
liquibase-standard/src/main/java/liquibase/precondition/core/IndexExistsPrecondition.java
liquibase-standard/src/main/java/liquibase/precondition/core/PrimaryKeyExistsPrecondition.java
liquibase-standard/src/main/java/liquibase/precondition/core/SequenceExistsPrecondition.java
liquibase-standard/src/main/java/liquibase/precondition/core/TableExistsPrecondition.java
liquibase-standard/src/main/java/liquibase/precondition/core/UniqueConstraintExistsPrecondition.java
liquibase-standard/src/main/java/liquibase/precondition/core/ViewExistsPrecondition.java

Also added some test file cleanup
Github issue #6660

Use hasIgnoreNested method for all database preconditions

---

liquibase-standard/src/main/javacc/liquibase/util/grammar/SimpleSqlGrammar.jj

While trying to call a liquibase update for this changeset:
```
function check_name_special_chr(p_name sis_students.first_name%type)
return varchar2 is
v_name varchar2(100);
begin
select replace(translate(trim(p_name),
'_/\?.?+*&^%$#@!ٍِ][,؟:;[]`={}؛َ،?ْ~<>|',
' '),
null)
into v_name
from dual;
if p_name != v_name then
return '103';
else
return '1';
end if;
end check_name_special_chr;
```
This error will be thrown:
```
Exception in thread "main" liquibase.util.grammar.TokenMgrError: Lexical error at line 3939, column 37.  Encountered: '\u0650' (1616),
at liquibase.util.grammar.SimpleSqlGrammarTokenManager.getNextToken(SimpleSqlGrammarTokenManager.java:1410)
at liquibase.util.grammar.SimpleSqlGrammar.getNextToken(SimpleSqlGrammar.java:113)
at …
```

6743: support the Arabic character "Kasra"

---

liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
liquibase-cli/src/test/groovy/liquibase/integration/commandline/LiquibaseCommandLineTest.groovy
liquibase-standard/src/main/java/liquibase/integration/commandline/LiquibaseCommandLineConfiguration.java

gzip log files if log-file parameter ends in .gz (DAT-18971)

---

liquibase-standard/src/main/java/liquibase/command/core/SnapshotCommandStep.java
liquibase-standard/src/main/java/liquibase/snapshot/SnapshotGeneratorFactory.java
liquibase-standard/src/main/java/liquibase/structure/core/PrimaryKey.java

For SQL Server, sync up the backing index for PK and UC to the one that is auto-generated  DAT-19267

---

liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy
liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseDbclHistoryMojo.java
liquibase-snowflake/src/main/java/liquibase/datatype/core/BinaryTypeSnowflake.java
liquibase-snowflake/src/main/java/liquibase/datatype/core/DoubleDataTypeSnowflake.java
liquibase-standard/src/main/java/liquibase/integration/commandline/Main.java

Some code refactoring mades to fix some of the sonar `High` issues listed [here](https://sonarcloud.io/project/issues?impactSeverities=HIGH&issueStatuses=OPEN%2CCONFIRMED&id=liquibase). 
NOTE: some other code changes made were applied to fix some other issues, but these changes were breaking existing functionality, so I decided to undo them for now.

DAT - 19691 :: Code refactorings to fix sonar issues

---

liquibase-integration-tests/src/test/groovy/liquibase/analytics/AnalyticsIntegrationTest.groovy
liquibase-standard/src/main/java/liquibase/Scope.java
liquibase-standard/src/main/java/liquibase/analytics/AnalyticsBatch.java
liquibase-standard/src/main/java/liquibase/analytics/AnalyticsTrackEvent.java
liquibase-standard/src/main/java/liquibase/analytics/Event.java
liquibase-standard/src/main/java/liquibase/analytics/LiquibaseAnalyticsListener.java
liquibase-standard/src/main/java/liquibase/integration/spring/SpringLiquibase.java

reduce number of API calls for analytics by caching events (DAT-19789)

---

liquibase-cli/src/test/groovy/liquibase/integration/commandline/LiquibaseCommandLineTest.groovy
liquibase-standard/src/main/java/liquibase/Scope.java
liquibase-standard/src/main/java/liquibase/analytics/LiquibaseAnalyticsListener.java
liquibase-standard/src/main/java/liquibase/command/CommandScope.java
liquibase-standard/src/main/java/liquibase/command/core/helpers/DbUrlConnectionCommandStep.java
liquibase-standard/src/main/java/liquibase/database/DatabaseConnection.java
liquibase-standard/src/main/java/liquibase/database/jvm/JdbcConnection.java
liquibase-standard/src/main/java/liquibase/license/LicenseTrack.java
liquibase-standard/src/main/java/liquibase/license/LicenseTrackList.java
liquibase-standard/src/main/java/liquibase/license/LicenseTrackingArgs.java
liquibase-standard/src/main/java/liquibase/license/LicenseTrackingFactory.java
liquibase-standard/src/main/java/liquibase/license/LicenseTrackingListener.java
liquibase-standard/src/main/resources/META-INF/services/liquibase.configuration.AutoloadedConfigurations

send license usage tracking information to license utility (DAT-17920)

---

liquibase-standard/src/main/java/liquibase/license/LicenseInfo.java

include additional info in LicenseInfo (DAT-19766)

---

liquibase-cli/src/test/groovy/liquibase/integration/commandline/LiquibaseCommandLineTest.groovy
liquibase-standard/src/main/java/liquibase/license/LicenseTrack.java
liquibase-standard/src/main/java/liquibase/license/LicenseTrackingArgs.java

change parameter to tracking-id (DAT-19783)

---

liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
liquibase-standard/src/main/java/liquibase/Scope.java

Show message and exit if user attempts to use Azure without extension DAT-19430

---

liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java

fix: during sonar refactoring the wrong parameter was used here - fixing it.

---

liquibase-integration-tests/src/test/groovy/liquibase/command/core/ExecuteSqlPostgresIntegrationTest.groovy
liquibase-standard/src/main/java/liquibase/command/core/ExecuteSqlCommandStep.java

fix multiline select statements in execute-sql (DAT-19722)

---

liquibase-dist/pom.xml

fix: exclude duplicated dependencies provided by opencsv

---

liquibase-dist/pom.xml
liquibase-standard/src/main/java/liquibase/database/core/PostgresDatabase.java
pom.xml

Fix handling of PostgreSQL uppercase catalog names after v42.7.5 driver changes 

---

liquibase-standard/src/main/java/liquibase/changelog/StandardChangeLogHistoryService.java
liquibase-standard/src/main/java/liquibase/command/core/TagCommandStep.java

Useful for checking whether a record in the DBCL is actually a tag record. Added `@Beta` because I'm not sure if having the database parameter is too limiting.

Add static method to generate tag dbcl record (DAT-19432)

---

liquibase-standard/src/main/java/liquibase/Liquibase.java

Context:
Fixes #6799
Explicitly pass `DatabaseChangelogCommandStep.CHANGELOG_ARG` to scope of `changelogSync` command. Without this changes `changelogSync` relies only on `changelogFile` argument which not always may be usefull.

Pass CHANGELOG_ARG to scope of changelogSync command 

---

liquibase-snowflake/src/main/java/liquibase/snapshot/jvm/SchemaSnapshotGeneratorSnowflake.java

fix: class should override replaces method

---

liquibase-standard/src/main/java/liquibase/license/LicenseTrackingFactory.java

improve license tracking error message (DAT-19864)

---

liquibase-standard/src/main/java/liquibase/license/LicenseInfo.java

track issued date in LicenseInfo (DAT-19875)

---

liquibase-standard/src/main/java/liquibase/analytics/LiquibaseAnalyticsListener.java
liquibase-standard/src/main/java/liquibase/license/LicenseTrackingArgs.java

add timeout to license tracking HTTP request (DAT-19866)

---

liquibase-integration-tests/src/test/groovy/liquibase/OracleTest.groovy
liquibase-integration-tests/src/test/resources/changelogs/oracle/complete/fkep.test.changelog.xml

Test fixes for path issue

---

.github/workflows/run-tests.yml

remove setup-python and localstack infra code that isn't used

---

liquibase-standard/src/main/java/liquibase/command/core/helpers/DbUrlConnectionCommandStep.java
liquibase-standard/src/test/groovy/liquibase/command/core/helpers/DbUrlConnectionCommandStepTest.groovy

improve parameter stripping logic for LLU (DAT-19793)

---

liquibase-standard/src/main/java/liquibase/command/core/helpers/DbUrlConnectionCommandStep.java
liquibase-standard/src/test/groovy/liquibase/command/core/helpers/DbUrlConnectionCommandStepTest.groovy

fix NPE (DAT-19803)

---

liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java

add licenseUtilityEnabled flag to maven plugin (DAT-19825)

---

liquibase-standard/src/main/java/liquibase/logging/core/BufferedLogService.java

This issue sometimes causes test failures in PSQL tests in Pro.

fix concurrent modification error in BufferedLogService

---

liquibase-cli/src/test/groovy/liquibase/integration/commandline/LiquibaseCommandLineTest.groovy
liquibase-standard/src/main/java/liquibase/analytics/AnalyticsFactory.java
liquibase-standard/src/main/java/liquibase/analytics/AnalyticsListener.java
liquibase-standard/src/main/java/liquibase/analytics/Event.java
liquibase-standard/src/main/java/liquibase/analytics/LiquibaseAnalyticsListener.java
liquibase-standard/src/main/java/liquibase/analytics/NoOpAnalyticsListener.java
liquibase-standard/src/main/java/liquibase/analytics/configuration/AnalyticsArgs.java
liquibase-standard/src/main/java/liquibase/command/CommandScope.java
liquibase-standard/src/test/groovy/liquibase/analytics/AnalyticsArgsTest.groovy

Functionally this should be no different than before.
Sets up mechanism to override enabling analytics behavior.

DAT-19917: Refactor analytics setup to prepare for pro analytics

---

.github/workflows/release-published.yml
liquibase-standard/src/main/java/liquibase/analytics/LiquibaseAnalyticsListener.java
liquibase-standard/src/main/java/liquibase/analytics/configuration/LiquibaseRemoteAnalyticsConfiguration.java

Fix for https://github.com/liquibase/liquibase/issues/6726
Upon evaluation of a `changeLogPropertyDefined` precondition in a changelog that is included by a master changelog also take properties with attribute `global` set to `false` into account.
Fixes #6726.

Upon Evaluation of changeLogPropertyDefinied precondition also include local properties of nested changesets.

---

liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy

CommandTests: add assertEquals method (DAT-18275)

---

liquibase-standard/src/main/java/liquibase/command/core/init/InitCopyCommandStep.java

Caused by https://github.com/liquibase/liquibase/pull/6899 .

feat: Override isInternal method to return false in InitCopyCommandStep

---

liquibase-standard/src/main/java/liquibase/command/core/helpers/DbUrlConnectionCommandStep.java
liquibase-standard/src/main/java/liquibase/database/jvm/ConnectionPatterns.java
liquibase-standard/src/main/java/liquibase/database/jvm/JdbcConnection.java
liquibase-standard/src/main/java/liquibase/database/jvm/JdbcConnectionPatterns.java
liquibase-standard/src/test/groovy/liquibase/database/jvm/JdbcConnectionTest.groovy

replace username and password in host part of JDBC URL with empty string (DAT-20016)

---

liquibase-standard/src/main/java/liquibase/serializer/core/string/StringSnapshotSerializerReadable.java

These changes will implement possibility to expand and skip new objects without duplicating serializer code in `liquibase-core`'s dependencies like `liquibase-commercial` and extensions. 
Sets were used to avoid checking each time if new type were previously added.

INT-1249: refactored StringSnapshotSerializerReadable to be able to extend expandable and skipped object types from Pro and Extensions.

---

liquibase-standard/src/main/java/liquibase/database/AbstractJdbcDatabase.java

fix toString exception when JDBC connection is closed (DAT-19849)

---

liquibase-cdi-jakarta/pom.xml

Reverts liquibase/liquibase#6870

Revert "chore(deps-dev): bump org.jboss.weld.se:weld-se-core from 5.1.3.Final to 6.0.2.Final"

---

liquibase-extension-testing/pom.xml

Revert of junit-platform-suite to v1.11.4

---

liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy

Added property on CommandTests to allow skipping at runtime

---

liquibase-standard/src/main/java/liquibase/configuration/AbstractMapConfigurationValueProvider.java

feat: Add getDescription method to provide source description

---

liquibase-standard/src/main/java/liquibase/lockservice/StandardLockService.java

Display the "Waiting for changelog lock" message to console as well as the log

---

.github/workflows/create-release.yml

Set permission-contents: write to Re-version artifacts

---

liquibase-standard/src/main/java/liquibase/license/LicenseInfo.java

readd constructor removed in LLU merge (DAT-20238)

---

changelog.txt
liquibase-dist/src/main/install4j/liquibase.install4j
liquibase-standard/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.32.xsd

4.32.0: Release prep

---

.github/workflows/release-published.yml

Reverts liquibase/liquibase#6968

Revert "♻️ DAT-20252: add GitHub App token retrieval for access token"

---

liquibase-integration-tests/src/test/resources/changelogs/h2/update/logicalFilePath.xml
liquibase-standard/src/test/groovy/liquibase/changelog/ExpressionExpanderTest.groovy

Change the name of a property from "test" to "test1", to avoid conflict with Maven -Dtest property
Changed column name in another test changelog

Small test fixes for issues that I found in another ticket

---

liquibase-standard/src/main/java/liquibase/executor/ExecutorService.java

Handle possible NPE in getPlug() method 

---

liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy

Added property for disabling command tests at runtime

---

liquibase-standard/src/main/java/liquibase/parser/core/sql/SqlChangeLogParser.java
liquibase-standard/src/main/java/liquibase/parser/core/xml/XMLChangeLogSAXParser.java
liquibase-standard/src/test/groovy/liquibase/changelog/DatabaseChangeLogTest.groovy

Enhancement for #6827 - Error message updated when trying to parse an empty file

---

.github/workflows/release-published.yml

feat: Remove liquibase-cdi and liquibase-cdi-jakarta from release artifacts

---

liquibase-standard/src/main/java/liquibase/lockservice/StandardLockService.java

fix: resolve inconsistency in StandardLockService by ensuring table snapshot is validated before processing changes
Fixes the problems happening in  https://github.com/quarkusio/quarkus/pull/48024

fix: resolve inconsistency in StandardLockService by ensuring table snapshot is validated before processing changes

---

.github/workflows/build.yml

I expect to reduce some costs by skipping functional tests when a Dependabot PR is merged

Skip running functional tests when a Dependabot PR is merged

---

liquibase-integration-tests/src/test/groovy/liquibase/util/ShowSummaryUtilCommandTest.groovy
liquibase-standard/src/main/java/liquibase/changelog/ChangeSet.java

Fix issue in DBMS skip check that caused a regression

---

liquibase-standard/src/main/java/liquibase/changelog/StandardChangeLogHistoryService.java

do not count DBCL queries in rows affected message (DAT-20282)

---

liquibase-standard/src/main/java/liquibase/changelog/visitor/ValidatingVisitor.java
liquibase-standard/src/main/java/liquibase/command/core/helpers/DatabaseChangelogCommandStep.java

DAT-20378
This change allows the parsers to return the correct value in their `supports` method.

Pass the database instance in scope when parsing the changelog  DAT-20378

---

changelog.txt
liquibase-standard/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.33.xsd

chore: update changelog for version 4.33.0 release with notable changes and enhancements + XSD file

---

.github/dependabot.yml

fix: exclude H2 updates in dependabot config due to Java 11 requirement

---

.github/CODEOWNERS

This pull request is a huge step forward for the future of developer-kind. The `CODEOWNERS` file has been updated to include **Wes**, so **Filipe** can enjoy his time off without blocking merges.

Update CODEOWNERS for better maintainability

---

liquibase-standard/src/main/java/liquibase/command/core/GenerateChangelogCommandStep.java

Use missing objects instead of changed objects in test DAT-20536

---

liquibase-standard/src/main/java/liquibase/logging/mdc/customobjects/History.java

Mapped tag from RanChangeSet to History.ChangeSet
Fixes #7176

[7176]: Mapped tag in History.Changeset

---

liquibase-standard/src/main/java/liquibase/command/core/helpers/DbUrlConnectionCommandStep.java
liquibase-standard/src/main/java/liquibase/license/LicenseTrack.java

include database product name in license tracking data (DAT-20592)

---

liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/generateChangelog.test.groovy
liquibase-standard/src/main/java/liquibase/diff/output/changelog/DiffToChangeLog.java

Handle overwrite flag for formatted SQL correctly in generateChangelog

---

liquibase-standard/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java
liquibase-standard/src/main/java/liquibase/parser/AbstractFormattedChangeLogParser.java
liquibase-standard/src/test/groovy/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParserTest.groovy

Remove duplicate header check for formatted SQL and add log message

---

changelog.txt

Updated changelog.txt

---

changelog.txt

Updated the links

---

liquibase-dist/src/main/archive/README.txt

DAT-20859 Secure: README.txt "What Was Installed" section does not match actual installation

---

liquibase-maven-plugin/src/main/maven/release.pom.xml
pom.xml

Fixes https://github.com/liquibase/liquibase/issues/7333

Update licensing and documentation for OSS distribution  

---

.github/workflows/run-tests.yml

chore: remove dependabot PR check from workflow
